// Generated by tools/generate-library.mjs from prototype/library-spec.js.
#pragma once
#include <HBEngine/Game.hpp>
namespace hb {

namespace hb_detail {
inline int toInteger(double v){if(!std::isfinite(v)||v<INT32_MIN||v>INT32_MAX)throw std::out_of_range("int32 range");return int(v);}
inline int integer(int a,int b,char op){if((op=='/'||op=='%')&&b==0)throw std::invalid_argument("zero divisor");const std::int64_t x=a,y=b;switch(op){case '+':return toInteger(double(x+y));case '-':return toInteger(double(x-y));case '*':return toInteger(double(x*y));case '/':return toInteger(double(x/y));case '%':return toInteger(double(x%y));case '&':return a&b;case '|':return a|b;default:return a^b;}}
inline float angle(float v){return std::fmod(std::fmod(v+180,360)+360,360)-180;}
inline Vec3 rotate(Vec3 v,Vec3 r,bool inverse){float p[]={v.x,v.y,v.z};const float angles[]={r.x,r.y,r.z};for(int n=0;n<3;n++){const int axis=inverse?2-n:n,i=(axis+1)%3,j=(axis+2)%3;const float a=Math::DegreesToRadians(angles[axis])*(inverse?-1:1),x=p[i],y=p[j];p[i]=x*std::cos(a)-y*std::sin(a);p[j]=x*std::sin(a)+y*std::cos(a);}return {p[0],p[1],p[2]};}
inline float gamma(float v,bool linear){return linear?(v<=.04045f?v/12.92f:std::pow((v+.055f)/1.055f,2.4f)):(v<=.0031308f?v*12.92f:1.055f*std::pow(v,1/2.4f)-.055f);}
template<class T>inline bool equal(const T& a,const T& b){return a==b;}
inline bool equal(const Vec2& a,const Vec2& b){return a.x==b.x&&a.y==b.y;}
inline bool equal(const Vec3& a,const Vec3& b){return a.x==b.x&&a.y==b.y&&a.z==b.z;}
inline bool equal(const Color& a,const Color& b){return a.r==b.r&&a.g==b.g&&a.b==b.b&&a.a==b.a;}
inline bool equal(const Transform& a,const Transform& b){return equal(a.position,b.position)&&equal(a.rotation,b.rotation)&&equal(a.scale,b.scale);}
inline std::vector<std::string> characters(const std::string& value){std::vector<std::string> r;for(size_t i=0;i<value.size();){const auto c=static_cast<unsigned char>(value[i]);const size_t n=c<128?1:c<224?2:c<240?3:4;if(i+n>value.size())throw std::invalid_argument("UTF8");r.push_back(value.substr(i,n));i+=n;}return r;}
inline std::string join(const std::vector<std::string>& values,const std::string& separator=""){std::string r;for(size_t i=0;i<values.size();i++){if(i)r+=separator;r+=values[i];}if(r.size()>16384)throw std::length_error("string limit");return r;}
inline std::string slice(const std::string& value,int start,int count){auto chars=characters(value);const int s=std::clamp(start,0,int(chars.size())),e=s+std::min(std::max(0,count),int(chars.size())-s);return join({chars.begin()+s,chars.begin()+e});}
inline std::vector<std::string> split(const std::string& value,const std::string& separator){if(separator.empty())return characters(value);std::vector<std::string> r;size_t start=0,pos;while((pos=value.find(separator,start))!=std::string::npos){r.push_back(value.substr(start,pos-start));start=pos+separator.size();if(r.size()>128)throw std::length_error("array limit");}r.push_back(value.substr(start));return r;}
inline std::string replace(std::string value,const std::string& search,const std::string& replacement){if(search.empty())return value;size_t pos=0;while((pos=value.find(search,pos))!=std::string::npos){value.replace(pos,search.size(),replacement);pos+=replacement.size();if(value.size()>16384)throw std::length_error("string limit");}return value;}
inline std::string trim(const std::string& value){auto start=value.find_first_not_of(" \t\r\n");if(start==std::string::npos)return {};return value.substr(start,value.find_last_not_of(" \t\r\n")-start+1);}
}

HB_CLASS()
class Extended : public Library {
public:
  HB_FUNCTION(BlueprintPure, NodeKey="tan", KoreanName="탄젠트", Category="수학") static float Tan(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="asin", KoreanName="역사인", Category="수학") static float Asin(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="acos", KoreanName="역코사인", Category="수학") static float Acos(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="atan", KoreanName="역탄젠트", Category="수학") static float Atan(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="exp", KoreanName="지수", Category="수학") static float Exp(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="log", KoreanName="자연 로그", Category="수학") static float Log(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="log2", KoreanName="밑 2 로그", Category="수학") static float Log2(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="log10", KoreanName="밑 10 로그", Category="수학") static float Log10(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="truncate", KoreanName="버림", Category="수학") static float Truncate(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="fraction", KoreanName="소수 부분", Category="수학") static float Fraction(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="sign", KoreanName="부호", Category="수학") static float Sign(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="square", KoreanName="제곱", Category="수학") static float Square(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="cube", KoreanName="세제곱", Category="수학") static float Cube(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="oneMinus", KoreanName="1에서 빼기", Category="수학") static float OneMinus(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="saturate", KoreanName="0~1 제한", Category="수학") static float Saturate(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="sinh", KoreanName="쌍곡 사인", Category="수학") static float Sinh(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="cosh", KoreanName="쌍곡 코사인", Category="수학") static float Cosh(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="tanh", KoreanName="쌍곡 탄젠트", Category="수학") static float Tanh(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="atan2", KoreanName="방향의 역탄젠트", Category="수학") static float Atan2(float y,float x);
  HB_FUNCTION(BlueprintPure, NodeKey="modulo", KoreanName="실수 나머지", Category="수학") static float Modulo(float a,float b);
  HB_FUNCTION(BlueprintPure, NodeKey="wrap", KoreanName="반복 범위", Category="수학") static float Wrap(float value,float min,float max);
  HB_FUNCTION(BlueprintPure, NodeKey="inverseLerp", KoreanName="보간 비율 구하기", Category="수학") static float InverseLerp(float a,float b,float value);
  HB_FUNCTION(BlueprintPure, NodeKey="mapRangeClamped", KoreanName="제한된 범위 변환", Category="수학") static float MapRangeClamped(float value,float inMin,float inMax,float outMin,float outMax);
  HB_FUNCTION(BlueprintPure, NodeKey="easeIn", KoreanName="가속 보간", Category="수학") static float EaseIn(float alpha,float exponent);
  HB_FUNCTION(BlueprintPure, NodeKey="easeOut", KoreanName="감속 보간", Category="수학") static float EaseOut(float alpha,float exponent);
  HB_FUNCTION(BlueprintPure, NodeKey="easeInOut", KoreanName="가속 감속 보간", Category="수학") static float EaseInOut(float alpha,float exponent);
  HB_FUNCTION(BlueprintPure, NodeKey="floatMoveTowards", KoreanName="일정 속도 실수 이동", Category="수학") static float FloatMoveTowards(float current,float target,float distance);
  HB_FUNCTION(BlueprintPure, NodeKey="snapFloat", KoreanName="격자에 실수 맞추기", Category="수학") static float SnapFloat(float value,float grid);
  HB_FUNCTION(BlueprintPure, NodeKey="greaterEqual", KoreanName="크거나 같다", Category="비교") static bool GreaterEqual(float a,float b);
  HB_FUNCTION(BlueprintPure, NodeKey="lessEqual", KoreanName="작거나 같다", Category="비교") static bool LessEqual(float a,float b);
  HB_FUNCTION(BlueprintPure, NodeKey="inRange", KoreanName="범위 안에 있는 실수", Category="비교") static bool InRange(float value,float min,float max);
  HB_FUNCTION(BlueprintPure, NodeKey="nearlyZero", KoreanName="거의 0", Category="비교") static bool NearlyZero(float value,float tolerance);
  HB_FUNCTION(BlueprintPure, NodeKey="intAdd", KoreanName="정수 더하기", Category="정수") static int IntAdd(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intSubtract", KoreanName="정수 빼기", Category="정수") static int IntSubtract(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intMultiply", KoreanName="정수 곱하기", Category="정수") static int IntMultiply(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intDivide", KoreanName="정수 나누기", Category="정수") static int IntDivide(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intModulo", KoreanName="정수 나머지", Category="정수") static int IntModulo(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="bitAnd", KoreanName="비트 AND", Category="정수") static int BitAnd(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="bitOr", KoreanName="비트 OR", Category="정수") static int BitOr(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="bitXor", KoreanName="비트 XOR", Category="정수") static int BitXor(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intMin", KoreanName="정수 최솟값", Category="정수") static int IntMin(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intMax", KoreanName="정수 최댓값", Category="정수") static int IntMax(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intEqual", KoreanName="정수 같다", Category="정수") static bool IntEqual(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intNotEqual", KoreanName="정수 다르다", Category="정수") static bool IntNotEqual(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intGreater", KoreanName="정수 크다", Category="정수") static bool IntGreater(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="intLess", KoreanName="정수 작다", Category="정수") static bool IntLess(int a,int b);
  HB_FUNCTION(BlueprintPure, NodeKey="boolXor", KoreanName="불리언 배타적 OR", Category="논리") static bool BoolXor(bool a,bool b);
  HB_FUNCTION(BlueprintPure, NodeKey="boolNand", KoreanName="불리언 NAND", Category="논리") static bool BoolNand(bool a,bool b);
  HB_FUNCTION(BlueprintPure, NodeKey="boolNor", KoreanName="불리언 NOR", Category="논리") static bool BoolNor(bool a,bool b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Multiply", KoreanName="벡터2 성분 곱하기", Category="벡터2") static Vec2 Vector2Multiply(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Divide", KoreanName="벡터2 성분 나누기", Category="벡터2") static Vec2 Vector2Divide(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Min", KoreanName="벡터2 성분 최솟값", Category="벡터2") static Vec2 Vector2Min(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Max", KoreanName="벡터2 성분 최댓값", Category="벡터2") static Vec2 Vector2Max(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Abs", KoreanName="벡터2 절댓값", Category="벡터2") static Vec2 Vector2Abs(const Vec2& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Negate", KoreanName="벡터2 반전", Category="벡터2") static Vec2 Vector2Negate(const Vec2& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Floor", KoreanName="벡터2 내림", Category="벡터2") static Vec2 Vector2Floor(const Vec2& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Ceil", KoreanName="벡터2 올림", Category="벡터2") static Vec2 Vector2Ceil(const Vec2& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2NearlyEqual", KoreanName="벡터2 거의 같다", Category="벡터2") static bool Vector2NearlyEqual(const Vec2& a,const Vec2& b,float tolerance);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2IsZero", KoreanName="벡터2 거의 0", Category="벡터2") static bool Vector2IsZero(const Vec2& value,float tolerance);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Clamp", KoreanName="벡터2 성분 제한", Category="벡터2") static Vec2 Vector2Clamp(const Vec2& value,float min,float max);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2GetX", KoreanName="벡터2 X 성분 읽기", Category="벡터2") static float Vector2GetX(const Vec2& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2GetY", KoreanName="벡터2 Y 성분 읽기", Category="벡터2") static float Vector2GetY(const Vec2& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Multiply", KoreanName="벡터3 성분 곱하기", Category="벡터") static Vec3 Vector3Multiply(const Vec3& a,const Vec3& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Divide", KoreanName="벡터3 성분 나누기", Category="벡터") static Vec3 Vector3Divide(const Vec3& a,const Vec3& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Min", KoreanName="벡터3 성분 최솟값", Category="벡터") static Vec3 Vector3Min(const Vec3& a,const Vec3& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Max", KoreanName="벡터3 성분 최댓값", Category="벡터") static Vec3 Vector3Max(const Vec3& a,const Vec3& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Abs", KoreanName="벡터3 절댓값", Category="벡터") static Vec3 Vector3Abs(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Negate", KoreanName="벡터3 반전", Category="벡터") static Vec3 Vector3Negate(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Floor", KoreanName="벡터3 내림", Category="벡터") static Vec3 Vector3Floor(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Ceil", KoreanName="벡터3 올림", Category="벡터") static Vec3 Vector3Ceil(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3NearlyEqual", KoreanName="벡터3 거의 같다", Category="벡터") static bool Vector3NearlyEqual(const Vec3& a,const Vec3& b,float tolerance);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3IsZero", KoreanName="벡터3 거의 0", Category="벡터") static bool Vector3IsZero(const Vec3& value,float tolerance);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3Clamp", KoreanName="벡터3 성분 제한", Category="벡터") static Vec3 Vector3Clamp(const Vec3& value,float min,float max);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3GetX", KoreanName="벡터3 X 성분 읽기", Category="벡터") static float Vector3GetX(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3GetY", KoreanName="벡터3 Y 성분 읽기", Category="벡터") static float Vector3GetY(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3GetZ", KoreanName="벡터3 Z 성분 읽기", Category="벡터") static float Vector3GetZ(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Add", KoreanName="벡터2 더하기", Category="벡터2") static Vec2 Vector2Add(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Subtract", KoreanName="벡터2 빼기", Category="벡터2") static Vec2 Vector2Subtract(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Dot", KoreanName="벡터2 내적", Category="벡터2") static float Vector2Dot(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Cross", KoreanName="벡터2 외적", Category="벡터2") static float Vector2Cross(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Distance", KoreanName="벡터2 거리", Category="벡터2") static float Vector2Distance(const Vec2& a,const Vec2& b);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Lerp", KoreanName="벡터2 보간", Category="벡터2") static Vec2 Vector2Lerp(const Vec2& a,const Vec2& b,float alpha);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2Rotate", KoreanName="벡터2 회전", Category="벡터2") static Vec2 Vector2Rotate(const Vec2& value,float degrees);
  HB_FUNCTION(BlueprintPure, NodeKey="rotateVector", KoreanName="벡터 회전", Category="회전") static Vec3 RotateVector(const Vec3& value,const Vec3& rotation);
  HB_FUNCTION(BlueprintPure, NodeKey="unrotateVector", KoreanName="벡터 역회전", Category="회전") static Vec3 UnrotateVector(const Vec3& value,const Vec3& rotation);
  HB_FUNCTION(BlueprintPure, NodeKey="forwardVector", KoreanName="회전의 전방 벡터", Category="회전") static Vec3 ForwardVector(const Vec3& rotation);
  HB_FUNCTION(BlueprintPure, NodeKey="rightVector", KoreanName="회전의 오른쪽 벡터", Category="회전") static Vec3 RightVector(const Vec3& rotation);
  HB_FUNCTION(BlueprintPure, NodeKey="upVector", KoreanName="회전의 위쪽 벡터", Category="회전") static Vec3 UpVector(const Vec3& rotation);
  HB_FUNCTION(BlueprintPure, NodeKey="normalizeAngle", KoreanName="각도 -180~180 정규화", Category="회전") static float NormalizeAngle(float degrees);
  HB_FUNCTION(BlueprintPure, NodeKey="deltaAngle", KoreanName="최단 각도 차이", Category="회전") static float DeltaAngle(float a,float b);
  HB_FUNCTION(BlueprintPure, NodeKey="lerpAngle", KoreanName="최단 각도 보간", Category="회전") static float LerpAngle(float a,float b,float alpha);
  HB_FUNCTION(BlueprintPure, NodeKey="lookAtRotation", KoreanName="목표 방향 회전", Category="회전") static Vec3 LookAtRotation(const Vec3& start,const Vec3& target);
  HB_FUNCTION(BlueprintPure, NodeKey="transformPosition", KoreanName="로컬 위치를 월드로", Category="변환") static Vec3 TransformPosition(const Transform& transform,const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="inverseTransformPosition", KoreanName="월드 위치를 로컬로", Category="변환") static Vec3 InverseTransformPosition(const Transform& transform,const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="transformDirection", KoreanName="로컬 방향을 월드로", Category="변환") static Vec3 TransformDirection(const Transform& transform,const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="inverseTransformDirection", KoreanName="월드 방향을 로컬로", Category="변환") static Vec3 InverseTransformDirection(const Transform& transform,const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="colorRed", KoreanName="색상 빨강", Category="색상") static float ColorRed(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="colorGreen", KoreanName="색상 초록", Category="색상") static float ColorGreen(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="colorBlue", KoreanName="색상 파랑", Category="색상") static float ColorBlue(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="colorAlpha", KoreanName="색상 알파", Category="색상") static float ColorAlpha(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="colorLerp", KoreanName="색상 보간", Category="색상") static Color ColorLerp(const Color& a,const Color& b,float alpha);
  HB_FUNCTION(BlueprintPure, NodeKey="colorMultiply", KoreanName="색상 곱하기", Category="색상") static Color ColorMultiply(const Color& a,const Color& b);
  HB_FUNCTION(BlueprintPure, NodeKey="colorLuminance", KoreanName="색상 휘도", Category="색상") static float ColorLuminance(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="colorInvert", KoreanName="색상 반전", Category="색상") static Color ColorInvert(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="sRGBToLinear", KoreanName="sRGB를 선형 색상으로", Category="색상") static Color SRGBToLinear(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="linearToSRGB", KoreanName="선형 색상을 sRGB로", Category="색상") static Color LinearToSRGB(const Color& value);
  HB_FUNCTION(BlueprintPure, NodeKey="stringEqual", KoreanName="문자열 같다", Category="문자열") static bool StringEqual(const std::string& a,const std::string& b);
  HB_FUNCTION(BlueprintPure, NodeKey="stringNotEqual", KoreanName="문자열 다르다", Category="문자열") static bool StringNotEqual(const std::string& a,const std::string& b);
  HB_FUNCTION(BlueprintPure, NodeKey="startsWith", KoreanName="문자열로 시작하는지", Category="문자열") static bool StartsWith(const std::string& value,const std::string& search);
  HB_FUNCTION(BlueprintPure, NodeKey="endsWith", KoreanName="문자열로 끝나는지", Category="문자열") static bool EndsWith(const std::string& value,const std::string& search);
  HB_FUNCTION(BlueprintPure, NodeKey="stringIsEmpty", KoreanName="빈 문자열", Category="문자열") static bool StringIsEmpty(const std::string& value);
  HB_FUNCTION(BlueprintPure, NodeKey="unicodeLength", KoreanName="한글 포함 문자 수", Category="문자열") static int UnicodeLength(const std::string& value);
  HB_FUNCTION(BlueprintPure, NodeKey="reverseString", KoreanName="문자열 뒤집기", Category="문자열") static std::string ReverseString(const std::string& value);
  HB_FUNCTION(BlueprintPure, NodeKey="leftString", KoreanName="앞에서 문자열 자르기", Category="문자열") static std::string LeftString(const std::string& value,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="rightString", KoreanName="뒤에서 문자열 자르기", Category="문자열") static std::string RightString(const std::string& value,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="leftChop", KoreanName="뒤쪽 문자 제거", Category="문자열") static std::string LeftChop(const std::string& value,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="rightChop", KoreanName="앞쪽 문자 제거", Category="문자열") static std::string RightChop(const std::string& value,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="substring", KoreanName="문자열 구간", Category="문자열") static std::string Substring(const std::string& value,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="findString", KoreanName="문자열 위치 찾기", Category="문자열") static int FindString(const std::string& value,const std::string& search);
  HB_FUNCTION(BlueprintPure, NodeKey="replaceString", KoreanName="문자열 모두 바꾸기", Category="문자열") static std::string ReplaceString(const std::string& value,const std::string& search,const std::string& replacement);
  HB_FUNCTION(BlueprintPure, NodeKey="splitString", KoreanName="문자열 분리 배열", Category="문자열") static std::vector<std::string> SplitString(const std::string& value,const std::string& separator);
  HB_FUNCTION(BlueprintPure, NodeKey="joinStrings", KoreanName="문자열 배열 합치기", Category="문자열") static std::string JoinStrings(const std::vector<std::string>& values,const std::string& separator);
  HB_FUNCTION(BlueprintPure, NodeKey="trimString", KoreanName="공백 문자 제거", Category="문자열") static std::string TrimString(const std::string& value);
  HB_FUNCTION(BlueprintPure, NodeKey="lowerString", KoreanName="영문 소문자로", Category="문자열") static std::string LowerString(const std::string& value);
  HB_FUNCTION(BlueprintPure, NodeKey="upperString", KoreanName="영문 대문자로", Category="문자열") static std::string UpperString(const std::string& value);
  HB_FUNCTION(BlueprintPure, NodeKey="intToString", KoreanName="정수를 문자열로", Category="변환") static std::string IntToString(int value);
  HB_FUNCTION(BlueprintPure, NodeKey="boolToString", KoreanName="불리언을 문자열로", Category="변환") static std::string BoolToString(bool value);
  HB_FUNCTION(BlueprintPure, NodeKey="intToFloat", KoreanName="정수를 실수로", Category="변환") static float IntToFloat(int value);
  HB_FUNCTION(BlueprintPure, NodeKey="floatToInt", KoreanName="실수를 정수로 버림", Category="변환") static int FloatToInt(float value);
  HB_FUNCTION(BlueprintPure, NodeKey="boolToInt", KoreanName="불리언을 정수로", Category="변환") static int BoolToInt(bool value);
  HB_FUNCTION(BlueprintPure, NodeKey="intToBool", KoreanName="정수를 불리언으로", Category="변환") static bool IntToBool(int value);
  HB_FUNCTION(BlueprintPure, NodeKey="vector2ToVector3", KoreanName="벡터2를 벡터3로", Category="변환") static Vec3 Vector2ToVector3(const Vec2& value,float z);
  HB_FUNCTION(BlueprintPure, NodeKey="vector3ToVector2", KoreanName="벡터3의 XY", Category="변환") static Vec2 Vector3ToVector2(const Vec3& value);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolLength", KoreanName="배열 길이 · Bool", Category="배열") static int ArrayBoolLength(const std::vector<bool>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolLastIndex", KoreanName="마지막 배열 인덱스 · Bool", Category="배열") static int ArrayBoolLastIndex(const std::vector<bool>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolIsEmpty", KoreanName="빈 배열 · Bool", Category="배열") static bool ArrayBoolIsEmpty(const std::vector<bool>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolIsValidIndex", KoreanName="유효한 배열 인덱스 · Bool", Category="배열") static bool ArrayBoolIsValidIndex(const std::vector<bool>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolGet", KoreanName="배열 원소 읽기 · Bool", Category="배열") static bool ArrayBoolGet(const std::vector<bool>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolFind", KoreanName="배열 원소 찾기 · Bool", Category="배열") static int ArrayBoolFind(const std::vector<bool>& array,bool item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolContains", KoreanName="배열 원소 포함 · Bool", Category="배열") static bool ArrayBoolContains(const std::vector<bool>& array,bool item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolReverse", KoreanName="배열 역순 사본 · Bool", Category="배열") static std::vector<bool> ArrayBoolReverse(const std::vector<bool>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolAppend", KoreanName="배열 합친 사본 · Bool", Category="배열") static std::vector<bool> ArrayBoolAppend(const std::vector<bool>& array,const std::vector<bool>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolSlice", KoreanName="배열 구간 사본 · Bool", Category="배열") static std::vector<bool> ArrayBoolSlice(const std::vector<bool>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayBoolUnique", KoreanName="중복 없는 배열 사본 · Bool", Category="배열") static std::vector<bool> ArrayBoolUnique(const std::vector<bool>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntLength", KoreanName="배열 길이 · Int", Category="배열") static int ArrayIntLength(const std::vector<int>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntLastIndex", KoreanName="마지막 배열 인덱스 · Int", Category="배열") static int ArrayIntLastIndex(const std::vector<int>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntIsEmpty", KoreanName="빈 배열 · Int", Category="배열") static bool ArrayIntIsEmpty(const std::vector<int>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntIsValidIndex", KoreanName="유효한 배열 인덱스 · Int", Category="배열") static bool ArrayIntIsValidIndex(const std::vector<int>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntGet", KoreanName="배열 원소 읽기 · Int", Category="배열") static int ArrayIntGet(const std::vector<int>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntFind", KoreanName="배열 원소 찾기 · Int", Category="배열") static int ArrayIntFind(const std::vector<int>& array,int item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntContains", KoreanName="배열 원소 포함 · Int", Category="배열") static bool ArrayIntContains(const std::vector<int>& array,int item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntReverse", KoreanName="배열 역순 사본 · Int", Category="배열") static std::vector<int> ArrayIntReverse(const std::vector<int>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntAppend", KoreanName="배열 합친 사본 · Int", Category="배열") static std::vector<int> ArrayIntAppend(const std::vector<int>& array,const std::vector<int>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntSlice", KoreanName="배열 구간 사본 · Int", Category="배열") static std::vector<int> ArrayIntSlice(const std::vector<int>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayIntUnique", KoreanName="중복 없는 배열 사본 · Int", Category="배열") static std::vector<int> ArrayIntUnique(const std::vector<int>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatLength", KoreanName="배열 길이 · Float", Category="배열") static int ArrayFloatLength(const std::vector<float>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatLastIndex", KoreanName="마지막 배열 인덱스 · Float", Category="배열") static int ArrayFloatLastIndex(const std::vector<float>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatIsEmpty", KoreanName="빈 배열 · Float", Category="배열") static bool ArrayFloatIsEmpty(const std::vector<float>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatIsValidIndex", KoreanName="유효한 배열 인덱스 · Float", Category="배열") static bool ArrayFloatIsValidIndex(const std::vector<float>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatGet", KoreanName="배열 원소 읽기 · Float", Category="배열") static float ArrayFloatGet(const std::vector<float>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatFind", KoreanName="배열 원소 찾기 · Float", Category="배열") static int ArrayFloatFind(const std::vector<float>& array,float item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatContains", KoreanName="배열 원소 포함 · Float", Category="배열") static bool ArrayFloatContains(const std::vector<float>& array,float item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatReverse", KoreanName="배열 역순 사본 · Float", Category="배열") static std::vector<float> ArrayFloatReverse(const std::vector<float>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatAppend", KoreanName="배열 합친 사본 · Float", Category="배열") static std::vector<float> ArrayFloatAppend(const std::vector<float>& array,const std::vector<float>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatSlice", KoreanName="배열 구간 사본 · Float", Category="배열") static std::vector<float> ArrayFloatSlice(const std::vector<float>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayFloatUnique", KoreanName="중복 없는 배열 사본 · Float", Category="배열") static std::vector<float> ArrayFloatUnique(const std::vector<float>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringLength", KoreanName="배열 길이 · String", Category="배열") static int ArrayStringLength(const std::vector<std::string>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringLastIndex", KoreanName="마지막 배열 인덱스 · String", Category="배열") static int ArrayStringLastIndex(const std::vector<std::string>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringIsEmpty", KoreanName="빈 배열 · String", Category="배열") static bool ArrayStringIsEmpty(const std::vector<std::string>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringIsValidIndex", KoreanName="유효한 배열 인덱스 · String", Category="배열") static bool ArrayStringIsValidIndex(const std::vector<std::string>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringGet", KoreanName="배열 원소 읽기 · String", Category="배열") static std::string ArrayStringGet(const std::vector<std::string>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringFind", KoreanName="배열 원소 찾기 · String", Category="배열") static int ArrayStringFind(const std::vector<std::string>& array,const std::string& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringContains", KoreanName="배열 원소 포함 · String", Category="배열") static bool ArrayStringContains(const std::vector<std::string>& array,const std::string& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringReverse", KoreanName="배열 역순 사본 · String", Category="배열") static std::vector<std::string> ArrayStringReverse(const std::vector<std::string>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringAppend", KoreanName="배열 합친 사본 · String", Category="배열") static std::vector<std::string> ArrayStringAppend(const std::vector<std::string>& array,const std::vector<std::string>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringSlice", KoreanName="배열 구간 사본 · String", Category="배열") static std::vector<std::string> ArrayStringSlice(const std::vector<std::string>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayStringUnique", KoreanName="중복 없는 배열 사본 · String", Category="배열") static std::vector<std::string> ArrayStringUnique(const std::vector<std::string>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Length", KoreanName="배열 길이 · Vec2", Category="배열") static int ArrayVec2Length(const std::vector<Vec2>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2LastIndex", KoreanName="마지막 배열 인덱스 · Vec2", Category="배열") static int ArrayVec2LastIndex(const std::vector<Vec2>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2IsEmpty", KoreanName="빈 배열 · Vec2", Category="배열") static bool ArrayVec2IsEmpty(const std::vector<Vec2>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2IsValidIndex", KoreanName="유효한 배열 인덱스 · Vec2", Category="배열") static bool ArrayVec2IsValidIndex(const std::vector<Vec2>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Get", KoreanName="배열 원소 읽기 · Vec2", Category="배열") static Vec2 ArrayVec2Get(const std::vector<Vec2>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Find", KoreanName="배열 원소 찾기 · Vec2", Category="배열") static int ArrayVec2Find(const std::vector<Vec2>& array,const Vec2& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Contains", KoreanName="배열 원소 포함 · Vec2", Category="배열") static bool ArrayVec2Contains(const std::vector<Vec2>& array,const Vec2& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Reverse", KoreanName="배열 역순 사본 · Vec2", Category="배열") static std::vector<Vec2> ArrayVec2Reverse(const std::vector<Vec2>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Append", KoreanName="배열 합친 사본 · Vec2", Category="배열") static std::vector<Vec2> ArrayVec2Append(const std::vector<Vec2>& array,const std::vector<Vec2>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Slice", KoreanName="배열 구간 사본 · Vec2", Category="배열") static std::vector<Vec2> ArrayVec2Slice(const std::vector<Vec2>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec2Unique", KoreanName="중복 없는 배열 사본 · Vec2", Category="배열") static std::vector<Vec2> ArrayVec2Unique(const std::vector<Vec2>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Length", KoreanName="배열 길이 · Vec3", Category="배열") static int ArrayVec3Length(const std::vector<Vec3>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3LastIndex", KoreanName="마지막 배열 인덱스 · Vec3", Category="배열") static int ArrayVec3LastIndex(const std::vector<Vec3>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3IsEmpty", KoreanName="빈 배열 · Vec3", Category="배열") static bool ArrayVec3IsEmpty(const std::vector<Vec3>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3IsValidIndex", KoreanName="유효한 배열 인덱스 · Vec3", Category="배열") static bool ArrayVec3IsValidIndex(const std::vector<Vec3>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Get", KoreanName="배열 원소 읽기 · Vec3", Category="배열") static Vec3 ArrayVec3Get(const std::vector<Vec3>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Find", KoreanName="배열 원소 찾기 · Vec3", Category="배열") static int ArrayVec3Find(const std::vector<Vec3>& array,const Vec3& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Contains", KoreanName="배열 원소 포함 · Vec3", Category="배열") static bool ArrayVec3Contains(const std::vector<Vec3>& array,const Vec3& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Reverse", KoreanName="배열 역순 사본 · Vec3", Category="배열") static std::vector<Vec3> ArrayVec3Reverse(const std::vector<Vec3>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Append", KoreanName="배열 합친 사본 · Vec3", Category="배열") static std::vector<Vec3> ArrayVec3Append(const std::vector<Vec3>& array,const std::vector<Vec3>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Slice", KoreanName="배열 구간 사본 · Vec3", Category="배열") static std::vector<Vec3> ArrayVec3Slice(const std::vector<Vec3>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayVec3Unique", KoreanName="중복 없는 배열 사본 · Vec3", Category="배열") static std::vector<Vec3> ArrayVec3Unique(const std::vector<Vec3>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorLength", KoreanName="배열 길이 · Color", Category="배열") static int ArrayColorLength(const std::vector<Color>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorLastIndex", KoreanName="마지막 배열 인덱스 · Color", Category="배열") static int ArrayColorLastIndex(const std::vector<Color>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorIsEmpty", KoreanName="빈 배열 · Color", Category="배열") static bool ArrayColorIsEmpty(const std::vector<Color>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorIsValidIndex", KoreanName="유효한 배열 인덱스 · Color", Category="배열") static bool ArrayColorIsValidIndex(const std::vector<Color>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorGet", KoreanName="배열 원소 읽기 · Color", Category="배열") static Color ArrayColorGet(const std::vector<Color>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorFind", KoreanName="배열 원소 찾기 · Color", Category="배열") static int ArrayColorFind(const std::vector<Color>& array,const Color& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorContains", KoreanName="배열 원소 포함 · Color", Category="배열") static bool ArrayColorContains(const std::vector<Color>& array,const Color& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorReverse", KoreanName="배열 역순 사본 · Color", Category="배열") static std::vector<Color> ArrayColorReverse(const std::vector<Color>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorAppend", KoreanName="배열 합친 사본 · Color", Category="배열") static std::vector<Color> ArrayColorAppend(const std::vector<Color>& array,const std::vector<Color>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorSlice", KoreanName="배열 구간 사본 · Color", Category="배열") static std::vector<Color> ArrayColorSlice(const std::vector<Color>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayColorUnique", KoreanName="중복 없는 배열 사본 · Color", Category="배열") static std::vector<Color> ArrayColorUnique(const std::vector<Color>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformLength", KoreanName="배열 길이 · Transform", Category="배열") static int ArrayTransformLength(const std::vector<Transform>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformLastIndex", KoreanName="마지막 배열 인덱스 · Transform", Category="배열") static int ArrayTransformLastIndex(const std::vector<Transform>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformIsEmpty", KoreanName="빈 배열 · Transform", Category="배열") static bool ArrayTransformIsEmpty(const std::vector<Transform>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformIsValidIndex", KoreanName="유효한 배열 인덱스 · Transform", Category="배열") static bool ArrayTransformIsValidIndex(const std::vector<Transform>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformGet", KoreanName="배열 원소 읽기 · Transform", Category="배열") static Transform ArrayTransformGet(const std::vector<Transform>& array,int index);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformFind", KoreanName="배열 원소 찾기 · Transform", Category="배열") static int ArrayTransformFind(const std::vector<Transform>& array,const Transform& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformContains", KoreanName="배열 원소 포함 · Transform", Category="배열") static bool ArrayTransformContains(const std::vector<Transform>& array,const Transform& item);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformReverse", KoreanName="배열 역순 사본 · Transform", Category="배열") static std::vector<Transform> ArrayTransformReverse(const std::vector<Transform>& array);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformAppend", KoreanName="배열 합친 사본 · Transform", Category="배열") static std::vector<Transform> ArrayTransformAppend(const std::vector<Transform>& array,const std::vector<Transform>& other);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformSlice", KoreanName="배열 구간 사본 · Transform", Category="배열") static std::vector<Transform> ArrayTransformSlice(const std::vector<Transform>& array,int start,int count);
  HB_FUNCTION(BlueprintPure, NodeKey="arrayTransformUnique", KoreanName="중복 없는 배열 사본 · Transform", Category="배열") static std::vector<Transform> ArrayTransformUnique(const std::vector<Transform>& array);
};
inline float Extended::Tan(float value){return std::tan(value);}
inline float Extended::Asin(float value){return std::asin(value);}
inline float Extended::Acos(float value){return std::acos(value);}
inline float Extended::Atan(float value){return std::atan(value);}
inline float Extended::Exp(float value){return std::exp(value);}
inline float Extended::Log(float value){return std::log(value);}
inline float Extended::Log2(float value){return std::log2(value);}
inline float Extended::Log10(float value){return std::log10(value);}
inline float Extended::Truncate(float value){return std::trunc(value);}
inline float Extended::Fraction(float value){return value-std::floor(value);}
inline float Extended::Sign(float value){return float((value>0)-(value<0));}
inline float Extended::Square(float value){return value*value;}
inline float Extended::Cube(float value){return value*value*value;}
inline float Extended::OneMinus(float value){return 1-value;}
inline float Extended::Saturate(float value){return std::clamp(value,0.0f,1.0f);}
inline float Extended::Sinh(float value){return std::sinh(value);}
inline float Extended::Cosh(float value){return std::cosh(value);}
inline float Extended::Tanh(float value){return std::tanh(value);}
inline float Extended::Atan2(float y,float x){return std::atan2(y,x);}
inline float Extended::Modulo(float a,float b){if(b==0)throw std::invalid_argument("zero divisor");return std::fmod(a,b);}
inline float Extended::Wrap(float value,float min,float max){if(max<=min)throw std::invalid_argument("range");return min+std::fmod(std::fmod(value-min,max-min)+max-min,max-min);}
inline float Extended::InverseLerp(float a,float b,float value){if(a==b)throw std::invalid_argument("range");return (value-a)/(b-a);}
inline float Extended::MapRangeClamped(float value,float inMin,float inMax,float outMin,float outMax){return Math::Lerp(outMin,outMax,std::clamp(Math::MapRange(value,inMin,inMax,0,1),0.0f,1.0f));}
inline float Extended::EaseIn(float alpha,float exponent){return std::pow(std::clamp(alpha,0.0f,1.0f),exponent);}
inline float Extended::EaseOut(float alpha,float exponent){return 1-std::pow(1-std::clamp(alpha,0.0f,1.0f),exponent);}
inline float Extended::EaseInOut(float alpha,float exponent){float t=std::clamp(alpha,0.0f,1.0f);return t<.5f?std::pow(2*t,exponent)*.5f:1-std::pow(2*(1-t),exponent)*.5f;}
inline float Extended::FloatMoveTowards(float current,float target,float distance){float d=std::max(0.0f,distance);return current+std::clamp(target-current,-d,d);}
inline float Extended::SnapFloat(float value,float grid){if(grid<=0)throw std::invalid_argument("grid");return std::round(value/grid)*grid;}
inline bool Extended::GreaterEqual(float a,float b){return a>=b;}
inline bool Extended::LessEqual(float a,float b){return a<=b;}
inline bool Extended::InRange(float value,float min,float max){return value>=min&&value<=max;}
inline bool Extended::NearlyZero(float value,float tolerance){return std::abs(value)<=std::max(0.0f,tolerance);}
inline int Extended::IntAdd(int a,int b){return hb_detail::integer(a,b,'+');}
inline int Extended::IntSubtract(int a,int b){return hb_detail::integer(a,b,'-');}
inline int Extended::IntMultiply(int a,int b){return hb_detail::integer(a,b,'*');}
inline int Extended::IntDivide(int a,int b){return hb_detail::integer(a,b,'/');}
inline int Extended::IntModulo(int a,int b){return hb_detail::integer(a,b,'%');}
inline int Extended::BitAnd(int a,int b){return hb_detail::integer(a,b,'&');}
inline int Extended::BitOr(int a,int b){return hb_detail::integer(a,b,'|');}
inline int Extended::BitXor(int a,int b){return hb_detail::integer(a,b,'^');}
inline int Extended::IntMin(int a,int b){return std::min(a,b);}
inline int Extended::IntMax(int a,int b){return std::max(a,b);}
inline bool Extended::IntEqual(int a,int b){return a==b;}
inline bool Extended::IntNotEqual(int a,int b){return a!=b;}
inline bool Extended::IntGreater(int a,int b){return a>b;}
inline bool Extended::IntLess(int a,int b){return a<b;}
inline bool Extended::BoolXor(bool a,bool b){return a!=b;}
inline bool Extended::BoolNand(bool a,bool b){return !(a&&b);}
inline bool Extended::BoolNor(bool a,bool b){return !(a||b);}
inline Vec2 Extended::Vector2Multiply(const Vec2& a,const Vec2& b){return {a.x*b.x,a.y*b.y};}
inline Vec2 Extended::Vector2Divide(const Vec2& a,const Vec2& b){if(b.x==0||b.y==0)throw std::invalid_argument("zero component");return {a.x/b.x,a.y/b.y};}
inline Vec2 Extended::Vector2Min(const Vec2& a,const Vec2& b){return {std::min(a.x,b.x),std::min(a.y,b.y)};}
inline Vec2 Extended::Vector2Max(const Vec2& a,const Vec2& b){return {std::max(a.x,b.x),std::max(a.y,b.y)};}
inline Vec2 Extended::Vector2Abs(const Vec2& value){return {std::abs(value.x),std::abs(value.y)};}
inline Vec2 Extended::Vector2Negate(const Vec2& value){return {-value.x,-value.y};}
inline Vec2 Extended::Vector2Floor(const Vec2& value){return {std::floor(value.x),std::floor(value.y)};}
inline Vec2 Extended::Vector2Ceil(const Vec2& value){return {std::ceil(value.x),std::ceil(value.y)};}
inline bool Extended::Vector2NearlyEqual(const Vec2& a,const Vec2& b,float tolerance){return std::abs(a.x-b.x)<=std::max(0.0f,tolerance)&&std::abs(a.y-b.y)<=std::max(0.0f,tolerance);}
inline bool Extended::Vector2IsZero(const Vec2& value,float tolerance){return std::abs(value.x)<=std::max(0.0f,tolerance)&&std::abs(value.y)<=std::max(0.0f,tolerance);}
inline Vec2 Extended::Vector2Clamp(const Vec2& value,float min,float max){if(min>max)throw std::invalid_argument("range");return {std::clamp(value.x,min,max),std::clamp(value.y,min,max)};}
inline float Extended::Vector2GetX(const Vec2& value){return value.x;}
inline float Extended::Vector2GetY(const Vec2& value){return value.y;}
inline Vec3 Extended::Vector3Multiply(const Vec3& a,const Vec3& b){return {a.x*b.x,a.y*b.y,a.z*b.z};}
inline Vec3 Extended::Vector3Divide(const Vec3& a,const Vec3& b){if(b.x==0||b.y==0||b.z==0)throw std::invalid_argument("zero component");return {a.x/b.x,a.y/b.y,a.z/b.z};}
inline Vec3 Extended::Vector3Min(const Vec3& a,const Vec3& b){return {std::min(a.x,b.x),std::min(a.y,b.y),std::min(a.z,b.z)};}
inline Vec3 Extended::Vector3Max(const Vec3& a,const Vec3& b){return {std::max(a.x,b.x),std::max(a.y,b.y),std::max(a.z,b.z)};}
inline Vec3 Extended::Vector3Abs(const Vec3& value){return {std::abs(value.x),std::abs(value.y),std::abs(value.z)};}
inline Vec3 Extended::Vector3Negate(const Vec3& value){return {-value.x,-value.y,-value.z};}
inline Vec3 Extended::Vector3Floor(const Vec3& value){return {std::floor(value.x),std::floor(value.y),std::floor(value.z)};}
inline Vec3 Extended::Vector3Ceil(const Vec3& value){return {std::ceil(value.x),std::ceil(value.y),std::ceil(value.z)};}
inline bool Extended::Vector3NearlyEqual(const Vec3& a,const Vec3& b,float tolerance){return std::abs(a.x-b.x)<=std::max(0.0f,tolerance)&&std::abs(a.y-b.y)<=std::max(0.0f,tolerance)&&std::abs(a.z-b.z)<=std::max(0.0f,tolerance);}
inline bool Extended::Vector3IsZero(const Vec3& value,float tolerance){return std::abs(value.x)<=std::max(0.0f,tolerance)&&std::abs(value.y)<=std::max(0.0f,tolerance)&&std::abs(value.z)<=std::max(0.0f,tolerance);}
inline Vec3 Extended::Vector3Clamp(const Vec3& value,float min,float max){if(min>max)throw std::invalid_argument("range");return {std::clamp(value.x,min,max),std::clamp(value.y,min,max),std::clamp(value.z,min,max)};}
inline float Extended::Vector3GetX(const Vec3& value){return value.x;}
inline float Extended::Vector3GetY(const Vec3& value){return value.y;}
inline float Extended::Vector3GetZ(const Vec3& value){return value.z;}
inline Vec2 Extended::Vector2Add(const Vec2& a,const Vec2& b){return {a.x+b.x,a.y+b.y};}
inline Vec2 Extended::Vector2Subtract(const Vec2& a,const Vec2& b){return {a.x-b.x,a.y-b.y};}
inline float Extended::Vector2Dot(const Vec2& a,const Vec2& b){return a.x*b.x+a.y*b.y;}
inline float Extended::Vector2Cross(const Vec2& a,const Vec2& b){return a.x*b.y-a.y*b.x;}
inline float Extended::Vector2Distance(const Vec2& a,const Vec2& b){return std::hypot(a.x-b.x,a.y-b.y);}
inline Vec2 Extended::Vector2Lerp(const Vec2& a,const Vec2& b,float alpha){return {Math::Lerp(a.x,b.x,alpha),Math::Lerp(a.y,b.y,alpha)};}
inline Vec2 Extended::Vector2Rotate(const Vec2& value,float degrees){float r=Math::DegreesToRadians(degrees);return {value.x*std::cos(r)-value.y*std::sin(r),value.x*std::sin(r)+value.y*std::cos(r)};}
inline Vec3 Extended::RotateVector(const Vec3& value,const Vec3& rotation){return hb_detail::rotate(value,rotation,false);}
inline Vec3 Extended::UnrotateVector(const Vec3& value,const Vec3& rotation){return hb_detail::rotate(value,rotation,true);}
inline Vec3 Extended::ForwardVector(const Vec3& rotation){return hb_detail::rotate({0,0,1},rotation,false);}
inline Vec3 Extended::RightVector(const Vec3& rotation){return hb_detail::rotate({1,0,0},rotation,false);}
inline Vec3 Extended::UpVector(const Vec3& rotation){return hb_detail::rotate({0,1,0},rotation,false);}
inline float Extended::NormalizeAngle(float degrees){return hb_detail::angle(degrees);}
inline float Extended::DeltaAngle(float a,float b){return hb_detail::angle(b-a);}
inline float Extended::LerpAngle(float a,float b,float alpha){return a+hb_detail::angle(b-a)*alpha;}
inline Vec3 Extended::LookAtRotation(const Vec3& start,const Vec3& target){Vec3 d=target-start;return {Math::RadiansToDegrees(-std::atan2(d.y,std::hypot(d.x,d.z))),Math::RadiansToDegrees(std::atan2(d.x,d.z)),0};}
inline Vec3 Extended::TransformPosition(const Transform& transform,const Vec3& value){return transform.position+hb_detail::rotate({value.x*transform.scale.x,value.y*transform.scale.y,value.z*transform.scale.z},transform.rotation,false);}
inline Vec3 Extended::InverseTransformPosition(const Transform& transform,const Vec3& value){if(transform.scale.x==0||transform.scale.y==0||transform.scale.z==0)throw std::invalid_argument("zero scale");Vec3 v=hb_detail::rotate(value-transform.position,transform.rotation,true);return {v.x/transform.scale.x,v.y/transform.scale.y,v.z/transform.scale.z};}
inline Vec3 Extended::TransformDirection(const Transform& transform,const Vec3& value){return hb_detail::rotate(value,transform.rotation,false);}
inline Vec3 Extended::InverseTransformDirection(const Transform& transform,const Vec3& value){return hb_detail::rotate(value,transform.rotation,true);}
inline float Extended::ColorRed(const Color& value){return value.r;}
inline float Extended::ColorGreen(const Color& value){return value.g;}
inline float Extended::ColorBlue(const Color& value){return value.b;}
inline float Extended::ColorAlpha(const Color& value){return value.a;}
inline Color Extended::ColorLerp(const Color& a,const Color& b,float alpha){float t=std::clamp(alpha,0.0f,1.0f);return {Math::Lerp(a.r,b.r,t),Math::Lerp(a.g,b.g,t),Math::Lerp(a.b,b.b,t),Math::Lerp(a.a,b.a,t)};}
inline Color Extended::ColorMultiply(const Color& a,const Color& b){return {a.r*b.r,a.g*b.g,a.b*b.b,a.a*b.a};}
inline float Extended::ColorLuminance(const Color& value){return value.r*.2126f+value.g*.7152f+value.b*.0722f;}
inline Color Extended::ColorInvert(const Color& value){return {1-value.r,1-value.g,1-value.b,value.a};}
inline Color Extended::SRGBToLinear(const Color& value){return {hb_detail::gamma(value.r,true),hb_detail::gamma(value.g,true),hb_detail::gamma(value.b,true),value.a};}
inline Color Extended::LinearToSRGB(const Color& value){return {hb_detail::gamma(value.r,false),hb_detail::gamma(value.g,false),hb_detail::gamma(value.b,false),value.a};}
inline bool Extended::StringEqual(const std::string& a,const std::string& b){return a==b;}
inline bool Extended::StringNotEqual(const std::string& a,const std::string& b){return a!=b;}
inline bool Extended::StartsWith(const std::string& value,const std::string& search){return value.rfind(search,0)==0;}
inline bool Extended::EndsWith(const std::string& value,const std::string& search){return value.size()>=search.size()&&value.compare(value.size()-search.size(),search.size(),search)==0;}
inline bool Extended::StringIsEmpty(const std::string& value){return value.empty();}
inline int Extended::UnicodeLength(const std::string& value){return int(hb_detail::characters(value).size());}
inline std::string Extended::ReverseString(const std::string& value){auto c=hb_detail::characters(value);std::reverse(c.begin(),c.end());return hb_detail::join(c);}
inline std::string Extended::LeftString(const std::string& value,int count){return hb_detail::slice(value,0,count);}
inline std::string Extended::RightString(const std::string& value,int count){return hb_detail::slice(value,std::max(0,int(hb_detail::characters(value).size())-count),count);}
inline std::string Extended::LeftChop(const std::string& value,int count){return hb_detail::slice(value,0,std::max(0,int(hb_detail::characters(value).size())-std::max(0,count)));}
inline std::string Extended::RightChop(const std::string& value,int count){return hb_detail::slice(value,std::max(0,count),4096);}
inline std::string Extended::Substring(const std::string& value,int start,int count){return hb_detail::slice(value,start,count);}
inline int Extended::FindString(const std::string& value,const std::string& search){auto p=value.find(search);return p==std::string::npos?-1:int(hb_detail::characters(value.substr(0,p)).size());}
inline std::string Extended::ReplaceString(const std::string& value,const std::string& search,const std::string& replacement){return hb_detail::replace(value,search,replacement);}
inline std::vector<std::string> Extended::SplitString(const std::string& value,const std::string& separator){return hb_detail::split(value,separator);}
inline std::string Extended::JoinStrings(const std::vector<std::string>& values,const std::string& separator){return hb_detail::join(values,separator);}
inline std::string Extended::TrimString(const std::string& value){return hb_detail::trim(value);}
inline std::string Extended::LowerString(const std::string& value){std::string r=value;for(char& c:r)if(c>='A'&&c<='Z')c+=32;return r;}
inline std::string Extended::UpperString(const std::string& value){std::string r=value;for(char& c:r)if(c>='a'&&c<='z')c+=-32;return r;}
inline std::string Extended::IntToString(int value){return std::to_string(value);}
inline std::string Extended::BoolToString(bool value){return value?"true":"false";}
inline float Extended::IntToFloat(int value){return float(value);}
inline int Extended::FloatToInt(float value){return hb_detail::toInteger(value);}
inline int Extended::BoolToInt(bool value){return value?1:0;}
inline bool Extended::IntToBool(int value){return value!=0;}
inline Vec3 Extended::Vector2ToVector3(const Vec2& value,float z){return {value.x,value.y,z};}
inline Vec2 Extended::Vector3ToVector2(const Vec3& value){return {value.x,value.y};}
inline int Extended::ArrayBoolLength(const std::vector<bool>& array){return int(array.size());}
inline int Extended::ArrayBoolLastIndex(const std::vector<bool>& array){return int(array.size())-1;}
inline bool Extended::ArrayBoolIsEmpty(const std::vector<bool>& array){return array.empty();}
inline bool Extended::ArrayBoolIsValidIndex(const std::vector<bool>& array,int index){return index>=0&&index<int(array.size());}
inline bool Extended::ArrayBoolGet(const std::vector<bool>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayBoolFind(const std::vector<bool>& array,bool item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(bool(array[i]),item))return i;return -1;}
inline bool Extended::ArrayBoolContains(const std::vector<bool>& array,bool item){for(auto v:array)if(hb_detail::equal(bool(v),item))return true;return false;}
inline std::vector<bool> Extended::ArrayBoolReverse(const std::vector<bool>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<bool> Extended::ArrayBoolAppend(const std::vector<bool>& array,const std::vector<bool>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<bool> Extended::ArrayBoolSlice(const std::vector<bool>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<bool>(array.begin()+s,array.begin()+e);}
inline std::vector<bool> Extended::ArrayBoolUnique(const std::vector<bool>& array){std::vector<bool> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(bool(v),bool(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayIntLength(const std::vector<int>& array){return int(array.size());}
inline int Extended::ArrayIntLastIndex(const std::vector<int>& array){return int(array.size())-1;}
inline bool Extended::ArrayIntIsEmpty(const std::vector<int>& array){return array.empty();}
inline bool Extended::ArrayIntIsValidIndex(const std::vector<int>& array,int index){return index>=0&&index<int(array.size());}
inline int Extended::ArrayIntGet(const std::vector<int>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayIntFind(const std::vector<int>& array,int item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(int(array[i]),item))return i;return -1;}
inline bool Extended::ArrayIntContains(const std::vector<int>& array,int item){for(auto v:array)if(hb_detail::equal(int(v),item))return true;return false;}
inline std::vector<int> Extended::ArrayIntReverse(const std::vector<int>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<int> Extended::ArrayIntAppend(const std::vector<int>& array,const std::vector<int>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<int> Extended::ArrayIntSlice(const std::vector<int>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<int>(array.begin()+s,array.begin()+e);}
inline std::vector<int> Extended::ArrayIntUnique(const std::vector<int>& array){std::vector<int> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(int(v),int(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayFloatLength(const std::vector<float>& array){return int(array.size());}
inline int Extended::ArrayFloatLastIndex(const std::vector<float>& array){return int(array.size())-1;}
inline bool Extended::ArrayFloatIsEmpty(const std::vector<float>& array){return array.empty();}
inline bool Extended::ArrayFloatIsValidIndex(const std::vector<float>& array,int index){return index>=0&&index<int(array.size());}
inline float Extended::ArrayFloatGet(const std::vector<float>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayFloatFind(const std::vector<float>& array,float item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(float(array[i]),item))return i;return -1;}
inline bool Extended::ArrayFloatContains(const std::vector<float>& array,float item){for(auto v:array)if(hb_detail::equal(float(v),item))return true;return false;}
inline std::vector<float> Extended::ArrayFloatReverse(const std::vector<float>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<float> Extended::ArrayFloatAppend(const std::vector<float>& array,const std::vector<float>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<float> Extended::ArrayFloatSlice(const std::vector<float>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<float>(array.begin()+s,array.begin()+e);}
inline std::vector<float> Extended::ArrayFloatUnique(const std::vector<float>& array){std::vector<float> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(float(v),float(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayStringLength(const std::vector<std::string>& array){return int(array.size());}
inline int Extended::ArrayStringLastIndex(const std::vector<std::string>& array){return int(array.size())-1;}
inline bool Extended::ArrayStringIsEmpty(const std::vector<std::string>& array){return array.empty();}
inline bool Extended::ArrayStringIsValidIndex(const std::vector<std::string>& array,int index){return index>=0&&index<int(array.size());}
inline std::string Extended::ArrayStringGet(const std::vector<std::string>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayStringFind(const std::vector<std::string>& array,const std::string& item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(std::string(array[i]),item))return i;return -1;}
inline bool Extended::ArrayStringContains(const std::vector<std::string>& array,const std::string& item){for(auto v:array)if(hb_detail::equal(std::string(v),item))return true;return false;}
inline std::vector<std::string> Extended::ArrayStringReverse(const std::vector<std::string>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<std::string> Extended::ArrayStringAppend(const std::vector<std::string>& array,const std::vector<std::string>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<std::string> Extended::ArrayStringSlice(const std::vector<std::string>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<std::string>(array.begin()+s,array.begin()+e);}
inline std::vector<std::string> Extended::ArrayStringUnique(const std::vector<std::string>& array){std::vector<std::string> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(std::string(v),std::string(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayVec2Length(const std::vector<Vec2>& array){return int(array.size());}
inline int Extended::ArrayVec2LastIndex(const std::vector<Vec2>& array){return int(array.size())-1;}
inline bool Extended::ArrayVec2IsEmpty(const std::vector<Vec2>& array){return array.empty();}
inline bool Extended::ArrayVec2IsValidIndex(const std::vector<Vec2>& array,int index){return index>=0&&index<int(array.size());}
inline Vec2 Extended::ArrayVec2Get(const std::vector<Vec2>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayVec2Find(const std::vector<Vec2>& array,const Vec2& item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(Vec2(array[i]),item))return i;return -1;}
inline bool Extended::ArrayVec2Contains(const std::vector<Vec2>& array,const Vec2& item){for(auto v:array)if(hb_detail::equal(Vec2(v),item))return true;return false;}
inline std::vector<Vec2> Extended::ArrayVec2Reverse(const std::vector<Vec2>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<Vec2> Extended::ArrayVec2Append(const std::vector<Vec2>& array,const std::vector<Vec2>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<Vec2> Extended::ArrayVec2Slice(const std::vector<Vec2>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<Vec2>(array.begin()+s,array.begin()+e);}
inline std::vector<Vec2> Extended::ArrayVec2Unique(const std::vector<Vec2>& array){std::vector<Vec2> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(Vec2(v),Vec2(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayVec3Length(const std::vector<Vec3>& array){return int(array.size());}
inline int Extended::ArrayVec3LastIndex(const std::vector<Vec3>& array){return int(array.size())-1;}
inline bool Extended::ArrayVec3IsEmpty(const std::vector<Vec3>& array){return array.empty();}
inline bool Extended::ArrayVec3IsValidIndex(const std::vector<Vec3>& array,int index){return index>=0&&index<int(array.size());}
inline Vec3 Extended::ArrayVec3Get(const std::vector<Vec3>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayVec3Find(const std::vector<Vec3>& array,const Vec3& item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(Vec3(array[i]),item))return i;return -1;}
inline bool Extended::ArrayVec3Contains(const std::vector<Vec3>& array,const Vec3& item){for(auto v:array)if(hb_detail::equal(Vec3(v),item))return true;return false;}
inline std::vector<Vec3> Extended::ArrayVec3Reverse(const std::vector<Vec3>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<Vec3> Extended::ArrayVec3Append(const std::vector<Vec3>& array,const std::vector<Vec3>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<Vec3> Extended::ArrayVec3Slice(const std::vector<Vec3>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<Vec3>(array.begin()+s,array.begin()+e);}
inline std::vector<Vec3> Extended::ArrayVec3Unique(const std::vector<Vec3>& array){std::vector<Vec3> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(Vec3(v),Vec3(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayColorLength(const std::vector<Color>& array){return int(array.size());}
inline int Extended::ArrayColorLastIndex(const std::vector<Color>& array){return int(array.size())-1;}
inline bool Extended::ArrayColorIsEmpty(const std::vector<Color>& array){return array.empty();}
inline bool Extended::ArrayColorIsValidIndex(const std::vector<Color>& array,int index){return index>=0&&index<int(array.size());}
inline Color Extended::ArrayColorGet(const std::vector<Color>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayColorFind(const std::vector<Color>& array,const Color& item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(Color(array[i]),item))return i;return -1;}
inline bool Extended::ArrayColorContains(const std::vector<Color>& array,const Color& item){for(auto v:array)if(hb_detail::equal(Color(v),item))return true;return false;}
inline std::vector<Color> Extended::ArrayColorReverse(const std::vector<Color>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<Color> Extended::ArrayColorAppend(const std::vector<Color>& array,const std::vector<Color>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<Color> Extended::ArrayColorSlice(const std::vector<Color>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<Color>(array.begin()+s,array.begin()+e);}
inline std::vector<Color> Extended::ArrayColorUnique(const std::vector<Color>& array){std::vector<Color> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(Color(v),Color(p)))found=true;if(!found)r.push_back(v);}return r;}
inline int Extended::ArrayTransformLength(const std::vector<Transform>& array){return int(array.size());}
inline int Extended::ArrayTransformLastIndex(const std::vector<Transform>& array){return int(array.size())-1;}
inline bool Extended::ArrayTransformIsEmpty(const std::vector<Transform>& array){return array.empty();}
inline bool Extended::ArrayTransformIsValidIndex(const std::vector<Transform>& array,int index){return index>=0&&index<int(array.size());}
inline Transform Extended::ArrayTransformGet(const std::vector<Transform>& array,int index){if(index<0||index>=int(array.size()))throw std::out_of_range("array index");return array[index];}
inline int Extended::ArrayTransformFind(const std::vector<Transform>& array,const Transform& item){for(int i=0;i<int(array.size());i++)if(hb_detail::equal(Transform(array[i]),item))return i;return -1;}
inline bool Extended::ArrayTransformContains(const std::vector<Transform>& array,const Transform& item){for(auto v:array)if(hb_detail::equal(Transform(v),item))return true;return false;}
inline std::vector<Transform> Extended::ArrayTransformReverse(const std::vector<Transform>& array){auto r=array;std::reverse(r.begin(),r.end());return r;}
inline std::vector<Transform> Extended::ArrayTransformAppend(const std::vector<Transform>& array,const std::vector<Transform>& other){auto r=array;r.insert(r.end(),other.begin(),other.end());if(r.size()>128)throw std::length_error("array limit");return r;}
inline std::vector<Transform> Extended::ArrayTransformSlice(const std::vector<Transform>& array,int start,int count){int s=std::clamp(start,0,int(array.size())),e=s+std::min(std::max(0,count),int(array.size())-s);return std::vector<Transform>(array.begin()+s,array.begin()+e);}
inline std::vector<Transform> Extended::ArrayTransformUnique(const std::vector<Transform>& array){std::vector<Transform> r;for(auto v:array){bool found=false;for(auto p:r)if(hb_detail::equal(Transform(v),Transform(p)))found=true;if(!found)r.push_back(v);}return r;}
}
