import {createRigidPhysics,validPhysicsSnapshot} from '../physics-world.js';
import {makeSceneComponent as component} from '../scene-components.js';
import {Scene} from 'three';
import {CollisionPreview} from '../collision-preview.js';

export async function physicsCases(){
  let assertions=0;const check=(condition,message)=>{if(!condition)throw Error(message);assertions++;},near=(a,b,tolerance=.02)=>Math.abs(a-b)<tolerance;
  const object=(id,dim,shape='Box',properties={},body=null)=>({id,name:id,kind:'empty',visible:true,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],components:[component(dim===2?shape==='Sphere'?'CircleCollider2D':shape+'Collider2D':shape+'Collider',properties,'collider'),...(body===null?[]:[component(dim===2?'Rigidbody2D':'Rigidbody',{useGravity:false,...body},'body')])]});
  const worlds=[];const create=async(objects,options={})=>{const p=createRigidPhysics(objects,options);worlds.push(p);await p.ready();return p;},run=(p,n)=>{for(let i=0;i<n;i++)p.step(1/60);};
  try{
    for(const dim of [2,3]){
      const fixed=object('fixed-skip',dim,'Box',{}, {bodyType:'static'}),sleeper=object('sleep-skip',dim,'Box',{}, {useGravity:false});sleeper.position=[5,0,0];let mirrors=0;const quiet=await create([fixed,sleeper],{update:()=>mirrors++});quiet.sleeping(sleeper,true);run(quiet,1);mirrors=0;run(quiet,8);check(mirrors===0,dim+'D static and sleeping bodies skip unchanged object updates');fixed.position[0]=2;quiet.step(1/60);check(near(quiet.inspect().dimensions.find(d=>d.dimension===dim).bodies.find(b=>b.id===fixed.id).position[0],2),dim+'D fixed teleport remains visible');quiet.applyForce(sleeper,[1,0,0],'velocityChange');quiet.step(1/60);check(mirrors>0&&sleeper.position[0]>5,dim+'D force wakes and resumes body updates');

      quiet.writeBatch(()=>{quiet.velocity(sleeper,[2,0,0]);quiet.applyForce(sleeper,[1,0,0],'velocityChange');check(near(sleeper.velocity[0],3),dim+'D consecutive velocity/force write order');quiet.sleeping(sleeper,true);quiet.sleeping(sleeper,false);});check(sleeper.gameplayDebug.physics.sleeping===false,dim+'D sleep/wake write order');
      let batchFailed=false;try{quiet.writeBatch(()=>{quiet.velocity(sleeper,[1,0,0]);throw Error('batch probe');});}catch{batchFailed=true;}quiet.writeBatch(()=>quiet.velocity(sleeper,[4,0,0]));check(batchFailed&&near(sleeper.velocity[0],4),dim+'D failed write batch releases its sync scope');
      fixed.rotation[2]=45;fixed.scale[0]=2;quiet.query('physicsOverlapSphere',{center:[2,0,0],radius:.1,dimension:dim});check(quiet.query('physicsRaycast',{start:[4,.9,0],end:[2,.9,0],dimension:dim}).actor===fixed.id,dim+'D cached root pose sees in-place rotation/scale');
      const poseParent={id:'cache-parent',kind:'empty',position:[3,0,0],rotation:[0,0,0],scale:[1,1,1],components:[]};const poseObjects=[poseParent,fixed];fixed.parent=poseParent.id;const reparented=await create(poseObjects);check(near(reparented.inspect().dimensions.find(d=>d.dimension===dim).bodies[0].position[0],5),dim+'D parent pose bypasses root cache');poseParent.position[0]=6;check(near(reparented.inspect().dimensions.find(d=>d.dimension===dim).bodies[0].position[0],8),dim+'D in-place parent move remains visible');delete fixed.parent;check(near(reparented.inspect().dimensions.find(d=>d.dimension===dim).bodies[0].position[0],2),dim+'D detaching restores root pose');
      const capsule=object('capsule',dim,'Capsule',{radius:.5,height:2}),box=object('rotated',dim,'Box',{extent:[2,.2,.2]});box.position=[5,0,0];box.rotation=[0,0,45];
      const trigger=object('trigger',dim,'Sphere',{trigger:true,layer:31});trigger.position=[10,0,0];const physicsOnly=object('physics-only',dim,'Sphere',{collisionMode:'physics'});physicsOnly.position=[15,0,0];
      const p=await create([capsule,box,trigger,physicsOnly]);
      const ray=(start,end,extra={})=>p.query('physicsRaycast',{start,end,dimension:dim,...extra});
      check(!ray([.49,.9,0],[.49,1.2,0]).hit,dim+'D capsule corner is not its bounding box');
      check(ray([0,3,0],[0,-3,0]).actor==='capsule',dim+'D capsule ray before the first simulation step');
      const rotated=ray([6.2,-3,0],[6.2,3,0]);check(rotated.actor==='rotated'&&Math.abs(rotated.normal[0])>.6,dim+'D rotated box normal');
      check(!ray([10,2,0],[10,-2,0]).hit,dim+'D default excludes triggers');
      check(ray([10,2,0],[10,-2,0],{includeTriggers:true,mask:0x80000000}).actor==='trigger',dim+'D 32-bit layer 31 query');
      check(!ray([0,3,0],[0,-3,0],{ignore:'capsule'}).hit,dim+'D ignore actor');check(!ray([15,3,0],[15,-3,0]).hit,dim+'D physics-only excluded from queries');
      check(p.query('physicsRaycastAll',{start:[-3,0,0],end:[8,0,0],dimension:dim}).length===2,dim+'D ray all returns sorted intersections');
      const sphere=p.query('physicsSphereCast',{start:[0,3,0],end:[0,-3,0],radius:.2,dimension:dim});check(sphere.actor==='capsule'&&near(sphere.position[1],1,.05)&&sphere.normal[1]>.9,dim+'D sphere cast world witness and normal');
      const cast=p.query('physicsBoxCast',{start:[0,3,0],end:[0,-3,0],extent:[.2,.2,.2],rotation:[0,0,25],dimension:dim});check(cast.actor==='capsule',dim+'D rotated box cast');
      check(p.query('physicsOverlapSphere',{center:[0,0,0],radius:.2,dimension:dim}).includes('capsule'),dim+'D exact overlap sphere');
      check(p.query('physicsOverlapBox',{center:[10,0,0],extent:[1,1,1],rotation:[0,0,45],includeTriggers:true,dimension:dim}).includes('trigger'),dim+'D rotated overlap box');
      check(p.query('physicsClosestPoint',{point:[0,3,0],dimension:dim}).actor==='capsule',dim+'D closest point');
      capsule.position=[20,0,0];check(!ray([0,3,0],[0,-3,0]).hit,dim+'D teleport reflected immediately');capsule.components[0].properties.enabled=false;check(!ray([20,3,0],[20,-3,0]).hit,dim+'D collider disable reflected immediately');
      const body=object('mass',dim,'Box',{}, {mass:7});body.components.push(component(dim===2?'CircleCollider2D':'SphereCollider',{center:[1,0,0]},'second'));
      const w=await create([body]);check(near(body.gameplayDebug.physics.mass,7,.001),dim+'D compound mass');body.components[1].properties.mass=7;body.components[0].properties.extent=[1,1,1];w.inspect();check(near(body.gameplayDebug.physics.mass,7,.001),dim+'D resizing retains manual mass');
      for(const [mode,expected] of [['force',1/60],['acceleration',7/60],['impulse',1],['velocityChange',7]]){w.velocity(body,[0,0,0]);w.applyForce(body,[7,0,0],mode);w.step(1/60);check(near(body.velocity[0],expected,.003),dim+'D '+mode+' mass/time semantics');}
      w.velocity(body,[0,0,0]);w.applyForce(body,[0,7,0],'impulse',[2,0,0]);check(Math.abs(body.angularVelocity[2])>.1,dim+'D off-center impulse creates angular velocity');
      w.angularVelocity(body,[0,0,2]);run(w,10);check(Math.abs(body.rotation[2])>1,dim+'D angular motion updates scene rotation');w.sleeping(body,true);check(body.gameplayDebug.physics.sleeping,dim+'D explicit sleep');w.sleeping(body,false);check(!body.gameplayDebug.physics.sleeping,dim+'D wake');
      body.components[1].properties.freezePosition=[1,0,dim===2?1:0];body.components[1].properties.freezeRotation=[1,1,1];w.angularVelocity(body,[0,0,2]);w.velocity(body,[20,0,0]);const x=body.position[0],rotation=body.rotation[2];run(w,5);check(near(body.position[0],x,.001)&&near(body.rotation[2],rotation,.001),dim+'D axis constraints');
      const ground=object('ground',dim,'Box',{extent:[4,.1,4]}),fall=object('fall',dim,'Sphere',{}, {useGravity:true});ground.position=[0,-.1,0];fall.position=[0,3,0];const g=await create([ground,fall]);run(g,160);check(near(fall.position[1],.5,.02)&&fall.grounded,dim+'D gravity and resting contacts');
      const wall=object('wall',dim,'Box',{extent:[.02,4,4]}),bullet=object('bullet',dim,'Sphere',{radius:.1},{velocity:[1000,0,0],collisionDetection:'continuous'});bullet.position=[-5,0,0];const ccd=await create([wall,bullet]);ccd.step(1/60);check(bullet.position[0]<.2,dim+'D CCD prevents tunneling');
      const forceBody=object('constant',dim,'Box',{}, {mass:2});forceBody.components.push(component(dim===2?'ConstantForce2D':'ConstantForce',{force:[6,0,0]},'force'));const forceWorld=await create([forceBody]);forceWorld.step(.1);check(near(forceBody.velocity[0],.3,.005),dim+'D constant force does not accumulate across substeps');
      forceBody.components[2].properties.force=[0,0,0];forceWorld.sleeping(forceBody,true);forceWorld.force(forceBody,[0,0,0]);forceWorld.step(1/60);check(forceBody.gameplayDebug.physics.sleeping,dim+'D zero forces preserve sleep');
      const dense=object('dense',dim,'Box',{physicalMaterial:'Assets/Dense.hbphysicalmaterial.json'}, {autoMass:true}),densityWorld=createRigidPhysics([dense]);worlds.push(densityWorld);await densityWorld.loadMaterials(async()=>({version:1,friction:0,restitution:0,density:3,frictionCombine:'min',restitutionCombine:'average'}));check(near(dense.gameplayDebug.physics.mass,3,.001),dim+'D physical material density controls automatic mass');
      const bare=object('bare',dim,'Box',{}, {autoMass:true,mass:3});bare.components.shift();const bareWorld=await create([bare]);check(near(bare.gameplayDebug.physics.mass,3,.001),dim+'D automatic mass without shapes falls back to configured mass');bareWorld.impulse(bare,[3,0,0]);bareWorld.step(1/60);check(near(bare.velocity[0],1,.001),dim+'D body without a collider still responds to linear impulses');bare.components.push(component(dim===2?'BoxCollider2D':'BoxCollider',{density:2},'added-shape'));bareWorld.inspect();check(near(bare.gameplayDebug.physics.mass,2,.001),dim+'D adding shape replaces fallback mass with density mass');bare.components.pop();bareWorld.inspect();check(near(bare.gameplayDebug.physics.mass,3,.001),dim+'D removing last shape restores configured mass');
      const sensor=object('sensor-mass',dim,'Box',{trigger:true,density:2},{autoMass:true}),sensorWorld=await create([sensor]);check(near(sensor.gameplayDebug.physics.mass,2,.001),dim+'D sensor geometry contributes automatic mass');sensorWorld.torque(sensor,[0,0,1],true);sensorWorld.step(1/60);check(sensor.angularVelocity[2]>.1,dim+'D sensor-only rigid body has angular inertia');
      const maskGround=object('mask-ground',dim,'Box',{extent:[4,.1,4],layer:31,mask:1}),maskFall=object('mask-fall',dim,'Sphere',{mask:0}, {useGravity:true});maskFall.position=[0,3,0];const masks=await create([maskGround,maskFall]);run(masks,100);check(maskFall.position[1]< -2,dim+'D collision masks disable solver contacts');maskFall.position=[0,3,0];masks.velocity(maskFall,[0,0,0]);maskFall.components[0].properties.mask=0x80000000;run(masks,120);check(maskFall.position[1]>.5&&maskFall.grounded,dim+'D collision mask includes layer 31 in solver');
      const kinematic=object('kinematic',dim,'Box',{}, {bodyType:'kinematic',useGravity:true}),kin=await create([kinematic]);kinematic.position=[4,3,0];kin.step(1/60);check(near(kinematic.position[0],4)&&near(kinematic.position[1],3),dim+'D kinematic transform control ignores gravity');
      for(const jointType of ['fixed','hinge','slider','spring','rope','ball']){
        const held=object('joint-'+jointType,dim,'Box',{}, {useGravity:true});held.position=[0,2,0];held.components.push(component(dim===2?'PhysicsConstraint2D':'PhysicsConstraint',{jointType,axis:[1,0,0],enableLimit:['hinge','slider'].includes(jointType),lowerLimit:-.1,upperLimit:.1,useMotor:['hinge','slider'].includes(jointType),motorPosition:0,motorVelocity:0},'joint'));
        const j=await create([held]);run(j,60);check(j.inspect().dimensions.find(d=>d.dimension===dim).joints.length===1,dim+'D '+jointType+' constructed');check(held.position[1]>(['spring','rope'].includes(jointType)?.7:1.7),dim+'D '+jointType+' constrains falling body');
        held.components.pop();j.step(1/60);check(!j.inspect().dimensions.find(d=>d.dimension===dim).joints.length,dim+'D removing joint releases it');
      }
      const driven=object('motor-hinge',dim,'Box',{}, {useGravity:false});driven.components.push(component(dim===2?'PhysicsConstraint2D':'PhysicsConstraint',{jointType:'hinge',axis:[0,0,1],useMotor:true,motorVelocity:90,motorStiffness:0,motorDamping:10},'motor'));const motorWorld=await create([driven]);run(motorWorld,60);check(driven.rotation[2]>40,dim+'D hinge motor converts degree velocity to actual angular drive');
      const sliding=object('motor-slider',dim,'Box',{}, {useGravity:false});sliding.components.push(component(dim===2?'PhysicsConstraint2D':'PhysicsConstraint',{jointType:'slider',axis:[1,0,0],useMotor:true,motorPosition:1,motorStiffness:100,motorDamping:10,enableLimit:true,lowerLimit:-2,upperLimit:2},'motor'));const sliderWorld=await create([sliding]);run(sliderWorld,90);check(near(sliding.position[0],1,.05),dim+'D slider motor drives linear position');
      const a=object('pair-a',dim,'Box',{}, {useGravity:true}),b=object('pair-b',dim,'Box',{},{useGravity:true});a.position=[-2,2,0];b.position=[2,2,0];a.components.push(component(dim===2?'PhysicsConstraint2D':'PhysicsConstraint',{connectedBody:b.id},'paired'));const linked=await create([a,b]);run(linked,30);check(near(b.position[0]-a.position[0],4,.03)&&near(a.position[1],b.position[1],.03),dim+'D connected body anchors');linked.objects.splice(1,1);linked.step(1/60);const linkedState=linked.inspect().dimensions.find(d=>d.dimension===dim);check(linkedState.bodies.length===1&&linkedState.joints.length===0,dim+'D destroy connected body safely removes joint');
      const parent={id:'parent',kind:'empty',name:'Parent',position:[3,0,0],rotation:[0,0,30],scale:[2,2,2],components:[]},child=object('child',dim,'Sphere',{}, {useGravity:true});child.parent=parent.id;child.position=[0,3,0];const hierarchy=await create([parent,child]);const before=hierarchy.inspect().dimensions.find(d=>d.dimension===dim).bodies[0].position[1];run(hierarchy,10);check(hierarchy.inspect().dimensions.find(d=>d.dimension===dim).bodies[0].position[1]<before,dim+'D parent/local/world simulation');
      const controlled=object('controlled',dim,'Box',{}, {useGravity:false});controlled.components.push(component(dim===2?'TopDownMovement2D':'PawnMovement',{speed:6,acceleration:1000},'movement'));
      const controlWorld=await create([controlled]);controlWorld.movement(controlled,[1,0,0]);controlWorld.step(1/60);
      check(near(controlled.position[0],.1,.001)&&near(controlled.velocity[0],6,.001),dim+'D movement changes backend velocity before the same solver step');
      check(near(controlled.gameplayDebug.physics.velocity[0],6,.001),dim+'D movement mirror is current after the step');
      const movingParent={id:'moving-parent',kind:'empty',name:'Moving parent',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],components:[component(dim===2?'TopDownMovement2D':'PawnMovement',{speed:60,acceleration:1000},'movement')]};
      const attached=object('attached-trigger',dim,'Box',{extent:[.1,.1,.1],trigger:true}),stationary=object('stationary-trigger',dim,'Box',{extent:[.1,.1,.1],trigger:true});attached.parent=movingParent.id;stationary.position=[1,0,0];
      const movingHierarchy=await create([movingParent,attached,stationary]);movingHierarchy.movement(movingParent,[1,0,0]);movingHierarchy.step(1/60);
      check(near(movingParent.position[0],1,.001),dim+'D movement without a Rigidbody changes scene pose');
      check(movingHierarchy.contacts().some(c=>[c.a,c.b].includes(attached.id)&&[c.a,c.b].includes(stationary.id)),dim+'D child collider observes parent movement in the same step without a later query/inspect sync');
      const scene=new Scene(),preview=new CollisionPreview(scene);preview.update([box],new Set([box.id]));check(preview.items.size===1&&near([...preview.items.values()][0].quaternion.z,Math.sin(Math.PI/8),.001),dim+'D oriented edit preview');preview.update([box],new Set(),{all:true,physicsDebug:p.debug()});const attribute=preview.runtime.get(dim).geometry.attributes.position;check(attribute.count>0&&Number.isInteger(attribute.count)&&attribute.array.every(Number.isFinite),dim+'D actual physics debug vertices');preview.dispose();
      check(validPhysicsSnapshot([body]),dim+'D query snapshot validates');const cyclic=structuredClone(body);cyclic.parent=cyclic.id;check(!validPhysicsSnapshot([cyclic]),dim+'D cyclic snapshot rejected');
      const invalid=structuredClone(body);invalid.components[1].properties.angularDrag=-1;check(!validPhysicsSnapshot([invalid]),dim+'D malformed body configuration rejected at query boundary');
    }
    return {assertions,dimensions:[2,3],backend:'Rapier 0.21.0'};
  }finally{for(const p of worlds)p.dispose();}
}
