import assert from 'node:assert/strict';
import { defaultObjects, defaultSurface, defaultEnvironment, validScene, fileKind, clone } from '../prototype/model.js';
import { defaultBlueprint, validBlueprint, canConnect, connect, splitPin, effectivePins, makeNode, collapseNodes, graphContext, catalog, makeComment, makeDefinition } from '../prototype/blueprint-model.js';
import {defaultDockRatio} from '../prototype/dock-layout.js';
assert.ok((720-110)*defaultDockRatio(720)>=360,'작은 화면도 주 작업창 높이를 360px 이상 확보해요.');assert.ok(defaultDockRatio(1080)>defaultDockRatio(720),'큰 화면은 주 작업창을 넓게 배치해요.');

const scene = { version: 1, objects: clone(defaultObjects), surface: clone(defaultSurface) };
assert.ok(validScene(JSON.parse(JSON.stringify(scene))), '기본 장면 저장/복원');
const broken = clone(scene);
broken.objects[0].position[1] = null;
assert.equal(validScene(broken), false, '손상된 숫자 거부');
broken.objects = [scene.objects[0], scene.objects[0]];
assert.equal(validScene(broken), false, '중복 ID 거부');
assert.equal(validScene({ ...scene, surface: { ...scene.surface, color: '<script>' } }), false, '손상된 색 거부');
assert.equal(fileKind('MyTexture.JPG'), 'texture');
assert.equal(fileKind('character.glb'), 'model');
assert.equal(fileKind('intro.avi'), 'media');
assert.equal(fileKind('tool.exe'), 'unsupported');
const copy = clone(scene);
copy.objects[0].position[0] = 42;
assert.equal(scene.objects[0].position[0], 0, '실행용 복사본과 편집 장면 분리');
console.log('HBEngine UI: 저장 데이터 검증, 파일 분류, 실행용 장면 분리 검사 통과');
const fullScene = {...scene, sceneName:'Garden', environment:clone(defaultEnvironment), blueprint:clone(defaultBlueprint)};
assert.ok(validScene(fullScene), '환경과 블루프린트 저장 데이터');
const noShadows=clone(fullScene);noShadows.environment.shadowEnabled=false;assert.ok(validScene(JSON.parse(JSON.stringify(noShadows))),'그림자 끄기 저장/복원');delete noShadows.environment.shadowEnabled;assert.ok(validScene(noShadows),'기존 장면 그림자 설정 호환');noShadows.environment.shadowEnabled='false';assert.equal(validScene(noShadows),false,'잘못된 그림자 설정 거부');
assert.equal(validScene({...fullScene,environment:{...defaultEnvironment,cloudDensity:2}}),false,'구름 설정 범위 검사');
const graph=clone(defaultBlueprint);
assert.ok(validBlueprint(graph),'기본 이벤트 그래프');
assert.equal(canConnect(graph,{node:'tick',pin:'delta'},{node:'branch',pin:'condition'}).ok,false,'Float → Bool 연결 거부');
assert.ok(splitPin(graph,'location','out','return'),'Vector3 핀 분할');
assert.deepEqual(effectivePins(graph.nodes.find(n=>n.id==='location'),'out',graph).map(p=>p.id),['return.x','return.y','return.z']);
assert.ok(validBlueprint(graph),'분할된 그래프 저장 검증');
assert.ok(splitPin(graph,'location','out','return',true),'분할 핀 합치기');
const set=makeNode('setVariable',700,40,'targetPosition');graph.nodes.push(set);
assert.ok(connect(graph,{node:'location',pin:'return'},{node:set.id,pin:'value'}).ok,'Vector3 타입 연결');
const array=makeNode('getVariable',700,200,'waypoints');graph.nodes.push(array);
assert.equal(canConnect(graph,{node:array.id,pin:'value'},{node:set.id,pin:'value'}).ok,false,'Vector3 배열 → 단일 값 연결 거부');
assert.ok(validBlueprint(JSON.parse(JSON.stringify(graph))),'AI JSON 왕복 저장');
const invalidGraph=clone(graph);invalidGraph.nodes[0].id='" onclick="x';
assert.equal(validBlueprint(invalidGraph),false,'손상된 노드 ID 거부');
assert.equal(validBlueprint({...graph,nodes:[null]}),false,'누락된 노드 데이터 거부');
console.log('HBEngine Blueprint: 이벤트, 타입 연결, 배열, 핀 분할/합치기, JSON 검증 통과');
const grouped=clone(defaultBlueprint);
const fn=collapseNodes(grouped,grouped,['print'],'function','시작 메시지');
assert.ok(fn.ok,'노드를 함수로 묶기');assert.ok(validBlueprint(grouped),'묶은 함수 그래프 저장 검증');
assert.ok(grouped.edges.some(e=>e.from.node==='begin'&&e.to.node===fn.call.id),'외부 실행 연결 보존');
const fnGraph=graphContext(grouped,fn.definition.id);
assert.ok(fnGraph.nodes.some(n=>n.key==='functionInput')&&fnGraph.nodes.some(n=>n.key==='functionOutput'),'함수 입출력 터널');
assert.ok(fnGraph.edges.some(e=>e.to.node==='print'),'함수 내부 연결 보존');
fnGraph.nodes.push(makeNode('vec2',900,100));assert.equal(fn.definition.graph.nodes.length,4,'내부 그래프 편집 원본 반영');
const macro=collapseNodes(grouped,grouped,['branch','door','getKey'],'macro','문 상호작용');
assert.ok(macro.ok,'여러 실행 출력은 매크로로 묶기');assert.ok(validBlueprint(JSON.parse(JSON.stringify(grouped))),'함수·매크로·Construction JSON 왕복');
assert.ok(grouped.edges.some(e=>e.from.node==='overlap'&&e.to.node===macro.call.id),'매크로 외부 연결 보존');
const rejected=clone(defaultBlueprint),before=JSON.stringify(rejected);
assert.equal(collapseNodes(rejected,rejected,['branch'],'function','잘못된 함수').ok,false,'복수 실행 반환은 함수 묶기 거부');
assert.equal(JSON.stringify(rejected),before,'실패한 묶기는 원본 보존');
assert.equal(collapseNodes(rejected,rejected,['begin'],'macro','이벤트').ok,false,'이벤트 묶기 거부');
const badDefinition=clone(grouped);badDefinition.functions[0].graph.edges[0].to.pin='missing';assert.equal(validBlueprint(badDefinition),false,'내부 그래프 손상 거부');
const construction=graphContext(grouped,'construction');construction.edges=[];assert.equal(grouped.construction.edges.length,0,'Construction 연결 독립 편집');assert.equal(grouped.edges.length,2,'이벤트 그래프 보존');
console.log('HBEngine Blueprint: 함수·매크로 추출, 경계 연결 보존, 내부 편집, Construction 분리 검사 통과');
const interleaved=clone(defaultBlueprint);interleaved.nodes=interleaved.nodes.filter(n=>['begin','print','door'].includes(n.id));const between=makeNode('sound',400,40);interleaved.nodes.push(between);interleaved.edges=[{from:{node:'begin',pin:'then'},to:{node:'print',pin:'exec'}},{from:{node:'print',pin:'then'},to:{node:between.id,pin:'exec'}},{from:{node:between.id,pin:'then'},to:{node:'door',pin:'exec'}}];
const original=JSON.stringify(interleaved);assert.equal(collapseNodes(interleaved,interleaved,['print','door'],'function','외부 노드 교차').ok,false,'묶기 때문에 생기는 순환 거부');assert.equal(JSON.stringify(interleaved),original,'교차 선택 실패 시 원본 연결 보존');
const generic=clone(defaultBlueprint),length=makeNode('arrayLength');generic.nodes.push(length);assert.ok(collapseNodes(generic,generic,[length.id],'function','배열 길이').ok);assert.ok(validBlueprint(generic),'범용 배열 핀 묶기 저장');
assert.equal(new Set(catalog.map(s=>s.key)).size,catalog.length,'노드 등록 키 중복 방지');assert.ok(catalog.length>=100,'확장 기본 노드');
const edited=clone(defaultBlueprint),node=makeNode('setPosition',-200,-100);node.inputValues={target:'self',position:[1,2,3]};edited.nodes.push(node);
edited.comments=[makeComment(edited,[node.id])];edited.comments[0].text='이동 처리';edited.components[2].properties={extent:[2,1,2],trigger:true};edited.settings={parentClass:'Actor',tickEnabled:true,tickInterval:.1,overlapEnabled:true};
assert.ok(validBlueprint(edited),'노드 입력값·주석·음수 좌표·컴포넌트·클래스 기본값 저장');
assert.ok(splitPin(edited,node.id,'in','position'));assert.equal(node.inputValues['position.x'],1,'입력 벡터 분할 시 기본값 보존');node.inputValues['position.x']=4;assert.ok(validBlueprint(edited));assert.ok(splitPin(edited,node.id,'in','position',true));assert.deepEqual(node.inputValues.position,[4,2,3],'합치기 시 편집값 보존');
const empty=makeDefinition(edited,'function','새 함수');assert.ok(empty.ok);assert.ok(validBlueprint(edited),'빈 사용자 함수 생성');
const typedArray=makeNode('arrayGet',30,800);typedArray.valueType='vec3';typedArray.inputValues={array:[[1,2,3]],index:0};edited.nodes.push(typedArray);assert.equal(effectivePins(typedArray,'out',edited)[0].type,'vec3');assert.ok(validBlueprint(edited),'배열 노드 원소 타입 편집');
const badInput=clone(edited);badInput.nodes.find(n=>n.id===node.id).inputValues.position='wrong';assert.equal(validBlueprint(badInput),false,'잘못된 노드 기본값 거부');
const badComment=clone(edited);badComment.comments[0].size.width=-1;assert.equal(validBlueprint(badComment),false,'손상된 주석 크기 거부');
console.log(`HBEngine Blueprint: ${catalog.length}개 노드, 상세 속성, 주석 저장 검사 통과`);
const {parseNativeHeader,nativeExample,nativeEntries,validNative}=await import('../prototype/native-model.js');
const exposed=clone(defaultBlueprint);exposed.native={...parseNativeHeader(nativeExample),header:nativeExample};exposed.settings={parentClass:'DoorController',nativeDefaults:{'DoorController.OpenAngle':120}};
assert.equal(exposed.native.classes[0].functions.length,4,'C++ 헤더의 함수 노출');assert.equal(exposed.native.classes[0].properties[0].value,90,'C++ 속성 기본값 읽기');
assert.equal(nativeEntries(exposed).length,7,'호출·순수 함수·재정의·Get/Set 등록');
const nativeEvent={...makeNode('nativeEvent'),nativeId:'DoorController.OnOpened'},nativePure={...makeNode('nativeCall',300,30),nativeId:'DoorController.GetDoorPosition'};exposed.nodes.push(nativeEvent,nativePure);
assert.equal(effectivePins(nativeEvent,'out',exposed)[1].type,'vec3','C++ 이벤트 인자를 출력 핀으로 노출');assert.ok(!effectivePins(nativePure,'in',exposed).some(p=>p.type==='exec'),'C++ 순수 함수 실행 핀 없음');
assert.ok(splitPin(exposed,nativePure.id,'out','result'));assert.deepEqual(effectivePins(nativePure,'out',exposed).map(p=>p.label),['X','Y','Z'],'C++ 벡터 반환값 분할');
assert.ok(validBlueprint(JSON.parse(JSON.stringify(exposed))),'C++ 상속·공개 노드·반환 분할 JSON 왕복');
const badNative=clone(exposed);badNative.native.classes[0].properties[0].readOnly=true;badNative.nodes.push({...makeNode('nativeSet'),nativeId:'DoorController.OpenAngle'});assert.equal(validBlueprint(badNative),false,'읽기 전용 C++ 속성 쓰기 거부');
const orphan=clone(exposed);orphan.native.classes[0].functions=[];assert.equal(validBlueprint(orphan),false,'등록 변경 시 기존 노드의 서명 누락 거부');
const wrongParent=clone(exposed);wrongParent.settings.parentClass='Actor';assert.equal(validBlueprint(wrongParent),false,'부모가 아닌 C++ 이벤트 재정의 거부');
assert.throws(()=>parseNativeHeader(nativeExample.replace('float Angle','Mystery Angle')),/자료형/,'미지원 공개 타입을 조용히 누락하지 않음');
assert.throws(()=>parseNativeHeader(nativeExample.replace('void Open(float Angle);','void Open(float Angle) { }')),/헤더 선언/,'함수 본문을 헤더 분석기로 실행하지 않음');
assert.throws(()=>parseNativeHeader(nativeExample.replace('OpenAngle = 90.0f','OpenAngle = dangerous()')),/기본값/,'C++ 초기화 표현식 실행 금지');
assert.equal(validNative({version:1,classes:[null]}),false,'손상된 C++ 등록 데이터 거부');
const signal={id:'signal_test',name:'OnChanged',inputs:[{id:'position',label:'Position',type:'vec3',array:false}],outputs:[]};exposed.dispatchers=[signal];exposed.interfaces=[{id:'interface_test',name:'Interact',inputs:[],outputs:[{id:'accepted',label:'Accepted',type:'bool',array:false}]}];
const signalNode={...makeNode('dispatcherEvent'),symbolId:signal.id},messageNode={...makeNode('interfaceCall'),symbolId:'interface_test'};exposed.nodes.push(signalNode,messageNode);assert.equal(effectivePins(signalNode,'out',exposed)[1].type,'vec3','디스패처 시그니처 핀');assert.equal(effectivePins(messageNode,'out',exposed)[1].type,'bool','인터페이스 반환 핀');assert.ok(validBlueprint(exposed),'디스패처·인터페이스 정의 저장');
const badSignal=clone(exposed);badSignal.dispatchers[0].inputs[0].id='target';assert.equal(validBlueprint(badSignal),false,'시그니처 예약 핀 ID 충돌 거부');
console.log('HBEngine C++: 헤더 등록, 상속 기본값, 순수 함수, 이벤트 재정의, 디스패처·인터페이스 검사 통과');
const {pasteNodes,validTimeline,sampleTimeline}=await import('../prototype/blueprint-model.js');
const timeline=makeNode('timeline');exposed.nodes.push(timeline);assert.ok(validTimeline(timeline.timeline));assert.equal(sampleTimeline(timeline.timeline.tracks[0],.5),.5,'타임라인 중간 보간');timeline.timeline.tracks[0].interpolation='step';assert.equal(sampleTimeline(timeline.timeline.tracks[0],.5),0,'타임라인 계단 보간');assert.ok(validBlueprint(exposed));
const badTimeline=clone(timeline.timeline);badTimeline.tracks[0].keys.reverse();assert.equal(validTimeline(badTimeline),false,'역순 타임라인 키 거부');
const pair=clone(defaultBlueprint),clip={nodes:pair.nodes.filter(n=>['print','begin'].includes(n.id)),edges:[pair.edges[0]]};const pasted=pasteNodes(pair,'event',clip,{x:-100,y:-100});assert.ok(pasted.ok);assert.ok(validBlueprint(pair));assert.notEqual(pasted.nodes[0].id,clip.nodes[0].id,'붙여넣기 노드 ID 재생성');assert.ok(pair.edges.some(e=>pasted.nodes.some(n=>n.id===e.from.node)&&pasted.nodes.some(n=>n.id===e.to.node)),'붙여넣기 내부 연결 보존');
const destination=makeDefinition(pair,'function','함수 붙여넣기');const pairBefore=JSON.stringify(pair);assert.equal(pasteNodes(pair,destination.definition.id,clip,{x:0,y:0}).ok,false,'함수에 이벤트 붙여넣기 거부');assert.equal(JSON.stringify(pair),pairBefore,'거부된 붙여넣기 원본 보존');
const memberRoot=clone(exposed);memberRoot.nodes.push({...makeNode('nativeMembers'),nativeId:'DoorController.__members'});assert.ok(validBlueprint(memberRoot),'C++ 클래스 공개 멤버 노드');assert.equal(effectivePins(memberRoot.nodes.at(-1),'out',memberRoot)[0].label,'OpenAngle');
console.log('HBEngine Blueprint: 타임라인 보간, 클래스 멤버, 붙여넣기·원본 보존 검사 통과');
const {generatedCore}=await import('./generate-api.mjs');
const {readFileSync}=await import('node:fs');
const {coreApi}=await import('../prototype/core-api.js');
assert.equal(readFileSync('prototype/core-api.js','utf8'),generatedCore(),'C++ 선언과 생성 노드 정보 일치');
assert.ok(coreApi.length>=289,'공통 C++ 함수 등록');
for(const api of coreApi){const registered=catalog.find(n=>n.key===api.key);assert.equal(registered.cppName,api.cppName);assert.deepEqual(registered.inputs,api.inputs);assert.deepEqual(registered.outputs,api.outputs);}
const {createCorePreview,evaluateCore,evaluateCoreNode}=await import('../prototype/core-preview.js');
let now=0;const runtime=createCorePreview(()=>now),call=(key,args={})=>evaluateCore(key,args,runtime);
const closeVector=(a,b)=>assert.ok(a.every((v,i)=>Math.abs(v-b[i])<1e-6));closeVector(call('normalize',{value:[3,4,0]}).return,[.6,.8,0]);assert.deepEqual(call('normalize',{value:[0,0,0]}).return,[0,0,0]);
assert.deepEqual(call('vectorMoveTowards',{current:[0,0,0],target:[1,0,0],distance:10}).return,[1,0,0],'목표를 지나치지 않는 이동');
assert.deepEqual(call('cross',{a:[1,0,0],b:[0,1,0]}).return,[0,0,1]);assert.equal(call('floatInterp',{current:0,target:10,delta:.1,speed:2}).return,2);
assert.throws(()=>call('divide',{a:1,b:0}),/0/);assert.throws(()=>call('normalize',{value:[NaN,0,0]}),/입력값/);assert.throws(()=>runtime.advance(-1),/시간/);
const handle=call('timer',{duration:1,loop:true,event:'OnTimer'}).handle;runtime.advance(.25);assert.equal(call('timerRemaining',{handle}).return,.75);
call('pauseTimer',{handle});runtime.advance(1);assert.equal(call('timerElapsed',{handle}).return,.25);assert.equal(call('timerActive',{handle}).return,false);
call('resumeTimer',{handle});call('timeScale',{scale:2});runtime.advance(.5);assert.deepEqual(runtime.events,['OnTimer']);assert.equal(call('timerElapsed',{handle}).return,.25);
call('gamePaused',{paused:true});runtime.advance(1);assert.equal(call('deltaSeconds').return,0);call('clearTimer',{handle});assert.equal(call('timerActive',{handle}).return,false);
const measure=call('startStopwatch',{name:'measure'}).handle;now=2;assert.equal(call('stopwatchElapsed',{handle:measure}).return,2);assert.equal(call('stopStopwatch',{handle:measure}).return,2);now=3;assert.equal(call('stopwatchElapsed',{handle:measure}).return,2,'측정 종료 후 값 유지');
const actor={position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]};runtime.object=id=>id==='self'?actor:null;
call('translate',{target:'self',value:[1,2,3]});assert.deepEqual(actor.position,[1,2,3]);assert.equal(call('moveActorTowards',{target:'self',destination:[2,2,3],speed:10,delta:1}).return,true);
const calculation=clone(defaultBlueprint),vector=makeNode('vec3'),normal=makeNode('normalize'),magnitude=makeNode('vectorLength');calculation.nodes=[vector,normal,magnitude];calculation.edges=[];vector.inputValues={x:3,y:4,z:0};
assert.ok(connect(calculation,{node:vector.id,pin:'return'},{node:normal.id,pin:'value'}).ok);closeVector(evaluateCoreNode(calculation,normal.id,runtime).return,[.6,.8,0]);
assert.ok(splitPin(calculation,normal.id,'out','return'));assert.ok(splitPin(calculation,magnitude.id,'in','value'));assert.ok(connect(calculation,{node:normal.id,pin:'return.x'},{node:magnitude.id,pin:'value.x'}).ok);assert.ok(connect(calculation,{node:normal.id,pin:'return.y'},{node:magnitude.id,pin:'value.y'}).ok);assert.equal(evaluateCoreNode(calculation,magnitude.id,runtime).return,1,'분할 핀 재조합과 데이터 계산');
const timerNode=makeNode('timer'),remainingNode=makeNode('timerRemaining');calculation.nodes.push(timerNode,remainingNode);assert.ok(connect(calculation,{node:timerNode.id,pin:'handle'},{node:remainingNode.id,pin:'handle'}).ok);assert.throws(()=>evaluateCoreNode(calculation,remainingNode.id,runtime),/먼저/);evaluateCoreNode(calculation,timerNode.id,runtime);assert.equal(evaluateCoreNode(calculation,remainingNode.id,runtime).return,1,'명시 호출의 반환 핸들을 소비하고 다시 실행하지 않음');
console.log('HBEngine 공통 API: C++ 선언·'+coreApi.length+'개 노드 서명 일치, 벡터·시간·타이머·측정·이동·연결된 계산 검사 통과');
const completeCatalog=clone(defaultBlueprint);completeCatalog.nodes=catalog.filter(s=>!s.internal&&s.key!=='callParent').map(s=>makeNode(s.key));completeCatalog.edges=[];assert.ok(validBlueprint(completeCatalog),'독립 그래프용 노드 전체를 한 그래프에 저장할 수 있어요.');completeCatalog.nodes.push(makeNode('callParent'));assert.equal(validBlueprint(completeCatalog),false,'부모 호출은 실제 부모 대상이 필요해요.');completeCatalog.nodes=Array.from({length:1001},()=>makeNode('print'));assert.equal(validBlueprint(completeCatalog),false,'그래프 크기 제한은 유지해요.');

// 표시 모드를 바꿔도 선택·Shift 기준과 카드 순서를 유지하고 프로젝트별로 복원한다.
const {ProjectBrowser}=await import('../prototype/project-browser.js');
const {storage,storageKey}=await import('../prototype/project-session.js');
const viewKey=storageKey('hbengine.project.view'),savedView=storage.getItem(viewKey),browserKey=storageKey('hbengine.project.browsers'),savedBrowsers=storage.getItem(browserKey);
try{
  storage.removeItem(viewKey);
  storage.removeItem(browserKey);
  const grid={dataset:{}},heading={},labels=[],buttons=['list','tiles'].map(view=>({dataset:{projectView:view},setAttribute(key,value){this[key]=value;}}));
  const fields=new Map();const element={querySelector:selector=>selector==='[data-project-grid]'?grid:selector==='.project-list-heading'?heading:(fields.has(selector)?fields.get(selector):(fields.set(selector,{}),fields.get(selector))),querySelectorAll:selector=>selector==='[data-project-view]'?buttons:labels,addEventListener(){}};
  class BrowserCheck extends ProjectBrowser {refresh(){}}
  const browser=new BrowserCheck(element,{});assert.equal(browser.view,'list','파일 브라우저 기본 목록');assert.equal(heading.hidden,false);
  browser.entries=[{name:'Hero.hbblueprint.json',path:'Assets/Hero.hbblueprint.json'}];browser.selected.add(browser.entries[0].path);browser.anchor=0;labels.push({});const selected=browser.selected,entries=browser.entries;
  browser.setView('tiles');assert.equal(grid.dataset.view,'tiles');assert.equal(labels[0].textContent,'Hero');assert.equal(buttons[1]['aria-pressed'],'true');assert.equal(heading.hidden,true);
  assert.equal(browser.selected,selected);assert.equal(browser.entries,entries);assert.equal(browser.anchor,0);assert.equal(new BrowserCheck({...element,querySelectorAll:selector=>selector==='[data-project-view]'?buttons:[]},{}).view,'tiles','프로젝트 표시 방식 복원');
  browser.setView('list');assert.equal(labels[0].textContent,'Hero.hbblueprint.json');assert.equal(storage.getItem(viewKey),'list');assert.notEqual(storageKey('hbengine.project.view',{id:'one'}),storageKey('hbengine.project.view',{id:'two'}));
  browser.setView('invalid');assert.equal(browser.view,'list','손상된 표시 방식 무시');
}finally{if(savedView===null)storage.removeItem(viewKey);else storage.setItem(viewKey,savedView);if(savedBrowsers===null)storage.removeItem(browserKey);else storage.setItem(browserKey,savedBrowsers);}
console.log('HBEngine Project: 목록·타일 전환, 선택 유지, 프로젝트별 표시 방식 복원 검사 통과');
