import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {catalog,defaultBlueprint,makeNode,makeDefinition,validBlueprint,defaultTimeline,sampleTimeline,timelineLength} from '../prototype/blueprint-model.js';
import {BlueprintRuntime,runtimeKeys} from '../prototype/blueprint-runtime.js';
import {NativeHost} from './native-host.mjs';
import {validLayout,restoreLayout} from '../prototype/dock-layout.js';
import {engineOperations,validRuntimeSave} from '../prototype/engine-services.js';
const object=()=>({id:'door',name:'Door',kind:'cube',visible:true,position:[1,2,3],rotation:[0,0,0],scale:[1,1,1]});
const root=()=>({...structuredClone(defaultBlueprint),nodes:[],edges:[],functions:[],macros:[],construction:{nodes:[],edges:[],comments:[]}});
const node=(g,key,id,values={})=>{const n={...makeNode(key),id,inputValues:values};g.nodes.push(n);return n;};
const edge=(g,a,out,b,input='exec')=>g.edges.push({from:{node:a,pin:out},to:{node:b,pin:input}});
const runtime=(g,hooks={},o=[object()])=>new BlueprintRuntime(o,[{root:g,self:'door'}],hooks);
assert.deepEqual(catalog.filter(n=>!runtimeKeys.has(n.key)).map(n=>n.key),[],'모든 기본 노드에 실행 경로가 필요해요.');
const saved={axis:'column',ratio:.6,a:{tabs:['scene','timeline:deleted'],active:'timeline:deleted'},b:{tabs:['project'],active:'project'}};
const restored=restoreLayout(saved,new Set(['scene','project']));assert.equal(validLayout(restored,new Set(['scene','project'])),true);assert.equal(restored.a.active,'scene');
const timeline=structuredClone(defaultTimeline);timeline.lastKeyframe=true;timeline.tracks[0].keys=[{time:0,value:0},{time:1,value:1}];assert.equal(timelineLength(timeline),1);assert.equal(sampleTimeline({...timeline.tracks[0],keys:[]},.5),0);
assert.equal(sampleTimeline({type:'float',interpolation:'constant',keys:[{time:0,value:1},{time:1,value:9}]},.5),1);
assert.ok(Math.abs(sampleTimeline({type:'float',interpolation:'user',keys:[{time:0,value:0,leaveTangent:0},{time:1,value:1,arriveTangent:0}]},.25)-.15625)<1e-6);
const saveVM=runtime(root()),savedState={version:1,objects:saveVM.objects,variables:saveVM.bindings.map(b=>({self:b.self,values:Object.fromEntries(b.variables)}))};assert.equal(validRuntimeSave(savedState,saveVM),true);
const badSave=structuredClone(savedState);badSave.objects[0].position[0]='bad';assert.equal(validRuntimeSave(badSave,saveVM),false);const beforeSave=structuredClone(saveVM.objects);globalThis.localStorage={getItem:()=>JSON.stringify(badSave)};await assert.rejects(engineOperations({update:()=>{throw Error('원본 변경');}}).operation('loadGame',{slot:'test'},saveVM.bindings[0],saveVM),/검증/);assert.deepEqual(saveVM.objects,beforeSave);delete globalThis.localStorage;

let g=root(),messages=[];node(g,'beginPlay','begin');node(g,'sequence','seq');node(g,'print','a',{message:'A'}).breakpoint=true;node(g,'print','b',{message:'B'});edge(g,'begin','then','seq');edge(g,'seq','first','a');edge(g,'seq','second','b');
let vm=runtime(g,{log:v=>messages.push(v)}),started=vm.start();await new Promise(setImmediate);assert.equal(vm.pending.n.id,'a');assert.deepEqual(messages,[]);vm.continue(true);await new Promise(setImmediate);assert.equal(vm.pending.n.id,'b');assert.deepEqual(messages,['A']);vm.continue();await started;assert.deepEqual(messages,['A','B']);await vm.stop();

g=root();messages=[];node(g,'doN','limit',{count:2});node(g,'print','message',{message:'limited'});edge(g,'limit','then','message');vm=runtime(g,{log:v=>messages.push(v)});await vm.start();for(let i=0;i<3;i++)await vm.execute(vm.bindings[0].root.nodes[0],vm.frame(vm.bindings[0]));assert.equal(messages.length,2);await vm.execute(vm.bindings[0].root.nodes[0],vm.frame(vm.bindings[0]),'reset');await vm.execute(vm.bindings[0].root.nodes[0],vm.frame(vm.bindings[0]));assert.equal(messages.length,3);await vm.stop();
g=root();messages=[];node(g,'beginPlay','begin');node(g,'forLoopBreak','loop',{first:0,last:10});node(g,'print','body',{message:'one'});node(g,'print','complete',{message:'complete'});edge(g,'begin','then','loop');edge(g,'loop','body','body');edge(g,'body','then','loop','break');edge(g,'loop','completed','complete');assert.ok(validBlueprint(g));vm=runtime(g,{log:v=>messages.push(v)});await vm.start();assert.deepEqual(messages,['one','complete']);await vm.stop();
g=root();messages=[];node(g,'retriggerDelay','delay',{duration:.2});node(g,'print','after',{message:'only once'});edge(g,'delay','then','after');vm=runtime(g,{log:v=>messages.push(v)});await vm.start();const delayed=vm.bindings[0].root.nodes[0];await vm.execute(delayed,vm.frame(vm.bindings[0]));await vm.tick(.1);await vm.execute(delayed,vm.frame(vm.bindings[0]));await vm.tick(.1);assert.deepEqual(messages,[]);await vm.tick(.11);assert.deepEqual(messages,['only once']);await vm.stop();
g=root();messages=[];node(g,'delay','delay',{duration:.2});node(g,'print','after',{message:'once per wait'});edge(g,'delay','then','after');vm=runtime(g,{log:v=>messages.push(v)});await vm.start();const regularDelay=vm.bindings[0].root.nodes[0];await vm.execute(regularDelay,vm.frame(vm.bindings[0]));await vm.tick(.1);await vm.execute(regularDelay,vm.frame(vm.bindings[0]));await vm.tick(.1);assert.deepEqual(messages,['once per wait']);await vm.tick(.11);assert.equal(messages.length,1);await vm.execute(regularDelay,vm.frame(vm.bindings[0]));await vm.tick(.21);assert.equal(messages.length,2);await vm.stop();
g=root();const gate=node(g,'multiGate','gate',{startIndex:1,random:false,loop:true});vm=runtime(g);await vm.start();const order=[];for(let i=0;i<4;i++){await vm.execute(vm.bindings[0].root.nodes[0],vm.frame(vm.bindings[0]));order.push(vm.values.get('gate').index);}assert.deepEqual(order,[1,2,0,1]);await vm.stop();

g=root();messages=[];const def=makeDefinition(g,'macro','Wait').definition;const entry=def.graph.nodes[0],exit=def.graph.nodes[1];def.graph.edges=[];node(def.graph,'delay','delay',{duration:.2});edge(def.graph,entry.id,'exec','delay');edge(def.graph,'delay','then',exit.id,'then');node(g,'beginPlay','begin');node(g,'callMacro','call').definitionId=def.id;node(g,'print','after',{message:'after delay'});edge(g,'begin','then','call');edge(g,'call','then','after');assert.ok(validBlueprint(g));vm=runtime(g,{log:v=>messages.push(v)});await vm.start();assert.deepEqual(messages,[]);await vm.tick(.1);assert.deepEqual(messages,[]);await vm.tick(.1);assert.deepEqual(messages,['after delay']);await vm.stop();

g=root();messages=[];node(g,'tick','tick').options={tickInterval:.25};node(g,'print','onTick',{message:'tick'});edge(g,'tick','then','onTick');vm=runtime(g,{log:v=>messages.push(v)});await vm.start();await vm.tick(.1);await vm.tick(.1);assert.equal(messages.length,0);await vm.tick(.1);assert.equal(messages.length,1);await vm.stop();

g=root();messages=[];node(g,'beginPlay','begin');const t=node(g,'timeline','timeline');t.timeline={length:1,loop:false,autoplay:false,playRate:1,tracks:[{id:'alpha',name:'Alpha',type:'float',interpolation:'linear',keys:[{time:0,value:0},{time:1,value:1}]},{id:'pulse',name:'Pulse',type:'event',keys:[{time:.2}]}]};node(g,'print','pulse',{message:'event'});node(g,'print','done',{message:'finished'});edge(g,'begin','then','timeline','start');edge(g,'timeline','pulse','pulse');edge(g,'timeline','finished','done');vm=runtime(g,{log:v=>messages.push(v)});await vm.start();await vm.tick(.25);assert.deepEqual(messages,['event']);assert.equal(vm.values.get('timeline').alpha,.25);await vm.tick(.75);assert.deepEqual(messages,['event','finished']);const binding=vm.bindings[0],f=vm.frame(binding);await vm.execute(binding.root.nodes.find(n=>n.id==='timeline'),f,'reverse');assert.equal(vm.timelines.get('door:timeline').time,1);await vm.tick(.5);assert.equal(vm.values.get('timeline').direction,'Backward');await vm.stop();

g=root();messages=[];g.variables=[{id:'counter',name:'counter',type:'int',container:'single',value:0}];node(g,'beginPlay','begin');node(g,'getVariable','read').variableId='counter';node(g,'intLess','condition',{b:3});node(g,'whileLoop','while');node(g,'intAdd','increment',{b:1});node(g,'setVariable','write').variableId='counter';node(g,'print','done',{message:'while done'});edge(g,'begin','then','while');edge(g,'read','value','condition','a');edge(g,'condition','return','while','condition');edge(g,'while','body','write');edge(g,'read','value','increment','a');edge(g,'increment','return','write','value');edge(g,'while','completed','done');assert.ok(validBlueprint(g));vm=runtime(g,{log:v=>messages.push(v)});await vm.start();assert.equal(vm.bindings[0].variables.get('counter'),3);assert.deepEqual(messages,['while done']);await vm.stop();
for(const [key,selection,cases] of [['switchInt',20,[10,20,30]],['switchString','b',['a','b','c']]]){g=root();messages=[];node(g,'beginPlay','begin');node(g,key,'switch',{selection,case0:cases[0],case1:cases[1],case2:cases[2]});node(g,'print','match',{message:'match'});node(g,'print','fallback',{message:'default'});edge(g,'begin','then','switch');edge(g,'switch','out1','match');edge(g,'switch','default','fallback');assert.ok(validBlueprint(g));vm=runtime(g,{log:v=>messages.push(v)});await vm.start();assert.deepEqual(messages,['match']);const n=vm.bindings[0].root.nodes.find(n=>n.id==='switch');n.inputValues.selection=key==='switchInt'?99:'missing';await vm.execute(n,vm.frame(vm.bindings[0]));assert.deepEqual(messages,['match','default']);await vm.stop();}
g=root();messages=[];node(g,'beginPlay','begin');node(g,'forEachBreak','loop',{array:[10,20,30]});node(g,'print','body',{message:'first item'});node(g,'print','done',{message:'array done'});edge(g,'begin','then','loop');edge(g,'loop','body','body');edge(g,'body','then','loop','break');edge(g,'loop','completed','done');assert.ok(validBlueprint(g));vm=runtime(g,{log:v=>messages.push(v)});await vm.start();assert.deepEqual(messages,['first item','array done']);assert.equal(vm.values.get('loop').item,10);await vm.stop();

const host=new NativeHost();
try{
  const header=await fs.readFile(new URL('../prototype/examples/DoorController.h',import.meta.url),'utf8'),source=await fs.readFile(new URL('../prototype/examples/DoorController.cpp',import.meta.url),'utf8');
  const built=await host.build(header,source);g=root();g.native={...built.metadata,header};g.settings={parentClass:'DoorController',nativeDefaults:{'DoorController.OpenAngle':90}};
  node(g,'beginPlay','begin');node(g,'nativeCall','open',{Angle:45}).nativeId='DoorController.Open';node(g,'nativeEvent','event').nativeId='DoorController.OnOpened';node(g,'translate','move',{target:null,value:[0,2,0]});edge(g,'begin','then','open');edge(g,'event','then','move');assert.ok(validBlueprint(g));
  const objects=[{...object(),nativeClass:'DoorController',nativeProperties:{OpenAngle:90}}];
  vm=runtime(g,{native:async request=>{const r=await host.call(built.token,{...request,objects});for(const state of r.objects){const o=objects.find(o=>o.id===state.id);if(o)Object.assign(o,state);}return r;}},objects);
  await vm.start();assert.deepEqual(objects[0].rotation,[0,45,0]);assert.deepEqual(objects[0].position,[1,4,3]);await vm.stop();
}finally{host.close();}
console.log('그래프 실행·중단점 이어가기·매크로 지연·Tick 간격·Timeline 이벤트·실제 C++→BP 검사 통과');
