import assert from 'node:assert/strict';
import {session,validSession,storageKey,migrateLegacyStorage,createProjectStorage} from '../prototype/project-session.js';
class Storage {
  values=new Map();get length(){return this.values.size;}key(index){return [...this.values.keys()][index]??null;}getItem(key){return this.values.get(key)??null;}setItem(key,value){this.values.set(key,String(value));}removeItem(key){this.values.delete(key);}
}
const project=(id,legacyStorage=false)=>({id,name:'QuietGarden',projectFile:'C:/Projects/'+id+'/QuietGarden.hbproject',startupScene:'Assets/Scenes/Garden.hbscene.json',startupBlueprint:'Assets/Blueprints/BP_Garden.hbblueprint.json',legacyStorage});
assert.equal(session,null,'Node에서 서버를 요청하면 안 돼요.');
const original=project('original',true),other=project('other'),storage=new Storage();
assert.equal(validSession(original),true);for(const invalid of [{...original,id:''},{...original,legacyStorage:'true'},{...original,startupScene:'../outside.hbscene.json'},{...original,startupScene:'C:/outside.hbscene.json'},{...original,startupBlueprint:'Assets/../outside.hbblueprint.json'}])assert.equal(validSession(invalid),false);
const recovery=JSON.stringify({active:original.startupBlueprint,documents:[{path:original.startupBlueprint,kind:'blueprint',data:{name:'사용자 편집'},dirty:true}]});
for(const [key,value] of [['hbengine.documents.v2',recovery],['hbengine-ui-scene-v1','legacy scene'],['hbengine.docks.v2','legacy layout'],['hbengine.project.folder','Assets/Custom'],['hbengine.savegame.slotA','legacy save'],['unrelated','unchanged']])storage.setItem(key,value);
migrateLegacyStorage(storage,other);assert.equal(storage.getItem(storageKey('hbengine.documents.v2',other)),null,'같은 이름의 다른 프로젝트에 복구가 섞이면 안 돼요.');
migrateLegacyStorage(storage,original);assert.equal(storage.getItem('hbengine.documents.v2'),recovery,'사용자 원본 복구를 삭제하거나 수정하면 안 돼요.');assert.equal(storage.getItem(storageKey('hbengine.documents.v2',original)),recovery);assert.equal(storage.getItem(storageKey('hbengine.savegame.slotA',original)),'legacy save');assert.equal(storage.getItem(storageKey('hbengine.project.folder',original)),'Assets/Custom');assert.equal(storage.getItem(storageKey('unrelated',original)),null);
storage.setItem('hbengine.documents.v2','updated legacy');migrateLegacyStorage(storage,original);assert.equal(storage.getItem(storageKey('hbengine.documents.v2',original)),recovery,'이관은 한 번만 해야 해요.');
for(const key of ['hbengine.documents.v2','hbengine-ui-scene-v1','hbengine.docks.v2','hbengine.project.folder','hbengine.savegame.slotA']){assert.notEqual(storageKey(key,original),storageKey(key,other));storage.setItem(storageKey(key,other),'other data');assert.notEqual(storage.getItem(storageKey(key,original)),'other data');}
const existingStorage=new Storage();existingStorage.setItem('hbengine.documents.v2',recovery);existingStorage.setItem(storageKey('hbengine.documents.v2',original),'new recovery');migrateLegacyStorage(existingStorage,original);assert.equal(existingStorage.getItem(storageKey('hbengine.documents.v2',original)),'new recovery','이미 분리된 편집본이 이관으로 덮이면 안 돼요.');
const disk=new Map(),errors=[];let failWrite=false,putCount=0;
const requestDisk=async(url,options={})=>{
  if(url.startsWith('/api/storage?'))return {ok:true,json:async()=>({version:1,items:Object.fromEntries(disk)})};
  assert.equal(url,'/api/storage');assert.equal(options.method,'PUT');assert.equal(options.headers['X-HB-Editor'],'1');putCount++;if(failWrite)return {ok:false,json:async()=>({error:'disk failure'})};
  const data=JSON.parse(options.body);assert.equal(data.id,original.id);for(const [key,value] of Object.entries(data.items))value===null?disk.delete(key):disk.set(key,value);return {ok:true,json:async()=>({ok:true})};
};
const originOne=new Storage();originOne.setItem('hbengine.documents.v2',recovery);originOne.setItem('hbengine.docks.v2','legacy docks');originOne.setItem('hbengine.savegame.slotA','legacy progress');
const first=await createProjectStorage(original,{backup:originOne,request:requestDisk,debounce:60000,onError:issue=>errors.push(issue.message)});assert.equal(first.getItem(storageKey('hbengine.documents.v2',original)),recovery);await first.flush();assert.equal(disk.get(storageKey('hbengine.documents.v2',original)),recovery);assert.equal(originOne.getItem('hbengine.documents.v2'),recovery,'origin 원본 백업은 보존해요.');
const documentKey=storageKey('hbengine.documents.v2',original),dockKey=storageKey('hbengine.docks.v2',original),saveKey=storageKey('hbengine.savegame.slotA',original);
first.setItem(documentKey,'server recovery');first.setItem(dockKey,'server docks');first.setItem(saveKey,'server progress');await first.flush();
const originTwo=new Storage();const second=await createProjectStorage(original,{backup:originTwo,request:requestDisk,debounce:60000});assert.equal(second.getItem(documentKey),'server recovery');assert.equal(second.getItem(dockKey),'server docks');assert.equal(second.getItem(saveKey),'server progress');assert.equal(originTwo.getItem(documentKey),'server recovery','서버 복구를 새 origin의 로컬 백업에도 기록해요.');
const viewKey=storageKey('hbengine.project.view',original);first.setItem(viewKey,'tiles');await first.flush();const viewReload=await createProjectStorage(original,{backup:new Storage(),request:requestDisk,debounce:60000});assert.equal(viewReload.getItem(viewKey),'tiles','콘텐츠 표시 방식은 프로젝트 디스크에 저장하고 복원해요.');
const stale=new Storage();stale.setItem(documentKey,'stale recovery');stale.setItem(storageKey('hbengine.project.folder',original),'stale new key');const third=await createProjectStorage(original,{backup:stale,request:requestDisk,debounce:60000});assert.equal(third.getItem(documentKey),'server recovery');assert.equal(third.getItem(storageKey('hbengine.project.folder',original)),null,'완료된 최초 이관 후 다른 origin의 오래된 키를 다시 합치면 안 돼요.');await third.flush();assert.equal(disk.get(documentKey),'server recovery');
const serverFirstDisk=new Map([[documentKey,'existing disk data']]),localFirst=new Storage();localFirst.setItem(documentKey,'old local data');localFirst.setItem(dockKey,'old local docks');const priority=await createProjectStorage(original,{backup:localFirst,debounce:60000,request:async(url,options)=>{if(url.includes('?'))return {ok:true,json:async()=>({version:1,items:Object.fromEntries(serverFirstDisk)})};const changes=JSON.parse(options.body).items;for(const [key,value] of Object.entries(changes))serverFirstDisk.set(key,value);return {ok:true};}});assert.equal(priority.getItem(documentKey),'existing disk data');assert.equal(priority.getItem(dockKey),'old local docks');await priority.flush();
failWrite=true;first.setItem(documentKey,'unsaved disk change');await assert.rejects(first.flush(),/disk failure/);assert.equal(first.getItem(documentKey),'unsaved disk change');assert.equal(originOne.getItem(documentKey),'unsaved disk change');assert.equal(disk.get(documentKey),'server recovery');assert.deepEqual(errors,['disk failure']);failWrite=false;await first.flush();assert.equal(disk.get(documentKey),'unsaved disk change','실패한 변경을 유지해 명시적인 재시도로 저장해야 해요.');
assert.throws(()=>first.setItem(storageKey('hbengine.documents.v2',other),'foreign'),/다른 프로젝트/);
first.removeItem(saveKey);await first.flush();assert.equal(disk.has(saveKey),false);const deleted=await createProjectStorage(original,{backup:originTwo,request:requestDisk,debounce:60000});assert.equal(deleted.getItem(saveKey),null,'다른 origin에 남은 백업이 삭제한 서버값을 되살리면 안 돼요.');assert.ok(putCount>=4);
let releaseFirst,writeStarted;const started=new Promise(resolve=>writeStarted=resolve),release=new Promise(resolve=>releaseFirst=resolve),concurrentDisk=new Map([[storageKey('hbengine.storage-migrated.v1',original),'1']]);let writes=0;
const concurrent=await createProjectStorage(original,{backup:new Storage(),debounce:60000,request:async(url,options)=>{if(url.includes('?'))return {ok:true,json:async()=>({version:1,items:Object.fromEntries(concurrentDisk)})};if(++writes===1){writeStarted();await release;}for(const [key,value] of Object.entries(JSON.parse(options.body).items))concurrentDisk.set(key,value);return {ok:true};}});
concurrent.setItem(documentKey,'first');const flushing=concurrent.flush();await started;concurrent.setItem(documentKey,'second');releaseFirst();await flushing;assert.equal(concurrentDisk.get(documentKey),'second','진행 중인 저장 뒤 생긴 변경도 flush 완료 전에 저장해야 해요.');assert.equal(writes,2);

const quotaBackup=new Storage();quotaBackup.values.set('hbengine.documents.v2',recovery);quotaBackup.setItem=()=>{throw Error('QuotaExceededError');};const quotaErrors=[],quotaDisk=new Map();const quota=await createProjectStorage(original,{backup:quotaBackup,debounce:60000,onError:error=>quotaErrors.push(error.message),request:async(url,options)=>{if(url.includes('?'))return {ok:true,json:async()=>({version:1,items:{}})};for(const [key,value] of Object.entries(JSON.parse(options.body).items))quotaDisk.set(key,value);return {ok:true};}});assert.equal(quota.getItem(documentKey),recovery);await quota.flush();assert.equal(quotaDisk.get(documentKey),recovery,'로컬 백업 용량이 부족해도 기존 편집본을 디스크로 이관해야 해요.');assert.equal(quotaBackup.getItem('hbengine.documents.v2'),recovery);assert.ok(quotaErrors.includes('QuotaExceededError'));

const globals={window:globalThis.window,document:globalThis.document,localStorage:globalThis.localStorage,fetch:globalThis.fetch};
try{
  let requested,redirect;globalThis.window={location:{replace:url=>redirect=url},addEventListener:()=>{},dispatchEvent:()=>{}};globalThis.document={};globalThis.localStorage=new Storage();globalThis.fetch=async(url,options)=>{if(url==='/api/session'){requested={url,options};return {ok:true,json:async()=>other};}if(url.startsWith('/api/storage?'))return {ok:true,json:async()=>({version:1,items:{}})};return {ok:true,json:async()=>({ok:true})};};
  const loaded=await import('../prototype/project-session.js?browser-check');assert.equal(loaded.session.id,'other');assert.equal(requested.url,'/api/session');assert.equal(requested.options.cache,'no-store');assert.equal(loaded.storageKey('hbengine.documents.v2'),storageKey('hbengine.documents.v2',other));await loaded.flushStorage();
  globalThis.fetch=async()=>({ok:false,status:404});await assert.rejects(import('../prototype/project-session.js?failed-check'),/세션/);assert.ok(redirect.startsWith('/prototype/project-hub.html?error='),'세션 실패 시 잘못된 프로젝트 복구를 시작하면 안 돼요.');
}finally{for(const [key,value] of Object.entries(globals))if(value===undefined)delete globalThis[key];else globalThis[key]=value;}
console.log('프로젝트 세션 선행 로드·ID별 복구/도킹/폴더/SaveGame 격리·기본 프로젝트 1회 이관·원본 보존·디스크 우선·origin 간 복구·저장 실패 재시도 검사 통과');
