import assert from 'node:assert/strict';
import { defaultObjects, defaultSurface, defaultEnvironment, validScene, fileKind, clone } from '../prototype/model.js';
import { defaultBlueprint, validBlueprint, canConnect, connect, splitPin, effectivePins, makeNode, collapseNodes, graphContext } from '../prototype/blueprint-model.js';

const scene = { version: 1, objects: clone(defaultObjects), surface: clone(defaultSurface) };
assert.ok(validScene(JSON.parse(JSON.stringify(scene))), '기본 장면 저장/복원');
const broken = clone(scene);
broken.objects[0].position[1] = null;
assert.equal(validScene(broken), false, '손상된 숫자 거부');
broken.objects = [scene.objects[0], scene.objects[0]];
assert.equal(validScene(broken), false, '중복 ID 거부');
assert.equal(validScene({ ...scene, surface: { ...scene.surface, color: '<script>' } }), false, '손상된 색 거부');
assert.equal(fileKind('MyTexture.JPG'), 'texture');
assert.equal(fileKind('character.glb'), 'model');
assert.equal(fileKind('intro.avi'), 'media');
assert.equal(fileKind('tool.exe'), 'unsupported');
const copy = clone(scene);
copy.objects[0].position[0] = 42;
assert.equal(scene.objects[0].position[0], 0, '실행용 복사본과 편집 장면 분리');
console.log('HBEngine UI: 저장 데이터 검증, 파일 분류, 실행용 장면 분리 검사 통과');
const fullScene = {...scene, sceneName:'Garden', environment:clone(defaultEnvironment), blueprint:clone(defaultBlueprint)};
assert.ok(validScene(fullScene), '환경과 블루프린트 저장 데이터');
assert.equal(validScene({...fullScene,environment:{...defaultEnvironment,cloudDensity:2}}),false,'구름 설정 범위 검사');
const graph=clone(defaultBlueprint);
assert.ok(validBlueprint(graph),'기본 이벤트 그래프');
assert.equal(canConnect(graph,{node:'tick',pin:'delta'},{node:'branch',pin:'condition'}).ok,false,'Float → Bool 연결 거부');
assert.ok(splitPin(graph,'location','out','return'),'Vector3 핀 분할');
assert.deepEqual(effectivePins(graph.nodes.find(n=>n.id==='location'),'out',graph).map(p=>p.id),['return.x','return.y','return.z']);
assert.ok(validBlueprint(graph),'분할된 그래프 저장 검증');
assert.ok(splitPin(graph,'location','out','return',true),'분할 핀 합치기');
const set=makeNode('setVariable',700,40,'targetPosition');graph.nodes.push(set);
assert.ok(connect(graph,{node:'location',pin:'return'},{node:set.id,pin:'value'}).ok,'Vector3 타입 연결');
const array=makeNode('getVariable',700,200,'waypoints');graph.nodes.push(array);
assert.equal(canConnect(graph,{node:array.id,pin:'value'},{node:set.id,pin:'value'}).ok,false,'Vector3 배열 → 단일 값 연결 거부');
assert.ok(validBlueprint(JSON.parse(JSON.stringify(graph))),'AI JSON 왕복 저장');
const invalidGraph=clone(graph);invalidGraph.nodes[0].id='" onclick="x';
assert.equal(validBlueprint(invalidGraph),false,'손상된 노드 ID 거부');
assert.equal(validBlueprint({...graph,nodes:[null]}),false,'누락된 노드 데이터 거부');
console.log('HBEngine Blueprint: 이벤트, 타입 연결, 배열, 핀 분할/합치기, JSON 검증 통과');
const grouped=clone(defaultBlueprint);
const fn=collapseNodes(grouped,grouped,['print'],'function','시작 메시지');
assert.ok(fn.ok,'노드를 함수로 묶기');assert.ok(validBlueprint(grouped),'묶은 함수 그래프 저장 검증');
assert.ok(grouped.edges.some(e=>e.from.node==='begin'&&e.to.node===fn.call.id),'외부 실행 연결 보존');
const fnGraph=graphContext(grouped,fn.definition.id);
assert.ok(fnGraph.nodes.some(n=>n.key==='functionInput')&&fnGraph.nodes.some(n=>n.key==='functionOutput'),'함수 입출력 터널');
assert.ok(fnGraph.edges.some(e=>e.to.node==='print'),'함수 내부 연결 보존');
fnGraph.nodes.push(makeNode('vec2',900,100));assert.equal(fn.definition.graph.nodes.length,4,'내부 그래프 편집 원본 반영');
const macro=collapseNodes(grouped,grouped,['branch','door','getKey'],'macro','문 상호작용');
assert.ok(macro.ok,'여러 실행 출력은 매크로로 묶기');assert.ok(validBlueprint(JSON.parse(JSON.stringify(grouped))),'함수·매크로·Construction JSON 왕복');
assert.ok(grouped.edges.some(e=>e.from.node==='overlap'&&e.to.node===macro.call.id),'매크로 외부 연결 보존');
const rejected=clone(defaultBlueprint),before=JSON.stringify(rejected);
assert.equal(collapseNodes(rejected,rejected,['branch'],'function','잘못된 함수').ok,false,'복수 실행 반환은 함수 묶기 거부');
assert.equal(JSON.stringify(rejected),before,'실패한 묶기는 원본 보존');
assert.equal(collapseNodes(rejected,rejected,['begin'],'macro','이벤트').ok,false,'이벤트 묶기 거부');
const badDefinition=clone(grouped);badDefinition.functions[0].graph.edges[0].to.pin='missing';assert.equal(validBlueprint(badDefinition),false,'내부 그래프 손상 거부');
const construction=graphContext(grouped,'construction');construction.edges=[];assert.equal(grouped.construction.edges.length,0,'Construction 연결 독립 편집');assert.equal(grouped.edges.length,2,'이벤트 그래프 보존');
console.log('HBEngine Blueprint: 함수·매크로 추출, 경계 연결 보존, 내부 편집, Construction 분리 검사 통과');
const interleaved=clone(defaultBlueprint);interleaved.nodes=interleaved.nodes.filter(n=>['begin','print','door'].includes(n.id));const between=makeNode('sound',400,40);interleaved.nodes.push(between);interleaved.edges=[{from:{node:'begin',pin:'then'},to:{node:'print',pin:'exec'}},{from:{node:'print',pin:'then'},to:{node:between.id,pin:'exec'}},{from:{node:between.id,pin:'then'},to:{node:'door',pin:'exec'}}];
const original=JSON.stringify(interleaved);assert.equal(collapseNodes(interleaved,interleaved,['print','door'],'function','외부 노드 교차').ok,false,'묶기 때문에 생기는 순환 거부');assert.equal(JSON.stringify(interleaved),original,'교차 선택 실패 시 원본 연결 보존');
const generic=clone(defaultBlueprint),length=makeNode('arrayLength');generic.nodes.push(length);assert.ok(collapseNodes(generic,generic,[length.id],'function','배열 길이').ok);assert.ok(validBlueprint(generic),'범용 배열 핀 묶기 저장');
