import assert from 'node:assert/strict';
import {runInNewContext} from 'node:vm';
import fs from 'node:fs/promises';
import path from 'node:path';
import {AssetDocuments,createAsset,validAsset,assetSuffix,loadSceneBindings,evaluateMaterial} from '../prototype/asset-documents.js';
import {resolveMaterialAsset} from '../prototype/material-runtime.js';
import {BlueprintWorkspace} from '../prototype/blueprint-workspace.js';
import {blueprintInstanceDefaults} from '../prototype/blueprint-overrides.js';
import {objectComponents,defaultsForObject,componentDefaults} from '../prototype/scene-components.js';
import {validScene} from '../prototype/model.js';
import {blueprintClasses} from '../prototype/class-types.js';
import {InputActions} from '../prototype/input-actions.js';
import {BlueprintRuntime} from '../prototype/blueprint-runtime.js';
import {makeNode,connect,validBlueprint} from '../prototype/blueprint-model.js';
import {ProjectService} from './project-service.mjs';
import {TimelineEditor} from '../prototype/timeline-editor.js';
import {NativeHost} from './native-host.mjs';
import {nativeWorld,parseNativeHeader} from '../prototype/native-model.js';
import {createCppClass} from './external-editor.mjs';
const clip=createAsset('animation','Fit');const curve=Object.create(TimelineEditor.prototype);curve.getNode=()=>clip;curve.trackId='position';curve.selection=new Set();curve.fit();assert.ok(curve.view.max<10,'rotation values must not flatten the position curve');curve.trackId='rotation';curve.fit();assert.ok(curve.view.max>100);
const docs=new AssetDocuments(),a=docs.open('BP_A','blueprint',createAsset('blueprint','BP_A','Character')),b=docs.open('BP_B','blueprint',createAsset('blueprint','BP_B'));
assert.ok(a.data.components.some(c=>c.type==='CapsuleCollider'));
assert.equal(new Set(a.data.nodes.map(n=>n.position.y)).size,3,'new events must not overlap');
docs.select(a.path);a.data.name='Changed';a.dirty=true;a.history.push('own undo');docs.select(b.path);
assert.equal(b.history.length,0);assert.equal(docs.open(a.path,'blueprint',createAsset('blueprint','Disk')).data.name,'Changed');
assert.equal(docs.close(a.path),false);await assert.rejects(docs.save(a,async()=>{throw Error('disk full');}),/disk full/);assert.equal(a.dirty,true);
await docs.save(a,async()=>{a.data.name='Edited during save';});assert.equal(a.dirty,true,'saving must not clear concurrent edits');
await docs.save(a,async()=>{});assert.equal(a.dirty,false);docs.rename('BP_A','BP_Renamed');assert.equal(docs.items.get('BP_Renamed'),a);
// Run the real browser rename handler with isolated editor state, without opening user files.
const appSource=await fs.readFile(new URL('../prototype/app.js',import.meta.url),'utf8'),renameStart=appSource.indexOf('function renameDocumentPaths('),renameEnd=appSource.indexOf('\nasync function browseDocument(',renameStart);assert.ok(renameStart>=0&&renameEnd>renameStart);
const renamedDocs=new AssetDocuments(),renamedBp=renamedDocs.open('Assets/Old/BP_Test.hbblueprint.json','blueprint',createAsset('blueprint','BP_Test')),renamedScene=renamedDocs.open('Assets/L_Map.hbscene.json','scene',createAsset('scene','L_Map'));
renamedScene.data.objects=[{id:'actor',blueprintAsset:renamedBp.path}];renamedBp.data.settings.inputMapping='Assets/Old/IMC_Default.hbinputmapping.json';renamedBp.history=[{kind:'blueprint',data:structuredClone(renamedBp.data)}];renamedBp.dirty=true;
const renameElement={querySelector:()=>null},renamePane={id:'asset:Assets/Old/IA_Move.hbinputaction.json',element:renameElement},componentId='components:'+renamedBp.path,timelineId='timeline:'+renamedBp.path+':node',renameTree={tabs:[componentId,timelineId],active:componentId};
const renameState={blueprintWorkspace:{files:new Map([[renamedBp.path,structuredClone(renamedBp.data)]])},assetDocs:renamedDocs,documents:new Map([['asset:Assets/Old/Image.png',renameElement]]),assetPanes:new Map([['Assets/Old/IA_Move.hbinputaction.json',renamePane]]),timelineWindows:new Map([[timelineId,{}]]),inputActionTypes:new Map([['Assets/Old/IA_Move.hbinputaction.json','vec2']]),projectAssetFiles:[{path:'Assets/Old/Image.png',name:'Image.png'}],dock:{entries:new Map([['asset:Assets/Old/Image.png',{id:'asset:Assets/Old/Image.png',path:'Assets/Old/Image.png',title:'Image.png',element:renameElement}],[componentId,{id:componentId,element:renameElement}],[timelineId,{id:timelineId,element:renameElement}],[renamePane.id,{...renamePane,path:'Assets/Old/IA_Move.hbinputaction.json'}]]),tree:renameTree,render(){}},objects:structuredClone(renamedScene.data.objects),activeScenePath:renamedScene.path,activeBlueprintPath:renamedBp.path,codeHeaderPath:'Assets/Old/Hero.h',codeSourcePath:'Assets/Old/Hero.cpp',focusedWindow:componentId,workspace:'blueprint',captureDocument(){},assetTitle:p=>p.split('/').pop(),setWorkspace(){},renderDocumentTabs(){},queueRecovery(){}};
runInNewContext(appSource.slice(renameStart,renameEnd)+"renameDocumentPaths('Assets/Old','Assets/New');",renameState);
assert.ok(renameState.blueprintWorkspace.files.has('Assets/New/BP_Test.hbblueprint.json'));assert.equal(renameState.blueprintWorkspace.files.get('Assets/New/BP_Test.hbblueprint.json').settings.inputMapping,'Assets/New/IMC_Default.hbinputmapping.json');assert.ok(renamedDocs.items.has('Assets/New/BP_Test.hbblueprint.json'));assert.equal(renamedBp.dirty,true);assert.equal(renamedScene.data.objects[0].blueprintAsset,renamedBp.path);assert.equal(renamedScene.dirty,true);assert.equal(renameState.objects[0].blueprintAsset,renamedBp.path);assert.equal(renamedBp.history[0].data.settings.inputMapping,'Assets/New/IMC_Default.hbinputmapping.json');assert.equal(renameState.documents.get('asset:Assets/New/Image.png'),renameElement);assert.equal(renameState.dock.entries.get('asset:Assets/New/Image.png').path,'Assets/New/Image.png');assert.equal(renamePane.id,'asset:Assets/New/IA_Move.hbinputaction.json');assert.ok(renameState.timelineWindows.has('timeline:'+renamedBp.path+':node'));assert.equal(renameTree.active,'components:'+renamedBp.path);assert.equal(renameState.focusedWindow,renameTree.active);assert.ok(renameState.inputActionTypes.has('Assets/New/IA_Move.hbinputaction.json'));
// A pending native build writes its own blueprint even when another tab becomes active.
const buildStart=appSource.indexOf('async function buildNative(){'),buildEnd=appSource.indexOf('\nasync function saveCode()',buildStart);assert.ok(buildStart>=0&&buildEnd>buildStart);
const buildDocs=new AssetDocuments(),buildOwner=buildDocs.open('BP_BuildOwner','blueprint',createAsset('blueprint','BP_BuildOwner')),buildOther=buildDocs.open('BP_BuildOther','blueprint',createAsset('blueprint','BP_BuildOther'));
const buildHeader='#include <HBEngine/Game.hpp>\nHB_CLASS(Blueprintable)\nclass BuildOwner : public hb::Actor { public: HB_FUNCTION(BlueprintCallable) float Value(); };',buildSource='float BuildOwner::Value() { return 1; }',buildMetadata=parseNativeHeader(buildHeader);buildOwner.data.native={...buildMetadata,header:buildHeader,source:buildSource,headerPath:'Source/Owner.h',sourcePath:'Source/Owner.cpp'};buildDocs.select(buildOwner.path);
let releaseBuild;const buildGate=new Promise(resolve=>releaseBuild=resolve),buildRequests=[],buildButton={disabled:false},buildDiagnostics={hidden:true,textContent:''},buildState={assetDocs:buildDocs,blueprintWorkspace:new BlueprintWorkspace(async p=>buildDocs.items.get(p)?.data,p=>buildDocs.items.get(p)?.data,async p=>p.endsWith('.h')?buildHeader:buildSource),graphs:{blueprint:buildOwner.data},running:false,workspace:'blueprint',codeHeaderPath:'Source/Owner.h',codeSourcePath:'Source/Owner.cpp',nativeBuild:'other token',future:['other redo'],undoLimit:20,captureDocument(){},fileUrl:p=>p,editorRequest:async(url)=>{buildRequests.push(url);if(url==='/api/native/build')return {json:async()=>await buildGate};return {text:async()=>url.endsWith('.h')?buildHeader:buildSource};},parseNativeHeader,validBlueprint,clone:structuredClone,$:selector=>selector.includes('build-native')?buildButton:buildDiagnostics,renderDocumentTabs(){},queueRecovery(){},notify(){},log(){},dock:{open(){}},assetTitle:p=>p};
const otherBefore=JSON.stringify(buildOther.data),pendingBuild=runInNewContext(appSource.slice(buildStart,buildEnd)+'buildNative();',buildState);buildDocs.select(buildOther.path);buildState.graphs.blueprint=buildOther.data;buildState.codeHeaderPath='Source/Other.h';buildState.codeSourcePath='Source/Other.cpp';releaseBuild({metadata:buildMetadata,compiler:'check',token:'owner token'});await pendingBuild;
assert.deepEqual(buildRequests,['Source/Owner.h','Source/Owner.cpp','/api/native/build']);assert.equal(buildOwner.dirty,false);assert.equal(buildOwner.history.length,0);assert.equal(buildOwner.view.nativeBuild.token,'owner token');assert.equal(JSON.stringify(buildOther.data),otherBefore);assert.equal(buildOther.history.length,0);assert.equal(buildOther.dirty,false);assert.equal(buildState.nativeBuild,'other token');assert.equal(buildDocs.current,buildOther);
// A pending model import returns to its original scene before creating its undo record.
const modelStart=appSource.indexOf('async function placeModel(file){'),modelEnd=appSource.indexOf('\nfunction queueFiles(',modelStart);assert.ok(modelStart>=0&&modelEnd>modelStart);
const modelDocs=new AssetDocuments(),modelOwner=modelDocs.open('OwnerScene','scene',createAsset('scene','OwnerScene')),modelOther=modelDocs.open('OtherScene','scene',createAsset('scene','OtherScene'));modelDocs.select(modelOwner.path);let releaseModel;const modelGate=new Promise(resolve=>releaseModel=resolve);
const modelState={assetDocs:modelDocs,activeScenePath:modelOwner.path,running:false,objects:modelOwner.data.objects,loadModel:()=>modelGate,activateDocument:p=>{modelDocs.select(p);modelState.objects=modelDocs.current.data.objects;},remember:()=>modelDocs.current.history.push(structuredClone(modelDocs.current.data)),crypto:{randomUUID:()=> 'placed-model'},buildObject(){},selectObject(){},changed:()=>modelDocs.current.dirty=true,setWorkspace(){}};
const pendingModel=runInNewContext(appSource.slice(modelStart,modelEnd)+"placeModel({path:'Assets/Cube.obj',name:'Cube'});",modelState);modelDocs.select(modelOther.path);modelState.objects=modelOther.data.objects;releaseModel();await pendingModel;assert.equal(modelOwner.data.objects.length,1);assert.equal(modelOwner.history.length,1);assert.equal(modelOwner.dirty,true);assert.equal(modelOther.data.objects.length,0);assert.equal(modelOther.history.length,0);assert.equal(modelOther.dirty,false);assert.equal(modelDocs.current,modelOwner);
// 실제 에셋 지정·배치 함수를 실행해 비동기 응답 뒤에도 원 장면만 수정하는지 검사한다.
const assignStart=appSource.indexOf('async function assignObjectAsset(key,path){'),assignEnd=appSource.indexOf('\ndocument.addEventListener(\'change\',async e=>',assignStart),placeStart=appSource.indexOf('async function placeBlueprint(file){'),placeEnd=appSource.indexOf('\nfunction openComponentViewport()',placeStart);assert.ok(assignStart>=0&&assignEnd>assignStart&&placeStart>=0&&placeEnd>placeStart);
function sceneOperationState(){
  const docs=new AssetDocuments(),owner=docs.open('AssignOwner','scene',createAsset('scene','AssignOwner')),other=docs.open('AssignOther','scene',createAsset('scene','AssignOther')),actor=id=>({id,name:id,kind:'cube',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1],visible:true});owner.data.objects=[actor('owner-object')];other.data.objects=[actor('other-object')];docs.select(owner.path);
  let release;const gate=new Promise(resolve=>release=resolve),state={assetDocs:docs,activeScenePath:owner.path,selected:'owner-object',running:false,objects:owner.data.objects,fileUrl:p=>p,editorRequest:async()=>({json:async()=>await gate}),validAsset,validBlueprint,blueprintClasses,blueprintInstanceDefaults,componentDefaults,evaluateMaterial,resolveMaterialAsset,objectComponents,defaultsForObject,clone:structuredClone,readAsset:async()=>await gate,activateDocument:p=>{docs.select(p);state.activeScenePath=p;state.objects=docs.current.data.objects;},remember:()=>docs.current.history.push(structuredClone(docs.current.data)),changed:()=>docs.current.dirty=true,rebuildWorld(){},renderInspector(){},crypto:{randomUUID:()=> 'placed-blueprint'},buildObject(){},selectObject(){}};
  state.blueprintWorkspace=new BlueprintWorkspace(async()=>await gate,path=>docs.items.get(path)?.data);
  return {docs,owner,other,state,release,actor};
}
for(const kind of ['blueprint','material']){
  const test=sceneOperationState(),asset=createAsset(kind,'Pending_'+kind),key=kind+'Asset',assetPath='Assets/Pending'+assetSuffix[kind],before=JSON.stringify(test.other.data),promise=runInNewContext(appSource.slice(assignStart,assignEnd)+`assignObjectAsset('${key}','${assetPath}');`,test.state);
  test.state.activateDocument(test.other.path);test.state.selected='other-object';test.release(asset);await promise;
  assert.equal(test.owner.data.objects[0][key],assetPath);if(kind==='blueprint')assert.equal(test.owner.data.objects[0].blueprint,asset.name);else assert.deepEqual(test.owner.data.objects[0].materialSurface,evaluateMaterial(asset));assert.equal(test.owner.history.length,1);assert.equal(test.owner.dirty,true);assert.equal(JSON.stringify(test.other.data),before);assert.equal(test.other.history.length,0);assert.equal(test.other.dirty,false);assert.equal(test.docs.current,test.owner);
}
for(const interrupted of ['deleted','closed','running']){
  const test=sceneOperationState(),promise=runInNewContext(appSource.slice(assignStart,assignEnd)+"assignObjectAsset('blueprintAsset','Assets/Pending.hbblueprint.json');",test.state);
  if(interrupted==='deleted')test.owner.data.objects.splice(0);else if(interrupted==='closed')test.docs.close(test.owner.path,true);else test.state.running=true;test.release(createAsset('blueprint','Pending'));
  await assert.rejects(promise,interrupted==='deleted'?/삭제/:interrupted==='closed'?/닫혔/:/실행/);assert.equal(test.owner.history.length,0);assert.equal(test.owner.dirty,false);assert.equal(test.other.dirty,false);
}
{
  const test=sceneOperationState(),before=JSON.stringify(test.other.data),promise=runInNewContext(appSource.slice(placeStart,placeEnd)+"placeBlueprint({path:'Assets/Pending.hbblueprint.json'});",test.state);test.state.activateDocument(test.other.path);test.release(createAsset('blueprint','Pending','Character'));await promise;
  assert.equal(test.owner.data.objects.length,2);assert.equal(test.owner.data.objects[1].blueprintAsset,'Assets/Pending.hbblueprint.json');assert.equal(test.owner.history.length,1);assert.equal(test.owner.dirty,true);assert.equal(JSON.stringify(test.other.data),before);assert.equal(test.other.history.length,0);assert.equal(test.other.dirty,false);assert.equal(test.docs.current,test.owner);
}
for(const count of [500,10000]){
  const test=sceneOperationState();test.owner.data.objects=Array.from({length:count},(_,i)=>test.actor('existing-'+i));test.state.objects=test.owner.data.objects;const promise=runInNewContext(appSource.slice(placeStart,placeEnd)+"placeBlueprint({path:'Assets/Pending.hbblueprint.json'});",test.state);test.release(createAsset('blueprint','Pending'));await promise;assert.equal(test.owner.data.objects.length,count+1);assert.equal(test.owner.history.length,1);assert.equal(test.owner.dirty,true);
}
// 현재 월드의 장면을 닫아도 남은 장면 또는 마지막 저장본을 계속 유효한 owner로 사용한다.
const closeStart=appSource.indexOf('function removeDocumentViews(path){'),closeEnd=appSource.indexOf('\nfunction materialNodeProperties(',closeStart);assert.ok(closeStart>=0&&closeEnd>closeStart);
function closeSceneState({remaining=true,activeScene=true,choice='discard'}={}){
  const docs=new AssetDocuments(),garden=remaining?docs.open('Garden.hbscene.json','scene',createAsset('scene','Garden')):null,scene=docs.open('Closing.hbscene.json','scene',createAsset('scene','SavedClosing')),bp=docs.open('BP_Keep.hbblueprint.json','blueprint',createAsset('blueprint','BP_Keep'));
  if(garden){garden.data.sceneName='DirtyGarden';garden.dirty=true;}scene.data.sceneName='UnsavedClosing';scene.dirty=true;docs.select(activeScene?scene.path:bp.path);
  const messages=[],state={authoringBatchBusy:false,propagateMaterialFunctions(){},assetDocs:docs,activeScenePath:scene.path,objects:scene.data.objects,sceneName:scene.data.sceneName,running:false,dirty:true,documents:new Map(),assetPanes:new Map(),timelineWindows:new Map(),dock:{entries:new Map()},captureDocument(){},closeChoice:async()=>choice,assetTitle:p=>p,notify:m=>messages.push(m),validScene,installDocumentData:d=>{if(d.kind==='scene'){state.activeScenePath=d.path;state.objects=structuredClone(d.data.objects);state.sceneName=d.data.sceneName;}},activateDocument:p=>{docs.select(p);state.installDocumentData(docs.current);},renderDocumentTabs(){},queueRecovery(){},$:()=>({hidden:false}),fileUrl:p=>p,editorRequest:async()=>({json:async()=>JSON.parse(scene.saved)})};
  return {docs,garden,scene,bp,state,messages};
}
for(const activeScene of [true,false]){
  const test=closeSceneState({activeScene}),gardenBefore=JSON.stringify(test.garden.data),promise=runInNewContext(appSource.slice(closeStart,closeEnd)+"closeDocument('Closing.hbscene.json');",test.state);await promise;
  assert.equal(test.docs.items.has(test.scene.path),false);assert.equal(test.state.activeScenePath,test.garden.path);assert.equal(test.state.sceneName,'DirtyGarden');assert.equal(JSON.stringify(test.garden.data),gardenBefore);assert.equal(test.garden.dirty,true);assert.equal(test.docs.current,test.bp);assert.equal(test.bp.dirty,false);
}
for(const activeScene of [true,false]){
  const test=closeSceneState({remaining:false,activeScene});await runInNewContext(appSource.slice(closeStart,closeEnd)+"closeDocument('Closing.hbscene.json');",test.state);
  const restored=test.docs.items.get(test.state.activeScenePath);assert.ok(restored&&restored.kind==='scene');assert.equal(restored.data.sceneName,'SavedClosing');assert.equal(restored.dirty,false);assert.equal(restored.saved,JSON.stringify(restored.data));assert.equal(test.state.sceneName,'SavedClosing');assert.equal(test.docs.current,test.bp);
}
{
  const test=closeSceneState({remaining:false,choice:'save'});await runInNewContext(appSource.slice(closeStart,closeEnd)+"closeDocument('Closing.hbscene.json');",test.state);assert.equal(test.state.sceneName,'UnsavedClosing');assert.equal(test.docs.items.get(test.state.activeScenePath).dirty,false);assert.equal(test.docs.current,test.bp);
}
{
  const test=closeSceneState({remaining:false,choice:'cancel'});await runInNewContext(appSource.slice(closeStart,closeEnd)+"closeDocument('Closing.hbscene.json');",test.state);assert.equal(test.docs.current,test.scene);assert.equal(test.scene.dirty,true);assert.equal(test.state.sceneName,'UnsavedClosing');
}
{
  const test=closeSceneState({remaining:false});test.docs.close(test.bp.path,true);await runInNewContext(appSource.slice(closeStart,closeEnd)+"closeDocument('Closing.hbscene.json');",test.state);assert.equal(test.docs.current.kind,'scene');assert.equal(test.docs.current.path,test.state.activeScenePath);assert.equal(test.docs.current.data.sceneName,'SavedClosing');
}
{
  const test=closeSceneState({choice:'save'});test.state.editorRequest=async()=>{test.scene.data.sceneName='EditedDuringSave';return {};};await runInNewContext(appSource.slice(closeStart,closeEnd)+"closeDocument('Closing.hbscene.json');",test.state);assert.equal(test.docs.current,test.scene);assert.equal(test.scene.dirty,true);assert.equal(test.scene.data.sceneName,'EditedDuringSave');assert.match(test.messages[0],/새 변경/);
}
const mat=createAsset('material','M_A');mat.graph.nodes.push({id:'constant',title:'Scalar',kind:'value',body:'constant',value:.9,x:.3,y:150,output:'Float'});mat.graph.edges.push(['constant','surface',2]);assert.equal(evaluateMaterial(mat).metalness,.9);mat.graph.nodes[0].id='"><img';assert.equal(validAsset('material',mat),false);
const action={...createAsset('inputaction','IA_Move'),valueType:'vec2',trigger:'held'},context={...createAsset('inputmapping','IMC_Default'),mappings:[{action:'IA_Move',key:'W',axis:1,scale:1},{action:'IA_Move',key:'S',axis:1,scale:-1}]};
const input=new InputActions([context],new Map([['IA_Move',action]]));input.set('w',1);assert.deepEqual(input.sample().map(e=>e.event),['started']);assert.deepEqual(input.sample(true)[0].value,[0,1]);input.set('S',1);assert.equal(input.sample()[0].event,'completed');input.clear();assert.equal(input.sample().length,0);
const blocked=new InputActions([{...context,priority:5,mappings:[{action:'IA_Block',key:'W',axis:0,scale:1}]},context],new Map([['IA_Move',action],['IA_Block',createAsset('inputaction','IA_Block')]]));blocked.set('W',1);assert.ok(blocked.sample(true).every(e=>e.path==='IA_Block'),'higher priority consumes the key');
const parent=path.resolve('native/build');await fs.mkdir(parent,{recursive:true});const dir=await fs.mkdtemp(path.join(parent,'asset-check-'));
try{
  const host=new NativeHost();
  const project=await new ProjectService(dir).init();await project.mkdir('Assets');
  for(const kind of Object.keys(assetSuffix)){const file=await project.create('Assets',kind,'Test_'+kind);const data=JSON.parse(await fs.readFile((await project.read(file.path)).file,'utf8'));assert.ok(validAsset(kind,data));await assert.rejects(project.create('Assets',kind,'Test_'+kind),/EEXIST/);}
  for(const type of Object.keys(blueprintClasses)){assert.ok(validAsset('blueprint',createAsset('blueprint','BP_'+type,type)));const source=await createCppClass(project,'Source',type+'Test',type);assert.match(await fs.readFile((await project.read(source.path)).file,'utf8'),new RegExp('hb::'+type));}
  try{
    for(const type of Object.keys(blueprintClasses)){const header=await fs.readFile(path.join(dir,'Source',type+'Test.h'),'utf8'),source=await fs.readFile(path.join(dir,'Source',type+'Test.cpp'),'utf8'),built=await host.build(header,source);const own={id:'own',blueprintAsset:'Own',nativeClass:type+'Test',nativeProperties:{Speed:7},position:[1,2,3],rotation:[0,0,0],scale:[1,1,1]},foreign={...own,id:'foreign',blueprintAsset:'Other',nativeClass:'OtherClass',nativeProperties:{Foreign:123}};const world=nativeWorld([own,foreign],new Set(['Own']));assert.equal(world[1].nativeClass,undefined);assert.deepEqual(foreign.nativeProperties,{Foreign:123});const result=await host.call(built.token,{key:'nativeCall',nativeId:type+'Test.Start',args:{target:'own'},objects:world});const returned=world.map(o=>({...o,...result.objects.find(changed=>changed.id===o.id)}));assert.equal(returned.find(o=>o.id==='own').nativeProperties.Speed,7);assert.equal(returned.find(o=>o.id==='foreign').nativeProperties,undefined);assert.deepEqual(foreign.nativeProperties,{Foreign:123});}
    const pointerHeader='#include <HBEngine/Game.hpp>\nHB_CLASS(Blueprintable)\nclass NativePointerCheck : public hb::Character { public: HB_FUNCTION(BlueprintCallable) bool Check(hb::Character* character, hb::Pawn* pawn, hb::PlayerController* controller, hb::GameMode* mode, hb::SceneComponent* component); };',pointerSource='bool NativePointerCheck::Check(hb::Character* character, hb::Pawn* pawn, hb::PlayerController* controller, hb::GameMode* mode, hb::SceneComponent* component) { return character && pawn && !controller && !mode && !component; }';
    const pointerBuild=await host.build(pointerHeader,pointerSource),pointerObject={id:'pointer',nativeClass:'NativePointerCheck',position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]},pointerResult=await host.call(pointerBuild.token,{key:'nativeCall',nativeId:'NativePointerCheck.Check',args:{target:'pointer',character:'pointer',pawn:'pointer',controller:null,mode:null,component:null},objects:[pointerObject]});assert.equal(pointerResult.outputs.result,true,'built-in class pointer pins must compile and reach the native instance');
  }finally{host.close();}
  await project.rename('Assets/Test_blueprint.hbblueprint.json','Assets/Renamed.hbblueprint.json');assert.equal((await project.read('Assets/Test_blueprint.hbblueprint.json')).file,(await project.read('Assets/Renamed.hbblueprint.json')).file);const reopened=await new ProjectService(dir).init();assert.equal((await reopened.read('Assets/Test_blueprint.hbblueprint.json')).file,(await reopened.read('Assets/Renamed.hbblueprint.json')).file);
  await project.rename('Assets/Renamed.hbblueprint.json','Assets/Test_blueprint.hbblueprint.json');const returned=await new ProjectService(dir).init();assert.equal((await returned.read('Assets/Renamed.hbblueprint.json')).file,(await returned.read('Assets/Test_blueprint.hbblueprint.json')).file,'renaming to the original name must not follow its redirect');
  await project.rename('Assets/Test_blueprint.hbblueprint.json','Assets/Final.hbblueprint.json');const chained=await new ProjectService(dir).init();assert.equal((await chained.read('Assets/Renamed.hbblueprint.json')).file,(await chained.read('Assets/Test_blueprint.hbblueprint.json')).file);assert.equal((await chained.read('Assets/Final.hbblueprint.json')).file,(await chained.read('Assets/Test_blueprint.hbblueprint.json')).file);
  await assert.rejects(project.rename('Assets','Assets/Subfolder'),/경로/);
}finally{const target=await fs.realpath(dir);assert.ok(target.startsWith(parent+path.sep));await fs.rm(target,{recursive:true,force:true});}
// Two documents with the same event IDs execute against separate instance data.
const rootA=createAsset('blueprint','First'),rootB=createAsset('blueprint','Second'),messages=[];
for(const root of [rootA,rootB]){const print={...makeNode('print'),inputValues:{message:root.name}};root.nodes.push(print);assert.ok(connect(root,{node:'beginPlay',pin:'then'},{node:print.id,pin:'exec'}).ok);}
rootA.settings.inputMapping='IMC_Default';const event={...makeNode('inputAction'),options:{action:'IA_Move'},valueType:'vec2'},print={...makeNode('print'),inputValues:{message:'input fired'}};rootA.nodes.push(event,print);assert.ok(connect(rootA,{node:event.id,pin:'triggered'},{node:print.id,pin:'exec'}).ok);
const assets=new Map([['A',rootA],['B',rootB],['IMC_Default',context],['IA_Move',action]]),objects=[{id:'one',blueprintAsset:'A'},{id:'two',blueprintAsset:'B'}];
const loaded=await loadSceneBindings(objects,async p=>assets.get(p)),vm=new BlueprintRuntime(objects,loaded.bindings,{inputAssets:loaded.inputAssets,log:v=>messages.push(v)});await vm.start();assert.deepEqual(messages,['First','Second']);await vm.input('W',1);await vm.tick(.02);assert.equal(messages.at(-1),'input fired');await vm.releaseInput();await vm.stop();
console.log('에셋 8종·부모 클래스 7종·문서 전환/장면 닫기/저장 실패·참조 재열기/이름 변경·부모 포인터 연동·머테리얼 계산·입력 우선순위·다중 BP 실행 검사 통과');
