import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseNativeHeader} from '../prototype/native-model.js';
import {updateLibrary} from './generate-library.mjs';
export function generatedCore(){
  const native=parseNativeHeader(fs.readFileSync('native/include/HBEngine/Game.hpp','utf8')+'\n'+fs.readFileSync('native/include/HBEngine/Library.hpp','utf8')),entries=[],services=[];
  const group={Math:'수학',VectorMath:'벡터',Clock:'시간',Timers:'시간',Scene:'변환'};
  for(const c of native.classes)for(const f of c.functions){
    if(!f.nodeKey)throw Error(c.name+'.'+f.name+' 노드 ID 누락');
    const exec={id:'exec',label:'실행',type:'exec',array:false},then={id:'then',label:'다음',type:'exec',array:false};
    (f.service?services:entries).push({key:f.nodeKey,title:f.label.replace(/([a-z0-9])([A-Z])/g,'$1 $2'),ko:f.ko,group:group[c.name]||f.category,keywords:f.nodeKey+' '+f.label+' '+f.ko+' '+f.category+' c++ cpp',cppName:'hb::'+c.name+'::'+f.name,pure:f.pure,...(f.service?{service:true}:{}),inputs:[...(!f.pure?[exec]:[]),...f.inputs],outputs:[...(!f.pure?[then]:[]),...f.outputs.map(p=>({...p,id:p.id==='result'?'return':p.id}))],defaults:Object.fromEntries(f.inputs.filter(p=>['duration','speed','scale','alpha','tolerance','delta','maxLength'].includes(p.id)).map(p=>[p.id,p.id==='delta'?1/60:p.id==='tolerance'?.001:1]))});
  }
  if(new Set(entries.map(e=>e.key)).size!==entries.length)throw Error('중복된 공통 API 노드 ID');
  if(new Set([...entries,...services].map(e=>e.key)).size!==entries.length+services.length)throw Error('중복된 엔진 API 노드 ID');
  return '// Generated by tools/generate-api.mjs from HBEngine/Game.hpp and Library.hpp.\nexport const coreApi = '+JSON.stringify(entries,null,2)+';\nexport const serviceApi = '+JSON.stringify(services,null,2)+';\n';
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
  updateLibrary(process.argv.includes('--check'));
  const output=generatedCore();if(process.argv.includes('--check')){if(fs.readFileSync('prototype/core-api.js','utf8')!==output)throw Error('C++ API 변경 뒤 npm run api:generate를 실행하세요.');}else fs.writeFileSync('prototype/core-api.js',output);
  await import('./generate-catalog.mjs');
}
