import fs from 'node:fs';
import {catalog} from '../prototype/blueprint-model.js';
const groups=new Map();for(const node of catalog){if(!groups.has(node.group))groups.set(node.group,[]);groups.get(node.group).push(node);}
const limitations={openScene:'미구현: 명시적 실행 오류',impulse:'브라우저 속도 적용; 강체 solver 없음',playSoundAt:'오디오 재생; 위치 음향 없음',cast:'기본 객체 클래스 검사',damage:'외부 이벤트 진입점; 피해 시스템 없음',hitEvent:'AABB 접촉; 강체 solver 없음'};
const status=n=>n.cppName?'공통 C++ + VM':limitations[n.key]||n.kind==='event'&&'VM 이벤트 진입점'||'VM / 브라우저 서비스';
const pins=list=>list.map(p=>p.id+': '+p.type+(p.array?'[]':'')).join(', ')||'—';
const clean=s=>String(s).replaceAll('|','\\|');
let content=`# HBEngine 기본 노드 전체 목록\n\n기본 노드 **${catalog.length}개**, 실제 공통 C++ API **${catalog.filter(n=>n.cppName).length}개**. 변수·사용자 함수/매크로·C++ 공개 선언·통신 시그니처에서 생성되는 추가 노드는 별도다. 이 문서는 tools/generate-catalog.mjs가 실제 등록 테이블에서 생성한다.\n\n모든 노드에 실행 경로가 있다. 서비스가 필요한 노드는 아래 범위와 [BP 구현 상태](BLUEPRINT_SPEC.md)를 따른다. 실행 경로가 존재한다는 뜻을 모든 시스템의 native 구현 완료로 해석하지 않는다. 새 공통 221개 함수는 실제 C++/JS 결과 비교를 수행한다.\n\n[공식 흐름 제어](https://dev.epicgames.com/documentation/unreal-engine/flow-control-in-unreal-engine?lang=en-US), [공식 String 라이브러리](https://dev.epicgames.com/documentation/unreal-engine/API/Runtime/Engine/UKismetStringLibrary), [Epic 4.27 배열 노드](https://dev.epicgames.com/documentation/en-us/unreal-engine/array-nodes?application_version=4.27)를 제작 흐름 참고 자료로 사용했다. 아래 함수 구현은 HB 자체 코드다.\n\n## 분야별 수\n\n| 분야 | 노드 | 공통 C++ |\n| --- | ---: | ---: |\n`;
for(const [group,nodes] of groups)content+=`| ${group} | ${nodes.length} | ${nodes.filter(n=>n.cppName).length} |\n`;
content+='\n## 범위와 사용 규칙\n\n- C++ 칸이 있는 함수는 Game.hpp를 include해 같은 이름으로 직접 호출한다. VM 제어 노드는 C++ 함수와 다른 실행 구조이며, 브라우저 게임 서비스의 native API는 별도 구현 대상이다.\n- 자료형별 배열의 Reverse/Append/Slice/Unique는 사본 반환이다. Set/Add/Remove는 배열 변수를 수정하는 실행 노드다. 저장과 공통 배열 계산은 128원소다.\n- 32비트 int, 0~1 RGBA Color, XYZ Euler degree, +Z Forward/+Y Up을 사용한다. 새 Text 연산은 Unicode scalar 기준이고 대소문자 변환은 ASCII다.\n- Switch/MultiGate는 3출력, Sequence는 2출력이다. 동적 출력 핀은 미지원이다.\n- openScene은 실행 서비스를 아직 구현하지 않아 명시적으로 실패한다. Audio는 브라우저 코덱, Animation은 가져온 모델의 포함 클립을 사용한다. 충돌은 AABB 접촉, Trace는 Three mesh 검사, Impulse는 속도 적용이다.\n- Construction은 별도 그래프의 진입점이고 Timeline 트랙 핀은 편집한 트랙에 따라 추가된다. 사용자 이벤트·피해/위젯 이벤트에는 외부 emit 호출이 필요하다.\n';
for(const [group,nodes] of groups){content+=`\n## ${group}\n\n| ID | 영어 / 한글 | 입력 핀 | 출력 핀 | C++ | 실행 범위 |\n| --- | --- | --- | --- | --- | --- |\n`;for(const n of nodes)content+='| '+[n.key,n.title+' / '+n.ko,pins(n.inputs),pins(n.outputs),n.cppName||'—',status(n)].map(clean).join(' | ')+' |\n';}
const file='docs/NODE_CATALOG.md';if(process.argv.includes('--check')){if(fs.readFileSync(file,'utf8')!==content)throw Error('npm run api:generate로 노드 카탈로그를 갱신하세요.');}else fs.writeFileSync(file,content);
