import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {runTool} from './mobile-android.mjs';
const root=path.resolve(import.meta.dirname,'..'),quote=value=>JSON.stringify(value),id=value=>createHash('sha256').update(value).digest('hex').slice(0,24).toUpperCase();
const xml=value=>String(value).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export async function mobileCapability(){let xcode=false;if(process.platform==='darwin')try{await runTool('xcrun',['--sdk','iphoneos','--show-sdk-path'],{timeout:10000});xcode=true;}catch{}return {ready:true,projectExport:true,compileReady:xcode,requires:'Mac + Xcode; device/archive signing requires Apple team',artifactType:'xcodeProject'};}
export async function packageMobile({out,assets,profile,settings,native,signal,onProgress,capability}){
  signal?.throwIfAborted();onProgress('iOS Xcode 프로젝트');const main=path.join(out,'Native/Main.mm');await fs.copyFile(path.join(root,'native/mobile/ios/Main.mm'),main);
  const files=[main,...native.sources],objects=[],references=[],buildFiles=[];
  for(const file of files){const relative=path.relative(out,file).split(path.sep).join('/'),ref=id('ref'+relative),build=id('build'+relative);references.push(ref);buildFiles.push(build);objects.push(`${ref} = {isa = PBXFileReference; lastKnownFileType = ${relative.endsWith('.mm')?'sourcecode.cpp.objcpp':'sourcecode.cpp.cpp'}; path = ${quote(relative)}; sourceTree = "<group>"; };`,`${build} = {isa = PBXBuildFile; fileRef = ${ref}; };`);}
  const ids=Object.fromEntries(['project','group','products','app','assets','assetBuild','target','sources','resources','frameworks','projectConfigs','targetConfigs','projectDebug','projectRelease','targetDebug','targetRelease'].map(key=>[key,id(key)]));
  objects.push(`${ids.assets} = {isa = PBXFileReference; lastKnownFileType = folder; path = Assets; sourceTree = "<group>"; };`,`${ids.assetBuild} = {isa = PBXBuildFile; fileRef = ${ids.assets}; };`,`${ids.app} = {isa = PBXFileReference; explicitFileType = wrapper.application; path = HBGame.app; sourceTree = BUILT_PRODUCTS_DIR; };`,`${ids.group} = {isa = PBXGroup; children = (${[...references,ids.assets,ids.products].join(',')}); sourceTree = "<group>"; };`,`${ids.products} = {isa = PBXGroup; children = (${ids.app}); name = Products; sourceTree = "<group>"; };`,`${ids.sources} = {isa = PBXSourcesBuildPhase; buildActionMask = 2147483647; files = (${buildFiles.join(',')}); runOnlyForDeploymentPostprocessing = 0; };`,`${ids.resources} = {isa = PBXResourcesBuildPhase; buildActionMask = 2147483647; files = (${ids.assetBuild}); runOnlyForDeploymentPostprocessing = 0; };`,`${ids.frameworks} = {isa = PBXFrameworksBuildPhase; buildActionMask = 2147483647; files = (); runOnlyForDeploymentPostprocessing = 0; };`,`${ids.target} = {isa = PBXNativeTarget; buildConfigurationList = ${ids.targetConfigs}; buildPhases = (${ids.sources},${ids.frameworks},${ids.resources}); buildRules = (); dependencies = (); name = HBGame; productName = HBGame; productReference = ${ids.app}; productType = "com.apple.product-type.application"; };`,`${ids.project} = {isa = PBXProject; attributes = {LastUpgradeCheck = 1600; }; buildConfigurationList = ${ids.projectConfigs}; compatibilityVersion = "Xcode 14.0"; developmentRegion = en; knownRegions = (en,Base); mainGroup = ${ids.group}; productRefGroup = ${ids.products}; projectDirPath = ""; projectRoot = ""; targets = (${ids.target}); };`);
  for(const [name,release] of [['Debug',false],['Release',true]]){
    const projectID=release?ids.projectRelease:ids.projectDebug,targetID=release?ids.targetRelease:ids.targetDebug;
    objects.push(`${projectID} = {isa = XCBuildConfiguration; buildSettings = {SDKROOT = iphoneos; CLANG_CXX_LANGUAGE_STANDARD = "c++17"; CLANG_ENABLE_OBJC_ARC = YES; IPHONEOS_DEPLOYMENT_TARGET = 16.4; GCC_OPTIMIZATION_LEVEL = ${release?'2':'0'}; }; name = ${name}; };`,`${targetID} = {isa = XCBuildConfiguration; buildSettings = {PRODUCT_NAME = HBGame; PRODUCT_BUNDLE_IDENTIFIER = ${quote(settings.applicationId)}; INFOPLIST_FILE = Info.plist; TARGETED_DEVICE_FAMILY = "1,2"; CODE_SIGN_STYLE = Automatic; HEADER_SEARCH_PATHS = ("$(PROJECT_DIR)/Native", "$(PROJECT_DIR)/Native/include"); OTHER_LDFLAGS = ("-framework",UIKit,"-framework",WebKit); }; name = ${name}; };`);
  }
  for(const [key,debug,release] of [['projectConfigs',ids.projectDebug,ids.projectRelease],['targetConfigs',ids.targetDebug,ids.targetRelease]])objects.push(`${ids[key]} = {isa = XCConfigurationList; buildConfigurations = (${debug},${release}); defaultConfigurationIsVisible = 0; defaultConfigurationName = Release; };`);
  const project=path.join(out,'HBGame.xcodeproj');await fs.mkdir(project);await fs.writeFile(path.join(project,'project.pbxproj'),`// !$*UTF8*$!\n{archiveVersion = 1; classes = {}; objectVersion = 56; objects = {\n${objects.join('\n')}\n}; rootObject = ${ids.project};}\n`);
  const orientations=settings.orientation==='landscape'?['UIInterfaceOrientationLandscapeLeft','UIInterfaceOrientationLandscapeRight']:settings.orientation==='portrait'?['UIInterfaceOrientationPortrait']:['UIInterfaceOrientationPortrait','UIInterfaceOrientationLandscapeLeft','UIInterfaceOrientationLandscapeRight'];
  const plist=`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>CFBundleIdentifier</key><string>$(PRODUCT_BUNDLE_IDENTIFIER)</string><key>CFBundleExecutable</key><string>$(EXECUTABLE_NAME)</string><key>CFBundleName</key><string>HBGame</string><key>CFBundleDisplayName</key><string>${xml(profile.productName)}</string><key>CFBundlePackageType</key><string>APPL</string><key>CFBundleShortVersionString</key><string>${xml(settings.versionName)}</string><key>CFBundleVersion</key><string>${settings.versionCode}</string><key>UILaunchScreen</key><dict/><key>UISupportedInterfaceOrientations</key><array>${orientations.map(o=>'<string>'+o+'</string>').join('')}</array><key>NSAppTransportSecurity</key><dict><key>NSAllowsLocalNetworking</key><true/></dict></dict></plist>`;
  await fs.writeFile(path.join(out,'Info.plist'),plist);
  await fs.writeFile(path.join(out,'build-ios.sh'),'#!/bin/sh\nset -eu\ncd "$(dirname "$0")"\nxcodebuild -project HBGame.xcodeproj -scheme HBGame -configuration '+(profile.configuration==='release'?'Release':'Debug')+' -destination "generic/platform=iOS" -archivePath HBGame.xcarchive archive "$@"\n');
  await fs.writeFile(path.join(out,'iOS 빌드 안내.txt'),'HBGame.xcodeproj를 Mac의 Xcode에서 열어요.\nSigning & Capabilities에서 본인의 Apple 팀을 선택하고 기기 또는 시뮬레이터를 선택하세요.\nProduct > Archive 후 Organizer에서 앱을 내보낼 수 있어요.\nWindows에서 생성한 이 프로젝트는 아직 iOS 컴파일·서명·실행 검증을 거치지 않았어요.\n');
  return {artifact:project,artifactType:'xcodeProject',compileVerified:false,signingVerified:false,installVerified:false,launchVerified:false,capability};
}
