import {parseNativeHeader,nativeTargetPin} from '../prototype/native-model.js';
const cpp={bool:'bool',int:'int',float:'float',string:'std::string',vec2:'hb::Vec2',vec3:'hb::Vec3',color:'hb::Color',transform:'hb::Transform',object:'hb::Actor*',hit:'hb::HitResult'};
const cppType=p=>p.array?`std::vector<${cppType({...p,array:false})}>`:p.type==='object'?`${['Object','Actor','Pawn','Character','Controller','PlayerController','GameMode','GameState','PlayerState','AIController','Component','SceneComponent'].includes(p.className)?'hb::'+(p.className==='Object'?'Actor':p.className):p.className||'hb::Actor'}*`:cpp[p.type];
function unpack(p,expr){if(p.array&&p.type==='object')return `hb::bridgeObjectArray<${cppType({...p,array:false}).slice(0,-1)}>(${expr})`;return p.type==='object'?`dynamic_cast<${cppType(p)}>(hb::bridgeActor(${expr}))`:`${expr}.get<${cppType(p)}>()`;}
export function generatedWorker(meta,{portableName}={}){
  let definitions='',cases='',factory='',localCases='';
  for(const c of meta.classes){
    if(!['Actor','Pawn','Character','Controller','PlayerController','GameMode','GameState','PlayerState','AIController','Component','SceneComponent','Library'].includes(c.base))throw Error('실행 부모 클래스는 Actor·Component·Library를 지원해요.');
    const actor=['Actor','Pawn','Character','Controller','PlayerController','GameMode','GameState','PlayerState','AIController'].includes(c.base)?'return this;':['Component','SceneComponent'].includes(c.base)?'return this->'+c.name+'::actor;':'return nullptr;';
    const props=c.properties.map(p=>`j["${p.name}"]=hb::bridgeValue(this->${p.name});`).join('');
    const defaults=c.properties.map(p=>`if(j.contains("${p.name}"))this->${p.name}=${unpack(p,`j.at("${p.name}")`)};`).join('');
    const events=c.functions.filter(f=>f.event!=='none').map(f=>{const args=f.parameters.map(p=>`${p.cppType} ${p.name}`).join(','),id=c.name+'.'+f.name,payload=f.inputs.map(p=>`{"${p.id}",hb::bridgeValue(${p.id})}`).join(',');return `void ${f.name}(${args}) override {if(hb::overridden("${id}")){hb::bridgeEvents.push_back({{"nativeId","${id}"},{"target",this->id},{"args",hb::Json{${payload}}}});}else{${f.event==='native'?`${c.name}::${f.name}(${f.parameters.map(p=>p.name).join(',')});`:''}}}`;}).join('\n');
    definitions+=`struct HB_${c.name}: public ${c.name},public hb::BridgeCell {std::string id;${events} hb::Actor* actor() override {${actor}} hb::Json properties() override {hb::Json j=hb::Json::object();${props}return j;}void defaults(const hb::Json& j) override {${defaults}}};\n`;
    factory+=`if(className=="${c.name}"){auto cell=std::make_unique<HB_${c.name}>();cell->id=id;${['Component','SceneComponent'].includes(c.base)?'cell->'+c.name+'::actor=hb::bridgeActor(id);':''}${['Actor','Pawn','Character','Controller','PlayerController','GameMode','GameState','PlayerState','AIController'].includes(c.base)?'hb::bridgeActors.erase(id);':''}hb::bridgeCells[id]=std::move(cell);return true;}\n`;
    for(const p of c.properties){const id=c.name+'.'+p.name,target=`auto* target=dynamic_cast<HB_${c.name}*>(hb::bridgeCells.at(targetId).get());if(!target)throw std::runtime_error("C++ target class mismatch");`;
      if(!p.array&&['float','int'].includes(p.type))localCases+=`if(dynamic_cast<HB_${c.name}*>(cell->second.get())&&member=="${p.name}"&&operation!="call"){auto* target=dynamic_cast<HB_${c.name}*>(cell->second.get());if(operation=="getFloat")return hb::Json{{"value",target->${p.name}}};${!p.readOnly?`if(operation=="setFloat"){auto value=args.at("value").get<double>();if(!std::isfinite(value)${p.type==='int'?'||std::floor(value)!=value||value<INT32_MIN||value>INT32_MAX':''})throw std::runtime_error("invalid native number");target->${p.name}=static_cast<${cppType(p)}>(value);return hb::Json::object();}`:''}throw std::runtime_error("invalid native property operation");}\n`;
      cases+=`if(nativeId=="${id}"){if(ensure(targetId,"${c.name}"))hb::bridgeSync(objects);${target}if(key=="nativeGet")out["value"]=hb::bridgeValue(target->${p.name});${!p.readOnly?`else if(key=="nativeSet")target->${p.name}=${unpack(p,'args.at("value")')};`:''}else throw std::runtime_error("invalid property operation");handled=true;}\n`;
    }
    for(const f of c.functions){
      localCases+=`if(dynamic_cast<HB_${c.name}*>(cell->second.get())&&member=="${f.name}"&&operation=="call"){auto values=args.at("arguments");hb_native::CheckInputs(hb::Json::parse(${JSON.stringify(JSON.stringify(f.inputs))}),values,hb::bridgeWorld);${!f.static?`values["${nativeTargetPin(f)}"]=id;`:''}call["nativeId"]="${c.name+'.'+f.name}";call["args"]=values;return HB_invoke(call,hb::bridgeWorld);}\n`;
      const id=c.name+'.'+f.name,locals=f.parameters.map((_,i)=>'HB_arg_'+i),declarations=f.parameters.map((parameter,i)=>{const p=[...f.inputs,...f.outputs].find(p=>p.id===parameter.name);if(!p)throw Error('공개 매개변수 정보가 없어요.');return cppType(p)+' '+locals[i]+'='+(parameter.out?'{}':unpack(p,'args.at("'+p.id+'")'))+';';}).join('');
      const receiverId=!f.static?'args.at("'+nativeTargetPin(f)+'").get<std::string>()':'targetId',target=f.static?'':'if(ensure('+receiverId+',"'+c.name+'"))hb::bridgeSync(objects);auto* HB_receiver=dynamic_cast<HB_'+c.name+'*>(hb::bridgeCells.at('+receiverId+').get());if(!HB_receiver)throw std::runtime_error("C++ target class mismatch");',receiver=f.static?c.name+'::':'HB_receiver->';
      const invoke=receiver+f.name+'('+locals.join(',')+')',result=f.returnType==='void'?invoke+';':'auto HB_result='+invoke+';out["'+f.outputs.find(p=>!f.parameters.some(param=>param.out&&param.name===p.id)).id+'"]=hb::bridgeValue(HB_result);';
      cases+='if(nativeId=="'+id+'"&&key=="nativeCall"){'+target+declarations+'hb::Timers::SetContext('+receiverId+',request.value("scope",std::string{}));'+result+f.parameters.map((p,i)=>p.out?'out["'+p.name+'"]=hb::bridgeValue('+locals[i]+');':'').join('')+'handled=true;}\n';
    }
  }
  return `#include <HBEngine/Native.hpp>\n#include "User.hpp"\n${definitions}
static bool ensure(const std::string& id,const std::string& className){if(hb::bridgeCells.count(id))return false;${factory}throw std::runtime_error("unknown C++ class");}
static hb::Json HB_clock(){return {{"time",hb::Clock::GetGameTime()},{"delta",hb::Clock::GetWorldDeltaSeconds()},{"scale",hb::Clock::TimeScale()},{"paused",hb::Clock::IsPaused()}};}
static hb::Json HB_invoke(const hb::Json& request,const hb::Json& objects){hb::bridgeOverrides=request.value("overrides",std::vector<std::string>{});hb::Timers::SetContext(request.value("self",std::string{}),request.value("scope",std::string{}));const auto key=request.at("key").get<std::string>(),nativeId=request.at("nativeId").get<std::string>();const auto args=request.at("args");const auto targetId=(key=="nativeGet"||key=="nativeSet")?args.at("target").get<std::string>():request.value("self",std::string{});hb::Json out=hb::Json::object();bool handled=false;${cases}if(!handled)throw std::runtime_error("unknown native function");return out;}
static hb::Json HB_localNative(const hb::Json& args){const auto id=args.at("target").get<std::string>();const auto cell=hb::bridgeCells.find(id);if(cell==hb::bridgeCells.end())return nullptr;const auto member=args.at("member").get<std::string>(),operation=args.at("operation").get<std::string>();hb::Json overrides=hb::Json::array();for(const auto& binding:hb::bridgeNativeBindings)if(binding.at("id")==id)overrides=binding.at("overrides");hb::Json call={{"key","nativeCall"},{"self",id},{"scope",hb::Timers::GetContext().second},{"overrides",overrides}};${localCases}throw std::runtime_error("unknown local native member");}
static void HB_callbacks(hb::Json& response){for(const auto& event:hb::Timers::TakeCallbacks()){response["timerEvents"].push_back(event.event);response["timerCallbacks"].push_back({{"event",event.event},{"owner",event.owner},{"scope",event.scope},{"handle",event.handle}});}}
static std::string HB_process(const std::string& line){static hb::Json inputObjects=hb::Json::array();hb::Json response;const auto HB_started=std::chrono::steady_clock::now();auto HB_phase=HB_started;auto HB_ms=[](auto from){return std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-from).count();};hb::Json HB_timing=hb::Json::object();try{auto request=hb::Json::parse(line);HB_timing["parseMs"]=HB_ms(HB_started);HB_phase=std::chrono::steady_clock::now();response["timerEvents"]=hb::Json::array();response["timerCallbacks"]=hb::Json::array();hb::bridgeEvents=hb::Json::array();hb::bridgeOperations=hb::Json::array();hb::bridgeForeign=hb::Json::array();hb::bridgeNativeBindings=request.value("nativeBindings",hb::Json::array());hb::bridgeLocalNative=HB_localNative;hb::bridgeOverrides=request.value("overrides",std::vector<std::string>{});hb::bridgeInput=request.value("input",hb::Json::object());hb::Timers::SetContext(request.value("self",std::string{}),request.value("scope",std::string{}));if(request.contains("scopes"))hb::Timers::PruneScopes(request.at("scopes").get<std::vector<std::string>>());const auto command=request.value("command",std::string{});
if(request.value("command",std::string{})=="reset"){inputObjects=hb::Json::array();hb::bridgeCells.clear();hb::bridgeActors.clear();hb::bridgeActorIds.clear();hb::bridgeStateIndices.clear();hb::bridgeWorld=hb::Json::array();hb::Clock::Reset();hb::Timers::Reset();}
else if(request.value("command",std::string{})=="frame"){if(request.contains("clock")){hb::Clock::SetTimeScale(request.at("clock").at("scale").get<float>());hb::Clock::SetPaused(request.at("clock").at("paused").get<bool>());}hb::AdvanceFrame(request.at("delta").get<float>());}
else{if(request.contains("clock")){hb::Clock::SetTimeScale(request.at("clock").at("scale").get<float>());hb::Clock::SetPaused(request.at("clock").at("paused").get<bool>());}const bool HB_patch=request.contains("objectPatch");if(HB_patch){hb::bridgeRestoreWorld(inputObjects);inputObjects.patch_inplace(request.at("objectPatch"));hb::bridgeWorld.patch_inplace(request.at("objectPatch"));}else inputObjects=request.value("objects",hb::Json::array());HB_timing["patchMs"]=HB_ms(HB_phase);HB_phase=std::chrono::steady_clock::now();const auto& objects=inputObjects;bool HB_created=false;for(const auto& o:objects)if(o.contains("nativeClass")&&!o.at("nativeClass").is_null()&&o.at("nativeClass")!="Actor")HB_created=ensure(o.at("id").get<std::string>(),o.at("nativeClass").get<std::string>())||HB_created;hb::bridgeSync(objects,!HB_patch||HB_created);HB_timing["syncMs"]=HB_ms(HB_phase);HB_phase=std::chrono::steady_clock::now();
if(request.contains("calls")){response["results"]=hb::Json::array();response["objects"]=hb::Json::array();response["foreign"]=hb::Json::array();response["clock"]=HB_clock();for(const auto& call:request.at("calls")){try{auto out=HB_invoke(call,objects);response["results"].push_back({{"outputs",out}});response["objects"]=hb::bridgeChangedSnapshot(inputObjects);response["foreign"]=hb::bridgeForeign;HB_callbacks(response);const auto nextClock=HB_clock();const bool boundary=!hb::bridgeForeign.empty()||!hb::bridgeEvents.empty()||!hb::bridgeOperations.empty()||!response["timerCallbacks"].empty()||nextClock!=response["clock"];response["clock"]=nextClock;if(boundary){response["batchBoundary"]=true;break;}}catch(const std::exception& e){response["nativeError"]=e.what();hb::bridgeEvents=hb::Json::array();hb::bridgeOperations=hb::Json::array();break;}}HB_timing["calls"]=response["results"].size();}
else response["outputs"]=HB_invoke(request,objects);HB_timing["invokeMs"]=HB_ms(HB_phase);}HB_phase=std::chrono::steady_clock::now();
if(!response.contains("foreign"))response["foreign"]=hb::bridgeForeign;if(!response.contains("clock"))response["clock"]=HB_clock();response["events"]=hb::bridgeEvents;response["operations"]=hb::bridgeOperations;if(!response.contains("objects"))response["objects"]=command=="frame"||command=="reset"?hb::Json::array():hb::bridgeChangedSnapshot(inputObjects);HB_callbacks(response);HB_timing["snapshotMs"]=HB_ms(HB_phase);HB_timing["workerMs"]=HB_ms(HB_started);response["transport"]=HB_timing;response["ok"]=true;
}catch(const std::exception& e){response={{"ok",false},{"error",e.what()}};}return response.dump();}
${portableName?`std::string ${portableName}(const std::string& line,const std::function<std::string(const std::string&)>& query){hb::bridgeQuery=[&](const hb::Json& packet){return hb::Json::parse(query(packet.dump()));};auto result=HB_process(line);hb::bridgeQuery={};return result;}`:`int main(){std::string line;while(std::getline(std::cin,line)){auto result=HB_process(line);std::cout<<"HB_RESULT\\t"<<result<<std::endl;}return 0;}`}
`;
}

export function nativeSources(header,source,{portableName}={}){
 if(typeof source!=='string'||source.length>500000)throw Error('C++ 구현은 500 KB 이하로 입력하세요.');const metadata=parseNativeHeader(header);metadata.workerProtocol=3;metadata.nativeBatch=1;metadata.nativeModuleQueries=1;if(!metadata.classes.length)throw Error('공개 C++ 클래스가 없어요.');
 let compiledHeader=header.replace(/(HB_FUNCTION\([^)]*Blueprint(?:Native|Implementable)Event[^)]*\)\s*)(?!virtual\b)(void\s)/g,'$1virtual $2');
 let compiledSource='#include <HBEngine/Native.hpp>\n'+source.replace(/^\s*#include\s*"[^"\n]+\.(?:h|hpp)"\s*$/gm,'');compiledSource='#include "User.hpp"\n'+compiledSource;
 for(const c of metadata.classes)for(const f of c.functions.filter(f=>f.event==='implementable'))if(!new RegExp('\\b'+c.name+'\\s*::\\s*'+f.name+'\\s*\\(').test(source))compiledSource+='\nvoid '+c.name+'::'+f.name+'('+f.parameters.map(p=>p.cppType+' '+p.name).join(',')+'){}\n';
 return {metadata,header:compiledHeader,source:compiledSource,worker:generatedWorker(metadata,{portableName})};
}
