import {Object3D,Vector3,Quaternion,Euler,Matrix4,PropertyBinding,BufferGeometry,BufferAttribute,LineBasicMaterial,LineSegments} from 'three';
import {sceneWorldMatrix} from './scene-runtime.js';
export const animationIKTypes=['twoBoneIK','fabrik'];
export const animationIKSpaces=['component','world','bone','parentBone'];
const clamp=v=>Math.max(0,Math.min(1,v)),text=v=>typeof v==='string'&&v.length<=160,vector=v=>Array.isArray(v)&&v.length===3&&v.every(x=>Number.isFinite(x)&&Math.abs(x)<=100000),unit=v=>Number.isFinite(v)&&v>=0&&v<=1;
const referenceBones=new WeakMap();
export function animationIKDefaults(type){return {root:'',tip:'',alpha:1,alphaScale:1,alphaBias:0,parameter:'',target:[1,1,0],targetActor:'',space:'component',spaceBone:'',rotation:[0,0,0],rotationMode:'local',positionWeight:1,rotationWeight:1,maintainPositionOffset:false,maintainRotationOffset:false,debug:false,...type==='twoBoneIK'?{hint:[0,1,0],hintActor:'',hintSpace:'component',hintBone:'',hintWeight:1,allowStretch:false,startStretch:1,maxStretch:1.5,allowTwist:true,twistAxis:'x'}:{precision:.001,iterations:16}};}
export function validAnimationIK(type,p){return text(p.root)&&text(p.tip)&&unit(p.alpha)&&Number.isFinite(p.alphaScale)&&Math.abs(p.alphaScale)<=100&&Number.isFinite(p.alphaBias)&&Math.abs(p.alphaBias)<=100&&text(p.parameter)&&vector(p.target)&&vector(p.rotation)&&text(p.targetActor)&&animationIKSpaces.includes(p.space)&&text(p.spaceBone)&&['local','component','target'].includes(p.rotationMode)&&unit(p.positionWeight)&&unit(p.rotationWeight)&&typeof p.maintainPositionOffset==='boolean'&&typeof p.maintainRotationOffset==='boolean'&&typeof p.debug==='boolean'&&(type==='twoBoneIK'?vector(p.hint)&&text(p.hintActor)&&animationIKSpaces.includes(p.hintSpace)&&text(p.hintBone)&&unit(p.hintWeight)&&typeof p.allowStretch==='boolean'&&Number.isFinite(p.startStretch)&&p.startStretch>0&&p.startStretch<=1&&Number.isFinite(p.maxStretch)&&p.maxStretch>=1&&p.maxStretch<=10&&typeof p.allowTwist==='boolean'&&['x','y','z'].includes(p.twistAxis):Number.isFinite(p.precision)&&p.precision>0&&p.precision<=1&&Number.isInteger(p.iterations)&&p.iterations>=1&&p.iterations<=128);}

// A solver owns only the referenced hierarchy and reusable math scratch. It reads
// an input pose without changing the real skeleton or another branch's pose.
export class AnimationIK {
  constructor(owner,node,slot){
    this.actorTransform={...owner.object,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]};this.euler=new Euler();this.quaternion=new Quaternion();this.owner=owner;this.node=node;this.p=node.properties;this.hierarchy=new Map();this.scratch=new Object3D();this.override={};this.positionOffset=new Vector3();this.rotationOffset=new Quaternion();this.offsetReady=false;
    const find=name=>{let found;owner.group?.traverse(o=>{if(o.isBone&&o.name===name){if(found)throw Error('IK 뼈 이름이 중복돼요: '+name);found=o;}});if(!found)throw Error('IK 뼈가 없어요: '+name);return found;};
    const tip=find(this.p.tip),root=this.p.root?find(this.p.root):node.type==='twoBoneIK'?tip.parent?.parent:null;this.bones=[];let current=tip;
    const seen=new Set();while(current&&current!==owner.group&&current.isBone){if(seen.has(current))throw Error('IK 뼈 계층이 순환해요.');seen.add(current);this.bones.unshift(current);if(current===root)break;current=current.parent;}
    if(!root||this.bones[0]!==root||this.bones.length<2||node.type==='twoBoneIK'&&this.bones.length!==3)throw Error('IK 루트·중간·끝 뼈의 부모 연결을 확인하세요.');
    const add=original=>{if(!original||original===owner.group)return this.scratch;if(this.hierarchy.has(original))return this.hierarchy.get(original).value;let rest=referenceBones.get(original);if(!rest){rest={position:original.position.clone(),quaternion:original.quaternion.clone(),scale:original.scale.clone()};if(original.isBone)referenceBones.set(original,rest);}const parent=add(original.parent),value=new Object3D();value.position.copy(rest.position);value.quaternion.copy(rest.quaternion);value.scale.copy(rest.scale);parent.add(value);this.hierarchy.set(original,{value,position:rest.position.clone(),rotation:rest.quaternion.clone(),scale:rest.scale.clone()});return value;};
    this.chain=this.bones.map(add);this.spaceBone=['bone','parentBone'].includes(this.p.space)?find(this.p.spaceBone):null;this.hintBone=node.type==='twoBoneIK'&&['bone','parentBone'].includes(this.p.hintSpace)?find(this.p.hintBone):null;if(this.spaceBone)add(this.spaceBone);if(this.hintBone)add(this.hintBone);
    for(const bone of this.bones)for(const property of ['position','quaternion']){const binding=PropertyBinding.create(bone,'.'+property);binding.displayName=bone.name+'.'+property;binding.bind();const values=referenceBones.get(bone)[property].toArray(),index=slot(bone.uuid+'|'+property+'|',values,property==='quaternion'?'quaternion':'number',bone,binding);owner.slots[index].rest.set(values);}
    this.positions=this.chain.map(()=>new Vector3());this.originalRotations=this.chain.map(()=>new Quaternion());this.originalPositions=this.chain.map(()=>new Vector3());this.lengths=new Float64Array(this.chain.length-1);this.target=new Vector3();this.hint=new Vector3();this.targetRotation=new Quaternion();this.tipRotation=new Quaternion();this.world=new Matrix4();this.inverseWorld=new Matrix4();this.reference=new Matrix4();this.referenceRotation=new Quaternion();this.scale=new Vector3();this.origin=new Vector3();this.direction=new Vector3();this.bend=new Vector3();this.hintDirection=new Vector3();this.oldDirection=new Vector3();this.newDirection=new Vector3();this.parentRotation=new Quaternion();this.worldRotation=new Quaternion();this.deltaRotation=new Quaternion();this.twist=new Quaternion();this.axis=new Vector3();this.debug={node:node.id,name:node.name,type:node.type,tip:[0,0,0],target:[0,0,0],hint:[0,0,0],error:0,iterations:0,weight:0,draw:this.p.debug};
  }
  readPose(pose){
    for(const [original,row] of this.hierarchy){row.value.position.copy(row.position);row.value.quaternion.copy(row.rotation);row.value.scale.copy(row.scale);for(const property of ['position','quaternion','scale']){const index=this.owner.slotKeys.get(original.uuid+'|'+property+'|');if(index!==undefined)row.value[property].fromArray(pose[index]);}const s=row.value.scale;if(s.x<=0||Math.abs(s.x-s.y)>1e-6||Math.abs(s.x-s.z)>1e-6)throw Error('IK 뼈 계층에는 양의 균일 크기가 필요해요: '+original.name);}
    this.scratch.updateMatrixWorld(true);for(let i=0;i<this.chain.length;i++){this.chain[i].getWorldPosition(this.positions[i]);this.originalRotations[i].copy(this.chain[i].quaternion);this.originalPositions[i].copy(this.chain[i].position);if(i){this.lengths[i-1]=this.positions[i].distanceTo(this.positions[i-1]);if(this.lengths[i-1]<1e-8)throw Error('IK 체인의 관절이 겹쳐 있어요.');}}
    for(const property of ['position','rotation','scale'])for(let i=0;i<3;i++)this.actorTransform[property][i]=this.owner.object[property][i];for(const property of ['position','quaternion','scale']){const key='root|'+property,index=this.owner.slotKeys.get(key);if(index===undefined||this.owner.rootLocked(key))continue;if(property==='quaternion'){this.euler.setFromQuaternion(this.quaternion.fromArray(pose[index]));this.actorTransform.rotation[0]=this.euler.x*180/Math.PI;this.actorTransform.rotation[1]=this.euler.y*180/Math.PI;this.actorTransform.rotation[2]=this.euler.z*180/Math.PI;}else for(let i=0;i<3;i++)this.actorTransform[property][i]=pose[index][i];}
    this.actorTransform.parent=this.owner.object.parent;this.actorTransform.parentId=this.owner.object.parentId;this.world.copy(sceneWorldMatrix(this.actorTransform,this.owner.objects?.()||[this.owner.object]));this.inverseWorld.copy(this.world).invert();
  }
  referenceFrame(space,bone,actor){
    const objects=this.owner.objects?.()||[this.owner.object];if(actor){const o=objects.find(o=>o.id===actor&&o.poolActive!==false&&!o.destroying);if(!o){this.debug.missingActor=actor;return null;}this.reference.copy(this.inverseWorld).multiply(o===this.owner.object?this.world:sceneWorldMatrix(o,objects));}
    else if(space==='world')this.reference.copy(this.inverseWorld);else if(space==='component')this.reference.identity();else{const value=this.hierarchy.get(bone)?.value;if(!value)throw Error('IK 기준 뼈가 없어요.');this.reference.copy(space==='parentBone'?value.parent.matrixWorld:value.matrixWorld);}
    return this.reference;
  }
  targets(){
    const p=this.p,o=this.override;this.debug.missingActor='';const frame=this.referenceFrame(p.space,this.spaceBone,o.targetActor??p.targetActor);if(!frame)return false;frame.decompose(this.origin,this.referenceRotation,this.scale);this.target.fromArray(o.target??p.target).applyMatrix4(this.reference);const r=o.rotation??p.rotation;this.euler??=new Euler();this.targetRotation.setFromEuler(this.euler.set(r[0]*Math.PI/180,r[1]*Math.PI/180,r[2]*Math.PI/180)).premultiply(this.referenceRotation).normalize();
    if(this.node.type==='twoBoneIK'){if(!this.referenceFrame(p.hintSpace,this.hintBone,o.hintActor??p.hintActor))return false;this.hint.fromArray(o.hint??p.hint).applyMatrix4(this.reference);}
    this.chain.at(-1).getWorldQuaternion(this.tipRotation);
    if(!this.offsetReady){if(p.maintainPositionOffset)this.positionOffset.copy(this.positions.at(-1)).sub(this.target);if(p.maintainRotationOffset)this.rotationOffset.copy(this.targetRotation).invert().multiply(this.tipRotation);this.offsetReady=true;}
    this.target.add(this.positionOffset);this.targetRotation.multiply(this.rotationOffset);this.debug.target=this.target.toArray(this.debug.target);this.debug.hint=this.hint.toArray(this.debug.hint);this.target.lerpVectors(this.positions.at(-1),this.target,p.positionWeight);return true;
  }
  align(index,point){
    // ponytail: hierarchy refresh per joint is O(n²); batch transforms if large rigs profile hot.
    const bone=this.chain[index],child=this.chain[index+1];bone.getWorldPosition(this.origin);child.getWorldPosition(this.oldDirection);this.oldDirection.sub(this.origin);this.newDirection.copy(point).sub(this.origin);if(this.newDirection.lengthSq()<1e-16)return;this.deltaRotation.setFromUnitVectors(this.oldDirection.normalize(),this.newDirection.normalize());bone.getWorldQuaternion(this.worldRotation);bone.parent.getWorldQuaternion(this.parentRotation);bone.quaternion.copy(this.parentRotation.invert().multiply(this.deltaRotation).multiply(this.worldRotation)).normalize();this.scratch.updateMatrixWorld(true);
  }
  twoBone(){
    const p=this.p,[a,b,c]=this.positions;this.direction.copy(this.target).sub(a);let distance=this.direction.length();if(distance<1e-8){this.direction.copy(c).sub(a);if(this.direction.lengthSq()<1e-16)this.direction.set(1,0,0);}this.direction.normalize();let l1=this.lengths[0],l2=this.lengths[1],stretch=1;
    if(p.allowStretch&&p.maxStretch>1)stretch=1+(p.maxStretch-1)*clamp((distance/(l1+l2)-p.startStretch)/(p.maxStretch-p.startStretch));if(stretch>1){this.chain[1].position.multiplyScalar(stretch);this.chain[2].position.multiplyScalar(stretch);l1*=stretch;l2*=stretch;this.scratch.updateMatrixWorld(true);}
    distance=Math.max(Math.abs(l1-l2)+1e-8,Math.min(l1+l2-1e-8,distance));const along=(distance*distance+l1*l1-l2*l2)/(2*distance),height=Math.sqrt(Math.max(0,l1*l1-along*along));
    this.bend.copy(b).sub(a).addScaledVector(this.direction,-this.bend.dot(this.direction));this.hintDirection.copy(this.hint).sub(a).addScaledVector(this.direction,-this.hintDirection.dot(this.direction));if(this.bend.lengthSq()<1e-16){if(p.hintWeight>0)this.bend.copy(this.hintDirection);if(this.bend.lengthSq()<1e-16){this.bend.set(Math.abs(this.direction.x)<.8?1:0,Math.abs(this.direction.x)<.8?0:1,0).addScaledVector(this.direction,-this.bend.dot(this.direction));}}
    this.bend.normalize();if(this.hintDirection.lengthSq()>1e-16){this.deltaRotation.setFromUnitVectors(this.bend,this.hintDirection.normalize());this.twist.identity().slerp(this.deltaRotation,p.hintWeight);this.bend.applyQuaternion(this.twist);}b.copy(a).addScaledVector(this.direction,along).addScaledVector(this.bend,height);c.copy(a).addScaledVector(this.direction,distance);this.align(0,b);this.align(1,c);this.debug.iterations=1;
  }
  fabrik(){
    const p=this.p,points=this.positions,last=points.length-1;this.origin.copy(points[0]);let reach=0;for(const length of this.lengths)reach+=length;this.debug.iterations=0;
    if(this.origin.distanceTo(this.target)>=reach){this.direction.copy(this.target).sub(this.origin).normalize();for(let i=1;i<=last;i++)points[i].copy(points[i-1]).addScaledVector(this.direction,this.lengths[i-1]);}
    else {if(last>1){this.direction.copy(points[last]).sub(this.origin).normalize();this.bend.set(Math.abs(this.direction.x)<.8?1:0,Math.abs(this.direction.x)<.8?0:1,0).addScaledVector(this.direction,-this.bend.dot(this.direction)).normalize();let straight=true;for(let i=1;i<last;i++){this.oldDirection.copy(points[i]).sub(this.origin).cross(this.direction);if(this.oldDirection.lengthSq()>1e-12){straight=false;break;}}this.oldDirection.copy(this.target).sub(this.origin).cross(this.direction);if(straight&&this.oldDirection.lengthSq()<1e-12)for(let i=1;i<last;i++)points[i].addScaledVector(this.bend,this.lengths[i-1]*.01);}
      while(points[last].distanceTo(this.target)>p.precision&&this.debug.iterations<p.iterations){points[last].copy(this.target);for(let i=last-1;i>=0;i--){this.direction.copy(points[i]).sub(points[i+1]);if(this.direction.lengthSq()<1e-16)this.direction.set(1,0,0);points[i].copy(points[i+1]).addScaledVector(this.direction.normalize(),this.lengths[i]);}points[0].copy(this.origin);for(let i=1;i<=last;i++){this.direction.copy(points[i]).sub(points[i-1]);if(this.direction.lengthSq()<1e-16)this.direction.set(1,0,0);points[i].copy(points[i-1]).addScaledVector(this.direction.normalize(),this.lengths[i-1]);}this.debug.iterations++;}}
    for(let i=0;i<last;i++)this.align(i,points[i+1]);
  }
  apply(pose,weight){
    this.readPose(pose);if(!this.targets())weight=0;this.debug.weight=weight;if(weight>0){if(this.node.type==='twoBoneIK')this.twoBone();else this.fabrik();const tip=this.chain.at(-1);if(this.p.rotationMode!=='local'){tip.parent.getWorldQuaternion(this.parentRotation);tip.quaternion.copy(this.parentRotation.invert().multiply(this.p.rotationMode==='target'?this.targetRotation:this.tipRotation)).normalize();tip.quaternion.slerp(this.originalRotations.at(-1),1-this.p.rotationWeight);}
      for(let i=0;i<this.chain.length;i++){const bone=this.chain[i];if(this.node.type==='twoBoneIK'&&!this.p.allowTwist&&i<this.chain.length-1){this.deltaRotation.copy(this.originalRotations[i]).invert().multiply(bone.quaternion);this.axis.set(this.p.twistAxis==='x'?1:0,this.p.twistAxis==='y'?1:0,this.p.twistAxis==='z'?1:0);const projection=this.deltaRotation.x*this.axis.x+this.deltaRotation.y*this.axis.y+this.deltaRotation.z*this.axis.z;this.twist.set(this.axis.x*projection,this.axis.y*projection,this.axis.z*projection,this.deltaRotation.w).normalize();bone.quaternion.copy(this.originalRotations[i]).multiply(this.deltaRotation.multiply(this.twist.invert())).normalize();}bone.quaternion.slerp(this.originalRotations[i],1-weight);bone.position.lerp(this.originalPositions[i],1-weight);bone.quaternion.toArray(pose[this.owner.slotKeys.get(this.bones[i].uuid+'|quaternion|')]);bone.position.toArray(pose[this.owner.slotKeys.get(this.bones[i].uuid+'|position|')]);}}
    this.scratch.updateMatrixWorld(true);this.chain.at(-1).getWorldPosition(this.origin);this.debug.tip=this.origin.toArray(this.debug.tip);this.debug.error=this.origin.distanceTo(this.target);this.drawDebug();return this.debug;
  }
  drawDebug(){if(!this.p.debug||!this.owner.group)return;if(!this.lines){const geometry=new BufferGeometry();geometry.setAttribute('position',new BufferAttribute(new Float32Array((this.chain.length-1+4+(this.node.type==='twoBoneIK'?1:0))*6),3));this.lines=new LineSegments(geometry,new LineBasicMaterial({color:0x76dcaa,depthTest:false,transparent:true,opacity:.9}));this.lines.frustumCulled=false;this.lines.renderOrder=1000;this.lines.userData.animationIKDebug=true;this.owner.group.add(this.lines);}const attr=this.lines.geometry.attributes.position;let at=0;const line=(a,b)=>{a.toArray(attr.array,at);b.toArray(attr.array,at+3);at+=6;};for(let i=1;i<this.chain.length;i++){this.chain[i-1].getWorldPosition(this.oldDirection);this.chain[i].getWorldPosition(this.newDirection);line(this.oldDirection,this.newDirection);}line(this.origin,this.target);for(let axis=0;axis<3;axis++){this.oldDirection.copy(this.target);this.newDirection.copy(this.target);this.oldDirection.setComponent(axis,this.oldDirection.getComponent(axis)-.08);this.newDirection.setComponent(axis,this.newDirection.getComponent(axis)+.08);line(this.oldDirection,this.newDirection);}if(this.node.type==='twoBoneIK'){this.chain[1].getWorldPosition(this.oldDirection);line(this.oldDirection,this.hint);}attr.needsUpdate=true;this.lines.visible=!this.debug.missingActor;}
  dispose(){this.lines?.removeFromParent();this.lines?.geometry.dispose();this.lines?.material.dispose();this.lines=null;this.hierarchy.clear();this.scratch.clear();}
}
