import {RuntimeInput,inputKey,validInputPacket} from './runtime-input.js';
import {InputActions} from './input-actions.js';
import {derivesFrom} from './class-types.js';
import {catalog,basePins,fieldsFor,defaultInputValue,defaultsFor,validBlueprint,graphContext,sampleTimeline,timelineLength,legacyTemplateConstruction} from './blueprint-model.js';
import {createCorePreview,evaluateCore} from './core-preview.js';
import {nativeMember,nativeTargetPin} from './native-model.js';
import {installBlueprintComponents} from './scene-components.js';
import {sceneContacts} from './scene-runtime.js';
const copy=v=>structuredClone(v),eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const events=new Set(catalog.filter(s=>s.kind==='event').map(s=>s.key));
const pure={random:a=>({return:a.min+Math.random()*(a.max-a.min)}),greater:a=>({return:a.a>a.b}),less:a=>({return:a.a<a.b}),equal:a=>({return:eq(a.a,a.b)}),notEqual:a=>({return:!eq(a.a,a.b)}),and:a=>({return:a.a&&a.b}),or:a=>({return:a.a||a.b}),not:a=>({return:!a.value}),select:a=>({return:a.condition?a.a:a.b}),concat:a=>({return:a.a+a.b}),stringLength:a=>({return:a.value.length}),contains:a=>({return:a.value.includes(a.search)}),toString:a=>({return:String(a.value)}),arrayLength:a=>({return:a.array.length}),arrayFind:a=>({return:a.array.findIndex(v=>eq(v,a.item))}),arrayContains:a=>({return:a.array.some(v=>eq(v,a.item))}),makeTransform:a=>({return:{position:a.position,rotation:a.rotation,scale:a.scale}}),makeColor:a=>({return:[a.r,a.g,a.b,a.a]}),reroute:a=>({value:a.value})};
const adapters=new Set(['spawn','destroy','visibility','attach','getComponent','addComponent','componentEnabled','trace','lineTrace','impulse','collisionEnabled','sound','playSoundAt','stopSound','playAnimation','stopAnimation','setMaterial','materialFloat','lightIntensity','openScene','createWidget','addViewport','setText','saveGame','loadGame','door','getGameMode','getGameState','getPlayerController','getPlayerState','getPlayerPawn','possess','unPossess','addMovementInput','jump','getVelocity','setVelocity','addForce','getWorldPosition','setWorldPosition','getLocalPosition','setLocalPosition']);
export const runtimeKeys=new Set([...events,...Object.keys(pure),...adapters,...catalog.filter(s=>s.cppName).map(s=>s.key),'timeline','branch','sequence','delay','forLoop','forEach','doOnce','doN','multiGate','whileLoop','forLoopBreak','forEachBreak','retriggerDelay','switchInt','switchString','flipFlop','gate','print','arrayGet','arraySet','arrayAdd','arrayRemove','self','members','isValid','cast','customFunction']);
export class BlueprintRuntime {
  constructor(objects,bindings,hooks={}){
    this.objects=objects;this.hooks=hooks;this.inputState=new RuntimeInput();this.inputQueue=Promise.resolve();this.inputEpoch=0;this.core=createCorePreview(hooks.now);this.values=this.core.values;this.bindings=bindings.map(({root,self})=>{if(!validBlueprint(root))throw Error('블루프린트 검증 실패');return {root:copy(root),self,variables:new Map(root.variables.map(v=>[v.id,copy(v.value)])),states:new Map(),ticks:new Map(),input:new InputActions(hooks.inputAssets?.contexts.get(root.settings?.inputMapping)?[{...hooks.inputAssets.contexts.get(root.settings.inputMapping),path:root.settings.inputMapping}]:[],hooks.inputAssets?.actions||new Map())};});
    installBlueprintComponents(this.objects,this.bindings);
    for(const b of this.bindings)if(legacyTemplateConstruction(b.root.construction)){b.root.construction.nodes.splice(1);b.root.construction.edges=[];this.hooks.log?.(b.root.name+': 예전 자동 생성 Construction 위치 초기화를 제외했어요.');}
    this.jobs=[];this.timelines=new Map();this.subscriptions=new Map();this.scopes=new Set();this.active=false;this.paused=false;this.pending=null;this.steps=0;this.overlaps=new Map();this.hits=new Map();this.generation=0;this.depth=0;this.stepRemaining=null;
    this.core.object=id=>this.object(id);this.core.updateObject=o=>this.hooks.updateObject?.(o);
  }
  object(id,b){return this.objects.find(o=>o.id===(id==='self'?b?.self:id));}
  frame(b,g=b.root,args={},scope=''){return {b,g,args,scope,outputs:new Map(),stack:[],result:{},returned:false,exit:'then',generation:this.generation,evaluating:new Set()};}
  frameActive(f){return this.active&&f.generation===this.generation&&(!f.scope||this.scopes.has(f.scope));}
  beginScope(scope){if(scope)this.scopes.add(scope);}
  inspectWork(){return {scopes:[...this.scopes],delays:this.jobs.map(j=>({node:j.node,owner:j.owner,scope:j.scope||'',at:j.at})),timers:[...this.core.timers].map(([id,t])=>({id,owner:t.owner||'',scope:t.scope||'',elapsed:t.elapsed,active:t.active})),timelines:[...this.timelines].map(([id,t])=>({id,node:t.n.id,owner:t.f.b.self,scope:t.f.scope||'',time:t.time,playing:t.playing})),subscriptions:[...this.subscriptions].flatMap(([signal,list])=>list.map(s=>({signal,owner:s.b.self,event:s.event,scope:s.scope||''})))};}
  cancelScope(scope){if(!scope)return;this.scopes.delete(scope);this.jobs=this.jobs.filter(j=>j.scope!==scope);for(const [id,t] of this.timelines)if(t.f.scope===scope)this.timelines.delete(id);for(const [id,t] of this.core.timers)if(t.scope===scope)this.core.timers.delete(id);for(const [id,list] of this.subscriptions){const next=list.filter(s=>s.scope!==scope);if(next.length)this.subscriptions.set(id,next);else this.subscriptions.delete(id);}if(this.pending?.f.scope===scope){this.pending.resolve();this.pending=null;}}
  async start(){this.generation++;this.active=true;await this.hooks.prepare?.(this);for(const b of this.bindings)await this.emit(b,'construction',{},graphContext(b.root,'construction'));await this.hooks.start?.(this);if(this.hooks.gameplay)this.hooks.gameplay.matchState='playing';for(const b of this.bindings){await this.emit(b,'beginPlay');for(const n of b.root.nodes.filter(n=>n.key==='timeline'&&n.timeline.autoplay))await this.execute(n,this.frame(b),'start');}return this;}
  async stop(reason='Stopped'){
    if(!this.active||this.stopping)return;this.paused=false;this.stepRemaining=null;this.generation++;this.pending?.resolve();this.pending=null;this.stopping=true;let firstError;await this.inputQueue;
    try{for(const b of this.bindings)try{await this.emit(b,'endPlay',{reason});}catch(error){firstError??=error;}}
    finally{if(this.hooks.gameplay)this.hooks.gameplay.matchState='ended';this.active=false;this.stopping=false;this.sceneRequest=null;this.jobs=[];this.timelines.clear();this.subscriptions.clear();this.scopes.clear();this.core.timers.clear();this.overlaps.clear();this.hits.clear();this.resetInput();}
    if(firstError)throw firstError;
  }
  async emit(b,key,args={},g=b.root,match=()=>true,outputPin='then',scope=''){if(!this.active||scope&&!this.scopes.has(scope))return;if(++this.depth>64){this.depth--;throw Error('이벤트 재귀 깊이 64 초과');}if(this.depth===1)this.steps=0;try{for(const n of g.nodes.filter(n=>n.key===key&&match(n))){const f=this.frame(b,g,args,scope);f.outputs.set(n.id,args);await this.follow(n,outputPin,f);}}finally{this.depth--;}}
  async custom(b,name,args={},scope=''){return this.emit(b,'customEvent',args,b.root,n=>(n.options?.eventName||n.title||'Custom Event')===name,'then',scope);}
  async nativeTimers(result,bindings=this.bindings){if(Array.isArray(result.timerCallbacks)){for(const callback of result.timerCallbacks)for(const b of bindings.filter(b=>!callback.owner||b.self===callback.owner))await this.custom(b,callback.event,{timer:callback.handle},callback.scope||'');}else for(const event of result.timerEvents||[])for(const b of bindings)await this.custom(b,event);}
  async actionEvents(b,frame=false){if(this.object(b.self)?.poolActive===false)return;for(const event of b.input.sample(frame,frame?this.core.delta:0))for(const n of b.root.nodes.filter(n=>n.key==='inputAction'&&n.options?.action===event.path)){const a=b.input.actions.get(event.path);if((n.valueType||'bool')!==a.valueType)throw Error('Input Action 출력 자료형 불일치: '+a.name);const f=this.frame(b),out={value:copy(event.value),elapsed:event.elapsed};f.outputs.set(n.id,out);this.values.set(n.id,out);await this.follow(n,event.event,f);}}
  pointer(sample,camera){if(this.active&&!this.paused&&!this.stopping){this.pointerCamera=camera;this.inputState.pointerSample(sample);}}
  inputSnapshot(){return {...this.inputState.snapshot(this.pointerCamera?.()||this.hooks.inputCamera?.(this)),actions:this.bindings.flatMap(b=>b.input.snapshot().map(s=>({owner:b.self,...s})))};}
  flushInput(){return this.inputQueue;}
  dispatchInput(packet,camera){if(!validInputPacket(packet))return Promise.reject(Error('입력 키·값·마우스 좌표를 확인하세요.'));const generation=this.generation,epoch=this.inputEpoch,sample=copy(packet);const job=this.inputQueue.then(async()=>{if(!this.active||this.paused||this.stopping||this.generation!==generation||this.inputEpoch!==epoch)return;if(sample.pointer)this.pointer(sample.pointer,camera);if(sample.key!==undefined)await this.applyInput(sample.key,sample.value??1,sample.source);});this.inputQueue=job.catch(()=>{});return job;}
  input(key,value=1){return this.dispatchInput({key,value});}
  async applyInput(key,value,source){key=inputKey(key);value=this.inputState.set(key,value,source);this.hooks.input?.(key,value);for(const b of this.bindings){if(this.object(b.self)?.poolActive===false)continue;const old=b.input.keys.get(key)||0;b.input.set(key,value);if(!old&&value||old&&!value)await this.emit(b,'input',{},b.root,n=>inputKey(n.options?.key||'E')===key,!value?'released':'then');await this.emit(b,'inputAxis',{value},b.root,n=>inputKey(n.options?.key||'A')===key);await this.actionEvents(b);}}
  resetInput(){this.inputEpoch++;this.pointerCamera=null;this.inputState.clear();this.hooks.releaseInput?.();for(const b of this.bindings){b.input.clear();b.input.previous.clear();}}
  releaseInput(){if(!this.active||this.paused||this.stopping){this.resetInput();return Promise.resolve();}this.inputEpoch++;const generation=this.generation;const job=this.inputQueue.then(async()=>{if(!this.active||this.paused||this.stopping||this.generation!==generation){this.resetInput();return;}const keys=[...this.inputState.keys.keys()];this.inputState.clear();this.hooks.releaseInput?.();for(const b of this.bindings){for(const key of keys){const old=b.input.keys.get(key);b.input.set(key,0);if(old)await this.emit(b,'input',{},b.root,n=>inputKey(n.options?.key||'E')===key,'released');}b.input.clear();await this.actionEvents(b);}this.pointerCamera=null;this.inputState.clearPointer();});this.inputQueue=job.catch(()=>{});return job;}
  async releaseSource(source){for(const key of [...(this.inputState.sources.get(source)?.keys()||[])])await this.dispatchInput({key,value:0,source});}
  async fixedTick(delta){if(!this.active||this.paused)return;for(const b of this.bindings)if(this.object(b.self)?.poolActive!==false&&b.root.settings?.tickEnabled!==false)await this.emit(b,'fixedTick',{delta});}
  async tick(delta){await this.flushInput();if(!this.active||this.paused)return;this.inputSnapshot();this.steps=0;this.core.object=id=>this.object(id);const before=new Map([...this.core.timers].map(([id,t])=>[id,{elapsed:t.elapsed,active:t.active}]));this.core.advance(delta);
    for(const [id,t] of this.core.timers){const prev=before.get(id);if(prev?.active&&!t.paused&&(t.loop?prev.elapsed+this.core.delta>=t.duration:!t.active))await t.callback?.();}this.core.events.length=0;
    const due=this.jobs.filter(j=>j.at<=this.core.time);this.jobs=this.jobs.filter(j=>j.at>this.core.time);for(const j of due)await j.run();
    for(const t of this.timelines.values())await this.advanceTimeline(t,delta);
    for(const b of this.bindings)await this.actionEvents(b,true);
    for(const b of this.bindings)if(this.object(b.self)?.poolActive!==false&&b.root.settings?.tickEnabled!==false)for(const n of b.root.nodes.filter(n=>n.key==='tick')){const elapsed=(b.ticks.get(n.id)||0)+this.core.delta,interval=n.options?.tickInterval??b.root.settings?.tickInterval??0;b.ticks.set(n.id,elapsed);if(elapsed+1e-9>=interval&&this.core.delta>0){b.ticks.set(n.id,0);const f=this.frame(b),output={delta:elapsed};f.outputs.set(n.id,output);this.values.set(n.id,output);await this.follow(n,'then',f);}}
    await this.hooks.physics?.(this.core.delta,this,delta);await this.collisions();this.inputState.endFrame();for(const b of this.bindings)b.input.endFrame();if(this.inputState.keys.get('mousewheelaxis'))await this.applyInput('MouseWheelAxis',0);
  }
  async collisions(){const contacts=this.hooks.contacts?.()||sceneContacts(this.objects),now=new Map(),hits=new Map();for(const b of this.bindings)for(const contact of contacts){if(contact.a!==b.self&&contact.b!==b.self)continue;const reversed=contact.b===b.self,other=reversed?contact.a:contact.b,component=reversed?contact.componentB:contact.componentA,definition=(reversed?contact.colliderB:contact.colliderA)?.component,id=JSON.stringify([this.bindings.indexOf(b),b.self,other,component,reversed?contact.componentA:contact.componentB]),state={b,other,component,type:definition?.type,sources:definition?.blueprintSources};if(contact.trigger){if(b.root.settings?.overlapEnabled===false)continue;now.set(id,state);if(!this.overlaps.has(id))await this.emit(b,'beginOverlap',{other},b.root,n=>this.componentEvent(n,state));}else{hits.set(id,state);if(!this.hits.has(id))await this.emit(b,'hitEvent',{other,hit:{hit:true,position:copy(contact.position),normal:contact.normal.map(v=>reversed?-v:v),actor:other}},b.root,n=>this.componentEvent(n,state));}}for(const [id,state] of this.overlaps)if(!now.has(id))await this.emit(state.b,'endOverlap',{other:state.other},state.b.root,n=>this.componentEvent(n,state));this.overlaps=now;this.hits=hits;}
  componentEvent(node,state){const id=node.options?.componentId;return !id||id==='actor'||(state.sources?.length?state.sources.some(source=>source.name===state.b.root.name&&source.id===id):id===state.component||state.b.root.components.find(c=>c.id===id)?.type===state.type);}
  continue(step=false){this.stepRemaining=step?1:null;this.paused=false;this.pending?.resolve();this.pending=null;}
  pause(){this.paused=true;this.resetInput();}
  async gate(n,f){if(!this.stopping&&(this.paused||this.stepRemaining===0||n.breakpoint)){this.paused=true;this.resetInput();await new Promise(resolve=>{this.pending={n,f,resolve};this.hooks.breakpoint?.(n,f);});}if(this.stepRemaining!==null)this.stepRemaining--;return this.frameActive(f);}
  async follow(n,pin,f){if(!this.frameActive(f)||f.returned)return;for(const edge of f.g.edges.filter(e=>e.from.node===n.id&&e.from.pin===pin)){const next=f.g.nodes.find(n=>n.id===edge.to.node);if(next)await this.execute(next,f,edge.to.pin);}}
  timelineOutput(t){const output={direction:t.direction>0?'Forward':'Backward',...Object.fromEntries(t.n.timeline.tracks.filter(track=>track.type!=='event').map(track=>[track.id,copy(sampleTimeline(track,t.time))]))};t.f.outputs.set(t.n.id,output);this.values.set(t.n.id,output);}
  async advanceTimeline(t,delta){if(!t.playing)return;const data=t.n.timeline,length=timelineLength(data);let remaining=(data.ignoreTimeDilation?delta:this.core.delta)*(data.playRate??1),turns=0;if(remaining<=0)return;
    while(remaining>1e-9&&t.playing&&this.active){if(++turns>10000)throw Error('타임라인 반복 제한 초과');const previous=t.time,travel=Math.min(remaining,t.direction>0?length-t.time:t.time);t.time+=travel*t.direction;remaining-=travel;this.timelineOutput(t);
      for(const track of data.tracks.filter(track=>track.type==='event'))for(const key of [...track.keys].sort((a,b)=>(a.time-b.time)*t.direction))if(t.direction>0?(key.time>previous||t.initial&&key.time===previous)&&key.time<=t.time:(key.time<previous||t.initial&&key.time===previous)&&key.time>=t.time)await this.follow(t.n,track.id,t.f);
      t.initial=false;await this.follow(t.n,'update',t.f);if(t.time<=0||t.time>=length){if(data.loop){t.time=t.direction>0?0:length;t.initial=true;}else{t.playing=false;await this.follow(t.n,'finished',t.f);}}else break;
    }
  }
  async read(n,p,f){const edge=f.g.edges.find(e=>e.to.node===n.id&&e.to.pin===p.id);if(edge){const source=f.g.nodes.find(n=>n.id===edge.from.node),[id,...path]=edge.from.pin.split('.');let output=f.outputs.get(source.id);const spec=catalog.find(s=>s.key===source.key),dataOnly=!basePins(source,'in',f.g).some(p=>p.type==='exec');if(dataOnly&&!events.has(source.key)&&!['functionInput','macroInput','nativeEvent','dispatcherEvent','timeline'].includes(source.key)){if(f.evaluating.has(source.id))throw Error('데이터 연결 순환: '+source.id);if(++this.steps>10000)throw Error('데이터 계산량 제한 초과');f.evaluating.add(source.id);try{output=await this.evaluate(source,f);}finally{f.evaluating.delete(source.id);}}if(!output)throw Error('먼저 실행해야 하는 출력: '+source.key);let value=output[id],type=basePins(source,'out',f.g).find(p=>p.id===id)?.type;for(const field of path){const fields=fieldsFor(type),i=fields.findIndex(p=>p.id===field);value=Array.isArray(value)?value[i]:value?.[field];type=fields[i]?.type;}if(value===undefined)throw Error('출력 값이 없어요: '+edge.from.pin);return value;}
    if(n.splitPins?.includes('in:'+p.id)){const fields=fieldsFor(p.type),values=[];for(const field of fields)values.push(await this.read(n,{...field,id:p.id+'.'+field.id},f));return ['vec2','vec3','color'].includes(p.type)?values:Object.fromEntries(fields.map((p,i)=>[p.id,values[i]]));}return copy(defaultInputValue(n,p));}
  async args(n,f){const result={};for(const p of basePins(n,'in',f.g).filter(p=>p.type!=='exec'))result[p.id]=await this.read(n,p,f);return result;}
  async callDefinition(n,f,a,arrival){const d=[...f.b.root.functions,...f.b.root.macros].find(d=>d.id===n.definitionId);if(!d)throw Error('함수 정의가 없어요.');if(f.stack.length>=64)throw Error('호출 깊이 64 초과');const g=graphContext(f.b.root,d.id),sub=this.frame(f.b,g,a,f.scope);sub.stack=[...f.stack,d.name];const entry=g.nodes.find(n=>n.key.endsWith('Input')),exit=g.nodes.find(n=>n.key.endsWith('Output'));if(d.pure){sub.result=await this.args(exit,sub);}else{if(!entry)throw Error('Entry가 없어요.');sub.outputs.set(entry.id,a);await this.follow(entry,arrival||'exec',sub);}if(n.key==='callMacro'&&!sub.returned){sub.onReturn=async()=>{f.outputs.set(n.id,sub.result);this.values.set(n.id,copy(sub.result));await this.follow(n,sub.exit,f);};return {__deferred:true};}f.exit=sub.exit;return sub.result;}
  async evaluate(n,f,a){a??=await this.args(n,f);let output={};const b=f.b,k=n.key;
    if(k==='getVariable')output={value:b.variables.get(n.variableId)};
    else if(k==='callFunction'||k==='callMacro')output=await this.callDefinition(n,f,a);
    else if(k.startsWith('native')){if(!this.hooks.native)throw Error('C++을 먼저 빌드하세요.');const {c,f:fn,p}=nativeMember(b.root,n);if(!c)throw Error('C++ 클래스가 없어요.');const override=b.root.nodes.find(x=>x.key==='nativeEvent'&&x.nativeId===n.nativeId);if(fn&&fn.event!=='none'&&override){const eventFrame=this.frame(b,b.root,a,f.scope);eventFrame.outputs.set(override.id,a);await this.follow(override,'then',eventFrame);}else if(k==='nativeMembers'){for(const property of c.properties){const result=await this.hooks.native({key:'nativeGet',nativeId:c.name+'.'+property.name,args:{target:a.target==='self'||a.target===null?b.self:a.target},self:b.self,overrides:[]});output[property.name]=result.outputs.value;}}else{const args={...a},receiver=k==='nativeCall'?nativeTargetPin(fn):'target';if(!fn?.static)args[receiver]=args[receiver]==='self'||args[receiver]===null?b.self:args[receiver];const result=await this.hooks.native({key:k,nativeId:n.nativeId,args,self:b.self,scope:f.scope,overrides:b.root.nodes.filter(n=>n.key==='nativeEvent').map(n=>n.nativeId)});output=result.outputs||{};for(const event of result.events||[]){const owner=this.bindings.find(b=>b.self===event.target)||b;await this.emit(owner,'nativeEvent',event.args,owner.root,n=>n.nativeId===event.nativeId,'then',f.scope);}}}
    else if(catalog.find(s=>s.key===k)?.cppName&&!catalog.find(s=>s.key===k)?.service){this.core.object=id=>this.object(id===null?b.self:id,b);output=evaluateCore(k,a,this.core);if(k==='timer'){const timer=this.core.timers.get(output.handle);timer.owner=b.self;timer.scope=f.scope;timer.callback=()=>this.custom(b,a.event,{},f.scope);}}
    else if(pure[k])output=pure[k](a);
    else if(k==='arrayGet'){if(a.index<0||a.index>=a.array.length)throw Error('배열 인덱스 범위 초과');output={return:a.array[a.index]};}
    else if(k==='self')output={return:b.self};else if(k==='isValid')output={return:!!this.object(a.target,b)};
    else if(k==='members'){const o=this.object(a.target,b);if(!o)throw Error('오브젝트가 없어요.');output={position:o.position,rotation:o.rotation,scale:o.scale,name:o.name,visible:o.visible};}
    else if(adapters.has(k)||catalog.find(s=>s.key===k)?.service){if(!this.hooks.operation)throw Error('엔진 서비스가 없어요: '+k);output=await this.hooks.operation(k,a,b,this)||{};}
    else throw Error('실행 구현이 없는 노드: '+k);
    f.outputs.set(n.id,output);this.values.set(n.id,copy(output));return output;
  }
  async execute(n,f,arrival='exec'){if(!this.frameActive(f)||f.returned||n.enabled===false)return;if(++this.steps>10000)throw Error('한 이벤트 실행량 10000 초과');if(!await this.gate(n,f))return;this.hooks.trace?.(n,f);const a=await this.args(n,f),b=f.b,k=n.key;let output={},next='then';
    if(k==='branch')return this.follow(n,a.condition?'true':'false',f);
    if(k==='switchInt'||k==='switchString'){const i=[a.case0,a.case1,a.case2].findIndex(v=>v===a.selection);return this.follow(n,i<0?'default':'out'+i,f);}
    if(k==='whileLoop'){let iterations=0;while((await this.args(n,f)).condition&&this.active&&!f.returned){if(++iterations>10000)throw Error('While Loop 반복 제한 초과');await this.follow(n,'body',f);}return this.follow(n,'completed',f);}
    if(k==='forLoopBreak'||k==='forEachBreak'){if(arrival==='break'){b.states.set(n.id,true);return;}b.states.delete(n.id);const first=k==='forLoopBreak'?a.first:0,last=k==='forLoopBreak'?a.last:a.array.length-1;if(last-first>10000)throw Error('반복 횟수 제한 초과');for(let i=first;i<=last&&this.active&&!f.returned&&!b.states.get(n.id);i++){output={index:i,...(k==='forEachBreak'?{item:a.array[i]}:{})};f.outputs.set(n.id,output);this.values.set(n.id,copy(output));await this.follow(n,'body',f);}b.states.delete(n.id);return this.follow(n,'completed',f);}
    if(k==='sequence'){await this.follow(n,'first',f);return this.follow(n,'second',f);}
    if(k==='forLoop'||k==='forEach'){const first=k==='forLoop'?a.first:0,last=k==='forLoop'?a.last:a.array.length-1;if(last-first>10000)throw Error('반복 횟수 제한 초과');for(let i=first;i<=last&&this.active&&!f.returned;i++){output={index:i,...(k==='forEach'?{item:a.array[i]}:{})};f.outputs.set(n.id,output);this.values.set(n.id,copy(output));await this.follow(n,'body',f);}return this.follow(n,'completed',f);}
    if(k==='delay'||k==='retriggerDelay'){if(a.duration<0)throw Error('지연은 0초 이상이에요.');const pending=j=>j.node===n.id&&j.owner===b.self&&j.scope===f.scope;if(k==='delay'&&this.jobs.some(pending))return;if(k==='retriggerDelay')this.jobs=this.jobs.filter(j=>!pending(j));this.jobs.push({node:n.id,owner:b.self,scope:f.scope,at:this.core.time+a.duration,run:()=>this.follow(n,'then',f)});return;}
    if(k==='timeline'){const id=b.self+':'+n.id+(f.scope?':'+f.scope:''),t=this.timelines.get(id)||{n,f,time:0,direction:1,playing:false};t.f=f;if(arrival==='stop')t.playing=false;else if(arrival==='setTime'){t.time=Math.max(0,Math.min(timelineLength(n.timeline),a.time));this.timelineOutput(t);await this.follow(n,'update',f);}else{t.direction=['reverse','reverseEnd'].includes(arrival)?-1:1;if(arrival==='start')t.time=0;if(arrival==='reverseEnd')t.time=timelineLength(n.timeline);t.initial=['start','reverseEnd'].includes(arrival);t.playing=true;}this.timelines.set(id,t);return;}
    if(k==='setVariable')b.variables.set(n.variableId,copy(a.value));
    else if(k==='doN'){if(arrival==='reset'){b.states.delete(n.id);return;}const counter=b.states.get(n.id)||0;if(counter>=Math.max(0,a.count))return;b.states.set(n.id,counter+1);output={counter:counter+1};}
    else if(k==='multiGate'){if(arrival==='reset'){b.states.delete(n.id);return;}let used=b.states.get(n.id)||[];if(used.length===3){if(!a.loop)return;used=[];}const available=[0,1,2].filter(i=>!used.includes(i));const index=a.random?available[Math.floor(Math.random()*available.length)]:available.find(i=>i>=Math.max(0,Math.min(2,a.startIndex)))??available[0];used.push(index);b.states.set(n.id,used);output={index};next='out'+index;}
    else if(k==='doOnce'){if(arrival==='reset'){b.states.delete(n.id);return;}if(b.states.get(n.id))return;b.states.set(n.id,true);}
    else if(k==='flipFlop'){const isA=!b.states.get(n.id);b.states.set(n.id,isA);output={isA};next=isA?'a':'b';}
    else if(k==='gate'){let open=b.states.get(n.id)??true;if(arrival!=='exec'){open=arrival==='open'?true:arrival==='close'?false:!open;b.states.set(n.id,open);return;}if(!open)return;}
    else if(k==='print')this.hooks.log?.(a.message);
    else if(k==='cast'){const o=this.object(a.target,b);output={object:o&&(o.nativeClass===a.class||derivesFrom(o.nativeClass,a.class))?o?.id:null};if(!output.object)next='failed';}
    else if(k==='arraySet'||k==='arrayAdd'||k==='arrayRemove'){if(k!=='arrayAdd'&&(a.index<0||a.index>=a.array.length))throw Error('배열 인덱스 범위 초과');if(k==='arraySet')a.array[a.index]=copy(a.item);else if(k==='arrayAdd'){if(a.array.length>=100000)throw Error('배열 크기 제한 초과');output={index:a.array.push(copy(a.item))-1};}else a.array.splice(a.index,1);const edge=f.g.edges.find(e=>e.to.node===n.id&&e.to.pin==='array');if(!edge){n.inputValues??={};n.inputValues.array=a.array;}}
    else if(k==='functionOutput'||k==='macroOutput'){f.result=a;f.returned=true;f.exit=arrival;await f.onReturn?.();return;}
    else if(k==='callFunction'||k==='callMacro'){output=await this.callDefinition(n,f,a,arrival);if(output.__deferred)return;next=f.exit||'then';}
    else if(k.startsWith('dispatcher')){const signal=(b.root.dispatchers||[]).find(s=>s.id===n.symbolId),target=a.target==='self'||a.target===null?b.self:a.target,id=target+':'+signal?.name,list=this.subscriptions.get(id)||[];if(k==='dispatcherBind'){if(!list.some(s=>s.b===b&&s.event===a.event&&s.scope===f.scope))list.push({b,event:a.event,scope:f.scope});this.subscriptions.set(id,list);}else if(k==='dispatcherUnbind')this.subscriptions.set(id,list.filter(s=>!(s.b===b&&s.event===a.event)));else for(const s of list)await this.custom(s.b,s.event,a,s.scope);if(k==='dispatcherCall')for(const owner of this.bindings.filter(o=>o.self===target))await this.emit(owner,'dispatcherEvent',a,owner.root,x=>x.symbolId===n.symbolId);}
    else if(k==='interfaceCall'){const symbol=b.root.interfaces.find(s=>s.id===n.symbolId),target=a.target==='self'||a.target===null?b.self:a.target,owner=this.bindings.find(o=>o.self===target),d=owner?.root.functions.find(d=>d.name===symbol.name);if(!d)throw Error('인터페이스 구현이 없어요: '+symbol.name);output=await this.callDefinition({definitionId:d.id},this.frame(owner,owner.root,{},f.scope),a);}
    else if(!events.has(k)&&!['customFunction','functionInput','macroInput'].includes(k))output=await this.evaluate(n,f,a);
    f.outputs.set(n.id,output);this.values.set(n.id,copy(output));await this.follow(n,next,f);
  }
}
