import {catalog,variableTypes,typeColors,defaultsFor,defaultInputValue,effectivePins,nodeTitle,componentDefaults,sampleTimeline} from './blueprint-model.js';
import {nativeMember} from './native-model.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(label,control)=>`<div class="bp-detail-row" data-property-search="${esc(label.toLowerCase())}"><label>${esc(label)}</label>${control.includes('aria-label')?control:control.replace(/<(input|select|textarea)/,'<$1 aria-label="'+esc(label)+'"')}</div>`;
const group=(name,content)=>`<details class="bp-detail-group" open><summary>${esc(name)}</summary>${content}</details>`;
const input=(key,value,type='text',extra='')=>`<input data-detail-field="${key}" type="${type}" ${type==='checkbox'?(value?'checked':''):`value="${esc(value)}"`} ${extra}>`;
const select=(key,value,choices)=>`<select data-detail-field="${key}">${choices.map(([k,v])=>`<option value="${esc(k)}" ${k===value?'selected':''}>${esc(v)}</option>`).join('')}</select>`;
const types=Object.entries(variableTypes);
export function valueControl(type,value,attrs,label,array=false,objects=[]){
  if(array||['transform','hit'].includes(type))return `<textarea ${attrs} data-value-type="${type}" data-value-array="${array}" aria-label="${esc(label)}" spellcheck="false">${esc(JSON.stringify(value))}</textarea>`;
  if(['vec2','vec3','color'].includes(type))return `<div class="bp-value-vector">${value.map((v,i)=>`<label><span>${(type==='color'?['R','G','B','A']:['X','Y','Z'])[i]}</span><input type="number" step="0.1" value="${v}" ${attrs} data-value-axis="${i}" data-value-type="${type}" aria-label="${esc(label)} ${(type==='color'?['R','G','B','A']:['X','Y','Z'])[i]}"></label>`).join('')}</div>`;
  if(type==='object')return `<select ${attrs} data-value-type="object" aria-label="${esc(label)}">${[['null','None'],['self','Self'],...objects.map(o=>[o.id,o.name])].map(([id,name])=>`<option value="${esc(id)}" ${(value??'null')===id?'selected':''}>${esc(name)}</option>`).join('')}</select>`;
  return `<input ${attrs} data-value-type="${type}" type="${type==='bool'?'checkbox':['int','float'].includes(type)?'number':'text'}" ${type==='bool'?(value?'checked':''):`value="${esc(value)}"`} ${type==='float'?'step="0.1"':''} aria-label="${esc(label)}">`;
}
export {componentDefaults};
export function detailsMarkup(root,graph,selection,objects,assets){
  let title=root.name,content='';
  const row=(label,key,value,type='text',extra='')=>field(label,input(key,value,type,extra));
  if(selection.kind==='comment'){
    const c=(graph.comments||[]).find(c=>c.id===selection.id);if(!c)return detailsMarkup(root,graph,{kind:'blueprint'},objects,assets);title='주석';
    content=group('주석',field('내용',`<textarea data-detail-field="text" maxlength="2000" aria-label="주석 내용">${esc(c.text)}</textarea>`)+row('색상','color',c.color,'color')+row('글자 크기','fontSize',c.fontSize,'number','min="10" max="32"')+row('포함 노드 함께 이동','moveNodes',c.moveNodes,'checkbox'))+group('크기',row('너비','size.width',c.size.width,'number','min="120" max="10000"')+row('높이','size.height',c.size.height,'number','min="80" max="10000"'));
  }else if(selection.kind==='variable'){
    const v=root.variables.find(v=>v.id===selection.id);if(!v)return '';title=v.name;
    content=group('변수',row('이름','name',v.name,'text','maxlength="80" aria-label="변수 이름"')+field('자료형',select('type',v.type,types))+field('컨테이너',select('container',v.container,[['single','단일 값'],['array','배열']]))+row('카테고리','category',v.category||'Default')+row('인스턴스에서 편집','instanceEditable',v.instanceEditable??true,'checkbox')+row('외부 생성에 노출','exposeOnSpawn',v.exposeOnSpawn??false,'checkbox')+row('비공개','private',v.private??false,'checkbox'))+group('기본값',field(v.name,valueControl(v.type,v.value,'data-variable-default="'+v.id+'"',v.name,v.container==='array',objects)))+group('노드',`<div class="bp-detail-buttons"><button data-variable-node="getVariable" data-variable-id="${v.id}">Get · 읽기</button><button data-variable-node="setVariable" data-variable-id="${v.id}">Set · 쓰기</button></div>`);
  }else if(selection.kind==='component'){
    const c=root.components.find(c=>c.id===selection.id);if(!c)return '';title=c.name;const values=Object.fromEntries(Object.entries(componentDefaults(c.type)).map(([key,value])=>[key,c.properties?.[key]??value]));
    content=group('컴포넌트',row('이름','name',c.name,'text','maxlength="80"')+field('클래스',`<span class="bp-readonly">${esc(c.type)}</span>`));
    const labels={position:'위치',rotation:'회전',scale:'크기',center:'중심',extent:'박스 범위',trigger:'겹침 이벤트',enabled:'활성화',mesh:'메시',material:'머테리얼',visible:'표시',castShadow:'그림자',color:'색상',intensity:'밝기',radius:'반경',className:'C++ 클래스'};
    content+=group('속성',Object.entries(values).map(([key,value])=>field(labels[key]||key,['mesh','material'].includes(key)?`<select data-component-property="${key}" data-value-type="string">${assets.filter(a=>a.kind===(key==='mesh'?'model':'material')).map(a=>`<option ${a.name===value?'selected':''}>${esc(a.name)}</option>`).join('')}</select>`:valueControl(Array.isArray(value)?key==='color'?'color':'vec3':typeof value==='boolean'?'bool':typeof value==='number'?'float':'string',value,`data-component-property="${key}"`,labels[key]||key,false,objects))).join(''));
    if(c.type.includes('Collider'))content+=group('이벤트',`<div class="bp-detail-buttons"><button data-component-event="beginOverlap" data-component-id="${c.id}">Begin Overlap</button><button data-component-event="endOverlap" data-component-id="${c.id}">End Overlap</button></div>`);
  }else if(selection.kind==='definition'||selection.kind==='symbol'){
    const d=[...(root.functions||[]),...(root.macros||[]),...(root.dispatchers||[]),...(root.interfaces||[])].find(d=>d.id===selection.id);if(!d)return '';title=d.name;
    content=group(selection.kind==='symbol'?root.dispatchers?.some(s=>s.id===d.id)?'이벤트 디스패처':'인터페이스 함수':'함수 / 매크로',row('이름','name',d.name,'text','maxlength="80"')+row('카테고리','category',d.category||'사용자 정의')+field('접근',select('access',d.access||'public',[['public','Public'],['protected','Protected'],['private','Private']])));
    if(root.functions.some(f=>f.id===d.id))content+=group('호출',row('순수 함수','pure',d.pure??false,'checkbox'));
    for(const direction of ['inputs','outputs'].filter(k=>k==='inputs'||!root.dispatchers?.some(s=>s.id===d.id)))content+=group(direction==='inputs'?'입력':'출력',d[direction].map(p=>`<div class="bp-signature-pin"><input value="${esc(p.label)}" data-interface-pin="${p.id}" data-interface-direction="${direction}" aria-label="${esc(p.label)} 핀 이름">${p.type==='exec'?'<span>exec</span>':`<select data-interface-type="${p.id}" data-interface-direction="${direction}" aria-label="${esc(p.label)} 자료형">${types.map(([key,label])=>`<option value="${key}" ${key===p.type?'selected':''}>${label}</option>`).join('')}</select><input type="checkbox" data-interface-array="${p.id}" data-interface-direction="${direction}" ${p.array?'checked':''} aria-label="${esc(p.label)} 배열"><button data-interface-remove="${p.id}" data-interface-direction="${direction}" aria-label="${esc(p.label)} 핀 삭제">×</button>`}</div>`).join('')+`<button class="bp-add-pin" data-action="new-custom-pin" data-pin-direction="${direction==='inputs'?'in':'out'}">+ 핀 추가</button>`);
  }else if(selection.kind==='node'){
    const n=graph.nodes.find(n=>n.id===selection.id);if(!n)return detailsMarkup(root,graph,{kind:'blueprint'},objects,assets);title=nodeTitle(n,graph);const s=catalog.find(s=>s.key===n.key);
    content=group('노드',row('이름','title',title,'text','maxlength="80" aria-label="노드 표시 이름"')+row('활성화','enabled',n.enabled??true,'checkbox')+row('중단점','breakpoint',n.breakpoint??false,'checkbox')+(s?.arrayType?field('배열 원소 자료형',select('valueType',n.valueType||'float',types)):'')+field('주석',`<textarea data-detail-field="comment" maxlength="2000" aria-label="노드 주석">${esc(n.comment||'')}</textarea>`));
    if(n.nativeId){const {c,f,p}=nativeMember(root,n);content+=group('C++',field('클래스',`<span class="bp-readonly">${esc(c.name)}</span>`)+field('멤버',`<span class="bp-readonly">${esc(f?.name||p?.name)}</span>`)+field('노출',`<span class="bp-readonly">${esc(f?(f.event!=='none'?f.event==='native'?'Native Event':'Implementable Event':f.pure?'Pure':'Callable'):p.readOnly?'Read Only':'Read / Write')}</span>`));}
    if(s?.cppName)content+=group('공통 C++ API',`<code class="bp-api-name">${esc(s.cppName)}</code><button class="bp-add-pin" data-action="preview-api">${s.pure?'값 계산':'미리보기 호출'}</button><output id="node-api-result" aria-live="polite"></output>`);
    if(n.symbolId)content+=`<button class="bp-add-pin" data-inspect-symbol="${n.symbolId}">시그니처 편집</button>`;
    if(n.key==='reroute')content+=group('핀',field('자료형',select('valueType',n.valueType||'float',types))+row('배열','array',n.array??false,'checkbox'));
    if(n.key==='timeline'){const t=n.timeline;content+=group('타임라인',row('길이','timeline.length',t.length,'number','min="0.01" step="0.1"')+row('반복','timeline.loop',t.loop,'checkbox')+row('자동 재생','timeline.autoplay',t.autoplay,'checkbox')+`<button class="bp-add-pin" data-action="edit-timeline">타임라인 편집</button>`);}
    if(s?.kind==='event')content+=group('이벤트',n.key==='tick'?row('Tick 간격','options.tickInterval',n.options?.tickInterval||0,'number','min="0" step="0.01"'):['beginOverlap','endOverlap'].includes(n.key)?field('컴포넌트',select('options.componentId',n.options?.componentId||'actor',[['actor','Actor'],...root.components.map(c=>[c.id,c.name])])):n.key==='input'?row('입력 키','options.key',n.options?.key||'E'):row('이벤트 이름','options.eventName',n.options?.eventName||s.title));
    const inputs=effectivePins(n,'in',graph).filter(p=>p.type!=='exec');
    if(inputs.length)content+=group('입력값',inputs.map(p=>{const wire=graph.edges.find(e=>e.to.node===n.id&&e.to.pin===p.id),value=defaultInputValue(n,p);return field(p.label,wire?`<span class="bp-connected-value">← ${esc(nodeTitle(graph.nodes.find(n=>n.id===wire.from.node),graph))}</span>`:valueControl(p.type,value,`data-node-input="${p.id}"`,p.label,p.array,objects));}).join(''));
    const outputs=effectivePins(n,'out',graph);if(outputs.length)content+=group('출력',outputs.map(p=>field(p.label,`<span class="bp-type-value" style="color:${typeColors[p.type]||typeColors.any}">${esc(p.className||p.type)}${p.array?'[]':''}</span>`)).join(''));
    if(n.definitionId)content+=`<button class="bp-add-pin" data-inspect-definition="${n.definitionId}">함수 / 매크로 속성</button>`;
    if(['customEvent','customFunction'].includes(n.key))content+='<button class="bp-add-pin" data-action="new-custom-pin">+ 입력 / 반환 핀</button>';
  }else{
    const settings={parentClass:'Actor',tickEnabled:true,tickInterval:0,overlapEnabled:true,...root.settings};
    content=group('블루프린트',row('이름','name',root.name,'text','maxlength="80" aria-label="블루프린트 이름"')+field('부모 클래스',select('settings.parentClass',settings.parentClass,[['Actor','Actor'],['Component','Component'],['SceneComponent','SceneComponent'],...(root.native?.classes.filter(c=>c.blueprintable).map(c=>[c.name,c.name+' · C++'])||[])])) )+group('기본 이벤트',row('Tick 활성화','settings.tickEnabled',settings.tickEnabled,'checkbox')+row('Tick 간격','settings.tickInterval',settings.tickInterval,'number','min="0" step="0.01"')+row('Overlap 이벤트','settings.overlapEnabled',settings.overlapEnabled,'checkbox'));
    const parent=root.native?.classes.find(c=>c.name===settings.parentClass);if(parent?.properties.length)content+=group('상속 속성',parent.properties.map(p=>field(p.name,valueControl(p.type,settings.nativeDefaults?.[parent.name+'.'+p.name]??p.value??(p.array?[]:defaultsFor(p.type)),`data-native-default="${parent.name+'.'+p.name}"`,p.name,p.array,objects))).join(''));
  }
  return `<div class="bp-detail-title"><h3>${esc(title)}</h3><button data-action="blueprint-defaults">클래스 기본값</button></div><input class="bp-property-search" aria-label="속성 검색" placeholder="속성 검색">${content}`;
}
