export const buildTargets={'windows-x64':{label:'Windows x64',renderer:'WebView2/WebGL2'},android:{label:'Android',renderer:'WebView/WebGL2'},ios:{label:'iOS',renderer:'WKWebView/WebGL2'}};
export const buildContract={target:'windows-x64',targets:buildTargets,renderer:'WebView2/WebGL2',configurations:['development','release'],content:'All Assets except disabled scenes, plus referenced project files; C++ compiled ahead of time',output:'Builds/<profile id>/<unique build id>',maxProfiles:32,maxScenes:256};
export const profileTarget=p=>p.target||'windows-x64';
export const mobileDefaults={applicationId:'com.hbengine.game',versionCode:1,versionName:'1.0',orientation:'landscape',minSdk:26,abis:['arm64-v8a'],format:'apk'};
export function mobileSettings(p){return {...mobileDefaults,...p.mobile};}
export function validMobileSettings(p){if(p.mobile!==undefined&&(!p.mobile||typeof p.mobile!=='object'||Array.isArray(p.mobile)||Object.keys(p.mobile).some(k=>!Object.hasOwn(mobileDefaults,k)&&k!=='signingRef')))return false;const m=mobileSettings(p);return m&&typeof m.applicationId==='string'&&m.applicationId.length<=200&&/^[a-zA-Z][a-zA-Z0-9_]*(?:\.[a-zA-Z][a-zA-Z0-9_]*)+$/.test(m.applicationId)&&(profileTarget(p)!=='ios'||/^[a-zA-Z][a-zA-Z0-9-]*(?:\.[a-zA-Z][a-zA-Z0-9-]*)+$/.test(m.applicationId)&&/^\d+(?:\.\d+){0,2}$/.test(m.versionName))&&Number.isInteger(m.versionCode)&&m.versionCode>=1&&m.versionCode<=2100000000&&typeof m.versionName==='string'&&m.versionName.length>0&&m.versionName.length<=80&&!/[\x00-\x1f]/.test(m.versionName)&&['landscape','portrait','auto'].includes(m.orientation)&&Number.isInteger(m.minSdk)&&m.minSdk>=26&&m.minSdk<=36&&Array.isArray(m.abis)&&m.abis.length>=1&&m.abis.length<=2&&new Set(m.abis).size===m.abis.length&&m.abis.every(abi=>['arm64-v8a','x86_64'].includes(abi))&&['apk','aab'].includes(m.format)&&(m.signingRef===undefined||typeof m.signingRef==='string'&&/^[a-z][a-z0-9_-]{0,39}$/.test(m.signingRef));}
export function resolveBuildPath(name,redirects={}){const seen=new Set();for(let i=0;i<33;i++){if(typeof name!=='string'||/[\\:\x00-\x1f]/.test(name)||name.startsWith('/')||name.split('/').some(s=>!s||s==='.'||s==='..'))throw Error('패키지 참조 경로 오류');const from=Object.keys(redirects).sort((a,b)=>b.length-a.length).find(p=>name===p||name.startsWith(p+'/'));if(!from)return name;if(seen.has(from))throw Error('패키지 참조 순환');seen.add(from);name=redirects[from]+name.slice(from.length);}throw Error('패키지 참조 깊이 초과');}
export function defaultBuildProfile(session){return {id:'windows',name:'Windows',configuration:'development',productName:session.name,width:1280,height:720,scenes:[{path:session.startupScene,enabled:true}]};}
export const kioskDefaults={enabled:false,fullscreen:true,hideCursor:false,preventMinimize:true,idleResetSeconds:60};
export const kioskSettings=p=>({...kioskDefaults,...p.kiosk});
export function validKioskSettings(p){const k=kioskSettings(p);return (p.kiosk===undefined||p.kiosk&&typeof p.kiosk==='object'&&!Array.isArray(p.kiosk)&&Object.keys(p.kiosk).every(key=>Object.hasOwn(kioskDefaults,key)))&&['enabled','fullscreen','hideCursor','preventMinimize'].every(key=>typeof k[key]==='boolean')&&Number.isInteger(k.idleResetSeconds)&&k.idleResetSeconds>=0&&k.idleResetSeconds<=86400;}
export function validBuildProfile(p){return p&&validKioskSettings(p)&&Object.hasOwn(buildTargets,profileTarget(p))&&(profileTarget(p)==='windows-x64'||validMobileSettings(p))&&/^[a-z][a-z0-9_-]{0,39}$/.test(p.id)&&typeof p.name==='string'&&p.name.trim().length>0&&p.name.length<=80&&typeof p.productName==='string'&&p.productName.trim().length>0&&p.productName.length<=80&&!/[\x00-\x1f]/.test(p.productName)&&buildContract.configurations.includes(p.configuration)&&Number.isInteger(p.width)&&p.width>=320&&p.width<=7680&&Number.isInteger(p.height)&&p.height>=240&&p.height<=4320&&Array.isArray(p.scenes)&&p.scenes.length>0&&p.scenes.length<=256&&p.scenes.some(s=>s.enabled)&&new Set(p.scenes.map(s=>s.path)).size===p.scenes.length&&p.scenes.every(s=>s&&typeof s.path==='string'&&s.path.startsWith('Assets/')&&s.path.endsWith('.hbscene.json')&&!/[\\:\x00-\x1f]/.test(s.path)&&!s.path.split('/').some(v=>!v||v==='.'||v==='..')&&typeof s.enabled==='boolean');}
