import {validGameplayAsset,validBoardValue,boardTypes,gameplayValidationError} from './gameplay-assets.js';
import {AnimationNotifyTrack,deliverAnimationNotify} from './animation-notify-runtime.js';
import {animationSyncLimits} from './animation-sync.js';
import {enabledComponent} from './scene-components.js';
import {sceneWorldPosition,setSceneWorldPosition} from './scene-runtime.js';
const copy=v=>structuredClone(v);
export function testCondition(c,value){switch(c.operator){case 'equal':return JSON.stringify(value)===JSON.stringify(c.value);case 'notEqual':return JSON.stringify(value)!==JSON.stringify(c.value);case 'greater':return value>c.value;case 'less':return value<c.value;case 'greaterEqual':return value>=c.value;case 'lessEqual':return value<=c.value;case 'set':return value!==null&&value!==undefined&&value!==false&&value!=='';case 'notSet':return value===null||value===undefined||value===false||value==='';default:return false;}}
export class Blackboard {
  constructor(keys=[]){this.types=new Map();this.values=new Map();for(const key of keys){if(this.types.has(key.name)&&this.types.get(key.name)!==key.type)throw Error('블랙보드 키 자료형 충돌: '+key.name);this.types.set(key.name,key.type);this.values.set(key.name,copy(key.value));}this.revision=0;}
  set(key,value){if(!this.types.has(key)||!validBoardValue(this.types.get(key),value))throw Error('블랙보드 키나 값의 자료형 오류: '+key);if(JSON.stringify(this.values.get(key))===JSON.stringify(value))return;this.values.set(key,copy(value));this.revision++;}
  get(key){if(!this.types.has(key))throw Error('블랙보드 키가 없어요: '+key);return copy(this.values.get(key));}
  clear(key){this.set(key,boardTypes[this.types.get(key)]);}
  snapshot(){return Object.fromEntries(this.values);}
}
export async function loadBehaviorProgram(name,hooks){
  const cache=new Map(),boards=new Map(),keys=new Map();let expanded=0;
  const read=async(name,kind)=>{const path=await hooks.asset(name,kind);if(!path)throw Error('에셋이 없어요: '+name);const data=await hooks.readAsset(path);if(!validGameplayAsset(kind,data))throw Error(kind+' 에셋 검증 실패: '+path);return {path,data:copy(data)};};
  const visit=async(name,stack=[])=>{const path=await hooks.asset(name,'behaviortree');if(!path)throw Error('하위 행동트리 에셋이 없어요: '+name);if(stack.includes(path)||stack.length>=32)throw Error('하위 행동트리 순환·깊이 제한: '+[...stack,path].join(' → '));if(cache.has(path)){expanded+=cache.get(path).size;if(expanded>4096)throw Error('하위 행동트리 확장 노드 제한');return cache.get(path);}
    const loaded=await read(path,'behaviortree'),program={...loaded,subtrees:new Map(),size:loaded.data.nodes.length};expanded+=program.size;if(expanded>4096)throw Error('하위 행동트리 확장 노드 제한');
    if(program.data.blackboard){let board=boards.get(program.data.blackboard);if(!board){board=(await read(program.data.blackboard,'blackboard')).data;boards.set(program.data.blackboard,board);}for(const key of board.keys){if(keys.has(key.name)&&keys.get(key.name).type!==key.type)throw Error('하위 행동트리 블랙보드 자료형 충돌: '+key.name);if(!keys.has(key.name))keys.set(key.name,key);if(keys.size>128)throw Error('공유 블랙보드 키는 128개까지예요.');}}
    for(const node of program.data.nodes.filter(n=>n.type==='subtree')){const child=await visit(node.properties.asset,[...stack,path]);program.subtrees.set(node.id,child);program.size+=child.size;}cache.set(path,program);return program;
  };
  const root=await visit(name),board=new Blackboard([...keys.values()]);for(const program of cache.values())for(const n of program.data.nodes){const p=n.properties;if(n.type==='compareBlackboard'&&(!board.types.has(p.keyA)||board.types.get(p.keyA)!==board.types.get(p.keyB)))throw Error('비교 블랙보드 키 자료형 오류');if(['condition','set','moveTo','lookAt','waitBlackboard'].includes(n.type)){const type=board.types.get(p.key);if(!type)throw Error('블랙보드 키가 없어요: '+p.key);if(n.type==='waitBlackboard'&&!['float','int'].includes(type)||n.type==='set'&&!validBoardValue(type,p.value)||n.type==='condition'&&!['set','notSet'].includes(p.operator)&&!validBoardValue(type,p.value)||['moveTo','lookAt'].includes(n.type)&&!['object','vec3'].includes(type))throw Error('행동트리 키 자료형 오류: '+p.key);}}
  return {root,board};
}
export class BehaviorRunner {
  constructor(asset,board,hooks){
    if(!validGameplayAsset('behaviortree',asset))throw Error('행동트리 검증 실패');
    this.asset=copy(asset);this.board=board;this.hooks=hooks;this.nodes=new Map(this.asset.nodes.map(n=>[n.id,n]));this.memory=new Map();this.status={};this.running=true;this.elapsed=0;this.accumulator=0;this.activeNodes=new Set();this.cooldowns=new Map();this.serviceTimes=new Map();this.runId=crypto.randomUUID();this.taskSerial=0;this.observedRevision=board.revision;
    this.observers=new Map();this.parents=new Map();for(const n of this.asset.nodes)for(const child of n.children)this.parents.set(child,n.id);
    this.program=hooks.program;this.assetPath=hooks.program?.path||'';this.frameSerial=0;this.wake=true;
    this.rootGuards=new Map();this.proxyOwners=new Map();for(const n of this.asset.nodes.filter(n=>n.type==='subtree')){const program=this.program?.subtrees.get(n.id);if(program){const guard=this.injectRootGuards(n.id,program,program.data.root,n.id,n.id+'/root');if(guard)this.rootGuards.set(n.id,guard);}}
  }
  injectRootGuards(owner,program,id,parent,prefix){const source=program.data.nodes.find(n=>n.id===id);if(!['condition','compareBlackboard','cooldown','timeLimit','repeat','inverter','forceSuccess','subtree'].includes(source.type))return null;const key=prefix+'/'+id,node={...source,id:key,children:[]};this.nodes.set(key,node);this.parents.set(key,parent);this.proxyOwners.set(key,owner);const childProgram=source.type==='subtree'?program.subtrees.get(source.id):program,childId=source.type==='subtree'?childProgram?.data.root:source.children[0];if(childId){const child=this.injectRootGuards(owner,childProgram,childId,key,key);if(child)node.children.push(child);}return key;}
  taskHandle(key){if(typeof key!=='string')return '';const node=this.nodes.get(key)||this.asset.nodes.find(n=>n.name===key),m=node&&this.memory.get(node.id);if(m?.taskActive)return m.handle;for(const [id,m] of this.memory)if(m.child){const handle=m.child.taskHandle(key.startsWith(id+'/')?key.slice(id.length+1):key);if(handle)return handle;}return '';}
  finishTask(handle,success){if(typeof success!=='boolean')throw Error('태스크 결과는 bool이에요.');if(!this.running)return false;for(const m of this.memory.values()){if(m.taskActive&&m.handle===handle&&m.result===undefined){m.result=success?'success':'failure';this.wake=true;this.hooks.changed?.();return true;}if(m.child?.finishTask(handle,success)){this.wake=true;return true;}}return false;}
  ownTasks(){return [...this.memory].filter(([,m])=>m.taskActive).map(([id,m])=>({id,name:this.nodes.get(id).name,handle:m.handle,result:m.result||'running'}));}
  snapshot(){return [...this.ownTasks(),...[...this.memory].flatMap(([id,m])=>m.child?m.child.snapshot().map(t=>({...t,id:id+'/'+t.id,sourceNode:t.sourceNode||t.id,asset:t.asset||m.child.assetPath})):[])];}
  instances(scope='',path=[]){return [{scope,path,asset:this.assetPath,blackboard:this.asset.blackboard,result:this.result,status:copy(this.status),tasks:this.ownTasks()},...[...this.memory].flatMap(([id,m])=>m.child?m.child.instances(scope?scope+'/'+id:id,[...path,this.nodes.get(id).name]):[])];}
  condition(node){const p=node.properties;return node.type==='compareBlackboard'?testCondition({operator:p.comparison,value:this.board.get(p.keyB)},this.board.get(p.keyA)):testCondition(p,this.board.get(p.key));}
  observation(node){const p=node.properties;return {value:JSON.stringify(node.type==='compareBlackboard'?[this.board.get(p.keyA),this.board.get(p.keyB)]:this.board.get(p.key)),result:this.condition(node)};}
  registerConditions(id){const n=this.nodes.get(id);if(['condition','compareBlackboard'].includes(n.type)){this.observers.set(id,this.observation(n));if(n.children[0])this.registerConditions(n.children[0]);}else if(['cooldown','timeLimit','repeat','inverter','forceSuccess','subtree'].includes(n.type)){const child=this.rootGuards.get(id)||n.children[0];if(child)this.registerConditions(child);}}
  entryAllowed(id){const n=this.nodes.get(id);if(['condition','compareBlackboard'].includes(n.type))return this.condition(n)&&(!n.children[0]||this.entryAllowed(n.children[0]));if(n.type==='cooldown'&&(this.cooldowns.get(id)||0)>this.elapsed)return false;if(['cooldown','timeLimit','repeat','forceSuccess','subtree'].includes(n.type)){const child=this.rootGuards.get(id)||n.children[0];return !child||this.entryAllowed(child);}return true;}
  async observe(){
    let aborted=false;const restarts=new Map();for(const [id,previous] of [...this.observers]){if(!this.running)break;if(this.observers.get(id)!==previous)continue;const node=this.nodes.get(id),current=this.observation(node),p=node.properties,mode=p.abortMode||'both';this.observers.set(id,current);if((p.notify||'result')==='value'?previous.value===current.value:previous.result===current.result)continue;
      if(!this.proxyOwners.has(id)&&['self','both'].includes(mode)&&!current.result&&this.activeNodes.has(id)){await this.reset(id);aborted=true;}
      if(!current.result||!['lower','both'].includes(mode))continue;let branch=id;for(let parent=this.parents.get(branch);parent;branch=parent,parent=this.parents.get(parent)){const composite=this.nodes.get(parent),m=this.memory.get(parent);if(composite.type!=='selector'||!m?.active)continue;const index=composite.children.indexOf(branch),active=composite.children.indexOf(m.active);if(index<active&&this.entryAllowed(branch)){const existing=restarts.get(parent);if(!existing||index<existing.index)restarts.set(parent,{m,index});}}
    }
    for(const [id,{m,index}] of restarts){if(!this.running)break;if(this.memory.get(id)!==m||!m.active)continue;await this.reset(m.active);m.active=null;m.restartAt=index;aborted=true;}return aborted;
  }
  async notify(name,node,extra={},task=false){if(this.nativeCallbackSkip&&task&&extra.phase==='tick'&&this.nativeCallbackSkip.node===node.id&&this.nativeCallbackSkip.name===name){this.nativeCallbackSkip=null;return;}if(name)await (task?(this.hooks.taskEvent||this.hooks.event):this.hooks.event)?.(name,{node:node.id,task:this.memory.get(node.id)?.handle||'',delta:this.delta||0,time:this.elapsed,...extra});}
  async deactivate(node,m){if(!m?.servicesActive)return;m.servicesActive=false;for(const service of node.services||[])await this.notify(service.onDeactivation,node,{service:service.id});}
  async reset(id,{silent=false}={}){
    const node=this.nodes.get(id);if(!node)return;for(const child of node.children)await this.reset(child,{silent});const m=this.memory.get(id);
    if(m?.child)await m.child.stop({silent});
    if(m?.taskActive){m.taskActive=false;this.hooks.scopeEnd?.(m.handle);this.status[id]='aborted';this.hooks.changed?.();if(!silent)await this.notify(node.properties.onAbort,node,{phase:'abort'},true);}
    if(m?.moving&&!silent)await this.hooks.cancelMove?.(id);if(!silent)await this.deactivate(node,m);this.memory.delete(id);this.activeNodes.delete(id);this.observers.delete(id);for(const [key,owner] of this.proxyOwners)if(owner===id)this.observers.delete(key);
  }
  async shutdown(silent=false){if(this.shuttingDown)return;this.shuttingDown=true;try{await this.reset(this.asset.root,{silent});this.memory.clear();this.activeNodes.clear();this.observers.clear();this.cooldowns.clear();this.serviceTimes.clear();this.hooks.changed?.();}finally{this.shuttingDown=false;}}
  async stop({silent=false}={}){if(!this.running)return;this.running=false;this.stopSilent=silent;if(!this.ticking)await this.shutdown(silent);}
  nativeTickRow(delta,vm,id){
    // ponytail: batch one stable task path. Parallel work, subtree/service
    // callbacks and branches that must reconsider earlier children stay ordered.
    let node=this.nodes.get(this.asset.root);const binding=vm.bindings.find(b=>b.self===id);
    for(let depth=0;node&&node.type!=='task';depth++){
      if(depth>=64||node.services?.length)return;const m=this.memory.get(node.id),p=node.properties;let child;
      if(node.type==='sequence')child=node.children[m?.index||0];
      else if(node.type==='selector'){const index=node.children.indexOf(m?.active);if(index<0||index>0&&p.reactive!==false)return;child=m.active;}
      else if(['inverter','forceSuccess','repeat','condition','compareBlackboard','timeLimit','cooldown'].includes(node.type)){if(['condition','compareBlackboard'].includes(node.type)&&!this.condition(node)||node.type==='timeLimit'&&this.elapsed+delta-(m?.started??this.elapsed)>=p.duration||node.type==='cooldown'&&(this.cooldowns.get(node.id)||0)>this.elapsed+delta)return;child=node.children[0];}
      else return;node=this.nodes.get(child);
    }
    if(!node)return;const memory=this.memory.get(node.id);
    if(!binding||!this.running||this.ticking||!memory?.taskActive||memory.result!==undefined||node.services?.length||this.board.revision!==this.observedRevision||!node.properties.onTick||!Number.isFinite(delta)||delta<0||!this.wake&&this.accumulator+delta<this.asset.interval)return;
    const event={name:node.properties.onTick,args:{node:node.id,task:memory.handle,delta:this.accumulator+delta,time:this.elapsed+delta,phase:'tick'},scope:memory.handle};let begun=false,completed=false;
    return {binding,events:[event],before:()=>{begun=true;this.frameSerial++;this.elapsed+=delta;this.accumulator+=delta;this.ticking=true;},after:async()=>{this.nativeCallbackSkip={node:node.id,name:event.name};try{await this.tick(0,{prepared:true});completed=true;}finally{this.nativeCallbackSkip=null;}},canResume:()=>this.running&&this.memory.get(node.id)===memory,cleanup:async error=>{if(!begun)return;this.ticking=false;if(error&&!completed)this.running=false;if(!this.running)await this.shutdown(this.stopSilent);}};
  }
  async tick(delta,{prepared=false}={}){
    if(!this.running)return;if(!Number.isFinite(delta)||delta<0)throw Error('행동트리 시간 오류');if(this.ticking&&!prepared)throw Error('행동트리 Tick을 중첩 호출할 수 없어요.');
    if(!prepared){this.frameSerial++;this.elapsed+=delta;this.accumulator+=delta;}const changed=!prepared&&this.board.revision!==this.observedRevision;if(!prepared)this.observedRevision=this.board.revision;this.ticking=true;let interrupted=false;try{if(changed)interrupted=await this.observe();if(!prepared)for(const [id,m] of [...this.memory]){if(!this.running)break;if(this.memory.get(id)!==m||!m.child)continue;if(!m.child.result||m.child.result==='running'){await m.child.tick(delta);m.childFrame=this.frameSerial;}if(m.child.result&&m.child.result!=='running')this.wake=true;}}catch(error){this.running=false;await this.shutdown();throw error;}finally{this.ticking=false;if(!this.running)await this.shutdown(this.stopSilent);}if(!this.running)return;
    const legacy=changed&&[...this.memory].some(([id])=>this.nodes.get(id).type==='selector'&&this.nodes.get(id).properties.reactive===undefined);if(!this.wake&&!interrupted&&!legacy&&this.accumulator<this.asset.interval)return;
    this.delta=this.accumulator;this.accumulator=0;this.wake=false;this.ticking=true;this.status={};const previous=new Set(this.activeNodes),visited=new Set();this.activeNodes.clear();let budget=1024;
    const execute=async id=>{
      if(!this.running)return 'failure';if(--budget<0)throw Error('행동트리 실행량 제한 초과');
      const node=this.nodes.get(id),p=node.properties,m=this.memory.get(id)||{};this.memory.set(id,m);visited.add(id);let result='failure';const activation=!m.servicesActive;m.servicesActive=true;
      for(const service of node.services||[]){const key=id+':'+service.id;if(activation){await this.notify(service.onActivation,node,{service:service.id});if(service.restartTimer!==false||!this.serviceTimes.has(key))this.serviceTimes.set(key,service.callOnStart===false?this.elapsed+service.interval:this.elapsed);}
        if(this.serviceTimes.get(key)<=this.elapsed){await this.notify(service.event,node,{service:service.id});this.serviceTimes.set(key,this.elapsed+Math.max(.001,service.interval+(2*(this.hooks.random?.()??Math.random())-1)*(service.randomDeviation||0)));}if(!this.running)return 'failure';}
      if(node.type==='selector'){const start=p.reactive===false?(m.active?Math.max(0,node.children.indexOf(m.active)):m.restartAt||0):0;delete m.restartAt;for(let i=start;i<node.children.length;i++){const child=node.children[i];result=await execute(child);if(result!=='failure'){if(m.active&&m.active!==child)await this.reset(m.active);m.active=result==='running'?child:null;break;}if(m.active===child)m.active=null;}}
      else if(node.type==='sequence'){result='success';for(let i=m.index||0;i<node.children.length;i++){result=await execute(node.children[i]);if(result!=='success'){m.index=result==='running'?i:0;break;}m.index=i+1;}if(result!=='running'){m.index=0;for(const child of node.children)await this.reset(child);}}
      else if(node.type==='parallel'){if(m.mainResult===undefined)m.mainResult=node.children.length?await execute(node.children[0]):'failure';let background='success';if(node.children[1]&&(m.mainResult==='running'||p.finishMode==='delayed'))background=await execute(node.children[1]);result=m.mainResult==='running'?'running':p.finishMode==='delayed'&&background==='running'?'running':m.mainResult;if(m.mainResult==='running')delete m.mainResult;if(result!=='running'){for(const child of node.children)await this.reset(child);delete m.mainResult;}}
      else if(node.type==='condition'||node.type==='compareBlackboard'){this.registerConditions(id);const observed=this.observers.get(id),retain=m.entered&&['none','lower'].includes(p.abortMode);if(retain||observed.result)result=node.children[0]?await execute(node.children[0]):'success';else if(node.children[0]){await this.reset(node.children[0]);this.registerConditions(id);}m.entered=result==='running';}
      else if(node.type==='inverter'||node.type==='forceSuccess'){const status=node.children[0]?await execute(node.children[0]):'failure';result=status==='running'?status:node.type==='forceSuccess'?'success':status==='success'?'failure':'success';}
      else if(node.type==='repeat'){if(node.children[0]){result=await execute(node.children[0]);if(result==='success'){m.count=(m.count||0)+1;await this.reset(node.children[0]);result=p.count>0&&m.count>=p.count?'success':'running';if(result==='success')m.count=0;}}}
      else if(node.type==='wait'||node.type==='waitBlackboard'){m.duration??=node.type==='wait'?p.duration:this.board.get(p.key);if(!Number.isFinite(m.duration)||m.duration<0)throw Error('대기 시간 키는 0 이상 숫자여야 해요.');m.time=(m.time||0)+this.delta;result=m.time>=m.duration?'success':'running';if(result==='success'){m.time=0;delete m.duration;}}
      else if(node.type==='cooldown'){if((this.cooldowns.get(id)||0)<=this.elapsed){result=node.children[0]?await execute(node.children[0]):'failure';if(result!=='running')this.cooldowns.set(id,this.elapsed+p.duration);}}
      else if(node.type==='timeLimit'){m.started??=this.elapsed-this.delta;if(this.elapsed-m.started>=p.duration){if(node.children[0])await this.reset(node.children[0]);delete m.started;}else result=node.children[0]?await execute(node.children[0]):'failure';if(result!=='running')delete m.started;}
      else if(node.type==='task'){
        if(!m.taskActive){m.taskActive=true;m.handle=this.runId+':'+(++this.taskSerial);delete m.result;this.hooks.scopeBegin?.(m.handle);this.hooks.changed?.();await this.notify(p.onStart,node,{phase:'start'},true);}
        if(this.running&&m.result===undefined)await this.notify(p.onTick,node,{phase:'tick'},true);result=m.result||'running';
        if(result!=='running'){m.taskActive=false;this.hooks.scopeEnd?.(m.handle);this.hooks.changed?.();await this.notify(p.onFinish,node,{phase:'finish',success:result==='success'},true);}
      }
      else if(node.type==='subtree'){this.registerConditions(id);if(!m.child){const program=this.program?.subtrees.get(id);if(!program)throw Error('하위 행동트리 프로그램이 준비되지 않았어요: '+p.asset);m.child=new BehaviorRunner(program.data,this.board,{...this.hooks,program,taskEvent:(name,args)=>(this.hooks.taskEvent||this.hooks.event)?.(name,{...args,node:id+'/'+args.node,asset:args.asset||program.path})});}if(m.childFrame!==this.frameSerial){await m.child.tick(this.delta);m.childFrame=this.frameSerial;}result=m.child.result||'running';if(result!=='running'){await m.child.stop();m.child=null;}}
      else if(node.type==='set'){this.board.set(p.key,p.value);result='success';}
      else if(node.type==='moveTo'){m.moving=true;const moved=await this.hooks.move(this.board.get(p.key),p.speed,p.tolerance,id);result=typeof moved==='string'?moved:moved?'success':'running';if(result!=='running')m.moving=false;}
      else if(node.type==='lookAt'){await this.hooks.look(this.board.get(p.key));result='success';}
      else if(node.type==='event'){await this.notify(p.event,node);result='success';}
      else if(node.type==='playAnimation'){await this.hooks.animation(p.clip);result='success';}
      else result=node.type==='succeed'?'success':'failure';
      if(!this.running)return 'failure';this.status[id]=result;if(result==='running')this.activeNodes.add(id);else await this.deactivate(node,m);return result;
    };
    try{this.result=await execute(this.asset.root);for(const id of previous)if(!visited.has(id))await this.reset(id);return this.result;}
    catch(error){this.running=false;await this.shutdown();throw error;}
    finally{this.ticking=false;if(!this.running)await this.shutdown(this.stopSilent);}
  }
}
export class StateMachineRunner {
  constructor(asset,hooks){
    if(!validGameplayAsset('statemachine',asset))throw Error(gameplayValidationError('statemachine',asset));this.asset=copy(asset);this.board=new Blackboard(asset.parameters);this.hooks=hooks;this.states=new Map(this.asset.states.map(s=>[s.id,s]));this.children=new Map();for(const s of this.asset.states){const list=this.children.get(s.parent||'')||[];list.push(s);this.children.set(s.parent||'',list);}this.active=[];this.times=new Map();this.current=null;this.elapsed=0;this.events=new Set();this.running=true;this.revision=0;this.processing=false;this.pending=null;
  }
  matches(conditions){return (conditions||[]).every(c=>testCondition(c,this.board.get(c.key)));}
  select(id){
    const target=this.states.get(id)||this.asset.states.find(s=>s.name===id);if(!target)throw Error('상태가 없어요: '+id);
    const prefix=[];for(let s=target;s;s=this.states.get(s.parent))prefix.unshift(s);if(prefix.some(s=>!this.matches(s.enterConditions)))return null;
    const descend=state=>{const children=this.children.get(state.id)||[];if(!children.length)return [state];const ordered=state.initialChild?[...children.filter(s=>s.id===state.initialChild),...children.filter(s=>s.id!==state.initialChild)]:children;for(const child of ordered)if(this.matches(child.enterConditions)){const path=descend(child);if(path)return [state,...path];}return null;};
    const path=descend(target);return path?[...prefix.slice(0,-1),...path]:null;
  }
  changed(){this.current=this.active.at(-1)||null;this.elapsed=this.current?this.times.get(this.current.id)||0:0;this.revision++;this.hooks.changed?.();}
  snapshot(){return {running:this.running,active:this.active.map(s=>({id:s.id,name:s.name,time:this.times.get(s.id)||0})),elapsed:this.elapsed};}
  async drain(){
    if(this.processing)return;this.processing=true;
    try{let budget=64;while(this.pending){if(--budget<0)throw Error('상태 진입 이벤트의 재전환 제한 초과');const request=this.pending;this.pending=null;const next=request.stop?[]:this.select(request.id);if(!next)throw Error('진입 조건을 만족하는 하위 상태가 없어요.');let common=0;while(common<next.length&&common<this.active.length&&next[common].id===this.active[common].id)common++;
      if(request.reenter){const index=this.active.findIndex(s=>s.id===request.id);if(index>=0)common=Math.min(common,index);}
      while(this.active.length>common){const old=this.active.pop();this.times.delete(old.id);this.changed();if(old.onExit)await this.hooks.event(old.onExit);}
      for(const s of next.slice(common)){if(this.pending||!this.running)break;this.active.push(s);this.times.set(s.id,0);this.changed();if(s.clip)await this.hooks.animation(s.clip,s.loop);if(s.onEnter)await this.hooks.event(s.onEnter);}
      this.changed();
    }}catch(error){this.running=false;this.pending=null;this.events.clear();this.active=[];this.times.clear();this.changed();throw error;}finally{this.processing=false;}
  }
  async enter(id,{reenter=true}={}){if(!this.running)throw Error('상태 머신이 정지됐어요.');const state=this.states.get(id)||this.asset.states.find(s=>s.name===id);if(!state)throw Error('상태가 없어요: '+id);if(!this.select(state.id))throw Error('진입 조건을 만족하는 하위 상태가 없어요.');this.pending={id:state.id,reenter};await this.drain();}
  async tick(delta){
    if(!this.running)return;if(!Number.isFinite(delta)||delta<0)throw Error('상태 머신 시간 오류');if(this.ticking)throw Error('상태 머신 Tick을 중첩 호출할 수 없어요.');this.ticking=true;
    try{if(!this.current)await this.enter(this.asset.initial);if(!this.running)return;const revision=this.advanceTick(delta);
      for(const state of [...this.active]){if(state.onUpdate)await this.hooks.event(state.onUpdate);if(!this.running||this.revision!==revision)return;}
      await this.finishTick(revision);
    }finally{this.ticking=false;}
  }
  advanceTick(delta){for(const s of this.active)this.times.set(s.id,(this.times.get(s.id)||0)+delta);this.changed();return this.revision;}
  transitionFor(delta=0){
    if(this.transitionArray!==this.asset.transitions){this.transitionArray=this.asset.transitions;this.transitions=new Map();for(const t of this.transitionArray){const list=this.transitions.get(t.from)||[];list.push(t);this.transitions.set(t.from,list);}}
    for(const source of [...this.active].reverse().map(s=>s.id).concat('any')){const transition=this.transitions.get(source)?.find(t=>{if(t.hasExitTime&&((source==='any'?this.elapsed:this.times.get(source)||0)+delta)/(this.states.get(source)?.duration||this.current.duration)<t.exitTime||t.event&&!this.events.has(t.event)||!this.matches(t.conditions))return false;const path=this.select(t.to);return path&&(t.reenter||path.at(-1).id!==this.current.id);});if(transition)return transition;}
  }
  async finishTick(revision){if(!this.running||this.revision!==revision)return;const transition=this.transitionFor();this.events.clear();if(transition)await this.enter(transition.to,{reenter:transition.reenter===true});}
  nativeTickRow(delta,vm,id){
    if(!this.running||!this.current||this.ticking||this.processing||!Number.isFinite(delta)||delta<0)return;
    const binding=vm.bindings.find(b=>b.self===id),events=this.active.filter(s=>s.onUpdate).map(s=>s.onUpdate);if(!binding||!events.length)return;
    const snapshot=this.snapshot();snapshot.elapsed+=delta;for(const state of snapshot.active)state.time+=delta;
    const gameplayDebug=JSON.parse(JSON.stringify({...vm.object(id).gameplayDebug,stateMachine:snapshot}));let revision;
    return {binding,events,stateUpdates:[{id,gameplayDebug}],barrier:!!this.transitionFor(delta),before:()=>{this.ticking=true;revision=this.advanceTick(delta);},after:()=>this.finishTick(revision),canResume:()=>this.running&&this.revision===revision,cleanup:()=>{this.ticking=false;}};
  }
  async stop({silent=false}={}){this.running=false;this.events.clear();if(silent){this.pending=null;this.active=[];this.times.clear();this.changed();return;}this.pending={stop:true};await this.drain();}
}
export function gameplaySystems(hooks){
  const brains=new Map(),machines=new Map(),machineRequests=new Map(),brainRequests=new Map(),montages=new Map(),montageRequests=new Map(),sequences=new Map();let generation=0,montageSerial=0,actorRequestSerial=0,montageEpochs=new WeakMap();
  const binding=(vm,id)=>vm.bindings.find(b=>b.self===id)||{self:id,root:{components:[]}};
  const event=async(vm,id,name,args={},scope='')=>{if(!name)return;const b=vm.bindings.find(b=>b.self===id);if(b)await vm.custom(b,name,args,scope);};
  const load=async(name,kind)=>{const path=await hooks.asset(name,kind);if(!path)throw Error('에셋이 없어요: '+name);const value=await hooks.readAsset(path);if(!validGameplayAsset(kind,value))throw Error(gameplayValidationError(kind,value));return copy(value);};
  const pawn=(vm,id)=>{const owner=vm.object(id);if(!owner)throw Error('AI 대상이 없어요: '+id);return vm.object(owner.pawn||enabledComponent(owner,'AIController')?.pawn)||owner;};
  const montageState=(id,group)=>group!==undefined?montages.get(id)?.get(group):[...(montages.get(id)?.values()||[])].at(-1);
  const montageSnapshot=s=>s?{asset:s.asset,group:s.group,time:s.time,section:s.section,paused:s.paused,weight:s.weight,finished:s.finished,stopping:!!s.stopBlend,slots:[...s.player.slots.keys()],notifyStates:s.notifyTrack?.snapshot()||[]}:null;
  const debug=(vm,id)=>{const o=vm.object(id);if(!o)return;o.gameplayDebug={...o.gameplayDebug,blackboard:brains.get(id)?.board.snapshot(),blackboardAsset:brains.get(id)?.asset.blackboard,behavior:brains.get(id)?{result:brains.get(id).result,status:copy(brains.get(id).status),tasks:brains.get(id).snapshot(),instances:brains.get(id).instances()}:null,state:machines.get(id)?.current?.name||'',stateMachine:machines.get(id)?.snapshot()||null,parameters:machines.get(id)?.board.snapshot(),montage:montageSnapshot(montageState(id)),montageGroups:[...(montages.get(id)?.values()||[])].map(montageSnapshot),sequence:sequences.get(id)?{asset:sequences.get(id).asset,time:sequences.get(id).time,paused:sequences.get(id).paused}:null};};
  async function notifyEvents(id,state,vm,events){
    const object=vm.object(id),b=vm.bindings.find(b=>b.self===id);let error;
    for(const args of events){if(!vm.active||vm.object(id)!==object||!object)break;try{await deliverAnimationNotify(vm,b,{...args,asset:state.asset});}catch(e){error??=e;}}if(error)throw error;
  }
  async function cancelMontageNotifies(id,state,vm,reason){if(!state.notifyTrack)return;state.notifyRecord.epoch++;await notifyEvents(id,state,vm,state.notifyTrack.cancel(reason));}
  async function finishMontage(id,state,vm,reason){
    const groups=montages.get(id);if(groups?.get(state.group)!==state)return;groups.delete(state.group);if(!groups.size)montages.delete(id);state.player.dispose();debug(vm,id);
    const object=vm.object(id),args={asset:state.asset,group:state.group,reason,interrupted:reason!=='completed'};let error;
    try{await cancelMontageNotifies(id,state,vm,reason);}catch(e){error=e;}state.notifyTrack?.dispose();
    for(const name of [reason==='completed'?'OnMontageCompleted':'OnMontageInterrupted','OnMontageEnded'])if(vm.active&&vm.object(id)===object&&object)try{await event(vm,id,name,args);}catch(e){error??=e;}if(error)throw error;
  }
  async function blendStop(id,state,vm,duration){
    if(montages.get(id)?.get(state.group)!==state)return;if(!duration||!state.weight)return finishMontage(id,state,vm,'stopped');if(state.stopBlend&&duration>=state.stopBlend.duration-state.stopBlend.elapsed)return;
    state.stopBlend={duration,elapsed:0,weight:state.weight};state.revision++;await cancelMontageNotifies(id,state,vm,'stopped');if(montages.get(id)?.get(state.group)!==state)return;debug(vm,id);
    if(!state.blendingOut){state.blendingOut=true;await event(vm,id,'OnMontageBlendOut',{asset:state.asset,group:state.group,interrupted:true});}
  }
  async function stopMontages(id,vm,reason='stopped',blendTime=0){const owner=vm.object(id);if(owner)montageEpochs.set(owner,(montageEpochs.get(owner)||0)+1);let firstError;for(const state of [...(montages.get(id)?.values()||[])])try{if(reason==='stopped')await blendStop(id,state,vm,blendTime);else await finishMontage(id,state,vm,reason);}catch(error){firstError??=error;}if(firstError)throw firstError;}
  async function startBrain(id,name,vm){pawn(vm,id);const token=generation,request=++actorRequestSerial;brainRequests.set(id,request);let moveOwner;const {root:program,board}=await loadBehaviorProgram(name,hooks),data=program.data;if(token!==generation||!vm.active)throw Error('행동트리를 읽는 동안 월드가 종료됐어요.');if(brainRequests.get(id)!==request)return;await brains.get(id)?.stop();if(brainRequests.get(id)!==request)return;const runner=new BehaviorRunner(data,board,{program,
    move:async(value,speed,tolerance,node)=>{moveOwner=node;const o=pawn(vm,id),destination=typeof value==='string'?vm.object(value)&&sceneWorldPosition(vm.object(value),vm.objects):value;if(!o||!Array.isArray(destination))throw Error('Move To의 목표를 확인하세요.');if(enabledComponent(o,'NavigationAgent')){const state=o.gameplayDebug?.navigation;if(!state||JSON.stringify(state.destination)!==JSON.stringify(destination)){await hooks.operation('navigationMove',{target:o.id,destination},binding(vm,id),vm);o.gameplayDebug={...o.gameplayDebug,navigation:{...o.gameplayDebug?.navigation,destination}};}const status=(await hooks.operation('navigationStatus',{target:o.id},binding(vm,id),vm)).return;return status==='arrived'?'success':status==='failed'?'failure':'running';}const current=sceneWorldPosition(o,vm.objects),direction=destination.map((v,i)=>v-current[i]),distance=Math.hypot(...direction);if(distance<=tolerance)return true;const movement=enabledComponent(o,'CharacterMovement2D')||enabledComponent(o,'CharacterMovement')||enabledComponent(o,'PawnMovement');if(movement)hooks.physics(vm).movement(o,direction.map(v=>v/distance),speed/Math.max(.001,movement.speed));else{const step=Math.min(distance-tolerance,speed*data.interval);setSceneWorldPosition(o,current.map((v,i)=>v+direction[i]/distance*step),vm.objects);hooks.update(o);}return false;},
    look:async(value)=>{const o=pawn(vm,id),target=typeof value==='string'?vm.object(value)&&sceneWorldPosition(vm.object(value),vm.objects):value;if(!o||!Array.isArray(target))throw Error('Look At 목표 오류');const p=sceneWorldPosition(o,vm.objects);o.rotation[1]=Math.atan2(target[0]-p[0],target[2]-p[2])*180/Math.PI;hooks.update(o);},changed:()=>debug(vm,id),scopeBegin:handle=>vm.beginScope?.(handle),scopeEnd:handle=>vm.cancelScope?.(handle),taskEvent:(name,args)=>event(vm,id,name,args,['start','tick'].includes(args.phase)?args.task:''),cancelMove:async node=>{if(moveOwner!==node)return;moveOwner=null;const o=pawn(vm,id);if(enabledComponent(o,'NavigationAgent'))await hooks.operation('navigationStop',{target:o.id},binding(vm,id),vm);if(enabledComponent(o,'Rigidbody')||enabledComponent(o,'Rigidbody2D'))hooks.physics(vm).velocity(o,[0,0,0]);o.velocity=[0,0,0];},event:(name,args)=>event(vm,pawn(vm,id).id,name,args),animation:clip=>hooks.operation('playAnimation',{target:pawn(vm,id).id,clip,loop:false},binding(vm,id),vm)
  });brains.set(id,runner);debug(vm,id);}
  async function startMachine(id,name,vm){if(!vm.object(id))throw Error('상태 머신 대상이 없어요.');const token=generation,request=++actorRequestSerial;machineRequests.set(id,request);const data=await load(name,'statemachine');if(token!==generation||!vm.active)throw Error('상태 머신을 읽는 동안 실행이 종료됐어요.');if(machineRequests.get(id)!==request)return;await machines.get(id)?.stop();if(machineRequests.get(id)!==request)return;const runner=new StateMachineRunner(data,{changed:()=>debug(vm,id),event:name=>event(vm,id,name),animation:(clip,loop)=>hooks.operation('playAnimation',{target:id,clip,loop},binding(vm,id),vm)});machines.set(id,runner);await runner.enter(data.initial);debug(vm,id);}
  async function stopSequence(id,vm,restore=true){const state=sequences.get(id);if(!state)return;
    for(const track of state.data.tracks){if(track.type==='animation'&&vm.object(track.target||id))await hooks.operation('stopAnimation',{target:track.target||id},binding(vm,id),vm);if(track.type==='audio')for(const clip of track.clips)await hooks.operation('stopSound',{sound:clip.clip},binding(vm,id),vm);}
    if(restore&&state.data.restoreState){for(const [objectId,values] of state.original){const o=vm.object(objectId);if(o){Object.assign(o,copy(values));hooks.update(o);}}for(const effect of state.effects)if(vm.object(effect.target))await hooks.operation(effect.type==='light'?'lightIntensity':'materialFloat',{target:effect.target,value:effect.value,parameter:effect.parameter},binding(vm,id),vm);vm.core.scale=state.originalScale;vm.sequenceCamera=state.originalCamera;}
    sequences.delete(id);debug(vm,id);
  }
  async function operation(key,a,b,vm){const id=a.target===null||a.target===undefined||a.target==='self'?b.self:a.target;
    if(key==='runBehaviorTree'){await startBrain(id,a.asset,vm);return {};}
    if(key==='stopBehaviorTree'){brainRequests.set(id,++actorRequestSerial);const runner=brains.get(id);await runner?.stop();if(brains.get(id)===runner)brains.delete(id);debug(vm,id);return {};}
    if(key==='behaviorTaskHandle')return {return:brains.get(id)?.taskHandle(a.node)||''};
    if(key==='behaviorTaskFinish'){if(typeof a.task!=='string'||typeof a.success!=='boolean')throw Error('태스크 핸들·결과 자료형 오류');brains.get(id)?.finishTask(a.task,a.success);debug(vm,id);return {}; }
    if(key.startsWith('blackboard')){const board=brains.get(id)?.board;if(!board)throw Error('실행 중인 블랙보드가 없어요.');if(key==='blackboardClear')board.clear(a.key);else{const type={Bool:'bool',Float:'float',Int:'int',String:'string',Vector:'vec3',Object:'object'}[key.replace(/^blackboard(?:Set|Get)/,'')];if(!type||board.types.get(a.key)!==type)throw Error('블랙보드 함수 자료형 오류: '+a.key);if(key.startsWith('blackboardSet'))board.set(a.key,a.value);else return {return:board.get(a.key)};}debug(vm,id);return {};}
    if(key==='startStateMachine'){await startMachine(id,a.asset,vm);return {};}
    if(['stateSetFloat','stateSetBool','stateSetString','stateGet','stateIsActive','stateGetPath','stateElapsed','stateEvent','stateJump','stateStop'].includes(key)){const runner=machines.get(id);if(['stateIsActive','stateGetPath','stateElapsed'].includes(key)&&!vm.object(id))throw Error('상태 머신 대상이 없어요.');if(key==='stateIsActive')return {return:runner?.active.some(s=>s.id===a.state||s.name===a.state)||false};if(key==='stateGetPath')return {return:runner?.active.map(s=>s.name)||[]};if(key==='stateElapsed')return {return:runner?.elapsed||0};if(!runner)throw Error('상태 머신이 실행 중이 아니에요.');if(key==='stateGet')return {return:runner.current?.name||''};if(key==='stateEvent')runner.events.add(a.event);else if(key==='stateJump')await runner.enter(a.state);else if(key==='stateStop'){machineRequests.set(id,++actorRequestSerial);await runner.stop();if(machines.get(id)===runner)machines.delete(id);}else{const type={stateSetFloat:'float',stateSetBool:'bool',stateSetString:'string'}[key];if(type!==runner.board.types.get(a.key))throw Error('상태 파라미터 자료형 오류');runner.board.set(a.key,a.value);}debug(vm,id);return {};}
    if(key==='playMontage'){
      const object=vm.object(id);if(!object||object.destroying||vm.stopping)throw Error('몽타주 대상·실행 상태를 확인하세요.');const token=generation,epoch=montageEpochs.get(object)||0,request=++montageSerial,data=await load(a.asset,'montage'),group=data.group||'DefaultGroup',requestKey=JSON.stringify([id,group]);
      const current=()=>token===generation&&vm.active&&!vm.stopping&&vm.object(id)===object&&!object.destroying&&(montageEpochs.get(object)||0)===epoch&&(montageRequests.get(requestKey)||0)<=request;
      if(!current())return {};if(a.section&&!data.sections.some(s=>s.name===a.section))throw Error('몽타주 섹션이 없어요.');if(!data.clips.length||data.clips.some(c=>!c.clip))throw Error('몽타주에 클립을 지정하세요.');data.notifies.sort((a,b)=>a.time-b.time);montageRequests.set(requestKey,request);
      const player=await hooks.prepareMontage(id,data,vm);if(!current()){player.dispose();return {};}
      try{hooks.attachMontage?.(id,player);const old=montages.get(id)?.get(group);if(old)await finishMontage(id,old,vm,'replaced');if(!current()){player.dispose();return {};}hooks.attachMontage?.(id,player);const groups=montages.get(id)||new Map(),section=data.sections.find(s=>s.name===a.section)||[...data.sections].sort((a,b)=>a.time-b.time)[0],state={data,asset:a.asset,group,player,time:section.time,section:section.name,paused:false,next:new Map(),initial:true,age:0,weight:data.blendIn?0:1,finished:false,revision:0};if(data.notifyStates?.length){
        const node={id:'montage',properties:{notifyStates:data.notifyStates}},owner={data:{nodes:[node]},nodes:new Map([[node.id,node]]),events:[]};
        state.notifyTrack=new AnimationNotifyTrack(owner,animationSyncLimits);state.notifyRecord={id:node.id,context:{key:JSON.stringify(['montage',id,group,request])},length:data.length,p:{loop:false},notifyStates:data.notifyStates,grouped:true,leader:true,group,epoch:0};
      }groups.delete(group);groups.set(group,state);montages.set(id,groups);player.sample(state.time,state.weight);debug(vm,id);return {};}catch(error){player.dispose();throw error;}
    }
    if(['montageStop','montagePause','montageJump','montageNext','montagePosition','montageSeek','montageStopGroup','montagePauseGroup','montagePositionGroup','montageSeekGroup','montageWeightGroup','montagePlayingGroup'].includes(key)){
      const grouped=key.endsWith('Group');if(grouped&&(typeof a.group!=='string'||!a.group.trim()||a.group.length>80))throw Error('몽타주 그룹 이름 오류');const state=montageState(id,grouped?a.group:undefined),command=grouped?key.slice(0,-5):key;
      if(command==='montagePosition'||command==='montageWeight'||command==='montagePlaying')return {return:command==='montagePosition'?state?.time||0:command==='montageWeight'?state?.weight||0:!!state};
      if(command==='montageStop'){const duration=a.blendTime===undefined?0:a.blendTime;if(!Number.isFinite(duration)||duration<0||duration>60)throw Error('몽타주 중단 혼합 시간 범위 오류');if(grouped){montageRequests.set(JSON.stringify([id,a.group]),++montageSerial);if(state)await blendStop(id,state,vm,duration);}else await stopMontages(id,vm,'stopped',duration);return {};}
      if(!state)throw Error('재생 중인 몽타주가 없어요.');
      if(command==='montagePause'){if(typeof a.paused!=='boolean')throw Error('몽타주 정지 자료형 오류');state.paused=a.paused;}
      else if(command==='montageSeek'){
        if(!Number.isFinite(a.time)||a.time<0||a.time>state.data.length)throw Error('몽타주 시간 범위 오류');state.time=a.time;state.section=[...state.data.sections].filter(s=>s.time<=a.time).sort((a,b)=>b.time-a.time)[0].name;state.initial=false;state.finished=false;state.blendingOut=false;state.age=Math.max(state.age,state.data.blendIn||0);
      }else if(command==='montageNext'){if(!state.data.sections.some(s=>s.name===a.section)||a.next&&!state.data.sections.some(s=>s.name===a.next))throw Error('몽타주 섹션 이름 오류');state.next.set(a.section,a.next);}
      else{const section=state.data.sections.find(s=>s.name===a.section);if(!section)throw Error('몽타주 섹션이 없어요.');state.section=section.name;state.time=section.time;state.initial=true;state.finished=false;state.blendingOut=false;}
      if(command!=='montageNext')state.revision++;
      if(['montageSeek','montageJump'].includes(command)){await cancelMontageNotifies(id,state,vm,command==='montageSeek'?'seeked':'jumped');if(montages.get(id)?.get(state.group)!==state)return {};}
      state.player.sample(state.time,state.weight);debug(vm,id);return {};

    }
    if(key==='playSequence'){if(!vm.object(id))throw Error('시퀀스 소유자가 없어요.');const token=generation,data=await load(a.asset,'sequenceasset');if(token!==generation||!vm.active)throw Error('시퀀스를 읽는 동안 실행이 종료됐어요.');
      const original=new Map(),effects=[];for(const track of data.tracks){const o=vm.object(track.target||id);if(!o)throw Error('시퀀스 대상이 없어요: '+track.target);original.set(o.id,{position:copy(o.position),rotation:copy(o.rotation),scale:copy(o.scale),visible:o.visible});if(['light','material'].includes(track.type)){const value=hooks.captureParameter?.(o.id,track.type,track.name);if(!Number.isFinite(value))throw Error('시퀀스 렌더 파라미터를 확인하세요: '+track.name);effects.push({target:o.id,type:track.type,parameter:track.name,value});}if(track.type==='camera')for(const key of track.keys)if(key.value&&!enabledComponent(vm.object(key.value)||{kind:'empty'},'Camera'))throw Error('카메라 키의 대상을 확인하세요.');if(track.clips.some(c=>!c.clip))throw Error('시퀀스 클립을 지정하세요.');}
      await stopSequence(id,vm);original.clear();effects.length=0;for(const track of data.tracks){const o=vm.object(track.target||id);original.set(o.id,{position:copy(o.position),rotation:copy(o.rotation),scale:copy(o.scale),visible:o.visible});if(['light','material'].includes(track.type))effects.push({target:o.id,type:track.type,parameter:track.name,value:hooks.captureParameter(o.id,track.type,track.name)});}sequences.set(id,{asset:a.asset,data,time:0,paused:false,original,effects,originalScale:vm.core.scale,originalCamera:vm.sequenceCamera,active:new Map(),initial:true});debug(vm,id);return {};}
    if(['sequenceStop','sequencePause','sequenceSeek','sequencePosition'].includes(key)){const state=sequences.get(id);if(key==='sequencePosition')return {return:state?.time||0};if(!state)throw Error('재생 중인 시퀀스가 없어요.');if(key==='sequenceStop')await stopSequence(id,vm);else if(key==='sequencePause')state.paused=a.paused;else{if(!Number.isFinite(a.time)||a.time<0||a.time>state.data.length)throw Error('시퀀스 시간 범위 오류');state.time=a.time;state.seek=true;state.active.clear();}debug(vm,id);return {};}
  }
  const sample=(keys,time)=>{const sorted=[...keys].sort((a,b)=>a.time-b.time);if(!sorted.length)return undefined;let a=sorted[0],z=sorted.at(-1);for(let i=1;i<sorted.length;i++)if(time<=sorted[i].time){a=sorted[i-1];z=sorted[i];break;}if(time<=a.time||typeof a.value!=='number'&&!Array.isArray(a.value))return copy(a.value);const alpha=Math.max(0,Math.min(1,(time-a.time)/Math.max(.000001,z.time-a.time)));return Array.isArray(a.value)?a.value.map((v,i)=>v+(z.value[i]-v)*alpha):a.value+(z.value-a.value)*alpha;};
  async function tickLogic(delta,vm){
    const brainRows=[...brains];for(let index=0;index<brainRows.length;){const [id,runner]=brainRows[index],object=vm.object(id);if(!object||brains.get(id)!==runner||object.components?.some(c=>c.type==='BehaviorTree'&&c.properties?.enabled===false)){index++;continue;}const plans=[];for(const [nextId,nextRunner] of brainRows.slice(index)){const next=vm.object(nextId);if(!next||brains.get(nextId)!==nextRunner||next.components?.some(c=>c.type==='BehaviorTree'&&c.properties?.enabled===false))break;const plan=nextRunner.nativeTickRow(delta,vm,nextId);if(!plan)break;plans.push(plan);}const used=plans.length>1?await vm.nativeCallbackGroup?.(plans):0;if(used){for(const [done] of brainRows.slice(index,index+used))debug(vm,done);index+=used;}else{await runner.tick(delta);debug(vm,id);index++;}}
    const rows=[...machines];for(let index=0;index<rows.length;){const [id,runner]=rows[index];if(!vm.object(id)||machines.get(id)!==runner){index++;continue;}const plans=[];for(const [nextId,nextRunner] of rows.slice(index)){if(!vm.object(nextId)||machines.get(nextId)!==nextRunner)break;const plan=nextRunner.nativeTickRow(delta,vm,nextId);if(!plan)break;plans.push(plan);if(plan.barrier)break;}const used=plans.length>1?await vm.nativeCallbackGroup?.(plans):0;if(used){for(const [done] of rows.slice(index,index+used))debug(vm,done);index+=used;}else{await runner.tick(delta);debug(vm,id);index++;}}
  }
  function montageBlend(state,time,age,ordered){
    const section=ordered.find(s=>s.name===state.section),end=ordered.find(s=>s.time>section.time)?.time??state.data.length,next=state.next.get(section.name)??section.next,auto=state.data.autoBlendOut!==false;
    const blend=x=>{x=Math.max(0,Math.min(1,x));return state.data.blendCurve==='smooth'?x*x*(3-2*x):x;};let weight=blend(state.data.blendIn?age/state.data.blendIn:1);
    const fading=auto&&!next&&!state.data.loop&&state.data.blendOut&&(end-time)/state.data.rate<state.data.blendOut;if(fading)weight=Math.min(weight,blend((end-time)/state.data.rate/state.data.blendOut));return {weight,fading,auto};
  }
  async function montageNotifies(id,state,prev,destination,delta,weight,vm){
    if(!state.notifyTrack&&!state.data.notifies.length){state.initial=false;return true;}
    const pending=[],track=state.notifyTrack,record=state.notifyRecord,object=vm.object(id),revision=state.revision,epoch=record?.epoch;
    for(const n of state.data.notifies)if(n.time>prev&&n.time<=destination||state.initial&&n.time===prev)pending.push({fraction:destination===prev?0:(n.time-prev)/(destination-prev),event:{name:n.event,time:n.time}});
    if(track){Object.assign(record,{previous:prev,absolute:destination,weight,notifyWeight:weight});track.resolve(new Map([[record,weight]]),pending,delta);pending.sort((a,b)=>a.fraction-b.fraction);}
    state.initial=false;for(const item of pending){const args=item.event;state.time=Math.max(prev,Math.min(destination,args.time));
      try{if(item.window){track.acknowledge(args);await notifyEvents(id,state,vm,[args]);}else await event(vm,id,args.name,{asset:state.asset,group:state.group,time:args.time});}
      catch(error){try{await finishMontage(id,state,vm,'failed');}catch{}throw error;}
      if(!vm.active||vm.object(id)!==object||montages.get(id)?.get(state.group)!==state)return false;
      if(state.revision!==revision){if(track&&record.epoch===epoch&&!state.stopBlend)await notifyEvents(id,state,vm,track.interrupt(pending,state.time).map(args=>{track.acknowledge(args);return args;}));debug(vm,id);return false;}
    }return true;
  }
  async function tickMontages(delta,vm){
    montageLoop:for(const [id,group, state] of [...montages].flatMap(([id,groups])=>[...groups].map(([group,state])=>[id,group,state]))){
      const object=vm.object(id),revision=state.revision;if(!object||montages.get(id)?.get(group)!==state)continue;if(object.poolActive===false)continue;if(object.components?.some(c=>c.type==='MontagePlayer'&&c.properties?.enabled===false)){await finishMontage(id,state,vm,'disabled');continue;}if(state.stopBlend){const fade=state.stopBlend;fade.elapsed=Math.min(fade.duration,fade.elapsed+delta);const t=fade.elapsed/fade.duration,alpha=state.data.blendCurve==='smooth'?t*t*(3-2*t):t;state.weight=fade.weight*(1-alpha);if(fade.elapsed===fade.duration){await finishMontage(id,state,vm,'stopped');continue;}state.player.sample(state.time,state.weight);debug(vm,id);continue;}if(state.finished){state.player.sample(state.time,state.weight);continue;}
      let remaining=state.paused?0:delta*state.data.rate,finished=false,budget=256;const ordered=[...state.data.sections].sort((a,b)=>a.time-b.time);
      do{if(--budget<0)throw Error('몽타주 섹션 반복 한도 초과');const section=ordered.find(s=>s.name===state.section),end=ordered.find(s=>s.time>section.time)?.time??state.data.length,prev=state.time,step=Math.min(remaining,end-prev),destination=prev+step;remaining-=step;
        if(!await montageNotifies(id,state,prev,destination,step/state.data.rate,state.notifyTrack?montageBlend(state,destination,state.age+(state.paused?0:delta),ordered).weight:state.weight,vm))continue montageLoop;state.time=destination;state.initial=false;
        if(state.time<end)break;const next=state.next.get(section.name)??section.next;if(next||state.data.loop){const destination=next?ordered.find(s=>s.name===next):ordered[0];state.section=destination.name;state.time=destination.time;state.initial=true;if(destination.time!==end){await cancelMontageNotifies(id,state,vm,'sectionChanged');if(!vm.active||montages.get(id)?.get(group)!==state||state.revision!==revision)continue montageLoop;}}else{finished=true;break;}
      }while(remaining>0);
      state.age+=state.paused?0:delta;const {weight,fading,auto}=montageBlend(state,state.time,state.age,ordered);state.weight=weight;

      if(fading&&!state.blendingOut){state.blendingOut=true;await event(vm,id,'OnMontageBlendOut',{asset:state.asset,group,interrupted:false});if(!vm.active||montages.get(id)?.get(group)!==state||state.revision!==revision)continue;}
      if(finished&&auto){await finishMontage(id,state,vm,'completed');continue;}if(finished)state.finished=true;state.player.sample(state.time,state.weight);debug(vm,id);
    }
  }
  async function tick(delta,vm,afterPose=false){if(!afterPose){await tickLogic(delta,vm);await tickMontages(delta,vm);}
    for(const [id,state] of [...sequences]){const prev=state.time,ranges=[];let remaining=state.seek||state.paused?0:delta*state.data.rate,budget=256,finished=false;
      do{if(--budget<0)throw Error('시퀀스 반복 한도 초과');const begin=state.time,step=Math.min(remaining,state.data.length-begin);state.time+=step;remaining-=step;ranges.push({begin,end:state.time,initial:state.initial});state.initial=false;if(state.time<state.data.length)break;if(state.data.loop&&remaining>0){state.time=0;state.initial=true;state.active.clear();}else{finished=!state.data.loop;break;}}while(remaining>0);
      const b=binding(vm,id);for(const track of state.data.tracks){const o=vm.object(track.target||id);if(!o)continue;const value=sample(track.keys,state.time);if(['position','rotation','scale','visible'].includes(track.type)&&value!==undefined){o[track.type]=value;hooks.update(o);}if(track.type==='camera'&&value!==undefined)vm.sequenceCamera=value||null;if(track.type==='timeScale'&&value!==undefined)vm.core.scale=value;if(track.type==='light'&&value!==undefined)await hooks.operation('lightIntensity',{target:o.id,value},b,vm);if(track.type==='material'&&value!==undefined)await hooks.operation('materialFloat',{target:o.id,parameter:track.name,value},b,vm);
        if(track.type==='event'&&!state.seek&&!state.paused)for(const range of ranges)for(const key of track.keys)if(key.time>range.begin&&key.time<=range.end||range.initial&&key.time===range.begin)await event(vm,o.id,key.value);
        const clip=track.clips.find(c=>c.start<=state.time&&c.start+c.duration>state.time);if(clip){if(state.active.get(track.id)!==clip.id){await hooks.operation(track.type==='audio'?'playSoundAt':'playAnimation',track.type==='audio'?{sound:clip.clip,position:sceneWorldPosition(o,vm.objects),volume:1}:{target:o.id,clip:clip.clip,loop:false},b,vm);state.active.set(track.id,clip.id);}const time=clip.sourceStart+(state.time-clip.start)*clip.rate;if(track.type==='animation')await hooks.sampleAnimation?.(o.id,time);if(track.type==='audio')await hooks.sampleAudio?.(clip.clip,time,state.paused);}else if(state.active.has(track.id)){await hooks.operation(track.type==='audio'?'stopSound':'stopAnimation',track.type==='audio'?{sound:track.clips.find(c=>c.id===state.active.get(track.id)).clip}:{target:o.id},b,vm);state.active.delete(track.id);}}
      state.seek=false;debug(vm,id);if(finished){await stopSequence(id,vm);await event(vm,id,'OnSequenceCompleted');}else if(state.time>=state.data.length&&state.data.loop){state.time=0;state.initial=true;state.active.clear();}
    }
  }

  return {operation,tick,tickLogic,tickMontages,stopMontages,montagePlayers:id=>[...(montages.get(id)?.values()||[])].map(s=>s.player),slotPose:(id,group,slot)=>montages.get(id)?.get(group)?.player.slot(slot),async applyMontage(id){for(const player of this.montagePlayers(id))await player.apply();},perception(id,targets,vm){const board=brains.get(id)?.board,p=vm.object(id)&&enabledComponent(vm.object(id),'AIPerception');if(!board||!p)return;for(const [key,type,value] of [[p.targetKey,'object',targets[0]?.id||null],[p.sensedKey,'bool',targets.length>0]]){if(!key)continue;if(board.types.get(key)!==type)throw Error('감지 블랙보드 키 자료형 오류: '+key);if(JSON.stringify(board.get(key))!==JSON.stringify(value))board.set(key,value);}debug(vm,id);},async remove(id,vm){brainRequests.set(id,++actorRequestSerial);const brain=brains.get(id);await brain?.stop();if(brains.get(id)!==brain)await brains.get(id)?.stop({silent:true});brainRequests.set(id,++actorRequestSerial);brains.delete(id);machineRequests.set(id,++actorRequestSerial);const machine=machines.get(id);await machine?.stop();if(machines.get(id)!==machine)await machines.get(id)?.stop({silent:true});machineRequests.set(id,++actorRequestSerial);machines.delete(id);await stopMontages(id,vm,'released');await stopSequence(id,vm);brainRequests.delete(id);machineRequests.delete(id);for(const key of montageRequests.keys())if(JSON.parse(key)[0]===id)montageRequests.delete(key);},async start(vm,owner){for(const object of owner?[vm.object(owner)].filter(Boolean):vm.objects){const tree=enabledComponent(object,'BehaviorTree'),fsm=enabledComponent(object,'StateMachine'),montage=enabledComponent(object,'MontagePlayer'),sequence=enabledComponent(object,'SequencePlayer');if(tree?.asset&&tree.autoStart)await startBrain(object.id,tree.asset,vm);if(fsm?.asset&&fsm.autoStart)await startMachine(object.id,fsm.asset,vm);if(montage?.asset&&montage.autoPlay)await operation('playMontage',{target:object.id,asset:montage.asset,section:montage.section},binding(vm,object.id),vm);if(sequence?.asset&&sequence.autoPlay)await operation('playSequence',{target:object.id,asset:sequence.asset},binding(vm,object.id),vm);}},dispose(){generation++;for(const runner of brains.values())runner.stop({silent:true});for(const runner of machines.values())runner.stop({silent:true});brains.clear();machines.clear();machineRequests.clear();brainRequests.clear();for(const groups of montages.values())for(const state of groups.values()){state.notifyTrack?.dispose();state.player.dispose();}montages.clear();montageRequests.clear();montageEpochs=new WeakMap();sequences.clear();}};
}
