import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {clone as cloneSkeleton} from 'three/addons/utils/SkeletonUtils.js';
import {BlueprintRuntime} from './blueprint-runtime.js';
import {engineOperations} from './engine-services.js';
import {sceneRendering} from './scene-rendering.js';
import {fileUrl} from './project-browser.js';

// Preview runs the same services against a separate world, without user gameplay events.
export function gameplayPreview(doc,files,hooks){
  const element=document.createElement('div');element.className='gameplay-preview';const canvas=document.createElement('canvas');canvas.ariaLabel='게임플레이 에셋 미리보기';element.append(canvas);const diagnostic=document.createElement('div');diagnostic.className='gameplay-preview-error';diagnostic.setAttribute('role','status');element.append(diagnostic);
  const renderer=new THREE.WebGLRenderer({canvas,antialias:true}),camera=new THREE.PerspectiveCamera(45,1,.1,1000),controls=new OrbitControls(camera,canvas);camera.position.set(6,4,8);controls.target.set(0,1,0);controls.update();
  let vm,services,world,objects,groups,visuals,signature,disposed=false,pending=null,processing=false,frame,sampledTime=0;
  const observer=new ResizeObserver(()=>{if(!canvas.clientWidth||!canvas.clientHeight)return;renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);camera.aspect=canvas.clientWidth/canvas.clientHeight;camera.updateProjectionMatrix();});observer.observe(element);
  const cleanup=()=>{if(vm)vm.active=false;services?.dispose();for(const group of groups?.values()||[])visuals?.dispose(group);vm=null;services=null;};
  async function initialize(){
    cleanup();const source=hooks.world();world=new THREE.Scene();world.background=new THREE.Color('#1d2228');groups=new Map();objects=structuredClone(source.objects);for(const o of objects){o.components=o.components?.filter(c=>!['BehaviorTree','StateMachine','MontagePlayer','SequencePlayer','Rigidbody','Rigidbody2D'].includes(c.type));for(const c of o.components||[])if(['Animator','AudioSource'].includes(c.type))c.properties.playOnStart=false;const original=source.groups.get(o.id);if(original){const group=cloneSkeleton(original);group.userData={objectId:o.id,resources:new Set(),disposed:false,animations:original.userData.animations,materialData:original.userData.materialData&&structuredClone(original.userData.materialData)};const nested=[];group.traverse(c=>{if(c!==group&&(c.isPoints||c.userData.objectId&&c.userData.objectId!==o.id))nested.push(c);});nested.forEach(c=>c.removeFromParent());group.traverse(c=>{if(c.isCamera)group.userData.gameCamera=c;if(c.userData.sprite)group.userData.spriteMesh=c;if(c.geometry){c.geometry=c.geometry.clone();group.userData.resources.add(c.geometry);}if(c.material){const cloneMaterial=m=>{const next=m.clone();group.userData.resources.add(next);for(const [key,value] of Object.entries(next))if(value?.isTexture){next[key]=value.clone();group.userData.resources.add(next[key]);}for(const uniform of Object.values(next.uniforms||{}))if(uniform.value?.isTexture)group.userData.resources.add(uniform.value);return next;};c.material=Array.isArray(c.material)?c.material.map(cloneMaterial):cloneMaterial(c.material);}});groups.set(o.id,group);world.add(group);}}
    if(!objects.length)throw Error('미리볼 장면을 먼저 여세요.');for(const o of objects)if(o.parent&&groups.has(o.parent))groups.get(o.parent).add(groups.get(o.id));
    world.add(new THREE.HemisphereLight(0xe7edfa,0x334155,1.5));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(3,6,4);world.add(light);
    const update=o=>{const group=groups.get(o.id);if(!group)return;group.position.fromArray(o.position);group.rotation.set(...o.rotation.map(THREE.MathUtils.degToRad));group.scale.fromArray(o.scale);group.visible=o.visible;};
    const read=path=>path===doc.path?structuredClone(doc.data):hooks.read(path);visuals=sceneRendering({read,fileUrl,current:id=>groups.get(id),error:hooks.error});for(const o of objects){const particle=o.components?.find(c=>c.type==='ParticleSystem');if(particle&&groups.has(o.id))await visuals.build({id:o.id,components:[particle]},groups.get(o.id));}sampledTime=0;
    services=engineOperations({readAsset:read,asset:async(name,kind)=>name===doc.path?doc.path:hooks.asset?hooks.asset(name,kind):files().find(f=>f.kind===kind&&(f.path===name||f.name===name||f.name.split('.')[0]===name))?.path,update,mesh:id=>groups.get(id),particleSnapshot:visuals.particleSnapshot,material:visuals.material,materialFloat:visuals.materialFloat,spriteFrame:visuals.spriteFrame});
    if(disposed)return;vm=new BlueprintRuntime(objects,[],{...services,operation:async(key,args,b,v)=>['sound','playSoundAt','stopSound'].includes(key)?{}:services.operation(key,args,b,v)});await vm.start();if(disposed)return;
    const target=doc.kind==='montage'?(hooks.target?.()||source.selected||objects[0].id):objects[0].id,key=doc.kind==='montage'?'playMontage':'playSequence';playback=doc.kind==='montage'?doc.data.clips.length>0&&doc.data.clips.every(c=>c.clip):doc.data.tracks.every(t=>t.clips.every(c=>c.clip));if(playback){await services.operation(key,{target,asset:doc.path,section:''},{self:target},vm);await services.operation(doc.kind==='montage'?'montagePause':'sequencePause',{target,paused:true},{self:target},vm);}return target;
  }
  let target,playback;
  async function process(){if(processing||disposed)return;processing=true;try{while(pending&&!disposed){const request=pending;pending=null;const next=JSON.stringify([doc.data,hooks.target?.(),hooks.world().scene]);if(next!==signature||request.time<sampledTime){target=await initialize();signature=next;diagnostic.textContent='';}if(disposed)break;const seek=async time=>playback&&services.operation(doc.kind==='montage'?'montageSeek':'sequenceSeek',{target,time:Math.min(time,doc.data.length-.000001)},{self:target},vm);
      // ponytail: replay at 60 Hz up to 4096 samples per scrub; long cuts use larger steps until a baked simulation cache exists.
      const stepSize=Math.max(1/60,(request.time-sampledTime)/4096);if(request.time===sampledTime){await seek(sampledTime);await services.physics(0,vm);}while(sampledTime<request.time&&!pending){const step=Math.min(stepSize,request.time-sampledTime);sampledTime+=step;await seek(sampledTime);await services.physics(step,vm);}visuals.tickParticles(objects,0,true);}}catch(error){signature=null;cleanup();diagnostic.textContent=error.message;hooks.error(error.message);}finally{processing=false;}}
  function render(){if(disposed)return;if(element.isConnected&&element.clientWidth&&world){controls.update();visuals.tickParticles(objects,0,true);renderer.render(world,visuals.gameCamera(objects,camera.aspect,vm?.sequenceCamera)||camera);}frame=requestAnimationFrame(render);}frame=requestAnimationFrame(render);
  return {element,sample(time){pending={time};process();},dispose(){disposed=true;pending=null;cleanup();observer.disconnect();controls.dispose();renderer.dispose();cancelAnimationFrame(frame);}};
}
