import {validGameplayAsset,validBoardValue,boardTypes} from './gameplay-assets.js';
import {enabledComponent} from './scene-components.js';
import {sceneWorldPosition,setSceneWorldPosition} from './scene-runtime.js';
const copy=v=>structuredClone(v);
export function testCondition(c,value){switch(c.operator){case 'equal':return JSON.stringify(value)===JSON.stringify(c.value);case 'notEqual':return JSON.stringify(value)!==JSON.stringify(c.value);case 'greater':return value>c.value;case 'less':return value<c.value;case 'greaterEqual':return value>=c.value;case 'lessEqual':return value<=c.value;case 'set':return value!==null&&value!==undefined&&value!==false&&value!=='';case 'notSet':return value===null||value===undefined||value===false||value==='';default:return false;}}
export class Blackboard {
  constructor(keys=[]){this.types=new Map();this.values=new Map();for(const key of keys){if(this.types.has(key.name)&&this.types.get(key.name)!==key.type)throw Error('블랙보드 키 자료형 충돌: '+key.name);this.types.set(key.name,key.type);this.values.set(key.name,copy(key.value));}this.revision=0;}
  set(key,value){if(!this.types.has(key)||!validBoardValue(this.types.get(key),value))throw Error('블랙보드 키나 값의 자료형 오류: '+key);this.values.set(key,copy(value));this.revision++;}
  get(key){if(!this.types.has(key))throw Error('블랙보드 키가 없어요: '+key);return copy(this.values.get(key));}
  clear(key){this.set(key,boardTypes[this.types.get(key)]);}
  snapshot(){return Object.fromEntries(this.values);}
}
export class BehaviorRunner {
  constructor(asset,board,hooks){if(!validGameplayAsset('behaviortree',asset))throw Error('행동트리 검증 실패');this.asset=copy(asset);this.board=board;this.hooks=hooks;this.nodes=new Map(this.asset.nodes.map(n=>[n.id,n]));this.memory=new Map();this.status={};this.running=true;this.elapsed=0;this.accumulator=0;}
  reset(id){this.memory.delete(id);for(const child of this.nodes.get(id)?.children||[])this.reset(child);}
  async tick(delta){if(!this.running)return;this.elapsed+=delta;this.accumulator+=delta;if(this.accumulator<this.asset.interval)return;const dt=this.accumulator;this.accumulator=0;this.status={};let budget=1024;const execute=async id=>{
    if(--budget<0)throw Error('행동트리 실행량 제한 초과');const node=this.nodes.get(id),p=node.properties,m=this.memory.get(id)||{};this.memory.set(id,m);let result='failure';for(const service of node.services||[]){m.services??={};if((m.services[service.id]??-Infinity)+service.interval<=this.elapsed){await this.hooks.event(service.event);m.services[service.id]=this.elapsed;}}
    if(node.type==='selector'){for(const child of node.children){result=await execute(child);if(result!=='failure'){if(m.active&&m.active!==child)this.reset(m.active);m.active=child;break;}}}
    else if(node.type==='sequence'){result='success';for(let i=m.index||0;i<node.children.length;i++){result=await execute(node.children[i]);if(result!=='success'){m.index=result==='running'?i:0;break;}m.index=i+1;}if(result!=='running'){m.index=0;for(const child of node.children)this.reset(child);}}
    else if(node.type==='parallel'){result=node.children.length?await execute(node.children[0]):'failure';if(node.children[1])await execute(node.children[1]);if(result!=='running')for(const child of node.children)this.reset(child);}
    else if(node.type==='condition'){if(testCondition(p,this.board.get(p.key)))result=node.children[0]?await execute(node.children[0]):'success';else if(node.children[0])this.reset(node.children[0]);}
    else if(node.type==='inverter'){const status=node.children[0]?await execute(node.children[0]):'failure';result=status==='running'?status:status==='success'?'failure':'success';}
    else if(node.type==='repeat'){if(!node.children[0])result='failure';else{result=await execute(node.children[0]);if(result==='success'){m.count=(m.count||0)+1;this.reset(node.children[0]);result=p.count>0&&m.count>=p.count?'success':'running';if(result==='success')m.count=0;}}}
    else if(node.type==='wait'){m.time=(m.time||0)+dt;result=m.time>=p.duration?'success':'running';if(result==='success')m.time=0;}
    else if(node.type==='set'){this.board.set(p.key,p.value);result='success';}
    else if(node.type==='moveTo'){const moved=await this.hooks.move(this.board.get(p.key),p.speed,p.tolerance);result=typeof moved==='string'?moved:moved?'success':'running';}
    else if(node.type==='lookAt'){await this.hooks.look(this.board.get(p.key));result='success';}
    else if(node.type==='event'){await this.hooks.event(p.event);result='success';}
    else if(node.type==='playAnimation'){await this.hooks.animation(p.clip);result='success';}
    else result=node.type==='succeed'?'success':'failure';this.status[id]=result;return result;
  };this.result=await execute(this.asset.root);return this.result;}
  stop(){this.running=false;this.memory.clear();this.status={};}
}
export class StateMachineRunner {
  constructor(asset,hooks){if(!validGameplayAsset('statemachine',asset))throw Error('상태 머신 검증 실패');this.asset=copy(asset);this.board=new Blackboard(asset.parameters);this.hooks=hooks;this.current=null;this.elapsed=0;this.events=new Set();this.running=true;}
  async enter(id){const next=this.asset.states.find(s=>s.id===id||s.name===id);if(!next)throw Error('상태가 없어요: '+id);const old=this.current;if(old?.onExit)await this.hooks.event(old.onExit);this.current=next;this.elapsed=0;if(next.clip)await this.hooks.animation(next.clip,next.loop);if(next.onEnter)await this.hooks.event(next.onEnter);}
  async tick(delta){if(!this.running)return;if(!this.current)await this.enter(this.asset.initial);this.elapsed+=delta;const state=this.current;if(state.onUpdate)await this.hooks.event(state.onUpdate);const transition=this.asset.transitions.find(t=>(t.from===state.id||t.from==='any')&&t.to!==state.id&&(!t.hasExitTime||this.elapsed/state.duration>=t.exitTime)&&(!t.event||this.events.has(t.event))&&t.conditions.every(c=>testCondition(c,this.board.get(c.key))));this.events.clear();if(transition)await this.enter(transition.to);}
  stop(){this.running=false;this.events.clear();}
}
export function gameplaySystems(hooks){
  const brains=new Map(),machines=new Map(),montages=new Map(),sequences=new Map();let generation=0;
  const binding=(vm,id)=>vm.bindings.find(b=>b.self===id)||{self:id,root:{components:[]}};
  const event=async(vm,id,name)=>{if(!name)return;const b=vm.bindings.find(b=>b.self===id);if(b)await vm.custom(b,name);};
  const load=async(name,kind)=>{const path=await hooks.asset(name,kind);if(!path)throw Error('에셋이 없어요: '+name);const value=await hooks.readAsset(path);if(!validGameplayAsset(kind,value))throw Error(kind+' 에셋 검증 실패');return copy(value);};
  const pawn=(vm,id)=>{const owner=vm.object(id);if(!owner)throw Error('AI 대상이 없어요: '+id);return vm.object(owner.pawn||enabledComponent(owner,'AIController')?.pawn)||owner;};
  const debug=(vm,id)=>{const o=vm.object(id);if(!o)return;o.gameplayDebug={...o.gameplayDebug,blackboard:brains.get(id)?.board.snapshot(),blackboardAsset:brains.get(id)?.asset.blackboard,behavior:brains.get(id)?{result:brains.get(id).result,status:copy(brains.get(id).status)}:null,state:machines.get(id)?.current?.name||'',parameters:machines.get(id)?.board.snapshot(),montage:montages.get(id)?{time:montages.get(id).time,section:montages.get(id).section,paused:montages.get(id).paused}:null,sequence:sequences.get(id)?{time:sequences.get(id).time,paused:sequences.get(id).paused}:null};};
  async function startBrain(id,name,vm){pawn(vm,id);const token=generation,data=await load(name,'behaviortree'),keys=data.blackboard?(await load(data.blackboard,'blackboard')).keys:[];if(token!==generation||!vm.active)throw Error('행동트리를 읽는 동안 월드가 종료됐어요.');const board=new Blackboard(keys);for(const n of data.nodes){const p=n.properties;if(['condition','set','moveTo','lookAt'].includes(n.type)){const type=board.types.get(p.key);if(!type)throw Error('블랙보드 키가 없어요: '+p.key);if(n.type==='set'&&!validBoardValue(type,p.value)||n.type==='condition'&&!['set','notSet'].includes(p.operator)&&!validBoardValue(type,p.value)||['moveTo','lookAt'].includes(n.type)&&!['object','vec3'].includes(type))throw Error('행동트리 키 자료형 오류: '+p.key);}}brains.get(id)?.stop();const runner=new BehaviorRunner(data,board,{
    move:async(value,speed,tolerance)=>{const o=pawn(vm,id),destination=typeof value==='string'?vm.object(value)&&sceneWorldPosition(vm.object(value),vm.objects):value;if(!o||!Array.isArray(destination))throw Error('Move To의 목표를 확인하세요.');if(enabledComponent(o,'NavigationAgent')){const state=o.gameplayDebug?.navigation;if(!state||JSON.stringify(state.destination)!==JSON.stringify(destination)){await hooks.operation('navigationMove',{target:o.id,destination},binding(vm,id),vm);o.gameplayDebug={...o.gameplayDebug,navigation:{...o.gameplayDebug?.navigation,destination}};}const status=(await hooks.operation('navigationStatus',{target:o.id},binding(vm,id),vm)).return;return status==='arrived'?'success':status==='failed'?'failure':'running';}const current=sceneWorldPosition(o,vm.objects),direction=destination.map((v,i)=>v-current[i]),distance=Math.hypot(...direction);if(distance<=tolerance)return true;const movement=enabledComponent(o,'CharacterMovement2D')||enabledComponent(o,'CharacterMovement')||enabledComponent(o,'PawnMovement');if(movement)hooks.physics(vm).movement(o,direction.map(v=>v/distance),speed/Math.max(.001,movement.speed));else{const step=Math.min(distance-tolerance,speed*data.interval);setSceneWorldPosition(o,current.map((v,i)=>v+direction[i]/distance*step),vm.objects);hooks.update(o);}return false;},
    look:async(value)=>{const o=pawn(vm,id),target=typeof value==='string'?vm.object(value)&&sceneWorldPosition(vm.object(value),vm.objects):value;if(!o||!Array.isArray(target))throw Error('Look At 목표 오류');const p=sceneWorldPosition(o,vm.objects);o.rotation[1]=Math.atan2(target[0]-p[0],target[2]-p[2])*180/Math.PI;hooks.update(o);},event:name=>event(vm,pawn(vm,id).id,name),animation:clip=>hooks.operation('playAnimation',{target:pawn(vm,id).id,clip,loop:false},binding(vm,id),vm)
  });brains.set(id,runner);debug(vm,id);}
  async function startMachine(id,name,vm){if(!vm.object(id))throw Error('상태 머신 대상이 없어요.');const token=generation,data=await load(name,'statemachine');if(token!==generation||!vm.active)throw Error('상태 머신을 읽는 동안 실행이 종료됐어요.');machines.get(id)?.stop();const runner=new StateMachineRunner(data,{event:name=>event(vm,id,name),animation:(clip,loop)=>hooks.operation('playAnimation',{target:id,clip,loop},binding(vm,id),vm)});machines.set(id,runner);await runner.enter(data.initial);debug(vm,id);}
  async function stopSequence(id,vm,restore=true){const state=sequences.get(id);if(!state)return;
    for(const track of state.data.tracks){if(track.type==='animation'&&vm.object(track.target||id))await hooks.operation('stopAnimation',{target:track.target||id},binding(vm,id),vm);if(track.type==='audio')for(const clip of track.clips)await hooks.operation('stopSound',{sound:clip.clip},binding(vm,id),vm);}
    if(restore&&state.data.restoreState){for(const [objectId,values] of state.original){const o=vm.object(objectId);if(o){Object.assign(o,copy(values));hooks.update(o);}}for(const effect of state.effects)if(vm.object(effect.target))await hooks.operation(effect.type==='light'?'lightIntensity':'materialFloat',{target:effect.target,value:effect.value,parameter:effect.parameter},binding(vm,id),vm);vm.core.scale=state.originalScale;vm.sequenceCamera=state.originalCamera;}
    sequences.delete(id);debug(vm,id);
  }
  async function operation(key,a,b,vm){const id=a.target??b.self;
    if(key==='runBehaviorTree'){await startBrain(id,a.asset,vm);return {};}
    if(key==='stopBehaviorTree'){brains.get(id)?.stop();brains.delete(id);debug(vm,id);return {};}
    if(key.startsWith('blackboard')){const board=brains.get(id)?.board;if(!board)throw Error('실행 중인 블랙보드가 없어요.');if(key==='blackboardClear')board.clear(a.key);else{const type={Bool:'bool',Float:'float',Int:'int',String:'string',Vector:'vec3',Object:'object'}[key.replace(/^blackboard(?:Set|Get)/,'')];if(!type||board.types.get(a.key)!==type)throw Error('블랙보드 함수 자료형 오류: '+a.key);if(key.startsWith('blackboardSet'))board.set(a.key,a.value);else return {return:board.get(a.key)};}debug(vm,id);return {};}
    if(key==='startStateMachine'){await startMachine(id,a.asset,vm);return {};}
    if(['stateSetFloat','stateSetBool','stateSetString','stateGet','stateEvent','stateJump','stateStop'].includes(key)){const runner=machines.get(id);if(!runner)throw Error('상태 머신이 실행 중이 아니에요.');if(key==='stateGet')return {return:runner.current?.name||''};if(key==='stateEvent')runner.events.add(a.event);else if(key==='stateJump')await runner.enter(a.state);else if(key==='stateStop'){runner.stop();machines.delete(id);}else{const type={stateSetFloat:'float',stateSetBool:'bool',stateSetString:'string'}[key];if(type!==runner.board.types.get(a.key))throw Error('상태 파라미터 자료형 오류');runner.board.set(a.key,a.value);}debug(vm,id);return {};}
    if(key==='playMontage'){if(!vm.object(id))throw Error('몽타주 대상이 없어요.');const token=generation,data=await load(a.asset,'montage');if(token!==generation||!vm.active)throw Error('몽타주를 읽는 동안 실행이 종료됐어요.');if(a.section&&!data.sections.some(s=>s.name===a.section))throw Error('몽타주 섹션이 없어요.');if(!data.clips.length||data.clips.some(c=>!c.clip))throw Error('몽타주에 클립을 지정하세요.');if(data.clips.some((c,i)=>data.clips.some((other,j)=>j>i&&c.start<other.start+other.duration&&other.start<c.start+c.duration)))throw Error('동시에 재생하는 몽타주 슬롯은 아직 지원하지 않아요.');const section=data.sections.find(s=>s.name===a.section)||[...data.sections].sort((a,b)=>a.time-b.time)[0];montages.set(id,{data,time:section.time,section:section.name,paused:false,active:new Map(),next:new Map(),initial:true});debug(vm,id);return {};}
    if(['montageStop','montagePause','montageJump','montageNext','montagePosition','montageSeek'].includes(key)){const state=montages.get(id);if(key==='montagePosition')return {return:state?.time||0};if(!state)throw Error('재생 중인 몽타주가 없어요.');if(key==='montageStop'){await hooks.operation('stopAnimation',{target:id},binding(vm,id),vm);montages.delete(id);}else if(key==='montagePause')state.paused=a.paused;else if(key==='montageSeek'){if(!Number.isFinite(a.time)||a.time<0||a.time>state.data.length)throw Error('몽타주 시간 범위 오류');state.time=a.time;state.section=[...state.data.sections].filter(s=>s.time<=a.time).sort((a,b)=>b.time-a.time)[0].name;state.initial=false;}else if(key==='montageNext'){if(!state.data.sections.some(s=>s.name===a.section)||a.next&&!state.data.sections.some(s=>s.name===a.next))throw Error('몽타주 섹션 이름 오류');state.next.set(a.section,a.next);}else{const section=state.data.sections.find(s=>s.name===a.section);if(!section)throw Error('몽타주 섹션이 없어요.');state.section=section.name;state.time=section.time;state.active.clear();state.initial=true;}debug(vm,id);return {};}
    if(key==='playSequence'){if(!vm.object(id))throw Error('시퀀스 소유자가 없어요.');const token=generation,data=await load(a.asset,'sequenceasset');if(token!==generation||!vm.active)throw Error('시퀀스를 읽는 동안 실행이 종료됐어요.');
      const original=new Map(),effects=[];for(const track of data.tracks){const o=vm.object(track.target||id);if(!o)throw Error('시퀀스 대상이 없어요: '+track.target);original.set(o.id,{position:copy(o.position),rotation:copy(o.rotation),scale:copy(o.scale),visible:o.visible});if(['light','material'].includes(track.type)){const value=hooks.captureParameter?.(o.id,track.type,track.name);if(!Number.isFinite(value))throw Error('시퀀스 렌더 파라미터를 확인하세요: '+track.name);effects.push({target:o.id,type:track.type,parameter:track.name,value});}if(track.type==='camera')for(const key of track.keys)if(key.value&&!enabledComponent(vm.object(key.value)||{kind:'empty'},'Camera'))throw Error('카메라 키의 대상을 확인하세요.');if(track.clips.some(c=>!c.clip))throw Error('시퀀스 클립을 지정하세요.');}
      await stopSequence(id,vm);original.clear();effects.length=0;for(const track of data.tracks){const o=vm.object(track.target||id);original.set(o.id,{position:copy(o.position),rotation:copy(o.rotation),scale:copy(o.scale),visible:o.visible});if(['light','material'].includes(track.type))effects.push({target:o.id,type:track.type,parameter:track.name,value:hooks.captureParameter(o.id,track.type,track.name)});}sequences.set(id,{data,time:0,paused:false,original,effects,originalScale:vm.core.scale,originalCamera:vm.sequenceCamera,active:new Map(),initial:true});debug(vm,id);return {};}
    if(['sequenceStop','sequencePause','sequenceSeek','sequencePosition'].includes(key)){const state=sequences.get(id);if(key==='sequencePosition')return {return:state?.time||0};if(!state)throw Error('재생 중인 시퀀스가 없어요.');if(key==='sequenceStop')await stopSequence(id,vm);else if(key==='sequencePause')state.paused=a.paused;else{if(!Number.isFinite(a.time)||a.time<0||a.time>state.data.length)throw Error('시퀀스 시간 범위 오류');state.time=a.time;state.seek=true;state.active.clear();}debug(vm,id);return {};}
  }
  const sample=(keys,time)=>{const sorted=[...keys].sort((a,b)=>a.time-b.time);if(!sorted.length)return undefined;let a=sorted[0],z=sorted.at(-1);for(let i=1;i<sorted.length;i++)if(time<=sorted[i].time){a=sorted[i-1];z=sorted[i];break;}if(time<=a.time||typeof a.value!=='number'&&!Array.isArray(a.value))return copy(a.value);const alpha=Math.max(0,Math.min(1,(time-a.time)/Math.max(.000001,z.time-a.time)));return Array.isArray(a.value)?a.value.map((v,i)=>v+(z.value[i]-v)*alpha):a.value+(z.value-a.value)*alpha;};
  async function tick(delta,vm){
    for(const [id,runner] of brains){const object=vm.object(id);if(!object||object.components?.some(c=>c.type==='BehaviorTree'&&c.properties?.enabled===false))continue;await runner.tick(delta);debug(vm,id);}
    for(const [id,runner] of machines){if(!vm.object(id))continue;await runner.tick(delta);debug(vm,id);}
    for(const [id,state] of [...montages]){
      let remaining=state.paused?0:delta*state.data.rate,finished=false,budget=256;const ordered=[...state.data.sections].sort((a,b)=>a.time-b.time);
      do{if(--budget<0)throw Error('몽타주 섹션 반복 한도 초과');const section=ordered.find(s=>s.name===state.section),end=ordered.find(s=>s.time>section.time)?.time??state.data.length,prev=state.time,step=Math.min(remaining,end-prev);state.time+=step;remaining-=step;
        for(const notify of state.data.notifies)if(notify.time>prev&&notify.time<=state.time||state.initial&&notify.time===prev)await event(vm,id,notify.event);state.initial=false;
        if(state.time<end)break;const next=state.next.get(section.name)??section.next;if(next||state.data.loop){const destination=next?ordered.find(s=>s.name===next):ordered[0];state.section=destination.name;state.time=destination.time;state.initial=true;}else{finished=true;break;}
      }while(remaining>0);
      if(finished){await hooks.operation('stopAnimation',{target:id},binding(vm,id),vm);montages.delete(id);await event(vm,id,'OnMontageCompleted');debug(vm,id);continue;}
      // ponytail: the current animation renderer has one full-body slot per actor; reject concurrent slots until bone masks/mixing are available.
      const active=state.data.clips.filter(c=>c.start<=state.time&&c.start+c.duration>state.time);if(active.length>1)throw Error('동시에 재생하는 몽타주 슬롯은 아직 지원하지 않아요.');
      const clip=active[0];if(clip){if(state.active.get('clip')!==clip.id){await hooks.operation('playAnimation',{target:id,clip:clip.clip,loop:false},binding(vm,id),vm);state.active.set('clip',clip.id);}await hooks.sampleAnimation?.(id,clip.sourceStart+(state.time-clip.start)*clip.rate);}else if(state.active.size){await hooks.operation('stopAnimation',{target:id},binding(vm,id),vm);state.active.clear();}debug(vm,id);
    }
    for(const [id,state] of [...sequences]){const prev=state.time,ranges=[];let remaining=state.seek||state.paused?0:delta*state.data.rate,budget=256,finished=false;
      do{if(--budget<0)throw Error('시퀀스 반복 한도 초과');const begin=state.time,step=Math.min(remaining,state.data.length-begin);state.time+=step;remaining-=step;ranges.push({begin,end:state.time,initial:state.initial});state.initial=false;if(state.time<state.data.length)break;if(state.data.loop&&remaining>0){state.time=0;state.initial=true;state.active.clear();}else{finished=!state.data.loop;break;}}while(remaining>0);
      const b=binding(vm,id);for(const track of state.data.tracks){const o=vm.object(track.target||id);if(!o)continue;const value=sample(track.keys,state.time);if(['position','rotation','scale','visible'].includes(track.type)&&value!==undefined){o[track.type]=value;hooks.update(o);}if(track.type==='camera'&&value!==undefined)vm.sequenceCamera=value||null;if(track.type==='timeScale'&&value!==undefined)vm.core.scale=value;if(track.type==='light'&&value!==undefined)await hooks.operation('lightIntensity',{target:o.id,value},b,vm);if(track.type==='material'&&value!==undefined)await hooks.operation('materialFloat',{target:o.id,parameter:track.name,value},b,vm);
        if(track.type==='event'&&!state.seek&&!state.paused)for(const range of ranges)for(const key of track.keys)if(key.time>range.begin&&key.time<=range.end||range.initial&&key.time===range.begin)await event(vm,o.id,key.value);
        const clip=track.clips.find(c=>c.start<=state.time&&c.start+c.duration>state.time);if(clip){if(state.active.get(track.id)!==clip.id){await hooks.operation(track.type==='audio'?'playSoundAt':'playAnimation',track.type==='audio'?{sound:clip.clip,position:sceneWorldPosition(o,vm.objects),volume:1}:{target:o.id,clip:clip.clip,loop:false},b,vm);state.active.set(track.id,clip.id);}const time=clip.sourceStart+(state.time-clip.start)*clip.rate;if(track.type==='animation')await hooks.sampleAnimation?.(o.id,time);if(track.type==='audio')await hooks.sampleAudio?.(clip.clip,time,state.paused);}else if(state.active.has(track.id)){await hooks.operation(track.type==='audio'?'stopSound':'stopAnimation',track.type==='audio'?{sound:track.clips.find(c=>c.id===state.active.get(track.id)).clip}:{target:o.id},b,vm);state.active.delete(track.id);}}
      state.seek=false;debug(vm,id);if(finished){await stopSequence(id,vm);await event(vm,id,'OnSequenceCompleted');}else if(state.time>=state.data.length&&state.data.loop){state.time=0;state.initial=true;state.active.clear();}
    }
  }

  return {operation,tick,perception(id,targets,vm){const board=brains.get(id)?.board,p=vm.object(id)&&enabledComponent(vm.object(id),'AIPerception');if(!board||!p)return;for(const [key,type,value] of [[p.targetKey,'object',targets[0]?.id||null],[p.sensedKey,'bool',targets.length>0]]){if(!key)continue;if(board.types.get(key)!==type)throw Error('감지 블랙보드 키 자료형 오류: '+key);if(JSON.stringify(board.get(key))!==JSON.stringify(value))board.set(key,value);}debug(vm,id);},async remove(id,vm){brains.get(id)?.stop();brains.delete(id);machines.get(id)?.stop();machines.delete(id);montages.delete(id);await stopSequence(id,vm);},async start(vm,owner){for(const object of vm.objects){if(owner&&object.id!==owner)continue;const tree=enabledComponent(object,'BehaviorTree'),fsm=enabledComponent(object,'StateMachine'),montage=enabledComponent(object,'MontagePlayer'),sequence=enabledComponent(object,'SequencePlayer');if(tree?.asset&&tree.autoStart)await startBrain(object.id,tree.asset,vm);if(fsm?.asset&&fsm.autoStart)await startMachine(object.id,fsm.asset,vm);if(montage?.asset&&montage.autoPlay)await operation('playMontage',{target:object.id,asset:montage.asset,section:montage.section},binding(vm,object.id),vm);if(sequence?.asset&&sequence.autoPlay)await operation('playSequence',{target:object.id,asset:sequence.asset},binding(vm,object.id),vm);}},dispose(){generation++;for(const runner of brains.values())runner.stop();for(const runner of machines.values())runner.stop();brains.clear();machines.clear();montages.clear();sequences.clear();}};
}
