import {materialDefaults,surfaceInputs,materialFunctionTypes,materialLayerParameters,newMaterialLayer,materialCatalog,makeMaterialNode,makeMaterialFunctionCall,materialPortName,refreshMaterialFunctionCall,materialPins,normalizedMaterialEdges,connectMaterial,disconnectMaterial,removeMaterialNodes,copyMaterialNodes,pasteMaterialNodes,validMaterialGraph,validMaterialSurface} from './material-runtime.js';
import {icon} from './icons.js';
import {validAsset} from './asset-documents.js';
import {materialLayersFields,editMaterialLayers} from './material-layers-ui.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const editable=target=>target.closest('input,textarea,select');
let copiedNodes=null;
export class MaterialEditor {
  get document(){return this.element.ownerDocument||globalThis.document;}
  constructor(element,getDocument,hooks={}){
    this.element=element;this.getDocument=getDocument;this.hooks=hooks;this.selected=new Set();this.pan={x:20,y:20};this.zoom=1;this.pending=null;this.listeners=[];element.classList.add('material-graph-editor');element.tabIndex=0;
    const listen=(name,callback,options)=>{element.addEventListener(name,callback,options);this.listeners.push(()=>element.removeEventListener(name,callback,options));};
    listen('pointerdown',event=>this.pointerDown(event));listen('click',event=>this.click(event));listen('change',event=>this.change(event));listen('contextmenu',event=>{event.preventDefault();event.stopPropagation();if(this.moved){this.moved=false;return;}this.menu(event);});
    listen('wheel',event=>{event.preventDefault();event.stopPropagation();const rect=element.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,next=Math.max(.25,Math.min(2,this.zoom*(event.deltaY<0?1.1:1/1.1)));this.pan={x:x-(x-this.pan.x)*next/this.zoom,y:y-(y-this.pan.y)*next/this.zoom};this.zoom=next;this.transform();this.saveView();},{passive:false});
    listen('dragover',event=>{if(event.dataTransfer.types.includes('application/x-hb-assets')){event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect='copy';}});listen('drop',event=>{const raw=event.dataTransfer.getData('application/x-hb-assets');if(!raw)return;event.preventDefault();event.stopPropagation();try{if(raw.length>1048576)throw Error('에셋 드래그 데이터를 확인하세요.');const files=JSON.parse(raw);if(!Array.isArray(files))throw Error('에셋 드래그 데이터를 확인하세요.');const rect=element.getBoundingClientRect();this.dropAssets(files,{x:(event.clientX-rect.left-this.pan.x)/this.zoom,y:(event.clientY-rect.top-this.pan.y)/this.zoom}).catch(e=>this.hooks.error?.(e.message));}catch(e){this.hooks.error?.(e.message);}});
    listen('keydown',event=>this.keydown(event));this.observer=new ResizeObserver(()=>this.drawWires());this.observer.observe(element);this.render();
  }
  get doc(){return this.getDocument();}get graph(){return ['material','materialfunction','materiallayer','materialblend'].includes(this.doc?.kind)?this.doc.data.graph:null;}
  saveView(){this.doc.view.material={pan:{...this.pan},zoom:this.zoom,selection:[...this.selected]};this.hooks.view?.();}
  render(){
    const doc=this.doc;if(!doc?.data.graph)return;if(this.owner!==doc.path){this.owner=doc.path;const view=doc.view.material||{};this.pan=view.pan||{x:20,y:20};this.zoom=view.zoom||1;this.selected=new Set(view.selection||[]);this.pending=null;}
    this.element.innerHTML='<div class="material-graph-plane"><svg class="node-wires" aria-hidden="true"></svg><div class="graph-nodes"></div></div><div class="material-selection-box" hidden></div>';
    this.element.querySelector('.graph-nodes').innerHTML=this.graph.nodes.map(node=>{const pins=materialPins(node,this.graph),x=node.px??(Math.abs(node.x)<2?node.x*(Math.max(this.element.clientWidth,700)-220):node.x);const inputs=pins.inputs.map(pin=>`<div class="pin-row"><button class="pin in" data-material-pin="in" data-node-id="${node.id}" data-pin-id="${pin.id}" data-pin-type="${pin.type}" title="${esc(pin.label+' · '+pin.type+(pin.useDefault===false?' · 필수 입력':'')+(pin.description?' · '+pin.description:''))}" aria-label="${esc(pin.label+' 입력')}"></button><span>${esc(pin.label)}${pin.useDefault===false?' *':''}</span>${this.inputField(node,pin)}</div>`).join(''),outputs=pins.outputs.map(pin=>`<div class="pin-row output"><span>${esc(pin.label)}</span><small>${pin.type}</small><button class="pin out" data-material-pin="out" data-node-id="${node.id}" data-pin-id="${pin.id}" data-pin-type="${pin.type}" title="${esc(pin.label+' · '+pin.type+(pin.useDefault===false?' · 필수 입력':'')+(pin.description?' · '+pin.description:''))}" aria-label="${esc(pin.label+' 출력')}"></button></div>`).join('');return `<div class="graph-node material-node ${node.kind} ${this.selected.has(node.id)?'selected':''}" data-material-node="${node.id}" style="left:${x}px;top:${node.y}px"><div class="node-title" title="${esc(node.description||node.title)}">${icon(node.kind==='output'?'material':'nodes')}<strong>${esc(['functionInput','functionOutput'].includes(node.key)?node.portName:node.title.split(' · ')[0])}</strong></div><div class="node-body">${this.nodeField(node)}${inputs}${outputs}</div></div>`;}).join('');this.transform();this.document.defaultView.requestAnimationFrame(()=>this.drawWires());this.saveView();this.hooks.select?.(this.graph.nodes.find(n=>this.selected.has(n.id)));
  }
  inputField(node,pin){if(pin.type==='attributes'||node.kind==='output'||this.edges().some(edge=>edge.to.node===node.id&&edge.to.pin===pin.id))return '';const value=node.inputValues?.[pin.id]??this.defaultPinValue(node,pin);if(value===undefined)return '';const required=pin.useDefault===false&&!Object.hasOwn(node.inputValues||{},pin.id),field=(v,i)=>`<input class="material-pin-value" type="number" step=".05" ${required?'placeholder="'+v+'"':'value="'+v+'"'} data-material-input="${pin.id}" ${i===undefined?'':'data-axis="'+i+'"'} aria-label="${esc(pin.label)} ${i===undefined?'값':'XYZW'[i]}">`;return (Array.isArray(value)?'<div class="material-vector-input">'+value.map(field).join('')+'</div>':field(value))+(node.key==='functionCall'&&Object.hasOwn(node.inputValues||{},pin.id)?`<button data-material-reset="${pin.id}" title="입력 기본값 복원" aria-label="${esc(pin.label)} 기본값 복원">${icon('undo')}</button>`:'');}

  defaultPinValue(node,pin){if(pin.value!==undefined)return pin.value;if(!['makeAttributes','setAttributes'].includes(node.key))return;const p=surfaceInputs.find(p=>p.id===pin.id),v=(this.doc.data.surface||materialDefaults)[p?.key];return typeof v==='string'?[1,3,5].map(i=>{const c=parseInt(v.slice(i,i+2),16)/255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4;}):v;}
  nodeField(node,details=false){
    if(node.body==='color')return `<input type="color" value="${this.doc.data.surface.color}" data-material-surface="color" aria-label="기본 색상">`;if(node.body==='rough')return `<input type="number" min="0" max="1" step=".01" value="${this.doc.data.surface.roughness}" data-material-surface="roughness" aria-label="거칠기">`;
    let fields=node.parameter!==undefined?`<label class="material-node-field"><span>이름</span><input value="${esc(node.parameter)}" data-material-property="parameter" aria-label="파라미터 이름"></label>`:'';
    if(details&&['functionInput','functionOutput'].includes(node.key)){fields+=`<label class="material-node-field"><span>이름</span><input value="${esc(node.portName)}" data-material-property="portName"></label><label class="material-node-field"><span>자료형</span><select data-material-property="valueType" ${this.doc.data.domain?'disabled':''}>${materialFunctionTypes.map(t=>`<option ${t===node.valueType?'selected':''}>${t}</option>`).join('')}</select></label><label class="material-node-field"><span>순서</span><input type="number" step="1" value="${node.priority}" data-material-property="priority"></label><label class="material-node-field"><span>설명</span><input value="${esc(node.description)}" data-material-property="description"></label>`;if(node.key==='functionInput')fields+=`<label class="material-node-field"><input type="checkbox" ${node.useDefault?'checked':''} data-material-property="useDefault">기본값 사용</label>`;}
    if(node.key==='functionCall')fields+=`<div class="material-node-field" title="${esc(node.asset)}">${esc(node.asset.split('/').at(-1))}<button data-material-function-open="${node.id}">열기</button><button data-material-function-refresh="${node.id}">핀 갱신</button></div>`;
    if(details&&node.key==='surface')fields+=`<label><input type="checkbox" data-material-property="useAttributes" ${node.useAttributes?'checked':''}>표면 속성 묶음 사용</label>`;
    if(details&&['setAttributes','getAttributes'].includes(node.key))fields+=surfaceInputs.map(p=>`<label class="material-attribute-choice"><input type="checkbox" data-material-attribute="${p.id}" ${node.fields.includes(p.id)?'checked':''}>${esc(p.label)}</label>`).join('');
    if(details&&node.key==='blendAttributes')fields+=`<label><input type="checkbox" data-material-property="normalizeNormal" ${node.normalizeNormal?'checked':''}>노멀 정규화</label>`;
    if(node.key==='layerStack'){if(details){this.loadLayerParameters();fields+=materialLayersFields(node.layers,this.hooks.files?.()||[],this.doc.view.layerParameters?.items||[]);}else fields+=`<small>${node.layers.filter(l=>l.enabled).length} 레이어</small>`;}
    if(node.key==='texture'){const files=(this.hooks.files?.()||[]).filter(file=>file.kind==='texture');fields+=`<label class="material-node-field"><span>텍스처</span><select data-material-property="texture"><option value="">없음</option>${[...files,...(node.texture&&!files.some(file=>file.path===node.texture)?[{path:node.texture,name:node.texture}]:[])].map(file=>`<option value="${esc(file.path)}" ${file.path===node.texture?'selected':''}>${esc(file.name)}</option>`).join('')}</select></label><label class="material-node-field"><span>색 공간</span><select data-material-property="colorSpace"><option value="srgb" ${node.colorSpace==='srgb'?'selected':''}>sRGB · 색상</option><option value="linear" ${node.colorSpace==='linear'?'selected':''}>Linear · 데이터</option></select></label><label class="material-node-field"><span>반복</span><select data-material-property="wrap"><option value="repeat" ${node.wrap==='repeat'?'selected':''}>Repeat</option><option value="clamp" ${node.wrap==='clamp'?'selected':''}>Clamp</option></select></label>`;}
    if(node.value!==undefined&&typeof node.value!=='object'||Array.isArray(node.value))fields+=Array.isArray(node.value)?`<div class="material-vector-input">${node.value.map((v,i)=>`<input type="number" step=".05" value="${v}" data-material-property="value" data-axis="${i}" aria-label="${'XYZW'[i]} 값">`).join('')}</div>`:`<input type="${typeof node.value==='string'?'color':'number'}" value="${esc(node.value)}" step=".01" data-material-property="value" aria-label="노드 값">`;return fields;
  }
  edges(){return normalizedMaterialEdges(this.graph);}
  setZoom(next){next=Math.max(.25,Math.min(2,next));const x=this.element.clientWidth/2,y=this.element.clientHeight/2;this.pan={x:x-(x-this.pan.x)*next/this.zoom,y:y-(y-this.pan.y)*next/this.zoom};this.zoom=next;this.transform();this.saveView();}
  transform(){const label=this.element.parentElement?.querySelector('[data-action=material-zoom-reset]');if(label)label.textContent=Math.round(this.zoom*100)+'%';const plane=this.element.querySelector('.material-graph-plane');if(plane)plane.style.transform=`translate(${this.pan.x}px,${this.pan.y}px) scale(${this.zoom})`;}
  drawWires(){if(!this.graph)return;const plane=this.element.querySelector('.material-graph-plane');if(!plane)return;const base=plane.getBoundingClientRect(),svg=plane.querySelector('.node-wires');let width=1500,height=1000;svg.innerHTML=this.edges().map(edge=>{const from=plane.querySelector(`[data-node-id="${edge.from.node}"][data-material-pin="out"][data-pin-id="${edge.from.pin}"]`),to=plane.querySelector(`[data-node-id="${edge.to.node}"][data-material-pin="in"][data-pin-id="${edge.to.pin}"]`);if(!from||!to)return '';const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=(a.left+a.width/2-base.left)/this.zoom,y1=(a.top+a.height/2-base.top)/this.zoom,x2=(b.left+b.width/2-base.left)/this.zoom,y2=(b.top+b.height/2-base.top)/this.zoom,bend=Math.max(50,Math.abs(x2-x1)*.45);width=Math.max(width,x1+100,x2+100);height=Math.max(height,y1+100,y2+100);return `<path d="M${x1} ${y1} C${x1+bend} ${y1},${x2-bend} ${y2},${x2} ${y2}" fill="none" stroke="#8eb59f" stroke-width="2"/>`;}).join('');svg.setAttribute('width',width);svg.setAttribute('height',height);svg.style.width=width+'px';svg.style.height=height+'px';}
  mutate(change){const next=structuredClone(this.doc.data);if(change(next)===false)return;if(next.previewOutput&&!next.graph.nodes.some(n=>n.key==='functionOutput'&&n.id===next.previewOutput))delete next.previewOutput;if(!validAsset(this.doc.kind,next)){this.hooks.error?.('머테리얼 값을 확인하세요.');this.render();return false;}this.hooks.before?.();this.doc.data=next;this.hooks.change?.();this.render();return true;}
  click(event){
    const layer=event.target.closest('[data-layer-action],[data-layer-open]');if(layer){event.stopPropagation();if(layer.dataset.layerOpen){this.hooks.openAsset?.(layer.dataset.layerOpen);return;}const id=layer.closest('[data-material-node]')?.dataset.materialNode;this.mutate(d=>editMaterialLayers(d.graph.nodes.find(n=>n.id===id)?.layers||[],layer,this.doc.view.layerParameters?.items||[]));return;}
    const reset=event.target.closest('[data-material-reset]');if(reset){event.stopPropagation();const id=reset.closest('[data-material-node]').dataset.materialNode;this.mutate(d=>delete d.graph.nodes.find(n=>n.id===id).inputValues[reset.dataset.materialReset]);return;}
    const action=event.target.closest('[data-material-function-open],[data-material-function-refresh]');if(action){event.stopPropagation();const id=action.dataset.materialFunctionOpen||action.dataset.materialFunctionRefresh,n=this.graph.nodes.find(n=>n.id===id);if(action.hasAttribute('data-material-function-open'))this.hooks.openAsset?.(n.asset);else this.refreshFunction(n).catch(e=>this.hooks.error?.(e.message));return;}
    const button=event.target.closest('[data-material-pin]');if(!button)return;event.preventDefault();event.stopPropagation();const direction=button.dataset.materialPin,node=button.dataset.nodeId,pin=button.dataset.pinId;
    if(event.altKey){this.mutate(data=>disconnectMaterial(data.graph,node,pin,direction==='out'?'from':'to'));return;}
    if(!this.pending||this.pending.direction===direction){this.pending={node,pin,direction};this.element.querySelectorAll('.pin.pending').forEach(p=>p.classList.remove('pending'));button.classList.add('pending');return;}
    const endpoint={node,pin},other={node:this.pending.node,pin:this.pending.pin};this.link(direction==='in'?other:endpoint,direction==='in'?endpoint:other);
  }
  link(from,to){this.mutate(data=>{const result=connectMaterial(data.graph,from,to);if(!result.ok){this.hooks.error?.(result.reason);return false;}});this.pending=null;}
  change(event){const input=event.target,node=this.graph.nodes.find(node=>node.id===input.closest('[data-material-node]')?.dataset.materialNode);if(!node)return;event.stopPropagation();this.mutate(data=>{const next=data.graph.nodes.find(value=>value.id===node.id),value=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;if(input.closest('.material-layer-stack'))return editMaterialLayers(next.layers,input,this.doc.view.layerParameters?.items||[]);if(input.dataset.materialAttribute){const field=input.dataset.materialAttribute;if(input.checked)next.fields.push(field);else{next.fields=next.fields.filter(f=>f!==field);delete next.inputValues[field];data.graph.edges=normalizedMaterialEdges(data.graph).filter(e=>!(e.to.node===next.id&&e.to.pin===field)||next.key==='getAttributes').filter(e=>!(e.from.node===next.id&&e.from.pin===field)||next.key==='setAttributes');}return;}if(input.dataset.materialSurface){data.surface[input.dataset.materialSurface]=value;return;}if(input.dataset.materialInput){const key=input.dataset.materialInput;next.inputValues??={};if(input.dataset.axis!==undefined){const pin=materialPins(next,data.graph).inputs.find(pin=>pin.id===key);next.inputValues[key]=[...(next.inputValues[key]||this.defaultPinValue(next,pin))];next.inputValues[key][Number(input.dataset.axis)]=value;}else next.inputValues[key]=value;}else if(input.dataset.materialProperty){if(input.dataset.axis!==undefined)next.value[Number(input.dataset.axis)]=value;else{if(input.dataset.materialProperty==='useAttributes'){this.toggleAttributes(data,next,value);return;}next[input.dataset.materialProperty]=value;if(input.dataset.materialProperty==='valueType'){if(next.key==='functionInput')next.value=value==='attributes'?{}:value==='float'?0:Array(Number(value.slice(3))).fill(0);next.inputValues={};data.graph.edges=normalizedMaterialEdges(data.graph).filter(e=>e.from.node!==next.id&&e.to.node!==next.id);}}}});}
  toggleAttributes(data,node,enabled){
    const wires=normalizedMaterialEdges(data.graph);node.useAttributes=enabled;
    if(enabled){const make=makeMaterialNode('makeAttributes',(node.px??this.element.querySelector('[data-material-node="'+node.id+'"]')?.offsetLeft??node.x)-330,node.y);make.inputValues=structuredClone(node.inputValues||{});node.inputValues={};data.graph.nodes.push(make);data.graph.edges=wires.map(e=>e.to.node===node.id?{from:e.from,to:{node:make.id,pin:e.to.pin}}:e);data.graph.edges.push({from:{node:make.id,pin:'value'},to:{node:node.id,pin:'attributes'}});}
    else{const split=makeMaterialNode('breakAttributes',(node.px??this.element.querySelector('[data-material-node="'+node.id+'"]')?.offsetLeft??node.x)-330,node.y),edge=wires.find(e=>e.to.node===node.id&&e.to.pin==='attributes');if(node.inputValues?.attributes)split.inputValues.attributes=structuredClone(node.inputValues.attributes);node.inputValues={};data.graph.nodes.push(split);data.graph.edges=wires.filter(e=>e.to.node!==node.id);if(edge)data.graph.edges.push({from:edge.from,to:{node:split.id,pin:'attributes'}});for(const p of surfaceInputs)data.graph.edges.push({from:{node:split.id,pin:p.id},to:{node:node.id,pin:p.id}});}
  }
  loadLayerParameters(){const doc=this.doc,stacks=()=>Object.fromEntries(doc.data.graph.nodes.filter(n=>n.key==='layerStack').map(n=>[n.id,n.layers])),key=()=>JSON.stringify([doc.view.materialEpoch||0,stacks()]),signature=key();if(!this.hooks.readAsset||doc.view.layerParameters?.signature===signature||doc.view.layerLoading===signature)return;doc.view.layerLoading=signature;materialLayerParameters(stacks(),this.hooks.readAsset).then(items=>{if(this.doc!==doc||key()!==signature)return;doc.view.layerParameters={signature,items};this.hooks.select?.();}).catch(e=>{if(this.doc!==doc||key()!==signature)return;doc.view.layerParameters={signature,items:[]};this.hooks.error?.(e.message);}).finally(()=>{if(doc.view.layerLoading===signature)delete doc.view.layerLoading;});}
  async dropAssets(files,position){const functions=files.filter(f=>f?.kind==='materialfunction'),layers=files.filter(f=>f?.kind==='materiallayer');if(layers.length){if(this.graph.mode==='function')throw Error('레이어 스택은 기본 머테리얼에 추가하세요.');const selected=this.graph.nodes.find(n=>n.key==='layerStack'&&this.selected.has(n.id));const node=selected||makeMaterialNode('layerStack',position.x,position.y);if(this.mutate(d=>{let stack=d.graph.nodes.find(n=>n.id===node.id);if(!stack){stack=node;d.graph.nodes.push(stack);}stack.layers.push(...layers.map(f=>newMaterialLayer(f.path,f.name||f.path.split('/').at(-1))));const link=!selected&&this.spawnLink(d.graph,stack);if(link)connectMaterial(d.graph,link.from,link.to);}))this.selected=new Set([node.id]);this.render();}if(functions.length)await this.addFunctions(functions,position);}
  pointerDown(event){
    if(editable(event.target))return;const source=event.target.closest('[data-material-pin]');if(source&&event.button===0&&!event.altKey){
      event.stopPropagation();const start={x:event.clientX,y:event.clientY};let dragged=false;
      const move=e=>{if(Math.hypot(e.clientX-start.x,e.clientY-start.y)<5)return;if(!dragged)this.pending={node:source.dataset.nodeId,pin:source.dataset.pinId,direction:source.dataset.materialPin};dragged=true;const base=this.element.querySelector('.material-graph-plane').getBoundingClientRect(),a=source.getBoundingClientRect(),x1=(a.left+a.width/2-base.left)/this.zoom,y1=(a.top+a.height/2-base.top)/this.zoom,x2=(e.clientX-base.left)/this.zoom,y2=(e.clientY-base.top)/this.zoom;this.element.querySelector('.pending-material-wire')?.remove();this.element.querySelector('.node-wires').insertAdjacentHTML('beforeend',`<path class="pending-material-wire" d="M${x1} ${y1} C${x1+60} ${y1},${x2-60} ${y2},${x2} ${y2}" fill="none" stroke="#a8ceb5" stroke-width="2"/>`);};
      const finish=e=>{this.document.removeEventListener('pointermove',move);this.document.removeEventListener('pointerup',finish);this.document.removeEventListener('pointercancel',finish);this.element.querySelector('.pending-material-wire')?.remove();if(e.type==='pointercancel'){this.pending=null;return;}if(!dragged)return;
        const stop=e=>{e.preventDefault();e.stopImmediatePropagation();};this.document.addEventListener('click',stop,{capture:true,once:true});setTimeout(()=>this.document.removeEventListener('click',stop,true),250);
        const element=this.document.elementFromPoint(e.clientX,e.clientY),target=element?.closest('[data-material-pin]');if(target&&this.element.contains(target)&&target.dataset.materialPin!==source.dataset.materialPin)this.click({target,preventDefault(){},stopPropagation(){}});else if(this.element.contains(element))this.menu({target:element,clientX:e.clientX,clientY:e.clientY});else this.pending=null;
      };this.document.addEventListener('pointermove',move);this.document.addEventListener('pointerup',finish);this.document.addEventListener('pointercancel',finish);return;
    }if(event.target.closest('[data-material-pin]'))return;event.stopPropagation();this.element.focus();const nodeElement=event.target.closest('[data-material-node]'),node=nodeElement&&this.graph.nodes.find(node=>node.id===nodeElement.dataset.materialNode),start={x:event.clientX,y:event.clientY},pan={...this.pan};this.moved=false;
    const panning=event.button===1||event.button===2;if(event.button!==0&&!panning)return;if(panning)event.preventDefault();
    if(node&&!panning){if(event.ctrlKey||event.metaKey){this.selected.has(node.id)?this.selected.delete(node.id):this.selected.add(node.id);}else if(!this.selected.has(node.id))this.selected=new Set([node.id]);this.hooks.select?.(node);this.render();}
    const points=new Map(this.graph.nodes.filter(value=>this.selected.has(value.id)).map(value=>{const el=this.element.querySelector(`[data-material-node="${value.id}"]`);return [value.id,{x:el.offsetLeft,y:el.offsetTop}];}));let remembered=false;const box=this.element.querySelector('.material-selection-box');if(!node&&!panning&&!event.ctrlKey)this.selected.clear();const baseSelection=new Set(this.selected);this.element.setPointerCapture(event.pointerId);
    const move=e=>{const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>3)this.moved=true;if(panning){this.pan={x:pan.x+dx,y:pan.y+dy};this.transform();}else if(node){if(!this.moved)return;if(!remembered){this.hooks.before?.();remembered=true;}for(const value of this.graph.nodes){const point=points.get(value.id);if(point){value.px=point.x+dx/this.zoom;value.y=point.y+dy/this.zoom;const el=this.element.querySelector(`[data-material-node="${value.id}"]`);el.style.left=value.px+'px';el.style.top=value.y+'px';}}this.drawWires();}else{const rect=this.element.getBoundingClientRect(),left=Math.min(start.x,e.clientX)-rect.left,top=Math.min(start.y,e.clientY)-rect.top;box.hidden=false;Object.assign(box.style,{left:left+'px',top:top+'px',width:Math.abs(dx)+'px',height:Math.abs(dy)+'px'});this.selected=new Set(baseSelection);for(const value of this.graph.nodes){const rect=this.element.querySelector(`[data-material-node="${value.id}"]`).getBoundingClientRect();if(rect.right>=Math.min(start.x,e.clientX)&&rect.left<=Math.max(start.x,e.clientX)&&rect.bottom>=Math.min(start.y,e.clientY)&&rect.top<=Math.max(start.y,e.clientY))this.selected.add(value.id);}}};
    const up=()=>{this.element.removeEventListener('pointermove',move);this.element.removeEventListener('pointerup',up);this.element.removeEventListener('pointercancel',up);if(remembered)this.hooks.change?.();this.saveView();if(!panning)this.render();};this.element.addEventListener('pointermove',move);this.element.addEventListener('pointerup',up);this.element.addEventListener('pointercancel',up);
  }
  menu(event){
    this.closeMenu?.();this.document.querySelector('.material-node-menu')?.remove();const node=event.target.closest('[data-material-node]');if(node&&!this.selected.has(node.dataset.materialNode)){this.selected=new Set([node.dataset.materialNode]);this.render();}const rect=this.element.getBoundingClientRect(),position={x:(event.clientX-rect.left-this.pan.x)/this.zoom,y:(event.clientY-rect.top-this.pan.y)/this.zoom},menu=this.document.createElement('div');menu.className='project-menu material-node-menu';menu.innerHTML='<input type="search" placeholder="노드 검색" aria-label="머테리얼 노드 검색"><div class="material-node-results"></div>';const search=menu.querySelector('input'),results=menu.querySelector('.material-node-results');
    let functions=[];const render=()=>{if(!this.graph)return;const query=search.value.trim().toLowerCase();let group='';results.innerHTML=(this.selected.size&&!query&&!this.pending?'<button data-material-delete>'+icon('close')+'선택 노드 삭제 <kbd>Delete</kbd></button>':'')+materialCatalog.filter(spec=>!['surface','functionCall'].includes(spec.key)&&(!['functionInput','functionOutput'].includes(spec.key)||this.graph.mode==='function'&&!this.doc.data.domain)&&(spec.key!=='layerStack'||this.graph.mode!=='function')&&(spec.title+' '+spec.key+' '+spec.category).toLowerCase().includes(query)&&this.canSpawn(spec.key)).map(spec=>{const heading=group!==spec.category?'<div class="palette-group">'+esc(spec.category)+'</div>':'';group=spec.category;return heading+`<button data-material-add="${spec.key}">${icon('nodes')}<span>${esc(spec.title)}</span></button>`;}).join('')+functions.filter(f=>(f.data.name+' '+f.path+' '+f.data.category+' '+f.data.description).toLowerCase().includes(query)&&this.canSpawnNode(f.node)).map(f=>{const heading=group!==f.data.category?'<div class="palette-group">'+esc(f.data.category)+'</div>':'';group=f.data.category;return heading+`<button data-material-function="${esc(f.path)}" title="${esc(f.data.description)}">${icon('nodes')}<span>${esc(f.data.name)}</span></button>`;}).join('');};
    const close=e=>{if(!e||!menu.contains(e.target)){menu.remove();this.document.removeEventListener('pointerdown',close,true);}};this.closeMenu=()=>close();menu.onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.materialAdd)this.add(button.dataset.materialAdd,position);else if(button.dataset.materialFunction)this.addFunction(button.dataset.materialFunction,position).catch(e=>this.hooks.error?.(e.message));else if(button.hasAttribute('data-material-delete'))this.deleteSelection();close();};search.oninput=render;search.onkeydown=e=>{if(e.key==='Escape')close();if(e.key==='Enter')results.querySelector('[data-material-add],[data-material-function]')?.click();};render();this.document.body.append(menu);menu.style.left=Math.max(8,Math.min(event.clientX,this.document.defaultView.innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(event.clientY,this.document.defaultView.innerHeight-menu.offsetHeight-8))+'px';search.focus();this.document.addEventListener('pointerdown',close,true);
    const doc=this.doc;Promise.all((this.hooks.files?.()||[]).filter(f=>f.kind==='materialfunction'&&f.path!==doc.path).map(async f=>{try{const data=await this.hooks.readAsset(f.path);return data.expose?{path:f.path,data,node:makeMaterialFunctionCall(f.path,data)}:null;}catch{return null;}})).then(items=>{if(!menu.isConnected||this.doc!==doc)return;functions=items.filter(Boolean).toSorted((a,b)=>a.data.category.localeCompare(b.data.category)||a.data.name.localeCompare(b.data.name));render();});
  }

  spawnLink(graph,node){if(!this.pending)return null;const endpoint={node:this.pending.node,pin:this.pending.pin},reverse=this.pending.direction==='in';for(const pin of materialPins(node,graph)[reverse?'outputs':'inputs']){const from=reverse?{node:node.id,pin:pin.id}:endpoint,to=reverse?endpoint:{node:node.id,pin:pin.id},candidate=structuredClone(graph);if(connectMaterial(candidate,from,to).ok)return {from,to};}return null;}
  canSpawnNode(node){if(!this.pending)return true;const candidate=structuredClone(this.graph);candidate.nodes.push(node);return !!this.spawnLink(candidate,node);}
  canSpawn(key){const node=makeMaterialNode(key);if(node.portName)node.portName=materialPortName(this.graph,key,node.portName);return this.canSpawnNode(node);}
  add(key,position={x:100,y:100}){const node=makeMaterialNode(key,position.x,position.y);if(node.portName)node.portName=materialPortName(this.graph,key,node.portName);if(node.parameter){const base=node.parameter;let index=1;while(this.graph.nodes.some(value=>value.parameter===node.parameter))node.parameter=base+(++index);}if(this.mutate(data=>{data.graph.nodes.push(node);const link=this.spawnLink(data.graph,node);if(link)connectMaterial(data.graph,link.from,link.to);}))this.selected=new Set([node.id]);this.pending=null;this.render();}
  addFunction(asset,position={x:100,y:100}){return this.addFunctions([{path:asset}],position);}
  async addFunctions(files,position){if(!files.length)return;const doc=this.doc;if(files.some(f=>f.path===doc.path))throw Error('머테리얼 함수가 자기 자신을 호출할 수 없어요.');if(files.length+this.graph.nodes.length>1000)throw Error('머테리얼 그래프 노드 한도를 넘어요.');const nodes=await Promise.all(files.map(async(f,i)=>makeMaterialFunctionCall(f.path,await this.hooks.readAsset(f.path),position.x+i*40,position.y+i*40)));if(this.doc!==doc)return;if(this.mutate(d=>{d.graph.nodes.push(...nodes);const link=this.spawnLink(d.graph,nodes[0]);if(link)connectMaterial(d.graph,link.from,link.to);}))this.selected=new Set(nodes.map(n=>n.id));this.pending=null;this.render();}
  async refreshFunction(node){const doc=this.doc,data=await this.hooks.readAsset(node.asset);if(this.doc!==doc)return;this.mutate(d=>refreshMaterialFunctionCall(d.graph,node.id,data));}

  deleteSelection(){this.mutate(data=>removeMaterialNodes(data.graph,this.selected));this.selected.clear();this.render();}
  copySelection(){const clip=copyMaterialNodes(this.graph,this.selected);if(!clip.nodes.length)return;for(const node of clip.nodes){const element=this.element.querySelector(`[data-material-node="${node.id}"]`);if(element)node.px=element.offsetLeft;}copiedNodes=clip;this.document.defaultView.navigator.clipboard?.writeText(JSON.stringify(clip)).catch(()=>{});}
  async pasteSelection(){let clip=copiedNodes;try{const text=await this.document.defaultView.navigator.clipboard?.readText();if(text?.length<=1048576){const parsed=JSON.parse(text);if(parsed.type==='HBMaterialNodes')clip=parsed;}}catch{}if(!clip)return;const position={x:(80-this.pan.x)/this.zoom,y:(80-this.pan.y)/this.zoom};let nodes;this.mutate(data=>{const result=pasteMaterialNodes(data.graph,clip,position);if(!result.ok){this.hooks.error?.(result.reason);return false;}nodes=result.nodes;});if(nodes){this.selected=new Set(nodes.map(node=>node.id));this.render();}}
  duplicateSelection(){const clip=copyMaterialNodes(this.graph,this.selected);if(!clip.nodes.length)return;for(const node of clip.nodes){const element=this.element.querySelector(`[data-material-node="${node.id}"]`);if(element)node.px=element.offsetLeft;}const position={x:Math.min(...clip.nodes.map(node=>node.px??node.x))+35,y:Math.min(...clip.nodes.map(node=>node.y))+35};let nodes;this.mutate(data=>{const result=pasteMaterialNodes(data.graph,clip,position);if(!result.ok){this.hooks.error?.(result.reason);return false;}nodes=result.nodes;});if(nodes){this.selected=new Set(nodes.map(node=>node.id));this.render();}}
  fit(selectionOnly=false,zoom){const elements=[...this.element.querySelectorAll('[data-material-node]')].filter(element=>!selectionOnly||!this.selected.size||this.selected.has(element.dataset.materialNode));if(!elements.length)return;const left=Math.min(...elements.map(element=>element.offsetLeft)),top=Math.min(...elements.map(element=>element.offsetTop)),right=Math.max(...elements.map(element=>element.offsetLeft+element.offsetWidth)),bottom=Math.max(...elements.map(element=>element.offsetTop+element.offsetHeight));this.zoom=zoom??Math.max(.25,Math.min(1,(this.element.clientWidth-40)/(right-left),(this.element.clientHeight-40)/(bottom-top)));this.pan={x:(this.element.clientWidth-(right-left)*this.zoom)/2-left*this.zoom,y:(this.element.clientHeight-(bottom-top)*this.zoom)/2-top*this.zoom};this.transform();this.saveView();}
  keydown(event){if(editable(event.target))return;const mod=event.ctrlKey||event.metaKey;if(mod&&['c','x','v','z','y'].includes(event.key.toLowerCase())){event.preventDefault();event.stopPropagation();const key=event.key.toLowerCase();if(key==='c'||key==='x'){this.copySelection();if(key==='x')this.deleteSelection();}else if(key==='v')this.pasteSelection();else{const action=key==='y'||event.shiftKey?this.hooks.redo:this.hooks.undo;if(action){action();this.render();}else this.hooks.error?.('문서의 Undo/Redo 연결을 확인하세요.');}}else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();event.stopPropagation();this.deleteSelection();}else if(mod&&event.key.toLowerCase()==='a'){event.preventDefault();event.stopPropagation();this.selected=new Set(this.graph.nodes.map(node=>node.id));this.render();}else if(mod&&event.key.toLowerCase()==='d'){event.preventDefault();event.stopPropagation();this.duplicateSelection();}else if(event.key==='f'||event.key==='F'||event.key==='Home'){event.preventDefault();event.stopPropagation();this.fit(event.key!=='Home');}else if(event.key==='Escape'){this.pending=null;this.selected.clear();this.render();}}
  dispose(){this.closeMenu?.();for(const remove of this.listeners)remove();this.observer.disconnect();this.document.querySelector('.material-node-menu')?.remove();}
}
