import {materialTextureTypes,textureNodeType,validateTextureImages,texturePlaceholder,loadMaterialTexture} from './texture-assets.js';
export {materialTextureTypes,textureNodeType} from './texture-assets.js';
const copy=value=>structuredClone(value),finite=value=>Number.isFinite(value)&&Math.abs(value)<=10000;
const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
export const materialDefaults={color:'#889878',roughness:.72,metalness:.08,light:3.2,normal:[0,0,1],emissive:'#000000',emissiveIntensity:1,opacity:1,ao:1,clearcoat:0,clearcoatRoughness:.1,transmission:0,ior:1.5,blendMode:'opaque',alphaTest:.5,doubleSided:false};
export const surfaceInputs=[['baseColor','Base Color · 기본 색상','vec3','color'],['roughness','Roughness · 거칠기','float','roughness'],['metallic','Metallic · 금속성','float','metalness'],['normal','Normal · 노멀','vec3','normal'],['emissive','Emissive · 발광','vec3','emissive'],['opacity','Opacity · 불투명도','float','opacity'],['ao','Ambient Occlusion · 차폐','float','ao'],['clearcoat','Clearcoat · 코팅','float','clearcoat'],['clearcoatRoughness','Coat Roughness · 코팅 거칠기','float','clearcoatRoughness'],['transmission','Transmission · 투과','float','transmission'],['ior','IOR · 굴절률','float','ior']].map(([id,label,type,key])=>({id,label,type,key}));
const pin=(id,label,type,value)=>({id,label,type,value}),out=(type='float')=>[pin('value','Value',type)];
const attributeFields=surfaceInputs.map(p=>p.id);
const attributeKeys=['makeAttributes','setAttributes','breakAttributes','getAttributes','blendAttributes'];
export const materialFunctionTypes=['float','vec2','vec3','vec4',...Object.keys(materialTextureTypes),'staticBool','attributes'];
export const materialParameterKey=node=>node.parameterScope?'layer.'+node.parameterScope.id+'.'+node.parameterScope.domain+'.'+node.parameter:node.parameter;
export const materialLayerParameterKey=(id,name,blend=false)=>'layer.'+id+'.'+(blend?'blend':'layer')+'.'+name;
const parameterName=v=>typeof v==='string'&&/^[A-Za-z_가-힣][\w가-힣]{0,79}$/.test(v);
export const validMaterialParameters=values=>!!values&&typeof values==='object'&&!Array.isArray(values)&&Object.keys(values).length<=128&&Object.entries(values).every(([name,v])=>parameterName(name)&&(typeof v==='boolean'||finite(v)||Array.isArray(v)&&v.length===3&&v.every(finite)||typeof v==='string'&&validAssetPath(v)));
const attributeLiteral=value=>!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.entries(value).every(([id,v])=>{const p=surfaceInputs.find(p=>p.id===id);return p&&(p.type==='float'?finite(v):Array.isArray(v)&&v.length===3&&v.every(finite));});
export const materialLiteralDefault=type=>type==='attributes'?{}:materialTextureTypes[type]?'':type==='staticBool'?false:type==='float'||type==='numeric'?0:Array(Number(type.slice(3))).fill(0);
const typedLiteral=(type,v)=>materialTextureTypes[type]?validAssetPath(v):type==='staticBool'?typeof v==='boolean':type==='attributes'?attributeLiteral(v):type==='float'?finite(v):finite(v)||Array.isArray(v)&&v.length===Number(type.slice(3))&&v.every(finite);
export const validMaterialLayers=layers=>Array.isArray(layers)&&layers.every((l,i)=>l&&/^[A-Za-z0-9_]{1,32}$/.test(l.id)&&typeof l.name==='string'&&l.name.length<=80&&!!l.asset&&validAssetPath(l.asset)&&validAssetPath(l.blend)&&typeof l.enabled==='boolean'&&(i!==0||l.enabled&&!l.blend)&&validMaterialParameters(l.parameters)&&validMaterialParameters(l.blendParameters))&&new Set(layers.map(l=>l.id)).size===layers.length;
export const newMaterialLayer=(asset,name)=>({id:'L_'+crypto.randomUUID().replaceAll('-','').slice(0,20),name,asset,blend:'',enabled:true,parameters:{},blendParameters:{}});
const specs=[
  ['scalar','Scalar · 상수','값',[],out(),{value:.5}],['vector2','Vector2 · 벡터2','값',[],out('vec2'),{value:[1,1]}],['vector3','Vector3 · 벡터3','값',[],out('vec3'),{value:[1,1,1]}],['vector4','Vector4 · 벡터4','값',[],out('vec4'),{value:[1,1,1,1]}],['color','Color · 색상','값',[],out('vec3'),{value:'#889878'}],
  ['scalarParameter','Scalar Parameter · 스칼라 변수','파라미터',[],out(),{value:.5,parameter:'Scalar'}],['vectorParameter','Vector Parameter · 색상 변수','파라미터',[],out('vec3'),{value:[1,1,1],parameter:'Color'}],
  ['texture','Texture Sample · 텍스처 샘플','텍스처',[pin('uv','UV','vec2',[0,0]),pin('textureObject','Texture Object · 텍스처 객체','texture2d','')],[pin('rgba','RGBA','vec4'),pin('rgb','RGB','vec3'),...['r','g','b','a'].map(id=>pin(id,id.toUpperCase(),'float'))],{texture:'',colorSpace:'srgb',wrap:'repeat',parameter:'Texture'}],
  ['textureObject','Texture Object · 텍스처 객체','텍스처',[],out('texture2d'),{texture:''}],
  ['textureObjectParameter','Texture Object Parameter · 텍스처 객체 변수','파라미터',[],out('texture2d'),{texture:'',parameter:'Texture'}],
  ...Object.entries(materialTextureTypes).filter(([t])=>t!=='texture2d').flatMap(([type,v])=>{const label={texturecube:'Cubemap · 큐브맵',texturearray:'Texture 2D Array · 텍스처 배열',texture3d:'Texture 3D · 볼륨 텍스처'}[type];return [[v.sample,'Sample '+label,'텍스처',[...(type==='texturecube'?[pin('direction','Direction','vec3'),pin('lod','LOD','float',0)]:[pin('uv','UV',type==='texture3d'?'vec3':'vec2',type==='texture3d'?[.5,.5,.5]:[0,0]),...(type==='texturearray'?[pin('index','Index','float',0)]:[])]),pin('textureObject','Texture',''+type,'')],[pin('rgba','RGBA','vec4'),pin('rgb','RGB','vec3'),...['r','g','b','a'].map(id=>pin(id,id.toUpperCase(),'float'))],{texture:'',colorSpace:'srgb',wrap:'clamp',parameter:'Texture'}],[v.object,label+' Object','텍스처',[],out(type),{texture:''}],[v.parameter,label+' Parameter','파라미터',[],out(type),{texture:'',parameter:'Texture'}]];}),
  ['staticBool','Static Bool · 정적 불리언','값',[],out('staticBool'),{value:false}],
  ['staticBoolParameter','Static Bool Parameter · 정적 불리언 변수','파라미터',[],out('staticBool'),{value:false,parameter:'Enabled'}],
  ['staticSwitch','Static Switch · 정적 분기','수학',[],out('numeric'),{valueType:'numeric'}],
  ['uv','Texture Coordinate · UV 좌표','좌표',[],out('vec2')],['time','Time · 시간','좌표',[],out()],
  ['tilingOffset','Tiling And Offset · 반복과 위치','좌표',[pin('uv','UV','vec2'),pin('tiling','Tiling','vec2',[1,1]),pin('offset','Offset','vec2',[0,0])],out('vec2')],
  ['panner','Panner · UV 이동','좌표',[pin('uv','UV','vec2'),pin('speed','Speed','vec2',[.1,0]),pin('time','Time','float')],out('vec2')],
  ['rotateUV','Rotate UV · UV 회전','좌표',[pin('uv','UV','vec2'),pin('angle','Angle · 라디안','float',0),pin('center','Center','vec2',[.5,.5])],out('vec2')],
  ...['add','subtract','multiply','divide','power','min','max','step'].map(key=>[key,({add:'Add · 더하기',subtract:'Subtract · 빼기',multiply:'Multiply · 곱하기',divide:'Divide · 나누기',power:'Power · 제곱',min:'Minimum · 최솟값',max:'Maximum · 최댓값',step:'Step · 경계'})[key],'수학',[pin('a','A','numeric',key==='multiply'||key==='divide'?1:0),pin('b','B','numeric',1)],out('numeric')]),
  ['lerp','Linear Interpolate · 선형 보간','수학',[pin('a','A','numeric',0),pin('b','B','numeric',1),pin('alpha','Alpha','float',.5)],out('numeric')],
  ['clamp','Clamp · 범위 제한','수학',[pin('value','Value','numeric',.5),pin('min','Min','numeric',0),pin('max','Max','numeric',1)],out('numeric')],
  ...['saturate','oneMinus','normalize','sine','absolute','fraction'].map(key=>[key,({saturate:'Saturate · 0~1 제한',oneMinus:'One Minus · 반전',normalize:'Normalize · 정규화',sine:'Sine · 사인',absolute:'Absolute · 절댓값',fraction:'Fraction · 소수 부분'})[key],'수학',[pin('value','Value','numeric',.5)],out('numeric')]),
  ['dot','Dot Product · 내적','수학',[pin('a','A','vec3',[1,0,0]),pin('b','B','vec3',[0,1,0])],out()],['length','Length · 길이','수학',[pin('value','Value','numeric',0)],out()],
  ['normalMap','Unpack Normal · 노멀 변환','텍스처',[pin('value','RGB','vec3',[.5,.5,1]),pin('strength','Strength','float',1)],out('vec3')],
  ...['cosine','floor','ceil','squareRoot','sign','exp2','log2'].map(key=>[key,({cosine:'Cosine · 코사인',floor:'Floor · 내림',ceil:'Ceil · 올림',squareRoot:'Square Root · 제곱근',sign:'Sign · 부호',exp2:'Exp2 · 지수',log2:'Log2 · 로그'})[key],'수학',[pin('value','Value','numeric',.5)],out('numeric')]),
  ['smoothstep','Smoothstep · 부드러운 경계','마스크',[pin('min','Min','numeric',0),pin('max','Max','numeric',1),pin('value','Value','numeric',.5)],out('numeric')],
  ['distance','Distance · 거리','벡터',[pin('a','A','vec3',[0,0,0]),pin('b','B','vec3',[1,0,0])],out()],
  ['cross','Cross Product · 외적','벡터',[pin('a','A','vec3',[1,0,0]),pin('b','B','vec3',[0,1,0])],out('vec3')],
  ['reflect','Reflect · 반사 방향','벡터',[pin('direction','Direction','vec3',[0,-1,0]),pin('normal','Normal','vec3',[0,1,0])],out('vec3')],
  ['split','Split · 채널 분리','벡터',[pin('value','Vector','vec4',[0,0,0,1])],['x','y','z','w'].map(id=>pin(id,id.toUpperCase(),'float'))],
  ['combine','Combine · 채널 조합','벡터',['x','y','z','w'].map(id=>pin(id,id.toUpperCase(),'float',id==='w'?1:0)),[pin('rgba','RGBA','vec4'),pin('rgb','RGB','vec3'),pin('rg','RG','vec2')]],
  ['worldPosition','World Position · 월드 위치','좌표',[],out('vec3')],
  ['worldNormal','World Normal · 월드 법선','좌표',[],out('vec3')],
  ['viewDirection','View Direction · 시선 방향','좌표',[],out('vec3')],
  ['fresnel','Fresnel · 가장자리 반사','마스크',[pin('normal','World Normal','vec3'),pin('view','View Direction','vec3'),pin('power','Exponent','float',5),pin('base','Base Reflectance','float',.04)],out()],
  ['noise','Value Noise · 값 노이즈','절차적',[pin('uv','UV','vec2'),pin('scale','Scale','float',5)],out()],
  ['checker','Checkerboard · 체크 패턴','절차적',[pin('uv','UV','vec2'),pin('scale','Scale','vec2',[8,8])],out()],
  ['radialGradient','Radial Gradient · 원형 그라데이션','마스크',[pin('uv','UV','vec2'),pin('center','Center','vec2',[.5,.5]),pin('radius','Radius','float',.5)],out()],
  ['linearGradient','Linear Gradient · 선형 그라데이션','마스크',[pin('uv','UV','vec2'),pin('angle','Angle · 라디안','float',0)],out()],
  ['functionInput','Function Input · 함수 입력','함수',[],out(),{valueType:'float',portName:'Input',value:0,useDefault:true,priority:0,description:''}],
  ['functionOutput','Function Output · 함수 출력','함수',[pin('value','Value','float',0)],[],{valueType:'float',portName:'Output',priority:0,description:''}],
  ['functionCall','Material Function · 머테리얼 함수','함수',[],[],{asset:'',signature:{inputs:[],outputs:[]}}],
  ['makeAttributes','Make Material Attributes · 표면 속성 만들기','표면 속성',surfaceInputs,out('attributes')],
  ['setAttributes','Set Material Attributes · 표면 속성 설정','표면 속성',[],out('attributes'),{fields:['baseColor']}],
  ['breakAttributes','Break Material Attributes · 표면 속성 분리','표면 속성',[pin('attributes','Attributes · 표면 속성','attributes')],surfaceInputs],
  ['getAttributes','Get Material Attributes · 표면 속성 가져오기','표면 속성',[pin('attributes','Attributes · 표면 속성','attributes')],[],{fields:['baseColor']}],
  ['blendAttributes','Blend Material Attributes · 표면 속성 혼합','표면 속성',[pin('bottom','Bottom · 하단','attributes'),pin('top','Top · 상단','attributes'),pin('alpha','Alpha · 마스크','float',.5)],out('attributes'),{normalizeNormal:true}],
  ['layerStack','Material Layers · 머테리얼 레이어','레이어',[pin('attributes','Input · 공용 속성','attributes')],out('attributes'),{layers:[]}],
  ['surface','Surface · PBR 표면','출력',surfaceInputs,[],{}]
];
export const materialCatalog=specs.map(([key,title,category,inputs,outputs,defaults={}])=>({key,title,category,inputs,outputs,defaults}));
const catalogMap=new Map(materialCatalog.map(spec=>[spec.key,spec]));
export const materialNodeKey=node=>node.key||(node.kind==='output'?'surface':({color:'legacyColor',rough:'legacyRough',constant:'scalar'})[node.body]);
const nodeKey=materialNodeKey;
const functionTypes=materialFunctionTypes,portName=v=>typeof v==='string'&&v.trim().length>0&&v.length<=100&&!/[\x00-\x1f]/.test(v);
const functionSpec=node=>nodeKey(node)==='functionCall'?node.signature:nodeKey(node)==='functionInput'?{inputs:[pin('preview','Preview · 미리보기',node.valueType)],outputs:[pin('value',node.portName,node.valueType)]}:nodeKey(node)==='functionOutput'?{inputs:[pin('value',node.portName,node.valueType,materialLiteralDefault(node.valueType))],outputs:[]}:nodeKey(node)==='surface'&&node.useAttributes?{inputs:[pin('attributes','Material Attributes · 표면 속성','attributes')],outputs:[]}:nodeKey(node)==='setAttributes'?{inputs:[pin('attributes','Attributes · 표면 속성','attributes'),...surfaceInputs.filter(p=>node.fields?.includes(p.id))],outputs:out('attributes')}:nodeKey(node)==='getAttributes'?{inputs:catalogMap.get('getAttributes').inputs,outputs:surfaceInputs.filter(p=>node.fields?.includes(p.id))}:nodeKey(node)==='staticSwitch'?{inputs:[pin('a','True · 참',node.valueType,materialLiteralDefault(node.valueType)),pin('b','False · 거짓',node.valueType,materialLiteralDefault(node.valueType)),pin('condition','Value · 조건','staticBool',false)],outputs:out(node.valueType)}:catalogMap.get(nodeKey(node));
export function materialFunctionSignature(graph){const ports=key=>graph.nodes.filter(n=>nodeKey(n)===key).toSorted((a,b)=>a.priority-b.priority).map(n=>({id:n.id,label:n.portName,type:n.valueType,...key==='functionInput'?{value:copy(n.value),useDefault:n.useDefault}:{},description:n.description}));return {inputs:ports('functionInput'),outputs:ports('functionOutput')};}
export function materialFunctionGraph(){const input={...makeMaterialNode('functionInput',60,80),id:'input',valueType:'vec3',value:[1,1,1]},output={...makeMaterialNode('functionOutput',500,80),id:'result',valueType:'vec3'};return {mode:'function',nodes:[input,output],edges:[{from:{node:input.id,pin:'value'},to:{node:output.id,pin:'value'}}]};}
export function validMaterialFunction(data){return data?.version===1&&portName(data.name)&&typeof data.description==='string'&&data.description.length<=1000&&typeof data.category==='string'&&data.category.length<=100&&typeof data.expose==='boolean'&&validMaterialSurface(data.surface)&&data.graph?.mode==='function'&&validMaterialGraph(data.graph)&&(data.previewOutput===undefined||data.graph.nodes.some(n=>nodeKey(n)==='functionOutput'&&n.id===data.previewOutput));}
export function materialPortName(graph,key,base){let name=base,index=1;while(graph.nodes.some(n=>nodeKey(n)===key&&n.portName===name)){const suffix=String(++index);name=base.slice(0,100-suffix.length)+suffix;}return name;}
export function refreshMaterialFunctionCall(graph,id,data){const node=graph.nodes.find(n=>n.id===id&&nodeKey(n)==='functionCall');if(!node)throw Error('머테리얼 함수 호출을 확인하세요.');const fresh=makeMaterialFunctionCall(node.asset,data),old=node.signature;const keep=(side,pin)=>fresh.signature[side].some(p=>p.id===pin&&old[side].some(v=>v.id===pin&&v.type===p.type));graph.edges=normalizedMaterialEdges(graph).filter(e=>(e.from.node!==id||keep('outputs',e.from.pin))&&(e.to.node!==id||keep('inputs',e.to.pin)));node.inputValues=Object.fromEntries(Object.entries(node.inputValues||{}).filter(([key])=>keep('inputs',key)));Object.assign(node,{title:fresh.title,signature:fresh.signature,description:fresh.description});}
export function makeMaterialFunctionCall(asset,data,x=80,y=80){if(!validAssetPath(asset)||!asset||!validMaterialFunction(data))throw Error('머테리얼 함수 에셋을 확인하세요.');return {...makeMaterialNode('functionCall',x,y),asset,title:data.name,description:data.description,signature:materialFunctionSignature(data.graph)};}
export function makeMaterialNode(key,x=80,y=80){const spec=catalogMap.get(key);if(!spec)throw Error('머테리얼 노드 종류를 확인하세요.');return {id:'mat_'+crypto.randomUUID().replaceAll('-',''),key,title:spec.title,kind:key==='surface'?'output':'value',x,y,...copy(spec.defaults),inputValues:{}};}
export const materialGraph=()=>({nodes:[{id:'color',title:'Base Color',kind:'value',x:.06,y:45,body:'color',output:'RGB'},{id:'rough',title:'Roughness',kind:'value',x:.06,y:195,body:'rough',output:'Float'},{id:'surface',key:'surface',title:'Surface',kind:'output',x:.64,y:70}],edges:[['color','surface',0],['rough','surface',1]]});
export function normalizedMaterialEdges(graph){return graph.edges.map(edge=>{if(!Array.isArray(edge))return edge;const target=graph.nodes.find(node=>node.id===edge[1]);return {from:{node:edge[0],pin:edge[3]||'value'},to:{node:edge[1],pin:nodeKey(target||{})==='surface'?surfaceInputs[edge[2]]?.id:catalogMap.get(nodeKey(target||{}))?.inputs[edge[2]]?.id}};});}
function actualType(node,graph,seen=new Set()){
  const key=nodeKey(node);if(key==='legacyColor')return 'vec3';if(key==='legacyRough')return 'float';const spec=functionSpec(node);if(spec?.outputs[0]?.type!=='numeric')return spec?.outputs[0]?.type;
  if(seen.has(node.id))return 'float';seen.add(node.id);let type='float';for(const edge of normalizedMaterialEdges(graph).filter(edge=>edge.to?.node===node.id)){const source=graph.nodes.find(n=>n.id===edge.from?.node);if(!source)continue;const sourceSpec=functionSpec(source),output=sourceSpec?.outputs.find(pin=>pin.id===edge.from.pin),next=output?.type==='numeric'?actualType(source,graph,new Set(seen)):output?.type||actualType(source,graph,new Set(seen));if(/^vec[234]$/.test(next)&&next>type)type=next;}
  for(const value of Object.values(node.inputValues||{}))if(Array.isArray(value)&&value.length>=2&&value.length<=4&&'vec'+value.length>type)type='vec'+value.length;return type;
}
export function materialPins(node,graph){const key=nodeKey(node);if(key==='legacyColor'||key==='legacyRough')return {inputs:[],outputs:out(key==='legacyColor'?'vec3':'float')};const spec=functionSpec(node);if(!spec)return {inputs:[],outputs:[]};const type=actualType(node,graph);return {inputs:spec.inputs.map(pin=>({...pin,type:pin.type==='numeric'?type:pin.type})),outputs:spec.outputs.map(pin=>({...pin,type:pin.type==='numeric'?type:pin.type}))};}
export function validMaterialGraph(graph){
  if(!graph||!Array.isArray(graph.nodes)||!Array.isArray(graph.edges)||graph.nodes.length>1000||graph.edges.length>5000||new Set(graph.nodes.map(node=>node?.id)).size!==graph.nodes.length||graph.mode!==undefined&&graph.mode!=='function')return false;
  const isFunction=graph.mode==='function';if(isFunction?graph.nodes.some(n=>n&&['surface','legacyColor','legacyRough','layerStack'].includes(nodeKey(n)))||!graph.nodes.some(n=>n&&nodeKey(n)==='functionOutput'):graph.nodes.filter(n=>n&&nodeKey(n)==='surface').length!==1||graph.nodes.some(n=>n&&['functionInput','functionOutput'].includes(nodeKey(n))))return false;
  if(!graph.edges.every(edge=>Array.isArray(edge)?(edge.length===3||edge.length===4)&&typeof edge[0]==='string'&&typeof edge[1]==='string'&&Number.isInteger(edge[2])&&edge[2]>=0&&edge[2]<surfaceInputs.length:edge&&edge.from&&edge.to&&['from','to'].every(key=>typeof edge[key].node==='string'&&typeof edge[key].pin==='string'&&edge[key].pin.length<=100)))return false;
  if(!graph.nodes.every(node=>node&&/^[A-Za-z0-9_-]{1,100}$/.test(node.id)&&typeof node.title==='string'&&node.title.length<=100&&(catalogMap.has(nodeKey(node))||['legacyColor','legacyRough'].includes(nodeKey(node)))&&finite(node.x)&&finite(node.y)&&(node.px===undefined||finite(node.px))&&(node.value===undefined||typeof node.value==='boolean'||materialTextureTypes[node.valueType]&&validAssetPath(node.value)||attributeLiteral(node.value)||typeof node.value==='string'&&/^#[0-9a-f]{6}$/i.test(node.value)||finite(node.value)||Array.isArray(node.value)&&node.value.length>=2&&node.value.length<=4&&node.value.every(finite))&&(node.parameter===undefined||typeof node.parameter==='string'&&/^[A-Za-z_가-힣][\w가-힣]{0,79}$/.test(node.parameter))&&(node.texture===undefined||validAssetPath(node.texture))&&(node.colorSpace===undefined||['srgb','linear'].includes(node.colorSpace))&&(node.wrap===undefined||['repeat','clamp'].includes(node.wrap))&&(node.inputValues===undefined||node.inputValues&&typeof node.inputValues==='object'&&!Array.isArray(node.inputValues)&&Object.values(node.inputValues).every(value=>typeof value==='boolean'||typeof value==='string'&&validAssetPath(value)||attributeLiteral(value)||finite(value)||Array.isArray(value)&&value.length>=2&&value.length<=4&&value.every(finite)))))return false;
  const names={functionInput:new Set(),functionOutput:new Set()};for(const node of graph.nodes){const key=nodeKey(node),value=node.value;if(value!==undefined){if(['scalar','scalarParameter'].includes(key)&&!finite(value))return false;if(key==='color'&&(typeof value!=='string'||!/^#[0-9a-f]{6}$/i.test(value)))return false;const size=({vector2:2,vector3:3,vector4:4,vectorParameter:3})[key];if(size&&(!Array.isArray(value)||value.length!==size))return false;}
    if(['staticBool','staticBoolParameter'].includes(key)&&typeof value!=='boolean'||key==='staticSwitch'&&!['numeric',...functionTypes].includes(node.valueType))return false;
    if(node.parameterScope!==undefined&&(!node.parameterScope||!/^[A-Za-z0-9_]{1,32}$/.test(node.parameterScope.id)||!['layer','blend'].includes(node.parameterScope.domain)))return false;if(attributeKeys.includes(key)&&['setAttributes','getAttributes'].includes(key)&&(!Array.isArray(node.fields)||new Set(node.fields).size!==node.fields.length||node.fields.some(id=>!attributeFields.includes(id))))return false;if(key==='blendAttributes'&&typeof node.normalizeNormal!=='boolean')return false;if(key==='surface'&&node.useAttributes!==undefined&&typeof node.useAttributes!=='boolean')return false;if(key==='layerStack'&&!validMaterialLayers(node.layers))return false;if(names[key]){if(!functionTypes.includes(node.valueType)||!portName(node.portName)||names[key].has(node.portName)||!Number.isInteger(node.priority)||Math.abs(node.priority)>10000||typeof node.description!=='string'||node.description.length>1000)return false;names[key].add(node.portName);if(key==='functionInput'&&(typeof node.useDefault!=='boolean'||!typedLiteral(node.valueType,value)))return false;}
    if(key==='functionCall'){if(node.description!==undefined&&(typeof node.description!=='string'||node.description.length>1000))return false;if(!node.asset||!validAssetPath(node.asset)||!node.signature||!['inputs','outputs'].every(k=>Array.isArray(node.signature[k])&&node.signature[k].length<=1000&&new Set(node.signature[k].map(p=>p?.id)).size===node.signature[k].length&&node.signature[k].every(p=>p&&/^[A-Za-z0-9_-]{1,100}$/.test(p.id)&&portName(p.label)&&functionTypes.includes(p.type)&&(p.description===undefined||typeof p.description==='string'&&p.description.length<=1000))))return false;if(!node.signature.outputs.length||node.signature.inputs.some(p=>typeof p.useDefault!=='boolean'||!typedLiteral(p.type,p.value)))return false;}
    if(node.inputValues&&Object.entries(node.inputValues).some(([id,v])=>{const p=functionSpec(node)?.inputs.find(p=>p.id===id);return !p||(p.type==='numeric'?!finite(v)&&(!Array.isArray(v)||v.length<2||v.length>4||!v.every(finite)):!typedLiteral(p.type,v));}))return false;if(['functionCall','functionInput','functionOutput'].includes(key)&&Object.entries(node.inputValues||{}).some(([id,v])=>{const p=functionSpec(node).inputs.find(p=>p.id===id);return !typedLiteral(p.type,v);}))return false;}
  const layerIds=graph.nodes.filter(n=>nodeKey(n)==='layerStack').flatMap(n=>n.layers.map(l=>l.id));if(new Set(layerIds).size!==layerIds.length)return false;const edges=normalizedMaterialEdges(graph),targets=new Set();for(const edge of edges){const from=graph.nodes.find(node=>node.id===edge?.from?.node),to=graph.nodes.find(node=>node.id===edge?.to?.node);if(!from||!to||from===to)return false;const output=materialPins(from,graph).outputs.find(pin=>pin.id===edge.from.pin),input=materialPins(to,graph).inputs.find(pin=>pin.id===edge.to.pin);if(!output||!input||output.type!==input.type&&(!['float','vec2','vec3','vec4'].includes(output.type)||!['float','vec2','vec3','vec4'].includes(input.type)||output.type!=='float'&&functionSpec(to)?.inputs.find(pin=>pin.id===input.id)?.type!=='numeric'))return false;const target=to.id+':'+input.id;if(targets.has(target))return false;targets.add(target);}
  const visiting=new Set(),done=new Set();const visit=id=>{if(visiting.has(id))return false;if(done.has(id))return true;visiting.add(id);if(!edges.filter(edge=>edge.from.node===id).every(edge=>visit(edge.to.node)))return false;visiting.delete(id);done.add(id);return true;};return graph.nodes.every(node=>visit(node.id));
}
export function validAssetPath(path){return typeof path==='string'&&path.length<=1000&&!/^(?:[A-Za-z]:|[\\/])/.test(path)&&!path.replaceAll('\\','/').split('/').includes('..')&&!/[\x00-\x1f]/.test(path);}
export function validMaterialSurface(surface){return surface&&/^#[0-9a-f]{6}$/i.test(surface.color)&&['roughness','metalness'].every(key=>finite(surface[key])&&surface[key]>=0&&surface[key]<=1)&&finite(surface.light)&&surface.light>=0&&surface.light<=10&&['opacity','ao','clearcoat','clearcoatRoughness','transmission'].every(key=>surface[key]===undefined||finite(surface[key])&&surface[key]>=0&&surface[key]<=1)&&(surface.ior===undefined||finite(surface.ior)&&surface.ior>=1&&surface.ior<=2.5)&&(surface.normal===undefined||Array.isArray(surface.normal)&&surface.normal.length===3&&surface.normal.every(finite))&&(surface.emissive===undefined||/^#[0-9a-f]{6}$/i.test(surface.emissive))&&(surface.emissiveIntensity===undefined||finite(surface.emissiveIntensity)&&surface.emissiveIntensity>=0)&&(surface.blendMode===undefined||['opaque','masked','translucent'].includes(surface.blendMode))&&(surface.alphaTest===undefined||finite(surface.alphaTest)&&surface.alphaTest>=0&&surface.alphaTest<=1)&&(surface.doubleSided===undefined||typeof surface.doubleSided==='boolean');}
export function connectMaterial(graph,from,to){const next=copy(graph);next.edges=normalizedMaterialEdges(next).filter(edge=>!(edge.to.node===to.node&&edge.to.pin===to.pin));next.edges.push({from:copy(from),to:copy(to)});if(!validMaterialGraph(next))return {ok:false,reason:'핀 자료형이나 순환 연결을 확인하세요.'};graph.edges=next.edges;return {ok:true};}
export function disconnectMaterial(graph,node,pin,direction){const edges=normalizedMaterialEdges(graph),next=edges.filter(edge=>edge[direction].node!==node||(pin&&edge[direction].pin!==pin));if(next.length===edges.length)return false;graph.edges=next;return true;}
export function removeMaterialNodes(graph,ids){const removable=new Set(graph.nodes.filter(node=>ids.has(node.id)&&nodeKey(node)!=='surface').map(node=>node.id));if(!removable.size)return false;graph.edges=normalizedMaterialEdges(graph).filter(edge=>!removable.has(edge.from.node)&&!removable.has(edge.to.node));graph.nodes=graph.nodes.filter(node=>!removable.has(node.id));return true;}
export function copyMaterialNodes(graph,ids){const nodes=graph.nodes.filter(node=>ids.has(node.id)&&nodeKey(node)!=='surface'),included=new Set(nodes.map(node=>node.id));return {type:'HBMaterialNodes',version:1,nodes:copy(nodes),edges:copy(normalizedMaterialEdges(graph).filter(edge=>included.has(edge.from.node)&&included.has(edge.to.node)))};}
export function pasteMaterialNodes(graph,clipboard,{x=100,y=100}={}){
  if(!clipboard||clipboard.type!=='HBMaterialNodes'||clipboard.version!==1||!Array.isArray(clipboard.nodes)||!clipboard.nodes.length||clipboard.nodes.length>1000||!Array.isArray(clipboard.edges)||clipboard.edges.length>5000||!finite(x)||!finite(y)||clipboard.nodes.some(node=>!node||nodeKey(node)==='surface'))return {ok:false,reason:'머테리얼 노드 복사 데이터를 확인하세요.'};
  const next=copy(graph),ids=new Map(clipboard.nodes.map(node=>[node.id,'mat_'+crypto.randomUUID().replaceAll('-','')]));if(ids.size!==clipboard.nodes.length)return {ok:false,reason:'복사한 노드 ID가 중복돼요.'};
  const left=Math.min(...clipboard.nodes.map(node=>node.px??node.x)),top=Math.min(...clipboard.nodes.map(node=>node.y));const nodes=copy(clipboard.nodes).map(node=>({...node,id:ids.get(node.id),px:(node.px??node.x)-left+x,y:node.y-top+y}));
  const edges=clipboard.edges.map(edge=>({from:{node:ids.get(edge?.from?.node),pin:edge?.from?.pin},to:{node:ids.get(edge?.to?.node),pin:edge?.to?.pin}}));for(const n of nodes){if(n.portName)n.portName=materialPortName(next,nodeKey(n),n.portName);if(nodeKey(n)==='layerStack'&&Array.isArray(n.layers))n.layers=n.layers.map(l=>({...l,id:newMaterialLayer(l?.asset,l?.name).id}));next.nodes.push(n);}next.edges.push(...edges);if(!validMaterialGraph(next))return {ok:false,reason:'복사한 노드 자료형이나 연결을 확인하세요.'};graph.nodes=next.nodes;graph.edges=next.edges;return {ok:true,nodes};
}
const rgb=color=>[1,3,5].map(index=>parseInt(color.slice(index,index+2),16)/255),hex=value=>'#'+value.slice(0,3).map(channel=>Math.round(clamp(channel)*255).toString(16).padStart(2,'0')).join('');
const vector=(value,size)=>Array.from({length:size},(_,index)=>Array.isArray(value)?value[index]??value[0]:value),map=(a,b,fn)=>Array.isArray(a)||Array.isArray(b)?vector(a,Math.max(a?.length||1,b?.length||1)).map((value,index)=>fn(value,vector(b,Math.max(a?.length||1,b?.length||1))[index])):fn(a,b);
const unit=v=>{const n=Math.hypot(...v);return v.map(x=>n?x/n:0);};
const hash2=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n);};
function noise2(uv){const [x,y]=uv,ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,u=fx*fx*(3-2*fx),v=fy*fy*(3-2*fy);return (hash2(ix,iy)*(1-u)+hash2(ix+1,iy)*u)*(1-v)+(hash2(ix,iy+1)*(1-u)+hash2(ix+1,iy+1)*u)*v;}
function operation(key,args){
  if(['cosine','floor','ceil','sign','exp2','log2','squareRoot'].includes(key))return map(args.value,0,({cosine:Math.cos,floor:Math.floor,ceil:Math.ceil,sign:Math.sign,exp2:x=>2**x,log2:x=>Math.log2(Math.max(x,1e-6)),squareRoot:x=>Math.sqrt(Math.max(x,0))})[key]);
  if(key==='smoothstep'){const t=map(map(args.value,args.min,(x,y)=>x-y),map(args.max,args.min,(x,y)=>Math.max(x-y,1e-6)),(x,y)=>clamp(x/y));return map(t,0,x=>x*x*(3-2*x));}
  if(key==='distance')return Math.hypot(...args.a.map((x,i)=>x-args.b[i]));
  if(key==='cross')return [args.a[1]*args.b[2]-args.a[2]*args.b[1],args.a[2]*args.b[0]-args.a[0]*args.b[2],args.a[0]*args.b[1]-args.a[1]*args.b[0]];
  if(key==='reflect'){const n=unit(args.normal),dot=args.direction.reduce((v,x,i)=>v+x*n[i],0);return args.direction.map((x,i)=>x-2*dot*n[i]);}
  if(key==='fresnel'){const n=unit(args.normal),v=unit(args.view),dot=clamp(n.reduce((s,x,i)=>s+x*v[i],0));return args.base+(1-args.base)*Math.pow(1-dot,Math.max(args.power,.0001));}
  if(key==='noise')return noise2(args.uv.map(x=>x*args.scale));
  if(key==='checker')return ((Math.floor(args.uv[0]*args.scale[0])+Math.floor(args.uv[1]*args.scale[1]))%2+2)%2;
  if(key==='radialGradient')return clamp(1-Math.hypot(...args.uv.map((x,i)=>x-args.center[i]))/Math.max(args.radius,1e-6));
  if(key==='linearGradient')return clamp((args.uv[0]-.5)*Math.cos(args.angle)+(args.uv[1]-.5)*Math.sin(args.angle)+.5);
  const a=args.a,b=args.b,v=args.value;if(key==='add')return map(a,b,(x,y)=>x+y);if(key==='subtract')return map(a,b,(x,y)=>x-y);if(key==='multiply')return map(a,b,(x,y)=>x*y);if(key==='divide')return map(a,b,(x,y)=>x/(Math.abs(y)<1e-6?1e-6:y));if(key==='power')return map(a,b,(x,y)=>Math.pow(Math.max(x,0),y));if(key==='min'||key==='max')return map(a,b,Math[key]);if(key==='step')return map(a,b,(x,y)=>y<x?0:1);if(key==='lerp')return map(a,b,(x,y)=>x+(y-x)*args.alpha);if(key==='clamp')return map(map(v,args.min,(x,y)=>Math.max(x,y)),args.max,(x,y)=>Math.min(x,y));if(key==='dot')return vector(a,3).reduce((sum,value,index)=>sum+value*vector(b,3)[index],0);if(key==='length')return Math.hypot(...(Array.isArray(v)?v:[v]));if(key==='normalize'){const length=Math.hypot(...(Array.isArray(v)?v:[v]));return map(v,1,x=>length?x/length:0);}if(key==='normalMap'){const n=vector(v,3).map(x=>x*2-1);n[0]*=args.strength;n[1]*=args.strength;return operation('normalize',{value:n});}if(key==='saturate')return map(v,0,x=>clamp(x));if(key==='oneMinus')return map(v,0,x=>1-x);if(key==='sine')return map(v,0,Math.sin);if(key==='absolute')return map(v,0,Math.abs);if(key==='fraction')return map(v,0,x=>x-Math.floor(x));if(key==='tilingOffset')return map(map(args.uv,args.tiling,(x,y)=>x*y),args.offset,(x,y)=>x+y);if(key==='panner')return map(args.uv,map(args.speed,args.time,(x,y)=>x*y),(x,y)=>x+y);if(key==='rotateUV'){const uv=vector(args.uv,2),center=args.center,c=Math.cos(args.angle),s=Math.sin(args.angle),x=uv[0]-center[0],y=uv[1]-center[1];return [x*c-y*s+center[0],x*s+y*c+center[1]];}throw Error('지원하지 않는 머테리얼 계산: '+key);}
export function evaluateMaterial(data,{uv=[0,0],time=0,worldPosition=[0,0,0],worldNormal=[0,0,1],viewDirection=[0,0,1],sampleTexture}={}){
  data=resolveMaterialAttributes(resolveMaterialInputs(data));const surface={...copy(materialDefaults),...copy(data.surface||{})},graph=data.graph;if(!graph)return surface;if(!validMaterialGraph(graph))throw Error('머테리얼 그래프 검증 실패');if(graph.mode==='function'||graph.nodes.some(n=>nodeKey(n)==='functionCall'))throw Error('머테리얼 함수를 resolveMaterialAsset으로 먼저 불러오세요.');const edges=normalizedMaterialEdges(graph),cache=new Map();
  const read=(id,output='value')=>{const token=id+':'+output;if(cache.has(token))return cache.get(token);const node=graph.nodes.find(node=>node.id===id),key=nodeKey(node);let value;if(key==='legacyColor')value=rgb(surface.color);else if(key==='legacyRough')value=surface.roughness;else if(['scalar','vector2','vector3','vector4','color','scalarParameter','vectorParameter'].includes(key)){value=data.parameters?.[materialParameterKey(node)]??node.value??.5;if(typeof value==='string')value=rgb(value);}else if(key==='uv')value=uv;else if(key==='time')value=time;else if(key==='worldPosition')value=worldPosition;else if(key==='worldNormal')value=unit(worldNormal);else if(key==='viewDirection')value=unit(viewDirection);else{const args={};for(const input of catalogMap.get(key).inputs.filter(p=>p.id!=='textureObject')){const edge=edges.find(edge=>edge.to.node===id&&edge.to.pin===input.id);args[input.id]=edge?read(edge.from.node,edge.from.pin):node.inputValues?.[input.id]??input.value??(input.id==='uv'?uv:input.id==='direction'&&key==='sampleCube'?unit(worldNormal):input.id==='time'?time:key==='fresnel'&&input.id==='normal'?worldNormal:key==='fresnel'&&input.id==='view'?viewDirection:0);}if(key==='split')value=vector(args.value,4)['xyzw'.indexOf(output)];else if(key==='combine')value=[args.x,args.y,args.z,args.w].slice(0,output.length);else if(materialTextureTypes[textureNodeType(key)]?.sample===key){const sample=sampleTexture?.(data.parameters?.[materialParameterKey(node)]??node.texture,args.uv??args.direction,node.colorSpace,{type:textureNodeType(key),index:args.index,lod:args.lod})||[1,1,1,1];value=output==='rgba'?sample:output==='rgb'?sample.slice(0,3):sample['rgba'.indexOf(output)]??1;}else value=operation(key,args);}cache.set(token,value);return value;};
  const output=graph.nodes.find(node=>nodeKey(node)==='surface');if(!output)return surface;for(const input of surfaceInputs){const edge=edges.find(edge=>edge.to.node===output.id&&edge.to.pin===input.id);if(!edge)continue;const value=read(edge.from.node,edge.from.pin);if(input.id==='baseColor'||input.id==='emissive')surface[input.key]=hex(vector(value,3));else if(input.id==='normal')surface.normal=vector(value,3);else surface[input.key]=clamp(Number(Array.isArray(value)?value[0]:value),input.id==='ior'?1:0,input.id==='ior'?2.5:1);}return surface;
}
export function materialParameters(data){const edges=data.graph?normalizedMaterialEdges(data.graph):[];return [...new Map([...(data.parameterDescriptors||[]).map(p=>[p.name,{...copy(p),value:copy(data.parameters?.[p.name]??p.value)}]),...(data.graph?.nodes||[]).filter(n=>{const k=nodeKey(n);return n.parameter&&(!(materialTextureTypes[textureNodeType(k)]?.sample===k)||!edges.some(e=>e.to.node===n.id&&e.to.pin==='textureObject')&&!Object.hasOwn(n.inputValues||{},'textureObject'));}).map(node=>{const k=nodeKey(node),t=textureNodeType(k);return [materialParameterKey(node),{name:materialParameterKey(node),label:node.parameter,scope:copy(node.parameterScope),type:k==='scalarParameter'?'float':t?(t==='texture2d'?'texture':t):k==='staticBoolParameter'?'bool':'vec3',value:copy(data.parameters?.[materialParameterKey(node)]??node.texture??node.value)}];})]).values()];}

export const materialPresets={fresnel:'Fresnel · 가장자리 발광',dissolve:'Dissolve · 소멸 마스크',checker:'Checker · 체크 표면',scroll:'Panner · 흐르는 텍스처'};
export function makeMaterialPreset(key){
  if(!Object.hasOwn(materialPresets,key))throw Error('머테리얼 템플릿을 확인하세요.');
  const data={surface:copy(materialDefaults),graph:{nodes:[],edges:[]}};
  const add=(key,id,x,y,values={})=>{const node={...makeMaterialNode(key,x,y),id,...values};data.graph.nodes.push(node);return node;};
  const wire=(from,pin,to,input)=>{const result=connectMaterial(data.graph,{node:from.id,pin},{node:to.id,pin:input});if(!result.ok)throw Error(result.reason);};
  const output=add('surface','surface',900,80);
  if(key==='fresnel'){
    const fresnel=add('fresnel','edge',60,80),color=add('vectorParameter','tint',60,350,{parameter:'EdgeColor',value:[.1,.5,1]}),multiply=add('multiply','emission',540,180),power=add('scalarParameter','falloff',60,560,{parameter:'Falloff',value:5});
    wire(power,'value',fresnel,'power');wire(fresnel,'value',multiply,'a');wire(color,'value',multiply,'b');wire(multiply,'value',output,'emissive');data.surface.color='#111c28';data.surface.emissiveIntensity=3;
  }else if(key==='dissolve'){
    const noise=add('noise','noise',40,50),amount=add('scalarParameter','amount',40,280,{parameter:'Dissolve',value:.45}),mask=add('step','mask',460,80),edge=add('subtract','edge',460,350),width=add('smoothstep','edgeMask',710,400);
    wire(amount,'value',mask,'a');wire(noise,'value',mask,'b');wire(mask,'value',output,'opacity');wire(noise,'value',edge,'a');wire(amount,'value',edge,'b');width.inputValues={min:0,max:.12};wire(edge,'value',width,'value');wire(width,'value',output,'roughness');data.surface.blendMode='masked';data.surface.color='#d39347';
  }else if(key==='checker'){
    const checker=add('checker','pattern',40,80),a=add('vectorParameter','colorA',40,310,{parameter:'ColorA',value:[.08,.13,.18]}),b=add('vectorParameter','colorB',40,480,{parameter:'ColorB',value:[.7,.8,.85]}),mix=add('lerp','mix',470,150);
    wire(a,'value',mix,'a');wire(b,'value',mix,'b');wire(checker,'value',mix,'alpha');wire(mix,'value',output,'baseColor');
  }else{
    const uv=add('panner','scroll',50,70),texture=add('texture','texture',470,100);wire(uv,'value',texture,'uv');wire(texture,'rgb',output,'baseColor');
  }
  return data;
}
export async function resolveMaterialAsset(data,read){
  const authored=async(d,seen=new Set())=>{
    if(!d.parent){if(d.surfaceOverrides)throw Error('부모 머테리얼을 선택하세요.');return copy(d);}
    if(!validAssetPath(d.parent)||seen.has(d.parent)||seen.size>=16)throw Error('머테리얼 인스턴스 부모가 순환하거나 너무 깊어요.');seen.add(d.parent);
    const parent=await read(d.parent);if(!parent||parent.version!==1||!parent.parent&&!validMaterialSurface(parent.surface)||parent.graph?.mode==='function')throw Error('부모 머테리얼을 확인하세요.');
    const base=await authored(parent,seen);base.materialDependencies=[...new Set([...(base.materialDependencies||[]),d.parent])];base.name=d.name;base.parameters={...base.parameters,...copy(d.parameters||{})};base.surface={...base.surface,...copy(d.surfaceOverrides||{})};base.graph??=materialGraph();
    for(const [id,layers] of Object.entries(d.layerStacks||{})){const n=base.graph.nodes.find(n=>nodeKey(n)==='layerStack'&&n.id===id);if(!n||!validMaterialLayers(layers)||n.layers[0]&&layers[0]?.id!==n.layers[0].id)throw Error('인스턴스 레이어 스택을 확인하세요: '+id);n.layers=copy(layers);}
    const output=base.graph.nodes.find(n=>nodeKey(n)==='surface');
    for(const input of surfaceInputs){if(!Object.hasOwn(d.surfaceOverrides||{},input.key))continue;
      if(output.useAttributes){const set=makeMaterialNode('setAttributes');set.fields=[input.id];if(typeof d.surfaceOverrides[input.key]==='string'){const color=makeMaterialNode('color');color.value=d.surfaceOverrides[input.key];base.graph.nodes.push(color);base.graph.edges.push({from:{node:color.id,pin:'value'},to:{node:set.id,pin:input.id}});}else set.inputValues[input.id]=copy(d.surfaceOverrides[input.key]);const edges=normalizedMaterialEdges(base.graph),wire=edges.find(e=>e.to.node===output.id&&e.to.pin==='attributes');base.graph.nodes.push(set);base.graph.edges=edges.filter(e=>e!==wire);if(wire)base.graph.edges.push({from:wire.from,to:{node:set.id,pin:'attributes'}});base.graph.edges.push({from:{node:set.id,pin:'value'},to:{node:output.id,pin:'attributes'}});
      }else{const id='hb_instance_'+input.key;base.graph.nodes=base.graph.nodes.filter(n=>n.id!==id);base.graph.nodes.push({id,key:input.type==='vec3'?(input.id==='normal'?'vector3':'color'):'scalar',title:input.label,kind:'value',x:80,y:80,value:copy(d.surfaceOverrides[input.key])});base.graph.edges=normalizedMaterialEdges(base.graph).filter(e=>!(e.to.node===output.id&&e.to.pin===input.id));base.graph.edges.push({from:{node:id,pin:'value'},to:{node:output.id,pin:input.id}});}
    }
    return base;
  };
  let base=await authored(data);base=await resolveMaterialLayers(base,read);base=await resolveMaterialFunctions(base,read);base=resolveMaterialAttributes(resolveMaterialInputs(base));
  for(const parameter of materialParameters(base)){if(!Object.hasOwn(base.parameters||{},parameter.name))continue;const value=base.parameters[parameter.name];if(parameter.type==='bool'?typeof value!=='boolean':(parameter.type==='texture'||materialTextureTypes[parameter.type])?!validAssetPath(value):parameter.type==='vec3'?!Array.isArray(value)||value.length!==3||!value.every(finite):!finite(value))throw Error('머테리얼 파라미터 자료형을 확인하세요: '+parameter.name);}const resources={};for(const b of base.graph?.nodes.some(n=>['sampleCube','sampleArray','sampleVolume'].includes(nodeKey(n)))?compileMaterial(base).textures:[]){if(b.type==='texture2d'||!b.path)continue;if(!resources[b.path])resources[b.path]=validateTextureImages(materialTextureTypes[b.type].kind,await read(b.path));else validateTextureImages(materialTextureTypes[b.type].kind,resources[b.path]);}if(Object.keys(resources).length){base.textureAssets=copy(resources);base.materialDependencies=[...new Set([...base.materialDependencies||[],...Object.keys(resources),...Object.values(resources).flatMap(d=>d.images)])];}return base;
}
export function materialLayerGraph(blend=false){
  const input=(id,name)=>({...makeMaterialNode('functionInput'),id,portName:name,valueType:'attributes',value:{},useDefault:true}),output={...makeMaterialNode('functionOutput',620,100),id:'result',portName:'Material Attributes',valueType:'attributes'};
  if(!blend){const source=input('input','Input'),set=makeMaterialNode('setAttributes',320,100);set.fields=['baseColor'];set.inputValues.baseColor=[.5,.5,.5];return {mode:'function',nodes:[source,set,output],edges:[{from:{node:'input',pin:'value'},to:{node:set.id,pin:'attributes'}},{from:{node:set.id,pin:'value'},to:{node:'result',pin:'value'}}]};}
  const bottom=input('bottom','Bottom'),top=input('top','Top'),mask={...makeMaterialNode('scalarParameter',60,430),id:'mask',parameter:'Alpha',value:.5},mix=makeMaterialNode('blendAttributes',340,100);top.y=240;
  return {mode:'function',nodes:[bottom,top,mask,mix,output],edges:[...['bottom','top'].map(id=>({from:{node:id,pin:'value'},to:{node:mix.id,pin:id}})),{from:{node:mask.id,pin:'value'},to:{node:mix.id,pin:'alpha'}},{from:{node:mix.id,pin:'value'},to:{node:'result',pin:'value'}}]};
}
export function validMaterialLayer(data,blend=false){if(!validMaterialFunction(data)||data.domain!==(blend?'blend':'layer'))return false;const s=materialFunctionSignature(data.graph),ids=blend?['bottom','top']:['input'];return s.inputs.length===ids.length&&ids.every(id=>s.inputs.some(p=>p.id===id&&p.type==='attributes'))&&s.outputs.length===1&&s.outputs[0].id==='result'&&s.outputs[0].type==='attributes';}
export async function materialLayerParameters(stacks,read){
  const definitions=new Map(),items=[];
  for(const entry of Object.values(stacks).flat())for(const domain of ['layer','blend']){const path=domain==='layer'?entry.asset:entry.blend;if(!path)continue;
    if(!definitions.has(path)){const d=await read(path);if(!validMaterialLayer(d,domain==='blend'))throw Error('머테리얼 레이어 에셋 오류: '+path);definitions.set(path,materialParameters(await resolveMaterialAsset(d,read)));}
    const overrides=domain==='layer'?entry.parameters:entry.blendParameters;
    for(const p of definitions.get(path)){const v=overrides[p.label]??p.value,valid=p.type==='bool'?typeof v==='boolean':(p.type==='texture'||materialTextureTypes[p.type])?validAssetPath(v):p.type==='vec3'?Array.isArray(v)&&v.length===3&&v.every(finite):finite(v);items.push({...p,name:materialLayerParameterKey(entry.id,p.label,domain==='blend'),scope:{id:entry.id,domain},value:copy(valid?v:p.value)});}
  }return items;
}
export async function resolveMaterialLayers(data,read){
  const g=data.graph;if(!g?.nodes.some(n=>nodeKey(n)==='layerStack'))return data;if(!validMaterialGraph(g))throw Error('머테리얼 레이어 그래프 검증 실패');
  const stacks={},definitions=new Map(),dependencies=new Set(),nodes=g.nodes.filter(n=>nodeKey(n)!=='layerStack').map(copy),edges=normalizedMaterialEdges(g).filter(e=>!g.nodes.some(n=>nodeKey(n)==='layerStack'&&(n.id===e.from.node||n.id===e.to.node))),aliases=new Map();let serial=0;
  const load=async(path,blend)=>{if(!definitions.has(path))definitions.set(path,await read(path));const d=definitions.get(path);if(!validMaterialLayer(d,blend))throw Error('머테리얼 '+(blend?'블렌드':'레이어')+' 에셋 오류: '+path);dependencies.add(path);return d;};
  const id=()=>{let next;do{next='ml_'+serial++;}while(g.nodes.some(n=>n.id===next)||nodes.some(n=>n.id===next));return next;};
  const call=async(entry,path,blend,args)=>{const d=await load(path,blend),n=makeMaterialFunctionCall(path,d);n.id=id();n.parameterScope={id:entry.id,domain:blend?'blend':'layer'};nodes.push(n);for(const [pin,from] of Object.entries(args))edges.push({from,to:{node:n.id,pin}});for(const [name,value] of Object.entries(blend?entry.blendParameters:entry.parameters)){data.parameters??={};data.parameters[materialLayerParameterKey(entry.id,name,blend)]=copy(value);}return {node:n.id,pin:'result'};};
  for(const n of g.nodes.filter(n=>nodeKey(n)==='layerStack')){stacks[n.id]=copy(n.layers);const incoming=normalizedMaterialEdges(g).find(e=>e.to.node===n.id&&e.to.pin==='attributes');let common=incoming?.from;if(!common){const make=makeMaterialNode('makeAttributes');make.id=id();make.inputValues=copy(n.inputValues?.attributes||{});nodes.push(make);common={node:make.id,pin:'value'};}let result=common;
    for(const entry of n.layers.filter(l=>l.enabled)){const top=await call(entry,entry.asset,false,{input:common});result=entry.blend?await call(entry,entry.blend,true,{bottom:result,top}):top;}aliases.set(n.id,result);
  }
  const resolve=ref=>{const seen=new Set();while(aliases.has(ref.node)){if(seen.has(ref.node))throw Error('머테리얼 레이어 순환');seen.add(ref.node);ref=aliases.get(ref.node);}return ref;};
  for(const e of normalizedMaterialEdges(g))if(aliases.has(e.from.node)&&!aliases.has(e.to.node))edges.push({from:resolve(e.from),to:copy(e.to)});
  const graph={...g,nodes,edges:edges.map(e=>({from:resolve(e.from),to:e.to}))};if(!validMaterialGraph(graph))throw Error('머테리얼 레이어 그래프 한도 또는 연결 오류');return {...data,graph,layerStacks:stacks,layerDependencies:[...dependencies]};
}
// A view-only upstream slice; authored IDs, values and graph remain unchanged.
export function materialPreviewGraph(data,selection){
  if(!validMaterialGraph(data?.graph)||!validMaterialSurface(data.surface)||!selection||typeof selection.node!=='string'||selection.pin!==undefined&&typeof selection.pin!=='string')throw Error('미리보기 노드와 출력 핀을 확인하세요.');
  const g=data.graph,node=g.nodes.find(n=>n.id===selection.node),wires=normalizedMaterialEdges(g);if(!node)throw Error('미리보기 노드가 없어요.');
  const output=nodeKey(node)==='functionOutput',pins=materialPins(node,g)[output?'inputs':'outputs'],p=pins.find(p=>p.id===(selection.pin??pins[0]?.id));if(!p)throw Error('미리보기 출력 핀을 확인하세요.');
  const selected={node:node.id,pin:p.id,type:p.type,label:p.label},nodes=[],edges=[],keep=new Set();let serial=0;
  const visit=id=>{if(keep.has(id))return;keep.add(id);for(const e of wires.filter(e=>e.to.node===id))visit(e.from.node);};
  let source={node:node.id,pin:p.id};const edge=output&&wires.find(e=>e.to.node===node.id&&e.to.pin===p.id);if(edge)source=copy(edge.from);if(!output||edge)visit(source.node);
  nodes.push(...g.nodes.filter(n=>keep.has(n.id)).map(copy));edges.push(...wires.filter(e=>keep.has(e.from.node)&&keep.has(e.to.node)).map(copy));
  const add=(key,values={})=>{const n=makeMaterialNode(key);do{n.id='mp_'+serial++;}while(g.nodes.some(v=>v.id===n.id));Object.assign(n,values);nodes.push(n);return n;},wire=(from,n,pin)=>edges.push({from:copy(from),to:{node:n.id,pin}});
  if(output&&!edge){const value=copy(node.inputValues?.value??materialLiteralDefault(p.type)),n=add(p.type==='attributes'?'makeAttributes':materialTextureTypes[p.type]?.object||(p.type==='staticBool'?'staticBool':p.type==='float'?'scalar':'vector'+p.type.slice(3)),p.type==='attributes'?{inputValues:value}:materialTextureTypes[p.type]?{texture:value}:{value});source={node:n.id,pin:'value'};}
  if(materialTextureTypes[p.type]){const n=add(materialTextureTypes[p.type].sample);delete n.parameter;wire(source,n,'textureObject');source={node:n.id,pin:'rgb'};}
  else if(p.type==='staticBool'){const n=add('staticSwitch',{inputValues:{a:1,b:0}});wire(source,n,'condition');source={node:n.id,pin:'value'};}
  else if(p.type==='vec2'||p.type==='vec4'){const pad=add('add',{inputValues:{b:[0,0,0,0]}}),split=add('split'),combine=add('combine');wire(source,pad,'a');wire({node:pad.id,pin:'value'},split,'value');for(const id of p.type==='vec2'?['x','y']:['x','y','z'])wire({node:split.id,pin:id},combine,id);source={node:combine.id,pin:'rgb'};}
  const root=add(g.mode==='function'?'functionOutput':'surface',g.mode==='function'?{portName:'Preview',valueType:p.type==='attributes'?'attributes':'vec3'}:{useAttributes:p.type==='attributes'});wire(source,root,g.mode==='function'?'value':p.type==='attributes'?'attributes':'baseColor');
  const preview={...copy(data),graph:{...(g.mode?{mode:g.mode}:{}),nodes,edges},...(g.mode?{previewOutput:root.id}:{})};delete preview.parent;delete preview.domain;
  if(p.type!=='attributes')preview.surface={...materialDefaults,color:'#000000',roughness:1,metalness:0,emissiveIntensity:1};
  if(!validMaterialGraph(preview.graph))throw Error('미리보기 그래프 연결이나 한도를 확인하세요.');return {data:preview,selection:selected};
}
export async function resolveMaterialPreview(data,selection,read){
  const preview=materialPreviewGraph(data,selection),resolved=await resolveMaterialAsset(preview.data,read);
  if(preview.selection.type!=='attributes'){const root=resolved.graph.nodes.find(n=>nodeKey(n)==='surface');resolved.graph.edges=normalizedMaterialEdges(resolved.graph).map(e=>e.to.node===root.id&&e.to.pin==='baseColor'?{from:e.from,to:{node:root.id,pin:'emissive'}}:e);}
  return {data:resolved,selection:preview.selection};
}
export async function resolveMaterialFunctions(data,read){
  const graph=data.graph;if(!graph||graph.mode!=='function'&&!graph.nodes?.some(n=>nodeKey(n)==='functionCall'))return data;
  if(!validMaterialGraph(graph))throw Error('머테리얼 함수 그래프 검증 실패');const definitions=new Map(),loaded=new Set();
  const load=async(g,stack=[])=>{for(const n of g.nodes.filter(n=>nodeKey(n)==='functionCall')){if(stack.includes(n.asset)||stack.length>=16)throw Error('머테리얼 함수 의존성이 순환하거나 너무 깊어요: '+n.asset);if(!definitions.has(n.asset)){const d=await read(n.asset);if(!validMaterialFunction(d))throw Error('머테리얼 함수 에셋 오류: '+n.asset);definitions.set(n.asset,d);}const d=definitions.get(n.asset),signature=materialFunctionSignature(d.graph);
    for(const side of ['inputs','outputs'])if(n.signature[side].length!==signature[side].length||n.signature[side].some(p=>!signature[side].some(v=>p.id===v.id&&p.type===v.type)))throw Error('머테리얼 함수 핀이 변경됐어요. 핀을 갱신하세요: '+n.asset);
    if(!loaded.has(n.asset)){await load(d.graph,[...stack,n.asset]);loaded.add(n.asset);}}};await load(graph);
  // ponytail: inline expansion uses the existing 1000-node compile budget; shared subexpressions if shader size becomes a measured bottleneck.
  const nodes=[],edges=[],aliases=new Map();let serial=0;const refKey=r=>r.node+':'+r.pin;
  const constant=(type,value)=>{if(type==='attributes'){const n=makeMaterialNode('makeAttributes');n.id='mf_'+serial++;n.inputValues=copy(value);nodes.push(n);return {node:n.id,pin:'value'};}const n={...makeMaterialNode(materialTextureTypes[type]?.object||(type==='staticBool'?'staticBool':type==='float'?'scalar':'vector'+type.slice(3))),id:'mf_'+serial++,...(materialTextureTypes[type]?{texture:value}:{value:copy(type==='staticBool'||type==='float'?value:vector(value,Number(type.slice(3))))})};nodes.push(n);return {node:n.id,pin:'value'};};
  const expand=(g,bindings=new Map(),preview=false,scope)=>{
    if(nodes.length+g.nodes.length>1000)throw Error('펼친 머테리얼 함수가 그래프 한도를 넘어요.');const ids=new Map(g.nodes.map(n=>[n.id,'mf_'+serial++])),local=r=>({node:ids.get(r.node),pin:r.pin}),wires=normalizedMaterialEdges(g),results=new Map();
    for(const n of g.nodes){const key=nodeKey(n),id=ids.get(n.id);
      if(key==='functionCall'){
        const d=definitions.get(n.asset),args=new Map();for(const p of materialFunctionSignature(d.graph).inputs){const edge=wires.find(e=>e.to.node===n.id&&e.to.pin===p.id);if(edge)args.set(p.id,local(edge.from));else if(Object.hasOwn(n.inputValues||{},p.id))args.set(p.id,constant(p.type,n.inputValues[p.id]));}
        const output=expand(d.graph,args,false,n.parameterScope||scope);for(const [port,value] of output)aliases.set(id+':'+port,value);continue;
      }
      if(key==='functionInput'||key==='functionOutput'){
        let value;if(key==='functionInput'){value=bindings.get(n.id);if(!value){if(!preview&&!n.useDefault)throw Error('머테리얼 함수 필수 입력을 연결하세요: '+n.portName);const edge=wires.find(e=>e.to.node===n.id&&e.to.pin==='preview');value=edge?local(edge.from):constant(n.valueType,n.inputValues?.preview??n.value);}}
        else{const edge=wires.find(e=>e.to.node===n.id&&e.to.pin==='value');value=edge?local(edge.from):constant(n.valueType,n.inputValues?.value??materialLiteralDefault(n.valueType));results.set(n.id,{node:id,pin:'value'});}
        if(['attributes','staticBool',...Object.keys(materialTextureTypes)].includes(n.valueType)){aliases.set(id+':value',value);continue;}nodes.push({...makeMaterialNode('multiply',n.x,n.y),id,title:n.portName,inputValues:{b:n.valueType==='float'?1:vector(1,Number(n.valueType.slice(3)))}});edges.push({from:value,to:{node:id,pin:'a'}});continue;
      }
      nodes.push({...copy(n),id,...scope&&n.parameter?{parameterScope:copy(scope)}:{}});
    }
    for(const e of wires){const to=g.nodes.find(n=>n.id===e.to.node);if(['functionCall','functionInput','functionOutput'].includes(nodeKey(to)))continue;edges.push({from:local(e.from),to:local(e.to)});}return results;
  };
  const results=expand(graph,new Map(),graph.mode==='function');
  if(graph.mode==='function'){const signature=materialFunctionSignature(graph),output=signature.outputs.find(p=>p.id===data.previewOutput)||signature.outputs[0],surface=makeMaterialNode('surface');surface.id='mf_'+serial++;nodes.push(surface);surface.useAttributes=output.type==='attributes';const input=output.type==='attributes'?'attributes':output.type==='float'||output.type==='staticBool'?'roughness':'baseColor';let source=results.get(output.id);
    if(materialTextureTypes[output.type]){const sample=makeMaterialNode(materialTextureTypes[output.type].sample);sample.id='mf_'+serial++;delete sample.parameter;nodes.push(sample);edges.push({from:source,to:{node:sample.id,pin:'textureObject'}});source={node:sample.id,pin:'rgb'};}else if(output.type==='staticBool'){const choose=makeMaterialNode('staticSwitch');choose.id='mf_'+serial++;choose.inputValues={a:1,b:0};nodes.push(choose);edges.push({from:source,to:{node:choose.id,pin:'condition'}});source={node:choose.id,pin:'value'};}
    if(output.type==='vec2'||output.type==='vec4'){const pad=makeMaterialNode('add'),split=makeMaterialNode('split'),combine=makeMaterialNode('combine');pad.id='mf_'+serial++;pad.inputValues.b=[0,0,0,0];split.id='mf_'+serial++;combine.id='mf_'+serial++;nodes.push(pad,split,combine);edges.push({from:source,to:{node:pad.id,pin:'a'}},{from:{node:pad.id,pin:'value'},to:{node:split.id,pin:'value'}});for(const pin of output.type==='vec2'?['x','y']:['x','y','z'])edges.push({from:{node:split.id,pin},to:{node:combine.id,pin}});source={node:combine.id,pin:'rgb'};}
    edges.push({from:source,to:{node:surface.id,pin:input}});
  }
  const resolve=r=>{const seen=new Set();while(aliases.has(refKey(r))){if(seen.has(refKey(r)))throw Error('머테리얼 함수 핀 순환');seen.add(refKey(r));r=aliases.get(refKey(r));}return r;};
  const expanded={nodes,edges:edges.map(e=>({from:resolve(e.from),to:resolve(e.to)}))};if(!validMaterialGraph(expanded))throw Error('펼친 머테리얼 함수 자료형이나 연결을 확인하세요.');return {...data,graph:expanded,functionDependencies:[...definitions.keys()]};
}
// Typed resource and compile-time inputs lower into the existing numeric sampler graph.
export function resolveMaterialInputs(data){
  const graph=data.graph,typed=[...Object.values(materialTextureTypes).flatMap(v=>[v.object,v.parameter]),'staticBool','staticBoolParameter','staticSwitch'];
  if(!graph||!graph.nodes.some(n=>typed.includes(nodeKey(n))||materialTextureTypes[textureNodeType(nodeKey(n))]?.sample===nodeKey(n)&&(Object.hasOwn(n.inputValues||{},'textureObject')||normalizedMaterialEdges(graph).some(e=>e.to.node===n.id&&e.to.pin==='textureObject'))))return data;
  if(!validMaterialGraph(graph)||graph.mode==='function'||graph.nodes.some(n=>nodeKey(n)==='functionCall'))throw Error('머테리얼 함수를 resolveMaterialAsset으로 먼저 불러오세요.');
  const wires=normalizedMaterialEdges(graph),nodes=graph.nodes.filter(n=>!typed.includes(nodeKey(n))).map(copy),aliases=new Map(),cache=new Map(),visiting=new Set(),keyOf=r=>r.node+':'+r.pin,parameterDescriptors=materialParameters(data);
  for(const p of parameterDescriptors){const v=data.parameters?.[p.name]??p.value;if(p.type==='bool'?typeof v!=='boolean':(p.type==='texture'||materialTextureTypes[p.type])?!validAssetPath(v):p.type==='vec3'?!Array.isArray(v)||v.length!==3||!v.every(finite):!finite(v))throw Error('머테리얼 파라미터 자료형을 확인하세요: '+p.name);}
  const input=(n,id,type)=>{const e=wires.find(e=>e.to.node===n.id&&e.to.pin===id);return e?resource(e.from,type):n.inputValues?.[id]??materialLiteralDefault(type);};
  const resource=(r,type)=>{const token=keyOf(r);if(cache.has(token))return cache.get(token);if(visiting.has(token))throw Error('머테리얼 정적 입력 순환');visiting.add(token);const n=graph.nodes.find(n=>n.id===r.node),key=nodeKey(n);let value;
    if(key==='staticSwitch')value=input(n,input(n,'condition','staticBool')?'a':'b',type);
    else if(type==='staticBool'&&['staticBool','staticBoolParameter'].includes(key))value=data.parameters?.[materialParameterKey(n)]??n.value;
    else if(materialTextureTypes[type]&&[materialTextureTypes[type].object,materialTextureTypes[type].parameter].includes(key))value=data.parameters?.[materialParameterKey(n)]??n.texture;
    else throw Error('머테리얼 정적 입력 자료형을 확인하세요.');
    if(!typedLiteral(type,value))throw Error('머테리얼 정적 입력 값을 확인하세요.');visiting.delete(token);cache.set(token,value);return value;
  };
  for(const n of graph.nodes.filter(n=>nodeKey(n)==='staticSwitch')){if(['staticBool',...Object.keys(materialTextureTypes)].includes(n.valueType))continue;const selected=input(n,'condition','staticBool')?'a':'b',edge=wires.find(e=>e.to.node===n.id&&e.to.pin===selected),type=materialPins(n,graph).outputs[0].type;
    if(type==='attributes'){if(edge)aliases.set(n.id+':value',edge.from);else{const value=makeMaterialNode('makeAttributes');value.inputValues=copy(n.inputValues?.[selected]||{});nodes.push(value);aliases.set(n.id+':value',{node:value.id,pin:'value'});}}
    else{const value={...makeMaterialNode('multiply',n.x,n.y),id:n.id,inputValues:{b:type==='float'?1:vector(1,Number(type.slice(3)))}};nodes.push(value);if(!edge)value.inputValues.a=copy(n.inputValues?.[selected]??materialLiteralDefault(type));}
  }
  const resolve=r=>{const seen=new Set();while(aliases.has(keyOf(r))){if(seen.has(keyOf(r)))throw Error('머테리얼 정적 분기 순환');seen.add(keyOf(r));r=aliases.get(keyOf(r));}return r;};
  for(const n of nodes.filter(n=>materialTextureTypes[textureNodeType(nodeKey(n))]?.sample===nodeKey(n))){const original=graph.nodes.find(v=>v.id===n.id),edge=original&&wires.find(e=>e.to.node===n.id&&e.to.pin==='textureObject');if(edge||Object.hasOwn(n.inputValues||{},'textureObject')){n.texture=edge?resource(edge.from,textureNodeType(nodeKey(n))):n.inputValues.textureObject;delete n.parameter;delete n.inputValues.textureObject;}}
  const kept=new Set(nodes.map(n=>n.id)),edges=wires.filter(e=>kept.has(e.to.node)&&!(graph.nodes.find(n=>n.id===e.to.node)?.key==='staticSwitch'&&e.to.pin!=='a')&&e.to.pin!=='textureObject').map(e=>({from:resolve(e.from),to:copy(e.to)}));
  // The original switch input A may be the inactive branch; only the generated chosen edge survives.
  for(const n of graph.nodes.filter(n=>n.key==='staticSwitch'&&!['attributes','staticBool',...Object.keys(materialTextureTypes)].includes(n.valueType))){const chosen=nodes.find(v=>v.id===n.id);const selected=input(n,'condition','staticBool')?'a':'b',source=normalizedMaterialEdges(graph).find(e=>e.to.node===n.id&&e.to.pin===selected);for(let i=edges.length-1;i>=0;i--)if(edges[i].to.node===n.id)edges.splice(i,1);if(source)edges.push({from:resolve(source.from),to:{node:chosen.id,pin:'a'}});}
  const result={...data,parameterDescriptors,graph:{nodes,edges}};if(!validMaterialGraph(result.graph))throw Error('머테리얼 정적 입력 변환 결과를 확인하세요.');return result;
}
export function extractMaterialFunction(data,ids,asset,name,positions={}){
  if(!validMaterialGraph(data.graph)||!Array.isArray(ids)||!ids.length||new Set(ids).size!==ids.length||ids.some(id=>!data.graph.nodes.some(n=>n.id===id))||!validAssetPath(asset)||!asset.endsWith('.hbmaterialfunction.json')||!portName(name))throw Error('함수로 묶을 노드와 에셋 경로를 확인하세요.');
  const chosen=new Set(ids),selected=data.graph.nodes.filter(n=>chosen.has(n.id));if(selected.some(n=>['surface','functionInput','functionOutput','layerStack','legacyColor','legacyRough'].includes(nodeKey(n))))throw Error('출력·함수 경계·레이어 스택·기존 표면 노드를 제외하고 선택하세요.');
  const wires=normalizedMaterialEdges(data.graph),point=n=>positions[n.id]||{x:n.px??n.x,y:n.y},left=Math.min(...selected.map(n=>point(n).x)),top=Math.min(...selected.map(n=>point(n).y));if(!finite(left)||!finite(top))throw Error('노드 위치를 확인하세요.');
  const fn={version:1,name,description:'',category:'사용자 함수',expose:true,surface:copy(data.surface),graph:{mode:'function',nodes:selected.map(n=>({...copy(n),x:Math.min(8000,point(n).x-left+300),px:Math.min(8000,point(n).x-left+300),y:Math.min(8000,point(n).y-top+80)})),edges:copy(wires.filter(e=>chosen.has(e.from.node)&&chosen.has(e.to.node)))}};
  const incoming=wires.filter(e=>!chosen.has(e.from.node)&&chosen.has(e.to.node)),outgoing=wires.filter(e=>chosen.has(e.from.node)&&!chosen.has(e.to.node)),inputs=new Map(),outputs=new Map(),token=r=>r.node+':'+r.pin;
  for(const edge of incoming){const key=token(edge.from);let boundary=inputs.get(key);if(!boundary){const source=data.graph.nodes.find(n=>n.id===edge.from.node),p=materialPins(source,data.graph).outputs.find(p=>p.id===edge.from.pin);boundary={...makeMaterialNode('functionInput',30,80+inputs.size*180),portName:materialPortName(fn.graph,'functionInput',(source.parameter||source.portName||source.title).split(' · ')[0]),valueType:p.type,value:copy(typedLiteral(p.type,data.parameters?.[materialParameterKey(source)]??source.texture??source.value)?data.parameters?.[materialParameterKey(source)]??source.texture??source.value:materialLiteralDefault(p.type)),useDefault:false,priority:inputs.size};inputs.set(key,boundary);fn.graph.nodes.push(boundary);}fn.graph.edges.push({from:{node:boundary.id,pin:'value'},to:copy(edge.to)});}
  const expose=ref=>{const key=token(ref);if(outputs.has(key))return outputs.get(key);const source=data.graph.nodes.find(n=>n.id===ref.node),p=materialPins(source,data.graph).outputs.find(p=>p.id===ref.pin),boundary={...makeMaterialNode('functionOutput',Math.min(9500,Math.max(...fn.graph.nodes.map(n=>n.px??n.x))+280),80+outputs.size*180),portName:materialPortName(fn.graph,'functionOutput',p.label==='Value'?'Result':p.label.split(' · ')[0]),valueType:p.type,priority:outputs.size};outputs.set(key,boundary);fn.graph.nodes.push(boundary);fn.graph.edges.push({from:copy(ref),to:{node:boundary.id,pin:'value'}});return boundary;};
  for(const edge of outgoing)expose(edge.from);if(!outputs.size)for(const n of selected.filter(n=>!wires.some(e=>e.from.node===n.id&&chosen.has(e.to.node))))for(const p of materialPins(n,data.graph).outputs)expose({node:n.id,pin:p.id});
  if(selected.some(n=>nodeKey(n)==='functionCall'&&n.asset===asset))throw Error('머테리얼 함수가 자기 자신을 참조해요.');
  if(!validMaterialFunction(fn))throw Error('선택 노드의 함수 경계나 그래프 한도를 확인하세요.');const call=makeMaterialFunctionCall(asset,fn,left,top),next=copy(data);next.graph.nodes=next.graph.nodes.filter(n=>!chosen.has(n.id));next.graph.nodes.push(call);next.graph.edges=copy(wires.filter(e=>!chosen.has(e.from.node)&&!chosen.has(e.to.node)));
  for(const [key,n] of inputs){const edge=incoming.find(e=>token(e.from)===key);next.graph.edges.push({from:copy(edge.from),to:{node:call.id,pin:n.id}});}for(const edge of outgoing)next.graph.edges.push({from:{node:call.id,pin:outputs.get(token(edge.from)).id},to:copy(edge.to)});
  if(!validMaterialGraph(next.graph))throw Error('함수 호출의 연결을 확인하세요.');return {data:next,functionData:fn,callId:call.id};
}
export function resolveMaterialAttributes(data){
  const graph=data.graph;if(!graph?.nodes.some(n=>attributeKeys.includes(nodeKey(n))||nodeKey(n)==='surface'&&n.useAttributes))return data;
  if(!validMaterialGraph(graph)||graph.mode==='function'||graph.nodes.some(n=>['functionCall','layerStack'].includes(nodeKey(n))))throw Error('표면 속성을 resolveMaterialAsset으로 먼저 불러오세요.');
  const wires=normalizedMaterialEdges(graph),nodes=graph.nodes.filter(n=>!attributeKeys.includes(nodeKey(n))).map(copy),edges=[],cache=new Map(),visiting=new Set(),surface={...materialDefaults,...data.surface};let serial=0;
  const add=(key,inputValues={})=>{const n=makeMaterialNode(key);do{n.id='ma_'+serial++;}while(graph.nodes.some(x=>x.id===n.id)||nodes.some(x=>x.id===n.id));n.inputValues=copy(inputValues);nodes.push(n);return n;};
  const constant=(p,value)=>{const n=add(p.type==='float'?'scalar':typeof value==='string'?'color':'vector3');n.value=copy(value);return {node:n.id,pin:'value'};};
  const fallback=new Map(),defaultRef=p=>{if(!fallback.has(p.id))fallback.set(p.id,constant(p,surface[p.key]));return fallback.get(p.id);};
  const numeric=ref=>{const n=graph.nodes.find(n=>n.id===ref.node),key=nodeKey(n);return ['getAttributes','breakAttributes'].includes(key)?bundle(input(n,'attributes'),n.inputValues?.attributes)[ref.pin]:ref;};
  const input=(n,id)=>wires.find(e=>e.to.node===n.id&&e.to.pin===id)?.from;
  const bundle=(ref,literal={})=>{
    if(!ref)return Object.fromEntries(surfaceInputs.map(p=>[p.id,Object.hasOwn(literal,p.id)?constant(p,literal[p.id]):defaultRef(p)]));
    const token=ref.node+':'+ref.pin;if(cache.has(token))return cache.get(token);if(visiting.has(token))throw Error('표면 속성 순환');visiting.add(token);
    const n=graph.nodes.find(n=>n.id===ref.node),key=nodeKey(n);let result;
    if(key==='makeAttributes'||key==='setAttributes'){result=key==='setAttributes'?{...bundle(input(n,'attributes'),n.inputValues?.attributes)}:bundle();for(const p of surfaceInputs){if(key==='setAttributes'&&!n.fields.includes(p.id))continue;const edge=input(n,p.id);if(edge)result[p.id]=numeric(edge);else if(Object.hasOwn(n.inputValues||{},p.id))result[p.id]=constant(p,n.inputValues[p.id]);else if(key==='setAttributes')result[p.id]=defaultRef(p);}}
    else if(key==='blendAttributes'){const bottom=bundle(input(n,'bottom'),n.inputValues?.bottom),top=bundle(input(n,'top'),n.inputValues?.top),alpha=input(n,'alpha'),mask=add('saturate',{value:n.inputValues?.alpha??.5});if(alpha)edges.push({from:numeric(alpha),to:{node:mask.id,pin:'value'}});result={};for(const p of surfaceInputs){if(bottom[p.id].node===top[p.id].node&&bottom[p.id].pin===top[p.id].pin){result[p.id]=bottom[p.id];continue;}const mix=add('lerp');edges.push({from:bottom[p.id],to:{node:mix.id,pin:'a'}},{from:top[p.id],to:{node:mix.id,pin:'b'}},{from:{node:mask.id,pin:'value'},to:{node:mix.id,pin:'alpha'}});let value={node:mix.id,pin:'value'};if(p.id==='normal'&&n.normalizeNormal){const length=add('length'),valid=add('step',{a:1e-6}),safe=add('lerp',{a:[0,0,1]}),normalize=add('normalize');edges.push({from:value,to:{node:length.id,pin:'value'}},{from:{node:length.id,pin:'value'},to:{node:valid.id,pin:'b'}},{from:value,to:{node:safe.id,pin:'b'}},{from:{node:valid.id,pin:'value'},to:{node:safe.id,pin:'alpha'}},{from:{node:safe.id,pin:'value'},to:{node:normalize.id,pin:'value'}});value={node:normalize.id,pin:'value'};}result[p.id]=value;}}
    else throw Error('표면 속성 출력 오류: '+key);
    visiting.delete(token);cache.set(token,result);return result;
  };
  for(const n of nodes){if(nodeKey(n)==='surface'&&n.useAttributes){const values=bundle(input(n,'attributes'),n.inputValues?.attributes);delete n.useAttributes;delete n.inputValues?.attributes;for(const p of surfaceInputs)if(p.id!=='normal'||values[p.id].node!==defaultRef(p).node)edges.push({from:values[p.id],to:{node:n.id,pin:p.id}});}else for(const e of wires.filter(e=>e.to.node===n.id))edges.push({from:numeric(e.from),to:copy(e.to)});}
  const expanded={nodes,edges};if(!validMaterialGraph(expanded))throw Error('표면 속성 그래프 한도 또는 자료형 오류');return {...data,graph:expanded};
}
const glNumber=value=>{const number=finite(value)?value:0;return Number.isInteger(number)?number+'.0':String(number);},glValue=(value,type)=>{if(typeof value==='string')value=rgb(value);return type==='float'?glNumber(Array.isArray(value)?value[0]:value):type+'('+vector(value,Number(type.slice(3))).map(glNumber).join(',')+')';};
export function compileMaterial(data,{uniformParameters=false}={}){
  data=resolveMaterialAttributes(resolveMaterialInputs(data));
  const graph=data.graph||materialGraph();if(!validMaterialGraph(graph))throw Error('머테리얼 그래프 검증 실패');if(graph.mode==='function'||graph.nodes.some(n=>nodeKey(n)==='functionCall'))throw Error('머테리얼 함수를 resolveMaterialAsset으로 먼저 불러오세요.');const surface={...materialDefaults,...data.surface},edges=normalizedMaterialEdges(graph),lines=[],cache=new Map(),textures=[],floatBindings=new Map();let serial=0;
  const floatValue=(kind,key,value)=>{if(!uniformParameters)return glNumber(value);if(!finite(value))throw Error('Float 파라미터 자료형을 확인하세요.');const token=kind+':'+key;if(!floatBindings.has(token))floatBindings.set(token,{kind,key,uniform:'hbFloat'+floatBindings.size,value});return floatBindings.get(token).uniform;};
  const cast=(expr,type,target)=>type===target?expr:target==='float'?expr+'.x':type==='float'?target+'('+expr+')':Number(type.slice(3))>Number(target.slice(3))?expr+'.'+'xyzw'.slice(0,Number(target.slice(3))):target+'('+expr+','+Array(Number(target.slice(3))-Number(type.slice(3))).fill('0.0').join(',')+')';
  const expression=(id,output='value')=>{const token=id+':'+output;if(cache.has(token))return cache.get(token);const node=graph.nodes.find(node=>node.id===id),key=nodeKey(node),pins=materialPins(node,graph);let type=pins.outputs.find(pin=>pin.id===output)?.type||'float',code;
    if(key==='legacyColor')code='hbSRGB('+glValue(surface.color,'vec3')+')';else if(key==='legacyRough')code=floatValue('surface','roughness',surface.roughness);else if(key==='scalarParameter')code=floatValue('parameter',materialParameterKey(node),data.parameters?.[materialParameterKey(node)]??node.value);else if(['scalar','vector2','vector3','vector4','color','scalarParameter','vectorParameter'].includes(key)){const value=data.parameters?.[materialParameterKey(node)]??node.value??.5;code=typeof value==='string'?'hbSRGB('+glValue(value,type)+')':glValue(value,type);}else if(key==='uv')code='hbUv';else if(key==='time')code='hbTime';else if(key==='worldPosition')code='hbWorldPosition';else if(key==='worldNormal')code='normalize(hbWorldNormal)';else if(key==='viewDirection')code='normalize(cameraPosition-hbWorldPosition)';else{const spec=catalogMap.get(key),args={};for(const input of spec.inputs.filter(p=>p.id!=='textureObject')){const edge=edges.find(edge=>edge.to.node===id&&edge.to.pin===input.id),target=input.type==='numeric'?(key==='length'?actualType({...node,key:'normalize'},graph):type):input.type;const linked=edge&&expression(edge.from.node,edge.from.pin);args[input.id]=linked?cast(linked.code,linked.type,target):key==='fresnel'&&input.id==='normal'&&node.inputValues?.normal===undefined?'normalize(hbWorldNormal)':key==='fresnel'&&input.id==='view'&&node.inputValues?.view===undefined?'normalize(cameraPosition-hbWorldPosition)':input.id==='direction'&&key==='sampleCube'&&node.inputValues?.direction===undefined?'normalize(hbWorldNormal)':input.id==='uv'&&input.type==='vec2'&&node.inputValues?.uv===undefined?'hbUv':input.id==='time'&&node.inputValues?.time===undefined?'hbTime':glValue(node.inputValues?.[input.id]??input.value??0,target);}
      if(key==='split')code=args.value+'.'+output;
      else if(key==='combine')code=type+'('+['x','y','z','w'].slice(0,Number(type.slice(3))).map(k=>args[k]).join(',')+')';
      else if(key==='fresnel')code='('+args.base+'+(1.0-'+args.base+')*pow(1.0-clamp(dot(normalize('+args.normal+'),normalize('+args.view+')),0.0,1.0),max('+args.power+',0.0001)))';
      else if(key==='noise')code='hbNoise('+args.uv+'*'+args.scale+')';
      else if(key==='checker')code='mod(dot(floor('+args.uv+'*'+args.scale+'),vec2(1.0)),2.0)';
      else if(key==='radialGradient')code='clamp(1.0-length('+args.uv+'-'+args.center+')/max('+args.radius+',0.000001),0.0,1.0)';
      else if(key==='linearGradient')code='clamp(dot('+args.uv+'-vec2(0.5),vec2(cos('+args.angle+'),sin('+args.angle+')))+0.5,0.0,1.0)';
      else if(['cosine','floor','ceil','sign','exp2'].includes(key))code=(key==='cosine'?'cos':key)+'('+args.value+')';
      else if(['log2','squareRoot'].includes(key))code=(key==='log2'?'log2':'sqrt')+'(max('+args.value+','+glValue(key==='log2'?1e-6:0,type)+'))';
      else if(key==='smoothstep')code='hbSmooth('+args.min+','+args.max+','+args.value+')';
      else if(key==='cross'||key==='distance')code=key+'('+args.a+','+args.b+')';
      else if(key==='reflect')code='reflect('+args.direction+',normalize('+args.normal+'))';
      else if(materialTextureTypes[textureNodeType(key)]?.sample===key){const textureKey=node.id+':rgba';let sample=cache.get(textureKey);if(!sample){const uniform='hbTexture'+textures.length,path=data.parameters?.[materialParameterKey(node)]??node.texture; if(!path)code='vec4(1.0)';else{const resourceType=textureNodeType(key);textures.push({uniform,path,type:resourceType,colorSpace:node.colorSpace||'srgb',wrap:node.wrap||'repeat'});code=resourceType==='texturecube'?'textureLod('+uniform+','+args.direction+',max(0.0,'+args.lod+'))':resourceType==='texturearray'?'texture('+uniform+',vec3('+args.uv+',floor('+args.index+'+0.5)))':resourceType==='texture3d'?'texture('+uniform+','+args.uv+')':'texture2D('+uniform+','+args.uv+')';if(node.colorSpace!=='linear')code='vec4(hbSRGB('+code+'.rgb),'+code+'.a)';}const variable='hbN'+serial++;lines.push('vec4 '+variable+' = '+code+';');sample={code:variable,type:'vec4'};cache.set(textureKey,sample);}const suffix=output==='rgba'?'':'.'+output;const result={code:sample.code+suffix,type};cache.set(token,result);return result;
      }else if(['add','subtract','multiply','divide'].includes(key))code='('+args.a+({add:'+',subtract:'-',multiply:'*',divide:'/'})[key]+(key==='divide'?'mix('+glValue(1e-6,type)+','+args.b+',step('+glValue(1e-6,type)+',abs('+args.b+')))' :args.b)+')';else if(['min','max','step','power'].includes(key))code=(key==='power'?'pow':key)+'('+(key==='power'?'max('+args.a+','+glValue(0,type)+')':args.a)+','+args.b+')';else if(key==='lerp')code='mix('+args.a+','+args.b+','+args.alpha+')';else if(key==='clamp')code='clamp('+args.value+','+args.min+','+args.max+')';else if(key==='saturate')code='clamp('+args.value+','+glValue(0,type)+','+glValue(1,type)+')';else if(key==='oneMinus')code='('+glValue(1,type)+'-'+args.value+')';else if(['normalize','sine','absolute','fraction','length'].includes(key))code=({sine:'sin',absolute:'abs',fraction:'fract'}[key]||key)+'('+args.value+')';else if(key==='dot')code='dot('+args.a+','+args.b+')';else if(key==='normalMap')code='normalize(vec3(('+args.value+'.xy*2.0-1.0)*'+args.strength+','+args.value+'.z*2.0-1.0))';else if(key==='tilingOffset')code='('+args.uv+'*'+args.tiling+'+'+args.offset+')';else if(key==='panner')code='('+args.uv+'+'+args.speed+'*'+args.time+')';else if(key==='rotateUV')code='hbRotate('+args.uv+','+args.angle+','+args.center+')';else throw Error('미지원 머테리얼 노드: '+key);
    }const variable='hbN'+serial++;lines.push(type+' '+variable+' = '+code+';');const result={code:variable,type};cache.set(token,result);return result;};
  const output=graph.nodes.find(node=>nodeKey(node)==='surface'),values={};for(const input of surfaceInputs){const edge=edges.find(edge=>edge.to.node===output?.id&&edge.to.pin===input.id);if(edge){const linked=expression(edge.from.node,edge.from.pin);values[input.id]=cast(linked.code,linked.type,input.type);}else values[input.id]=['roughness','metalness','opacity'].includes(input.key)?floatValue('surface',input.key,surface[input.key]):typeof surface[input.key]==='string'?'hbSRGB('+glValue(surface[input.key],input.type)+')':glValue(surface[input.key],input.type);}
  return {lines:lines.join('\n'),values,textures,floatBindings:[...floatBindings.values()],normalConnected:edges.some(edge=>edge.to.node===output?.id&&edge.to.pin==='normal'),key:uniformParameters?JSON.stringify([lines,values,textures,[...floatBindings.values()].map(({kind,key,uniform})=>({kind,key,uniform}))]):JSON.stringify(data)};
}
const fragmentHelpers=`varying vec3 hbWorldPosition; varying vec3 hbWorldNormal; varying vec2 hbUv; uniform float hbTime; uniform float hbEmissionIntensity;
float hbHash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float hbNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hbHash(i),hbHash(i+vec2(1,0)),f.x),mix(hbHash(i+vec2(0,1)),hbHash(i+vec2(1,1)),f.x),f.y);}
${['float','vec2','vec3','vec4'].map(t=>`${t} hbSmooth(${t} a,${t} b,${t} v){${t} x=clamp((v-a)/max(b-a,${t}(0.000001)),${t}(0.0),${t}(1.0));return x*x*(${t}(3.0)-${t}(2.0)*x);}`).join('\n')}
vec3 hbSRGB(vec3 c){return mix(c/12.92,pow((c+0.055)/1.055,vec3(2.4)),step(vec3(0.04045),c));}
vec2 hbRotate(vec2 uv,float a,vec2 center){float s=sin(a),c=cos(a);vec2 p=uv-center;return vec2(c*p.x-s*p.y,s*p.x+c*p.y)+center;}
vec3 hbNormal(vec3 eye,vec3 n,vec3 mapN){vec3 q0=dFdx(eye),q1=dFdy(eye);vec2 st0=dFdx(hbUv),st1=dFdy(hbUv);vec3 s=normalize(q0*st1.t-q1*st0.t),t=normalize(-q0*st1.s+q1*st0.s);return normalize(mat3(s,t,n)*mapN);}`;
export function createThreeMaterial(THREE,data,{fileUrl=path=>'/api/file?path='+encodeURIComponent(path),onError=()=>{},renderer}={}){
  if(renderer?.hbMaterial)return renderer.hbMaterial(data,{fileUrl,onError,renderer});
  data=copy(data);const plan=compileMaterial(data,{uniformParameters:true}),surface={...materialDefaults,...data.surface},textures=[],loading=[],uniforms={hbTime:{value:0},hbEmissionIntensity:{value:surface.emissiveIntensity}};let disposed=false;const floatParameters=new Map(),floatSurfaces=new Map([['emissiveIntensity',uniforms.hbEmissionIntensity]]);for(const binding of plan.floatBindings){const u=uniforms[binding.uniform]={value:binding.value};(binding.kind==='parameter'?floatParameters:floatSurfaces).set(binding.key,u);}
  const material=new THREE.MeshPhysicalMaterial({color:'#ffffff',roughness:surface.roughness,metalness:surface.metalness,emissive:'#ffffff',emissiveIntensity:surface.emissiveIntensity,opacity:surface.opacity,transparent:surface.blendMode==='translucent',alphaTest:surface.blendMode==='masked'?surface.alphaTest:0,side:surface.doubleSided?THREE.DoubleSide:THREE.FrontSide,clearcoat:1,clearcoatRoughness:surface.clearcoatRoughness,transmission:plan.values.transmission!=='0.0'?1:surface.transmission,ior:surface.ior});
  for(const binding of plan.textures){const placeholder=texturePlaceholder(THREE,binding.type);textures.push(placeholder);uniforms[binding.uniform]={value:placeholder};loading.push(loadMaterialTexture(THREE,binding,data.textureAssets,fileUrl,renderer).then(texture=>{if(disposed){texture.dispose();return null;}uniforms[binding.uniform].value=texture;textures.push(texture);material.needsUpdate=true;return texture;},error=>{onError('텍스처를 읽을 수 없어요: '+binding.path+' · '+error.message);if(binding.type!=='texture2d')throw error;return null;}));}
  material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,uniforms);shader.vertexShader='varying vec3 hbWorldPosition; varying vec3 hbWorldNormal; varying vec2 hbUv;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <uv_vertex>','#include <uv_vertex>\nhbUv = uv;');shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\nhbWorldPosition=(modelMatrix*vec4(transformed,1.0)).xyz; hbWorldNormal=normalize(inverseTransformDirection(transformedNormal,viewMatrix));');shader.fragmentShader=fragmentHelpers+'\n'+plan.textures.map(binding=>'uniform '+({texturecube:'samplerCube',texturearray:'sampler2DArray',texture3d:'sampler3D'}[binding.type]||'sampler2D')+' '+binding.uniform+';').join('\n')+'\n'+plan.floatBindings.map(binding=>'uniform float '+binding.uniform+';').join('\n')+'\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\n'+plan.lines+'\ndiffuseColor.rgb = '+plan.values.baseColor+'; diffuseColor.a = '+plan.values.opacity+';');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor = clamp('+plan.values.roughness+',0.0,1.0);');shader.fragmentShader=shader.fragmentShader.replace('#include <metalnessmap_fragment>','#include <metalnessmap_fragment>\nmetalnessFactor = clamp('+plan.values.metallic+',0.0,1.0);');shader.fragmentShader=shader.fragmentShader.replace('#include <emissivemap_fragment>','#include <emissivemap_fragment>\ntotalEmissiveRadiance = '+plan.values.emissive+' * hbEmissionIntensity;');if(plan.normalConnected)shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nnormal = hbNormal(-vViewPosition,normal,normalize('+plan.values.normal+'));');shader.fragmentShader=shader.fragmentShader.replace('#include <lights_physical_fragment>',THREE.ShaderChunk.lights_physical_fragment.replace('material.ior = ior;','material.ior = clamp('+plan.values.ior+',1.0,2.5);').replace('material.clearcoat = clearcoat;','material.clearcoat = clamp('+plan.values.clearcoat+',0.0,1.0);').replace('material.clearcoatRoughness = clearcoatRoughness;','material.clearcoatRoughness = clamp('+plan.values.clearcoatRoughness+',0.0,1.0);'));shader.fragmentShader=shader.fragmentShader.replace('#include <transmission_fragment>',THREE.ShaderChunk.transmission_fragment.replace('material.transmission = transmission;','material.transmission = clamp('+plan.values.transmission+',0.0,1.0);'));shader.fragmentShader=shader.fragmentShader.replace('#include <aomap_fragment>','#include <aomap_fragment>\nreflectedLight.indirectDiffuse *= clamp('+plan.values.ao+',0.0,1.0);');};
  material.customProgramCacheKey=()=>plan.key;
  const baseDispose=material.dispose.bind(material);material.dispose=()=>{if(disposed)return;disposed=true;for(const texture of textures)texture.dispose();baseDispose();};
  material.userData.ready=Promise.all(loading);material.userData.hbMaterial=true;material.userData.materialSource=data;material.userData.updateTime=time=>uniforms.hbTime.value=time;material.userData.updateFloat=(key,value)=>{if(disposed)return false;if(!finite(value))throw Error('Float 파라미터 값을 확인하세요.');const parameter=floatParameters.get(key);if(parameter){parameter.value=value;data.parameters={...data.parameters,[key]:value};return true;}if(materialParameters(data).some(p=>p.name===key&&p.type!=='float'))throw Error('Float 파라미터가 아니에요.');const property={Roughness:'roughness',Metallic:'metalness',Opacity:'opacity',EmissiveIntensity:'emissiveIntensity'}[key]||key,u=floatSurfaces.get(property);if(!u)return false;u.value=value;data.surface[property]=value;return true;};
  // Three's default clone does not retain onBeforeCompile; own a fresh texture set.
  material.clone=()=>createThreeMaterial(THREE,data,{fileUrl,onError});return material;
}
