import {materialCatalog,makeMaterialNode,materialPins,normalizedMaterialEdges,connectMaterial,disconnectMaterial,removeMaterialNodes,copyMaterialNodes,pasteMaterialNodes,validMaterialGraph,validMaterialSurface} from './material-runtime.js';
import {icon} from './icons.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const editable=target=>target.closest('input,textarea,select');
let copiedNodes=null;
export class MaterialEditor {
  constructor(element,getDocument,hooks={}){
    this.element=element;this.getDocument=getDocument;this.hooks=hooks;this.selected=new Set();this.pan={x:20,y:20};this.zoom=1;this.pending=null;this.listeners=[];element.classList.add('material-graph-editor');element.tabIndex=0;
    const listen=(name,callback,options)=>{element.addEventListener(name,callback,options);this.listeners.push(()=>element.removeEventListener(name,callback,options));};
    listen('pointerdown',event=>this.pointerDown(event));listen('click',event=>this.click(event));listen('change',event=>this.change(event));listen('contextmenu',event=>{event.preventDefault();event.stopPropagation();if(this.moved){this.moved=false;return;}this.menu(event);});
    listen('wheel',event=>{event.preventDefault();event.stopPropagation();const rect=element.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,next=Math.max(.25,Math.min(2,this.zoom*(event.deltaY<0?1.1:1/1.1)));this.pan={x:x-(x-this.pan.x)*next/this.zoom,y:y-(y-this.pan.y)*next/this.zoom};this.zoom=next;this.transform();this.saveView();},{passive:false});
    listen('keydown',event=>this.keydown(event));this.observer=new ResizeObserver(()=>this.drawWires());this.observer.observe(element);this.render();
  }
  get doc(){return this.getDocument();}get graph(){return this.doc?.kind==='material'?this.doc.data.graph:null;}
  saveView(){this.doc.view.material={pan:{...this.pan},zoom:this.zoom,selection:[...this.selected]};this.hooks.view?.();}
  render(){
    const doc=this.doc;if(!doc?.data.graph)return;if(this.owner!==doc.path){this.owner=doc.path;const view=doc.view.material||{};this.pan=view.pan||{x:20,y:20};this.zoom=view.zoom||1;this.selected=new Set(view.selection||[]);this.pending=null;}
    this.element.innerHTML='<div class="material-graph-plane"><svg class="node-wires" aria-hidden="true"></svg><div class="graph-nodes"></div></div><div class="material-selection-box" hidden></div>';
    this.element.querySelector('.graph-nodes').innerHTML=this.graph.nodes.map(node=>{const pins=materialPins(node,this.graph),x=node.px??(Math.abs(node.x)<2?node.x*(Math.max(this.element.clientWidth,700)-220):node.x);const inputs=pins.inputs.map(pin=>`<div class="pin-row"><button class="pin in" data-material-pin="in" data-node-id="${node.id}" data-pin-id="${pin.id}" title="${esc(pin.label+' · '+pin.type)}" aria-label="${esc(pin.label+' 입력')}"></button><span>${esc(pin.label)}</span>${this.inputField(node,pin)}</div>`).join(''),outputs=pins.outputs.map(pin=>`<div class="pin-row output"><span>${esc(pin.label)}</span><small>${pin.type}</small><button class="pin out" data-material-pin="out" data-node-id="${node.id}" data-pin-id="${pin.id}" title="${esc(pin.label+' · '+pin.type)}" aria-label="${esc(pin.label+' 출력')}"></button></div>`).join('');return `<div class="graph-node material-node ${node.kind} ${this.selected.has(node.id)?'selected':''}" data-material-node="${node.id}" style="left:${x}px;top:${node.y}px"><div class="node-title">${icon(node.kind==='output'?'material':'nodes')}<strong>${esc(node.title)}</strong></div><div class="node-body">${this.nodeField(node)}${inputs}${outputs}</div></div>`;}).join('');this.transform();requestAnimationFrame(()=>this.drawWires());this.saveView();
  }
  inputField(node,pin){if(node.kind==='output'||this.edges().some(edge=>edge.to.node===node.id&&edge.to.pin===pin.id))return '';const value=node.inputValues?.[pin.id]??pin.value;if(value===undefined)return '';return Array.isArray(value)?`<div class="material-vector-input">${value.map((v,i)=>`<input type="number" step=".05" value="${v}" data-material-input="${pin.id}" data-axis="${i}" aria-label="${esc(pin.label)} ${'XYZW'[i]}">`).join('')}</div>`:`<input class="material-pin-value" type="number" step=".05" value="${value}" data-material-input="${pin.id}" aria-label="${esc(pin.label)} 값">`;}
  nodeField(node){
    if(node.body==='color')return `<input type="color" value="${this.doc.data.surface.color}" data-material-surface="color" aria-label="기본 색상">`;if(node.body==='rough')return `<input type="number" min="0" max="1" step=".01" value="${this.doc.data.surface.roughness}" data-material-surface="roughness" aria-label="거칠기">`;
    let fields=node.parameter!==undefined?`<label class="material-node-field">이름<input value="${esc(node.parameter)}" data-material-property="parameter" aria-label="파라미터 이름"></label>`:'';
    if(node.key==='texture'){const files=(this.hooks.files?.()||[]).filter(file=>file.kind==='texture');fields+=`<label class="material-node-field">텍스처<select data-material-property="texture"><option value="">없음</option>${[...files,...(node.texture&&!files.some(file=>file.path===node.texture)?[{path:node.texture,name:node.texture}]:[])].map(file=>`<option value="${esc(file.path)}" ${file.path===node.texture?'selected':''}>${esc(file.name)}</option>`).join('')}</select></label><label class="material-node-field">색 공간<select data-material-property="colorSpace"><option value="srgb" ${node.colorSpace==='srgb'?'selected':''}>sRGB · 색상</option><option value="linear" ${node.colorSpace==='linear'?'selected':''}>Linear · 데이터</option></select></label><label class="material-node-field">반복<select data-material-property="wrap"><option value="repeat" ${node.wrap==='repeat'?'selected':''}>Repeat</option><option value="clamp" ${node.wrap==='clamp'?'selected':''}>Clamp</option></select></label>`;}
    if(node.value!==undefined)fields+=Array.isArray(node.value)?`<div class="material-vector-input">${node.value.map((v,i)=>`<input type="number" step=".05" value="${v}" data-material-property="value" data-axis="${i}" aria-label="${'XYZW'[i]} 값">`).join('')}</div>`:`<input type="${typeof node.value==='string'?'color':'number'}" value="${esc(node.value)}" step=".01" data-material-property="value" aria-label="노드 값">`;return fields;
  }
  edges(){return normalizedMaterialEdges(this.graph);}
  setZoom(next){next=Math.max(.25,Math.min(2,next));const x=this.element.clientWidth/2,y=this.element.clientHeight/2;this.pan={x:x-(x-this.pan.x)*next/this.zoom,y:y-(y-this.pan.y)*next/this.zoom};this.zoom=next;this.transform();this.saveView();}
  transform(){const label=this.element.parentElement?.querySelector('[data-action=material-zoom-reset]');if(label)label.textContent=Math.round(this.zoom*100)+'%';const plane=this.element.querySelector('.material-graph-plane');if(plane)plane.style.transform=`translate(${this.pan.x}px,${this.pan.y}px) scale(${this.zoom})`;}
  drawWires(){if(!this.graph)return;const plane=this.element.querySelector('.material-graph-plane');if(!plane)return;const base=plane.getBoundingClientRect(),svg=plane.querySelector('.node-wires');let width=1500,height=1000;svg.innerHTML=this.edges().map(edge=>{const from=plane.querySelector(`[data-node-id="${edge.from.node}"][data-material-pin="out"][data-pin-id="${edge.from.pin}"]`),to=plane.querySelector(`[data-node-id="${edge.to.node}"][data-material-pin="in"][data-pin-id="${edge.to.pin}"]`);if(!from||!to)return '';const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x1=(a.left+a.width/2-base.left)/this.zoom,y1=(a.top+a.height/2-base.top)/this.zoom,x2=(b.left+b.width/2-base.left)/this.zoom,y2=(b.top+b.height/2-base.top)/this.zoom,bend=Math.max(50,Math.abs(x2-x1)*.45);width=Math.max(width,x1+100,x2+100);height=Math.max(height,y1+100,y2+100);return `<path d="M${x1} ${y1} C${x1+bend} ${y1},${x2-bend} ${y2},${x2} ${y2}" fill="none" stroke="#8eb59f" stroke-width="2"/>`;}).join('');svg.setAttribute('width',width);svg.setAttribute('height',height);svg.style.width=width+'px';svg.style.height=height+'px';}
  mutate(change){const next=structuredClone(this.doc.data);if(change(next)===false)return;if(!validMaterialGraph(next.graph)||!validMaterialSurface(next.surface)){this.hooks.error?.('머테리얼 값을 확인하세요.');this.render();return;}this.hooks.before?.();this.doc.data=next;this.hooks.change?.();this.render();}
  click(event){const button=event.target.closest('[data-material-pin]');if(!button)return;event.preventDefault();event.stopPropagation();const direction=button.dataset.materialPin==='out'?'from':'to',node=button.dataset.nodeId,pin=button.dataset.pinId;if(event.altKey){this.mutate(data=>disconnectMaterial(data.graph,node,pin,direction));return;}if(direction==='from'){this.pending={node,pin};this.element.querySelectorAll('.pin.pending').forEach(pin=>pin.classList.remove('pending'));button.classList.add('pending');return;}if(!this.pending)return;const from=this.pending;this.mutate(data=>{const result=connectMaterial(data.graph,from,{node,pin});if(!result.ok){this.hooks.error?.(result.reason);return false;}});this.pending=null;}
  change(event){const input=event.target,node=this.graph.nodes.find(node=>node.id===input.closest('[data-material-node]')?.dataset.materialNode);if(!node)return;event.stopPropagation();this.mutate(data=>{const next=data.graph.nodes.find(value=>value.id===node.id),value=input.type==='number'?Number(input.value):input.value;if(input.dataset.materialSurface){data.surface[input.dataset.materialSurface]=value;return;}if(input.dataset.materialInput){const key=input.dataset.materialInput;next.inputValues??={};if(input.dataset.axis!==undefined){const pin=materialPins(next,data.graph).inputs.find(pin=>pin.id===key);next.inputValues[key]=[...(next.inputValues[key]||pin.value)];next.inputValues[key][Number(input.dataset.axis)]=value;}else next.inputValues[key]=value;}else if(input.dataset.materialProperty){if(input.dataset.axis!==undefined)next.value[Number(input.dataset.axis)]=value;else next[input.dataset.materialProperty]=value;}});}
  pointerDown(event){
    if(editable(event.target))return;const source=event.target.closest('[data-material-pin="out"]');if(source&&event.button===0&&!event.altKey){event.stopPropagation();const from={node:source.dataset.nodeId,pin:source.dataset.pinId};const finish=e=>{const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-material-pin="in"]');if(!target||!this.element.contains(target))return;this.mutate(data=>{const result=connectMaterial(data.graph,from,{node:target.dataset.nodeId,pin:target.dataset.pinId});if(!result.ok){this.hooks.error?.(result.reason);return false;}});this.pending=null;};document.addEventListener('pointerup',finish,{once:true});return;}if(event.target.closest('[data-material-pin]'))return;event.stopPropagation();this.element.focus();const nodeElement=event.target.closest('[data-material-node]'),node=nodeElement&&this.graph.nodes.find(node=>node.id===nodeElement.dataset.materialNode),start={x:event.clientX,y:event.clientY},pan={...this.pan};this.moved=false;
    const panning=event.button===1||event.button===2;if(event.button!==0&&!panning)return;if(panning)event.preventDefault();
    if(node&&!panning){if(event.ctrlKey||event.metaKey){this.selected.has(node.id)?this.selected.delete(node.id):this.selected.add(node.id);}else if(!this.selected.has(node.id))this.selected=new Set([node.id]);this.hooks.select?.(node);this.render();}
    const points=new Map(this.graph.nodes.filter(value=>this.selected.has(value.id)).map(value=>{const el=this.element.querySelector(`[data-material-node="${value.id}"]`);return [value.id,{x:el.offsetLeft,y:el.offsetTop}];}));let remembered=false;const box=this.element.querySelector('.material-selection-box');if(!node&&!panning&&!event.ctrlKey)this.selected.clear();const baseSelection=new Set(this.selected);this.element.setPointerCapture(event.pointerId);
    const move=e=>{const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.hypot(dx,dy)>3)this.moved=true;if(panning){this.pan={x:pan.x+dx,y:pan.y+dy};this.transform();}else if(node){if(!this.moved)return;if(!remembered){this.hooks.before?.();remembered=true;}for(const value of this.graph.nodes){const point=points.get(value.id);if(point){value.px=point.x+dx/this.zoom;value.y=point.y+dy/this.zoom;const el=this.element.querySelector(`[data-material-node="${value.id}"]`);el.style.left=value.px+'px';el.style.top=value.y+'px';}}this.drawWires();}else{const rect=this.element.getBoundingClientRect(),left=Math.min(start.x,e.clientX)-rect.left,top=Math.min(start.y,e.clientY)-rect.top;box.hidden=false;Object.assign(box.style,{left:left+'px',top:top+'px',width:Math.abs(dx)+'px',height:Math.abs(dy)+'px'});this.selected=new Set(baseSelection);for(const value of this.graph.nodes){const rect=this.element.querySelector(`[data-material-node="${value.id}"]`).getBoundingClientRect();if(rect.right>=Math.min(start.x,e.clientX)&&rect.left<=Math.max(start.x,e.clientX)&&rect.bottom>=Math.min(start.y,e.clientY)&&rect.top<=Math.max(start.y,e.clientY))this.selected.add(value.id);}}};
    const up=()=>{this.element.removeEventListener('pointermove',move);this.element.removeEventListener('pointerup',up);this.element.removeEventListener('pointercancel',up);if(remembered)this.hooks.change?.();this.saveView();if(!panning)this.render();};this.element.addEventListener('pointermove',move);this.element.addEventListener('pointerup',up);this.element.addEventListener('pointercancel',up);
  }
  menu(event){
    document.querySelector('.material-node-menu')?.remove();const node=event.target.closest('[data-material-node]');if(node&&!this.selected.has(node.dataset.materialNode)){this.selected=new Set([node.dataset.materialNode]);this.render();}const rect=this.element.getBoundingClientRect(),position={x:(event.clientX-rect.left-this.pan.x)/this.zoom,y:(event.clientY-rect.top-this.pan.y)/this.zoom},menu=document.createElement('div');menu.className='project-menu material-node-menu';menu.innerHTML='<input type="search" placeholder="노드 검색" aria-label="머테리얼 노드 검색"><div class="material-node-results"></div>';const search=menu.querySelector('input'),results=menu.querySelector('.material-node-results');
    const render=()=>{const query=search.value.trim().toLowerCase();results.innerHTML=(this.selected.size&&!query?'<button data-material-delete>'+icon('close')+'선택 노드 삭제 <kbd>Delete</kbd></button>':'')+materialCatalog.filter(spec=>spec.key!=='surface'&&(spec.title+' '+spec.key+' '+spec.category).toLowerCase().includes(query)).map(spec=>`<button data-material-add="${spec.key}">${icon('nodes')}<span>${esc(spec.title)}</span><small>${esc(spec.category)}</small></button>`).join('');};
    menu.onclick=e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.materialAdd)this.add(button.dataset.materialAdd,position);else if(button.hasAttribute('data-material-delete'))this.deleteSelection();menu.remove();};search.oninput=render;search.onkeydown=e=>{if(e.key==='Escape')menu.remove();if(e.key==='Enter')results.querySelector('[data-material-add]')?.click();};render();document.body.append(menu);menu.style.left=Math.max(8,Math.min(event.clientX,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(8,Math.min(event.clientY,innerHeight-menu.offsetHeight-8))+'px';search.focus();const close=e=>{if(!menu.contains(e.target)){menu.remove();document.removeEventListener('pointerdown',close,true);}};document.addEventListener('pointerdown',close,true);
  }
  add(key,position={x:100,y:100}){const node=makeMaterialNode(key,position.x,position.y);if(node.parameter){const base=node.parameter;let index=1;while(this.graph.nodes.some(value=>value.parameter===node.parameter))node.parameter=base+(++index);}this.mutate(data=>data.graph.nodes.push(node));this.selected=new Set([node.id]);this.render();}
  deleteSelection(){this.mutate(data=>removeMaterialNodes(data.graph,this.selected));this.selected.clear();this.render();}
  copySelection(){const clip=copyMaterialNodes(this.graph,this.selected);if(!clip.nodes.length)return;for(const node of clip.nodes){const element=this.element.querySelector(`[data-material-node="${node.id}"]`);if(element)node.px=element.offsetLeft;}copiedNodes=clip;navigator.clipboard?.writeText(JSON.stringify(clip)).catch(()=>{});}
  async pasteSelection(){let clip=copiedNodes;try{const text=await navigator.clipboard?.readText();if(text?.length<=1048576){const parsed=JSON.parse(text);if(parsed.type==='HBMaterialNodes')clip=parsed;}}catch{}if(!clip)return;const position={x:(80-this.pan.x)/this.zoom,y:(80-this.pan.y)/this.zoom};let nodes;this.mutate(data=>{const result=pasteMaterialNodes(data.graph,clip,position);if(!result.ok){this.hooks.error?.(result.reason);return false;}nodes=result.nodes;});if(nodes){this.selected=new Set(nodes.map(node=>node.id));this.render();}}
  duplicateSelection(){const clip=copyMaterialNodes(this.graph,this.selected);if(!clip.nodes.length)return;for(const node of clip.nodes){const element=this.element.querySelector(`[data-material-node="${node.id}"]`);if(element)node.px=element.offsetLeft;}const position={x:Math.min(...clip.nodes.map(node=>node.px??node.x))+35,y:Math.min(...clip.nodes.map(node=>node.y))+35};let nodes;this.mutate(data=>{const result=pasteMaterialNodes(data.graph,clip,position);if(!result.ok){this.hooks.error?.(result.reason);return false;}nodes=result.nodes;});if(nodes){this.selected=new Set(nodes.map(node=>node.id));this.render();}}
  fit(selectionOnly=false,zoom){const elements=[...this.element.querySelectorAll('[data-material-node]')].filter(element=>!selectionOnly||!this.selected.size||this.selected.has(element.dataset.materialNode));if(!elements.length)return;const left=Math.min(...elements.map(element=>element.offsetLeft)),top=Math.min(...elements.map(element=>element.offsetTop)),right=Math.max(...elements.map(element=>element.offsetLeft+element.offsetWidth)),bottom=Math.max(...elements.map(element=>element.offsetTop+element.offsetHeight));this.zoom=zoom??Math.max(.25,Math.min(1,(this.element.clientWidth-40)/(right-left),(this.element.clientHeight-40)/(bottom-top)));this.pan={x:(this.element.clientWidth-(right-left)*this.zoom)/2-left*this.zoom,y:(this.element.clientHeight-(bottom-top)*this.zoom)/2-top*this.zoom};this.transform();this.saveView();}
  keydown(event){if(editable(event.target))return;const mod=event.ctrlKey||event.metaKey;if(mod&&['c','x','v','z','y'].includes(event.key.toLowerCase())){event.preventDefault();event.stopPropagation();const key=event.key.toLowerCase();if(key==='c'||key==='x'){this.copySelection();if(key==='x')this.deleteSelection();}else if(key==='v')this.pasteSelection();else{const action=key==='y'||event.shiftKey?this.hooks.redo:this.hooks.undo;if(action){action();this.render();}else this.hooks.error?.('문서의 Undo/Redo 연결을 확인하세요.');}}else if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();event.stopPropagation();this.deleteSelection();}else if(mod&&event.key.toLowerCase()==='a'){event.preventDefault();event.stopPropagation();this.selected=new Set(this.graph.nodes.map(node=>node.id));this.render();}else if(mod&&event.key.toLowerCase()==='d'){event.preventDefault();event.stopPropagation();this.duplicateSelection();}else if(event.key==='f'||event.key==='F'||event.key==='Home'){event.preventDefault();event.stopPropagation();this.fit(event.key!=='Home');}else if(event.key==='Escape'){this.pending=null;this.selected.clear();this.render();}}
  dispose(){for(const remove of this.listeners)remove();this.observer.disconnect();document.querySelector('.material-node-menu')?.remove();}
}
