const copy=value=>structuredClone(value),finite=value=>Number.isFinite(value)&&Math.abs(value)<=10000;
const clamp=(value,min=0,max=1)=>Math.max(min,Math.min(max,value));
export const materialDefaults={color:'#889878',roughness:.72,metalness:.08,light:3.2,normal:[0,0,1],emissive:'#000000',emissiveIntensity:1,opacity:1,ao:1,clearcoat:0,clearcoatRoughness:.1,transmission:0,ior:1.5,blendMode:'opaque',alphaTest:.5,doubleSided:false};
export const surfaceInputs=[['baseColor','Base Color · 기본 색상','vec3','color'],['roughness','Roughness · 거칠기','float','roughness'],['metallic','Metallic · 금속성','float','metalness'],['normal','Normal · 노멀','vec3','normal'],['emissive','Emissive · 발광','vec3','emissive'],['opacity','Opacity · 불투명도','float','opacity'],['ao','Ambient Occlusion · 차폐','float','ao'],['clearcoat','Clearcoat · 코팅','float','clearcoat'],['clearcoatRoughness','Coat Roughness · 코팅 거칠기','float','clearcoatRoughness'],['transmission','Transmission · 투과','float','transmission'],['ior','IOR · 굴절률','float','ior']].map(([id,label,type,key])=>({id,label,type,key}));
const pin=(id,label,type,value)=>({id,label,type,value}),out=(type='float')=>[pin('value','Value',type)];
const specs=[
  ['scalar','Scalar · 상수','값',[],out(),{value:.5}],['vector2','Vector2 · 벡터2','값',[],out('vec2'),{value:[1,1]}],['vector3','Vector3 · 벡터3','값',[],out('vec3'),{value:[1,1,1]}],['vector4','Vector4 · 벡터4','값',[],out('vec4'),{value:[1,1,1,1]}],['color','Color · 색상','값',[],out('vec3'),{value:'#889878'}],
  ['scalarParameter','Scalar Parameter · 스칼라 변수','파라미터',[],out(),{value:.5,parameter:'Scalar'}],['vectorParameter','Vector Parameter · 색상 변수','파라미터',[],out('vec3'),{value:[1,1,1],parameter:'Color'}],
  ['texture','Texture Sample · 텍스처 샘플','텍스처',[pin('uv','UV','vec2',[0,0])],[pin('rgba','RGBA','vec4'),pin('rgb','RGB','vec3'),...['r','g','b','a'].map(id=>pin(id,id.toUpperCase(),'float'))],{texture:'',colorSpace:'srgb',wrap:'repeat',parameter:'Texture'}],
  ['uv','Texture Coordinate · UV 좌표','좌표',[],out('vec2')],['time','Time · 시간','좌표',[],out()],
  ['tilingOffset','Tiling And Offset · 반복과 위치','좌표',[pin('uv','UV','vec2'),pin('tiling','Tiling','vec2',[1,1]),pin('offset','Offset','vec2',[0,0])],out('vec2')],
  ['panner','Panner · UV 이동','좌표',[pin('uv','UV','vec2'),pin('speed','Speed','vec2',[.1,0]),pin('time','Time','float')],out('vec2')],
  ['rotateUV','Rotate UV · UV 회전','좌표',[pin('uv','UV','vec2'),pin('angle','Angle · 라디안','float',0),pin('center','Center','vec2',[.5,.5])],out('vec2')],
  ...['add','subtract','multiply','divide','power','min','max','step'].map(key=>[key,({add:'Add · 더하기',subtract:'Subtract · 빼기',multiply:'Multiply · 곱하기',divide:'Divide · 나누기',power:'Power · 제곱',min:'Minimum · 최솟값',max:'Maximum · 최댓값',step:'Step · 경계'})[key],'수학',[pin('a','A','numeric',key==='multiply'||key==='divide'?1:0),pin('b','B','numeric',1)],out('numeric')]),
  ['lerp','Linear Interpolate · 선형 보간','수학',[pin('a','A','numeric',0),pin('b','B','numeric',1),pin('alpha','Alpha','float',.5)],out('numeric')],
  ['clamp','Clamp · 범위 제한','수학',[pin('value','Value','numeric',.5),pin('min','Min','numeric',0),pin('max','Max','numeric',1)],out('numeric')],
  ...['saturate','oneMinus','normalize','sine','absolute','fraction'].map(key=>[key,({saturate:'Saturate · 0~1 제한',oneMinus:'One Minus · 반전',normalize:'Normalize · 정규화',sine:'Sine · 사인',absolute:'Absolute · 절댓값',fraction:'Fraction · 소수 부분'})[key],'수학',[pin('value','Value','numeric',.5)],out('numeric')]),
  ['dot','Dot Product · 내적','수학',[pin('a','A','vec3',[1,0,0]),pin('b','B','vec3',[0,1,0])],out()],['length','Length · 길이','수학',[pin('value','Value','numeric',0)],out()],
  ['normalMap','Unpack Normal · 노멀 변환','텍스처',[pin('value','RGB','vec3',[.5,.5,1]),pin('strength','Strength','float',1)],out('vec3')],
  ...['cosine','floor','ceil','squareRoot','sign','exp2','log2'].map(key=>[key,({cosine:'Cosine · 코사인',floor:'Floor · 내림',ceil:'Ceil · 올림',squareRoot:'Square Root · 제곱근',sign:'Sign · 부호',exp2:'Exp2 · 지수',log2:'Log2 · 로그'})[key],'수학',[pin('value','Value','numeric',.5)],out('numeric')]),
  ['smoothstep','Smoothstep · 부드러운 경계','마스크',[pin('min','Min','numeric',0),pin('max','Max','numeric',1),pin('value','Value','numeric',.5)],out('numeric')],
  ['distance','Distance · 거리','벡터',[pin('a','A','vec3',[0,0,0]),pin('b','B','vec3',[1,0,0])],out()],
  ['cross','Cross Product · 외적','벡터',[pin('a','A','vec3',[1,0,0]),pin('b','B','vec3',[0,1,0])],out('vec3')],
  ['reflect','Reflect · 반사 방향','벡터',[pin('direction','Direction','vec3',[0,-1,0]),pin('normal','Normal','vec3',[0,1,0])],out('vec3')],
  ['split','Split · 채널 분리','벡터',[pin('value','Vector','vec4',[0,0,0,1])],['x','y','z','w'].map(id=>pin(id,id.toUpperCase(),'float'))],
  ['combine','Combine · 채널 조합','벡터',['x','y','z','w'].map(id=>pin(id,id.toUpperCase(),'float',id==='w'?1:0)),[pin('rgba','RGBA','vec4'),pin('rgb','RGB','vec3'),pin('rg','RG','vec2')]],
  ['worldPosition','World Position · 월드 위치','좌표',[],out('vec3')],
  ['worldNormal','World Normal · 월드 법선','좌표',[],out('vec3')],
  ['viewDirection','View Direction · 시선 방향','좌표',[],out('vec3')],
  ['fresnel','Fresnel · 가장자리 반사','마스크',[pin('normal','World Normal','vec3'),pin('view','View Direction','vec3'),pin('power','Exponent','float',5),pin('base','Base Reflectance','float',.04)],out()],
  ['noise','Value Noise · 값 노이즈','절차적',[pin('uv','UV','vec2'),pin('scale','Scale','float',5)],out()],
  ['checker','Checkerboard · 체크 패턴','절차적',[pin('uv','UV','vec2'),pin('scale','Scale','vec2',[8,8])],out()],
  ['radialGradient','Radial Gradient · 원형 그라데이션','마스크',[pin('uv','UV','vec2'),pin('center','Center','vec2',[.5,.5]),pin('radius','Radius','float',.5)],out()],
  ['linearGradient','Linear Gradient · 선형 그라데이션','마스크',[pin('uv','UV','vec2'),pin('angle','Angle · 라디안','float',0)],out()],
  ['surface','Surface · PBR 표면','출력',surfaceInputs,[],{}]
];
export const materialCatalog=specs.map(([key,title,category,inputs,outputs,defaults={}])=>({key,title,category,inputs,outputs,defaults}));
const catalogMap=new Map(materialCatalog.map(spec=>[spec.key,spec]));
export const materialNodeKey=node=>node.key||(node.kind==='output'?'surface':({color:'legacyColor',rough:'legacyRough',constant:'scalar'})[node.body]);
const nodeKey=materialNodeKey;
export function makeMaterialNode(key,x=80,y=80){const spec=catalogMap.get(key);if(!spec)throw Error('머테리얼 노드 종류를 확인하세요.');return {id:'mat_'+crypto.randomUUID().replaceAll('-',''),key,title:spec.title,kind:key==='surface'?'output':'value',x,y,...copy(spec.defaults),inputValues:{}};}
export const materialGraph=()=>({nodes:[{id:'color',title:'Base Color',kind:'value',x:.06,y:45,body:'color',output:'RGB'},{id:'rough',title:'Roughness',kind:'value',x:.06,y:195,body:'rough',output:'Float'},{id:'surface',key:'surface',title:'Surface',kind:'output',x:.64,y:70}],edges:[['color','surface',0],['rough','surface',1]]});
export function normalizedMaterialEdges(graph){return graph.edges.map(edge=>{if(!Array.isArray(edge))return edge;const target=graph.nodes.find(node=>node.id===edge[1]);return {from:{node:edge[0],pin:edge[3]||'value'},to:{node:edge[1],pin:nodeKey(target||{})==='surface'?surfaceInputs[edge[2]]?.id:catalogMap.get(nodeKey(target||{}))?.inputs[edge[2]]?.id}};});}
function actualType(node,graph,seen=new Set()){
  const key=nodeKey(node);if(key==='legacyColor')return 'vec3';if(key==='legacyRough')return 'float';const spec=catalogMap.get(key);if(spec?.outputs[0]?.type!=='numeric')return spec?.outputs[0]?.type;
  if(seen.has(node.id))return 'float';seen.add(node.id);let type='float';for(const edge of normalizedMaterialEdges(graph).filter(edge=>edge.to?.node===node.id)){const source=graph.nodes.find(n=>n.id===edge.from?.node);if(!source)continue;const sourceSpec=catalogMap.get(nodeKey(source)),output=sourceSpec?.outputs.find(pin=>pin.id===edge.from.pin),next=output?.type==='numeric'?actualType(source,graph,new Set(seen)):output?.type||actualType(source,graph,new Set(seen));if(/^vec[234]$/.test(next)&&next>type)type=next;}
  for(const value of Object.values(node.inputValues||{}))if(Array.isArray(value)&&value.length>=2&&value.length<=4&&'vec'+value.length>type)type='vec'+value.length;return type;
}
export function materialPins(node,graph){const key=nodeKey(node);if(key==='legacyColor'||key==='legacyRough')return {inputs:[],outputs:out(key==='legacyColor'?'vec3':'float')};const spec=catalogMap.get(key);if(!spec)return {inputs:[],outputs:[]};const type=actualType(node,graph);return {inputs:spec.inputs.map(pin=>({...pin,type:pin.type==='numeric'?type:pin.type})),outputs:spec.outputs.map(pin=>({...pin,type:pin.type==='numeric'?type:pin.type}))};}
export function validMaterialGraph(graph){
  if(!graph||!Array.isArray(graph.nodes)||!Array.isArray(graph.edges)||graph.nodes.length>1000||graph.edges.length>5000||new Set(graph.nodes.map(node=>node?.id)).size!==graph.nodes.length||graph.nodes.filter(node=>node&&nodeKey(node)==='surface').length!==1)return false;
  if(!graph.edges.every(edge=>Array.isArray(edge)?(edge.length===3||edge.length===4)&&typeof edge[0]==='string'&&typeof edge[1]==='string'&&Number.isInteger(edge[2])&&edge[2]>=0&&edge[2]<surfaceInputs.length:edge&&edge.from&&edge.to&&['from','to'].every(key=>typeof edge[key].node==='string'&&typeof edge[key].pin==='string'&&edge[key].pin.length<=100)))return false;
  if(!graph.nodes.every(node=>node&&/^[A-Za-z0-9_-]{1,100}$/.test(node.id)&&typeof node.title==='string'&&node.title.length<=100&&(catalogMap.has(nodeKey(node))||['legacyColor','legacyRough'].includes(nodeKey(node)))&&finite(node.x)&&finite(node.y)&&(node.px===undefined||finite(node.px))&&(node.value===undefined||typeof node.value==='string'&&/^#[0-9a-f]{6}$/i.test(node.value)||finite(node.value)||Array.isArray(node.value)&&node.value.length>=2&&node.value.length<=4&&node.value.every(finite))&&(node.parameter===undefined||typeof node.parameter==='string'&&/^[A-Za-z_가-힣][\w가-힣]{0,79}$/.test(node.parameter))&&(node.texture===undefined||validAssetPath(node.texture))&&(node.colorSpace===undefined||['srgb','linear'].includes(node.colorSpace))&&(node.wrap===undefined||['repeat','clamp'].includes(node.wrap))&&(node.inputValues===undefined||node.inputValues&&typeof node.inputValues==='object'&&!Array.isArray(node.inputValues)&&Object.values(node.inputValues).every(value=>finite(value)||Array.isArray(value)&&value.length>=2&&value.length<=4&&value.every(finite)))))return false;
  for(const node of graph.nodes){const key=nodeKey(node),value=node.value;if(value!==undefined){if(['scalar','scalarParameter'].includes(key)&&!finite(value))return false;if(key==='color'&&(typeof value!=='string'||!/^#[0-9a-f]{6}$/i.test(value)))return false;const size=({vector2:2,vector3:3,vector4:4,vectorParameter:3})[key];if(size&&(!Array.isArray(value)||value.length!==size))return false;}if(node.inputValues&&Object.keys(node.inputValues).some(id=>!catalogMap.get(key)?.inputs.some(pin=>pin.id===id)))return false;}
  const edges=normalizedMaterialEdges(graph),targets=new Set();for(const edge of edges){const from=graph.nodes.find(node=>node.id===edge?.from?.node),to=graph.nodes.find(node=>node.id===edge?.to?.node);if(!from||!to||from===to)return false;const output=materialPins(from,graph).outputs.find(pin=>pin.id===edge.from.pin),input=materialPins(to,graph).inputs.find(pin=>pin.id===edge.to.pin);if(!output||!input||output.type!==input.type&&output.type!=='float'&&catalogMap.get(nodeKey(to))?.inputs.find(pin=>pin.id===input.id)?.type!=='numeric')return false;const target=to.id+':'+input.id;if(targets.has(target))return false;targets.add(target);}
  const visiting=new Set(),done=new Set();const visit=id=>{if(visiting.has(id))return false;if(done.has(id))return true;visiting.add(id);if(!edges.filter(edge=>edge.from.node===id).every(edge=>visit(edge.to.node)))return false;visiting.delete(id);done.add(id);return true;};return graph.nodes.every(node=>visit(node.id));
}
export function validAssetPath(path){return typeof path==='string'&&path.length<=1000&&!/^(?:[A-Za-z]:|[\\/])/.test(path)&&!path.replaceAll('\\','/').split('/').includes('..')&&!/[\x00-\x1f]/.test(path);}
export function validMaterialSurface(surface){return surface&&/^#[0-9a-f]{6}$/i.test(surface.color)&&['roughness','metalness'].every(key=>finite(surface[key])&&surface[key]>=0&&surface[key]<=1)&&finite(surface.light)&&surface.light>=0&&surface.light<=10&&['opacity','ao','clearcoat','clearcoatRoughness','transmission'].every(key=>surface[key]===undefined||finite(surface[key])&&surface[key]>=0&&surface[key]<=1)&&(surface.ior===undefined||finite(surface.ior)&&surface.ior>=1&&surface.ior<=2.5)&&(surface.normal===undefined||Array.isArray(surface.normal)&&surface.normal.length===3&&surface.normal.every(finite))&&(surface.emissive===undefined||/^#[0-9a-f]{6}$/i.test(surface.emissive))&&(surface.emissiveIntensity===undefined||finite(surface.emissiveIntensity)&&surface.emissiveIntensity>=0)&&(surface.blendMode===undefined||['opaque','masked','translucent'].includes(surface.blendMode))&&(surface.alphaTest===undefined||finite(surface.alphaTest)&&surface.alphaTest>=0&&surface.alphaTest<=1)&&(surface.doubleSided===undefined||typeof surface.doubleSided==='boolean');}
export function connectMaterial(graph,from,to){const next=copy(graph);next.edges=normalizedMaterialEdges(next).filter(edge=>!(edge.to.node===to.node&&edge.to.pin===to.pin));next.edges.push({from:copy(from),to:copy(to)});if(!validMaterialGraph(next))return {ok:false,reason:'핀 자료형이나 순환 연결을 확인하세요.'};graph.edges=next.edges;return {ok:true};}
export function disconnectMaterial(graph,node,pin,direction){const edges=normalizedMaterialEdges(graph),next=edges.filter(edge=>edge[direction].node!==node||(pin&&edge[direction].pin!==pin));if(next.length===edges.length)return false;graph.edges=next;return true;}
export function removeMaterialNodes(graph,ids){const removable=new Set(graph.nodes.filter(node=>ids.has(node.id)&&nodeKey(node)!=='surface').map(node=>node.id));if(!removable.size)return false;graph.edges=normalizedMaterialEdges(graph).filter(edge=>!removable.has(edge.from.node)&&!removable.has(edge.to.node));graph.nodes=graph.nodes.filter(node=>!removable.has(node.id));return true;}
export function copyMaterialNodes(graph,ids){const nodes=graph.nodes.filter(node=>ids.has(node.id)&&nodeKey(node)!=='surface'),included=new Set(nodes.map(node=>node.id));return {type:'HBMaterialNodes',version:1,nodes:copy(nodes),edges:copy(normalizedMaterialEdges(graph).filter(edge=>included.has(edge.from.node)&&included.has(edge.to.node)))};}
export function pasteMaterialNodes(graph,clipboard,{x=100,y=100}={}){
  if(!clipboard||clipboard.type!=='HBMaterialNodes'||clipboard.version!==1||!Array.isArray(clipboard.nodes)||!clipboard.nodes.length||clipboard.nodes.length>1000||!Array.isArray(clipboard.edges)||clipboard.edges.length>5000||!finite(x)||!finite(y)||clipboard.nodes.some(node=>!node||nodeKey(node)==='surface'))return {ok:false,reason:'머테리얼 노드 복사 데이터를 확인하세요.'};
  const next=copy(graph),ids=new Map(clipboard.nodes.map(node=>[node.id,'mat_'+crypto.randomUUID().replaceAll('-','')]));if(ids.size!==clipboard.nodes.length)return {ok:false,reason:'복사한 노드 ID가 중복돼요.'};
  const left=Math.min(...clipboard.nodes.map(node=>node.px??node.x)),top=Math.min(...clipboard.nodes.map(node=>node.y));const nodes=copy(clipboard.nodes).map(node=>({...node,id:ids.get(node.id),px:(node.px??node.x)-left+x,y:node.y-top+y}));
  const edges=clipboard.edges.map(edge=>({from:{node:ids.get(edge?.from?.node),pin:edge?.from?.pin},to:{node:ids.get(edge?.to?.node),pin:edge?.to?.pin}}));next.nodes.push(...nodes);next.edges.push(...edges);if(!validMaterialGraph(next))return {ok:false,reason:'복사한 노드 자료형이나 연결을 확인하세요.'};graph.nodes=next.nodes;graph.edges=next.edges;return {ok:true,nodes};
}
const rgb=color=>[1,3,5].map(index=>parseInt(color.slice(index,index+2),16)/255),hex=value=>'#'+value.slice(0,3).map(channel=>Math.round(clamp(channel)*255).toString(16).padStart(2,'0')).join('');
const vector=(value,size)=>Array.from({length:size},(_,index)=>Array.isArray(value)?value[index]??value[0]:value),map=(a,b,fn)=>Array.isArray(a)||Array.isArray(b)?vector(a,Math.max(a?.length||1,b?.length||1)).map((value,index)=>fn(value,vector(b,Math.max(a?.length||1,b?.length||1))[index])):fn(a,b);
const unit=v=>{const n=Math.hypot(...v);return v.map(x=>n?x/n:0);};
const hash2=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n);};
function noise2(uv){const [x,y]=uv,ix=Math.floor(x),iy=Math.floor(y),fx=x-ix,fy=y-iy,u=fx*fx*(3-2*fx),v=fy*fy*(3-2*fy);return (hash2(ix,iy)*(1-u)+hash2(ix+1,iy)*u)*(1-v)+(hash2(ix,iy+1)*(1-u)+hash2(ix+1,iy+1)*u)*v;}
function operation(key,args){
  if(['cosine','floor','ceil','sign','exp2','log2','squareRoot'].includes(key))return map(args.value,0,({cosine:Math.cos,floor:Math.floor,ceil:Math.ceil,sign:Math.sign,exp2:x=>2**x,log2:x=>Math.log2(Math.max(x,1e-6)),squareRoot:x=>Math.sqrt(Math.max(x,0))})[key]);
  if(key==='smoothstep'){const t=map(map(args.value,args.min,(x,y)=>x-y),map(args.max,args.min,(x,y)=>Math.max(x-y,1e-6)),(x,y)=>clamp(x/y));return map(t,0,x=>x*x*(3-2*x));}
  if(key==='distance')return Math.hypot(...args.a.map((x,i)=>x-args.b[i]));
  if(key==='cross')return [args.a[1]*args.b[2]-args.a[2]*args.b[1],args.a[2]*args.b[0]-args.a[0]*args.b[2],args.a[0]*args.b[1]-args.a[1]*args.b[0]];
  if(key==='reflect'){const n=unit(args.normal),dot=args.direction.reduce((v,x,i)=>v+x*n[i],0);return args.direction.map((x,i)=>x-2*dot*n[i]);}
  if(key==='fresnel'){const n=unit(args.normal),v=unit(args.view),dot=clamp(n.reduce((s,x,i)=>s+x*v[i],0));return args.base+(1-args.base)*Math.pow(1-dot,Math.max(args.power,.0001));}
  if(key==='noise')return noise2(args.uv.map(x=>x*args.scale));
  if(key==='checker')return ((Math.floor(args.uv[0]*args.scale[0])+Math.floor(args.uv[1]*args.scale[1]))%2+2)%2;
  if(key==='radialGradient')return clamp(1-Math.hypot(...args.uv.map((x,i)=>x-args.center[i]))/Math.max(args.radius,1e-6));
  if(key==='linearGradient')return clamp((args.uv[0]-.5)*Math.cos(args.angle)+(args.uv[1]-.5)*Math.sin(args.angle)+.5);
  const a=args.a,b=args.b,v=args.value;if(key==='add')return map(a,b,(x,y)=>x+y);if(key==='subtract')return map(a,b,(x,y)=>x-y);if(key==='multiply')return map(a,b,(x,y)=>x*y);if(key==='divide')return map(a,b,(x,y)=>x/(Math.abs(y)<1e-6?1e-6:y));if(key==='power')return map(a,b,(x,y)=>Math.pow(Math.max(x,0),y));if(key==='min'||key==='max')return map(a,b,Math[key]);if(key==='step')return map(a,b,(x,y)=>y<x?0:1);if(key==='lerp')return map(a,b,(x,y)=>x+(y-x)*args.alpha);if(key==='clamp')return map(map(v,args.min,(x,y)=>Math.max(x,y)),args.max,(x,y)=>Math.min(x,y));if(key==='dot')return vector(a,3).reduce((sum,value,index)=>sum+value*vector(b,3)[index],0);if(key==='length')return Math.hypot(...(Array.isArray(v)?v:[v]));if(key==='normalize'){const length=Math.hypot(...(Array.isArray(v)?v:[v]));return map(v,1,x=>length?x/length:0);}if(key==='normalMap'){const n=vector(v,3).map(x=>x*2-1);n[0]*=args.strength;n[1]*=args.strength;return operation('normalize',{value:n});}if(key==='saturate')return map(v,0,x=>clamp(x));if(key==='oneMinus')return map(v,0,x=>1-x);if(key==='sine')return map(v,0,Math.sin);if(key==='absolute')return map(v,0,Math.abs);if(key==='fraction')return map(v,0,x=>x-Math.floor(x));if(key==='tilingOffset')return map(map(args.uv,args.tiling,(x,y)=>x*y),args.offset,(x,y)=>x+y);if(key==='panner')return map(args.uv,map(args.speed,args.time,(x,y)=>x*y),(x,y)=>x+y);if(key==='rotateUV'){const uv=vector(args.uv,2),center=args.center,c=Math.cos(args.angle),s=Math.sin(args.angle),x=uv[0]-center[0],y=uv[1]-center[1];return [x*c-y*s+center[0],x*s+y*c+center[1]];}throw Error('지원하지 않는 머테리얼 계산: '+key);}
export function evaluateMaterial(data,{uv=[0,0],time=0,worldPosition=[0,0,0],worldNormal=[0,0,1],viewDirection=[0,0,1],sampleTexture}={}){
  const surface={...copy(materialDefaults),...copy(data.surface||{})},graph=data.graph;if(!graph)return surface;if(!validMaterialGraph(graph))throw Error('머테리얼 그래프 검증 실패');const edges=normalizedMaterialEdges(graph),cache=new Map();
  const read=(id,output='value')=>{const token=id+':'+output;if(cache.has(token))return cache.get(token);const node=graph.nodes.find(node=>node.id===id),key=nodeKey(node);let value;if(key==='legacyColor')value=rgb(surface.color);else if(key==='legacyRough')value=surface.roughness;else if(['scalar','vector2','vector3','vector4','color','scalarParameter','vectorParameter'].includes(key)){value=data.parameters?.[node.parameter]??node.value??.5;if(typeof value==='string')value=rgb(value);}else if(key==='uv')value=uv;else if(key==='time')value=time;else if(key==='worldPosition')value=worldPosition;else if(key==='worldNormal')value=unit(worldNormal);else if(key==='viewDirection')value=unit(viewDirection);else{const args={};for(const input of catalogMap.get(key).inputs){const edge=edges.find(edge=>edge.to.node===id&&edge.to.pin===input.id);args[input.id]=edge?read(edge.from.node,edge.from.pin):node.inputValues?.[input.id]??input.value??(input.id==='uv'?uv:input.id==='time'?time:key==='fresnel'&&input.id==='normal'?worldNormal:key==='fresnel'&&input.id==='view'?viewDirection:0);}if(key==='split')value=vector(args.value,4)['xyzw'.indexOf(output)];else if(key==='combine')value=[args.x,args.y,args.z,args.w].slice(0,output.length);else if(key==='texture'){const sample=sampleTexture?.(node.texture,args.uv,node.colorSpace)||[1,1,1,1];value=output==='rgba'?sample:output==='rgb'?sample.slice(0,3):sample['rgba'.indexOf(output)]??1;}else value=operation(key,args);}cache.set(token,value);return value;};
  const output=graph.nodes.find(node=>nodeKey(node)==='surface');if(!output)return surface;for(const input of surfaceInputs){const edge=edges.find(edge=>edge.to.node===output.id&&edge.to.pin===input.id);if(!edge)continue;const value=read(edge.from.node,edge.from.pin);if(input.id==='baseColor'||input.id==='emissive')surface[input.key]=hex(vector(value,3));else if(input.id==='normal')surface.normal=vector(value,3);else surface[input.key]=clamp(Number(Array.isArray(value)?value[0]:value),input.id==='ior'?1:0,input.id==='ior'?2.5:1);}return surface;
}
export function materialParameters(data){return [...new Map((data.graph?.nodes||[]).filter(node=>node.parameter).map(node=>[node.parameter,{name:node.parameter,type:nodeKey(node)==='scalarParameter'?'float':nodeKey(node)==='texture'?'texture':'vec3',value:copy(data.parameters?.[node.parameter]??node.texture??node.value)}])).values()];}
export const materialPresets={fresnel:'Fresnel · 가장자리 발광',dissolve:'Dissolve · 소멸 마스크',checker:'Checker · 체크 표면',scroll:'Panner · 흐르는 텍스처'};
export function makeMaterialPreset(key){
  if(!Object.hasOwn(materialPresets,key))throw Error('머테리얼 템플릿을 확인하세요.');
  const data={surface:copy(materialDefaults),graph:{nodes:[],edges:[]}};
  const add=(key,id,x,y,values={})=>{const node={...makeMaterialNode(key,x,y),id,...values};data.graph.nodes.push(node);return node;};
  const wire=(from,pin,to,input)=>{const result=connectMaterial(data.graph,{node:from.id,pin},{node:to.id,pin:input});if(!result.ok)throw Error(result.reason);};
  const output=add('surface','surface',900,80);
  if(key==='fresnel'){
    const fresnel=add('fresnel','edge',60,80),color=add('vectorParameter','tint',60,350,{parameter:'EdgeColor',value:[.1,.5,1]}),multiply=add('multiply','emission',540,180),power=add('scalarParameter','falloff',60,560,{parameter:'Falloff',value:5});
    wire(power,'value',fresnel,'power');wire(fresnel,'value',multiply,'a');wire(color,'value',multiply,'b');wire(multiply,'value',output,'emissive');data.surface.color='#111c28';data.surface.emissiveIntensity=3;
  }else if(key==='dissolve'){
    const noise=add('noise','noise',40,50),amount=add('scalarParameter','amount',40,280,{parameter:'Dissolve',value:.45}),mask=add('step','mask',460,80),edge=add('subtract','edge',460,350),width=add('smoothstep','edgeMask',710,400);
    wire(amount,'value',mask,'a');wire(noise,'value',mask,'b');wire(mask,'value',output,'opacity');wire(noise,'value',edge,'a');wire(amount,'value',edge,'b');width.inputValues={min:0,max:.12};wire(edge,'value',width,'value');wire(width,'value',output,'roughness');data.surface.blendMode='masked';data.surface.color='#d39347';
  }else if(key==='checker'){
    const checker=add('checker','pattern',40,80),a=add('vectorParameter','colorA',40,310,{parameter:'ColorA',value:[.08,.13,.18]}),b=add('vectorParameter','colorB',40,480,{parameter:'ColorB',value:[.7,.8,.85]}),mix=add('lerp','mix',470,150);
    wire(a,'value',mix,'a');wire(b,'value',mix,'b');wire(checker,'value',mix,'alpha');wire(mix,'value',output,'baseColor');
  }else{
    const uv=add('panner','scroll',50,70),texture=add('texture','texture',470,100);wire(uv,'value',texture,'uv');wire(texture,'rgb',output,'baseColor');
  }
  return data;
}
export async function resolveMaterialAsset(data,read,seen=new Set()){
  if(!data.parent){if(data.surfaceOverrides)throw Error('부모 머테리얼을 선택하세요.');return copy(data);}if(!validAssetPath(data.parent))throw Error('부모 머테리얼 경로를 확인하세요.');if(seen.size>=16||seen.has(data.parent))throw Error('머테리얼 인스턴스 부모가 순환하거나 너무 깊어요.');seen.add(data.parent);const parent=await read(data.parent);if(!parent||parent.version!==1||!parent.parent&&!validMaterialSurface(parent.surface))throw Error('부모 머테리얼을 확인하세요.');const base=await resolveMaterialAsset(parent,read,seen);
  for(const parameter of materialParameters(base)){if(!Object.hasOwn(data.parameters||{},parameter.name))continue;const value=data.parameters[parameter.name],valid=parameter.type==='texture'?validAssetPath(value):parameter.type==='vec3'?Array.isArray(value)&&value.length===3&&value.every(finite):finite(value);if(!valid)throw Error('머테리얼 파라미터 자료형을 확인하세요: '+parameter.name);}
  base.name=data.name;base.parameters={...base.parameters,...copy(data.parameters||{})};base.surface={...base.surface,...copy(data.surfaceOverrides||{})};base.graph??=materialGraph();const output=base.graph.nodes.find(node=>nodeKey(node)==='surface');for(const input of surfaceInputs){if(!Object.hasOwn(data.surfaceOverrides||{},input.key))continue;const id='hb_instance_'+input.key;const node={id,key:input.type==='vec3'?(input.id==='normal'?'vector3':'color'):'scalar',title:input.label,kind:'value',x:80,y:80,value:copy(data.surfaceOverrides[input.key])};base.graph.nodes=base.graph.nodes.filter(node=>node.id!==id);base.graph.nodes.push(node);base.graph.edges=normalizedMaterialEdges(base.graph).filter(edge=>!(edge.to.node===output.id&&edge.to.pin===input.id));base.graph.edges.push({from:{node:id,pin:'value'},to:{node:output.id,pin:input.id}});}return base;
}
const glNumber=value=>{const number=finite(value)?value:0;return Number.isInteger(number)?number+'.0':String(number);},glValue=(value,type)=>{if(typeof value==='string')value=rgb(value);return type==='float'?glNumber(Array.isArray(value)?value[0]:value):type+'('+vector(value,Number(type.slice(3))).map(glNumber).join(',')+')';};
export function compileMaterial(data){
  const graph=data.graph||materialGraph();if(!validMaterialGraph(graph))throw Error('머테리얼 그래프 검증 실패');const surface={...materialDefaults,...data.surface},edges=normalizedMaterialEdges(graph),lines=[],cache=new Map(),textures=[];let serial=0;
  const cast=(expr,type,target)=>type===target?expr:target==='float'?expr+'.x':type==='float'?target+'('+expr+')':Number(type.slice(3))>Number(target.slice(3))?expr+'.'+'xyzw'.slice(0,Number(target.slice(3))):target+'('+expr+','+Array(Number(target.slice(3))-Number(type.slice(3))).fill('0.0').join(',')+')';
  const expression=(id,output='value')=>{const token=id+':'+output;if(cache.has(token))return cache.get(token);const node=graph.nodes.find(node=>node.id===id),key=nodeKey(node),pins=materialPins(node,graph);let type=pins.outputs.find(pin=>pin.id===output)?.type||'float',code;
    if(key==='legacyColor')code='hbSRGB('+glValue(surface.color,'vec3')+')';else if(key==='legacyRough')code=glNumber(surface.roughness);else if(['scalar','vector2','vector3','vector4','color','scalarParameter','vectorParameter'].includes(key)){const value=data.parameters?.[node.parameter]??node.value??.5;code=typeof value==='string'?'hbSRGB('+glValue(value,type)+')':glValue(value,type);}else if(key==='uv')code='hbUv';else if(key==='time')code='hbTime';else if(key==='worldPosition')code='hbWorldPosition';else if(key==='worldNormal')code='normalize(hbWorldNormal)';else if(key==='viewDirection')code='normalize(cameraPosition-hbWorldPosition)';else{const spec=catalogMap.get(key),args={};for(const input of spec.inputs){const edge=edges.find(edge=>edge.to.node===id&&edge.to.pin===input.id),target=input.type==='numeric'?(key==='length'?actualType({...node,key:'normalize'},graph):type):input.type;const linked=edge&&expression(edge.from.node,edge.from.pin);args[input.id]=linked?cast(linked.code,linked.type,target):key==='fresnel'&&input.id==='normal'&&node.inputValues?.normal===undefined?'normalize(hbWorldNormal)':key==='fresnel'&&input.id==='view'&&node.inputValues?.view===undefined?'normalize(cameraPosition-hbWorldPosition)':input.id==='uv'&&node.inputValues?.uv===undefined?'hbUv':input.id==='time'&&node.inputValues?.time===undefined?'hbTime':glValue(node.inputValues?.[input.id]??input.value??0,target);}
      if(key==='split')code=args.value+'.'+output;
      else if(key==='combine')code=type+'('+['x','y','z','w'].slice(0,Number(type.slice(3))).map(k=>args[k]).join(',')+')';
      else if(key==='fresnel')code='('+args.base+'+(1.0-'+args.base+')*pow(1.0-clamp(dot(normalize('+args.normal+'),normalize('+args.view+')),0.0,1.0),max('+args.power+',0.0001)))';
      else if(key==='noise')code='hbNoise('+args.uv+'*'+args.scale+')';
      else if(key==='checker')code='mod(dot(floor('+args.uv+'*'+args.scale+'),vec2(1.0)),2.0)';
      else if(key==='radialGradient')code='clamp(1.0-length('+args.uv+'-'+args.center+')/max('+args.radius+',0.000001),0.0,1.0)';
      else if(key==='linearGradient')code='clamp(dot('+args.uv+'-vec2(0.5),vec2(cos('+args.angle+'),sin('+args.angle+')))+0.5,0.0,1.0)';
      else if(['cosine','floor','ceil','sign','exp2'].includes(key))code=(key==='cosine'?'cos':key)+'('+args.value+')';
      else if(['log2','squareRoot'].includes(key))code=(key==='log2'?'log2':'sqrt')+'(max('+args.value+','+glValue(key==='log2'?1e-6:0,type)+'))';
      else if(key==='smoothstep')code='hbSmooth('+args.min+','+args.max+','+args.value+')';
      else if(key==='cross'||key==='distance')code=key+'('+args.a+','+args.b+')';
      else if(key==='reflect')code='reflect('+args.direction+',normalize('+args.normal+'))';
      else if(key==='texture'){const textureKey=node.id+':rgba';let sample=cache.get(textureKey);if(!sample){const uniform='hbTexture'+textures.length,path=data.parameters?.[node.parameter]??node.texture; if(!path)code='vec4(1.0)';else{textures.push({uniform,path,colorSpace:node.colorSpace||'srgb',wrap:node.wrap||'repeat'});code='texture2D('+uniform+','+args.uv+')';if(node.colorSpace!=='linear')code='vec4(hbSRGB('+code+'.rgb),'+code+'.a)';}const variable='hbN'+serial++;lines.push('vec4 '+variable+' = '+code+';');sample={code:variable,type:'vec4'};cache.set(textureKey,sample);}const suffix=output==='rgba'?'':'.'+output;const result={code:sample.code+suffix,type};cache.set(token,result);return result;
      }else if(['add','subtract','multiply','divide'].includes(key))code='('+args.a+({add:'+',subtract:'-',multiply:'*',divide:'/'})[key]+(key==='divide'?'mix('+glValue(1e-6,type)+','+args.b+',step('+glValue(1e-6,type)+',abs('+args.b+')))' :args.b)+')';else if(['min','max','step','power'].includes(key))code=(key==='power'?'pow':key)+'('+(key==='power'?'max('+args.a+','+glValue(0,type)+')':args.a)+','+args.b+')';else if(key==='lerp')code='mix('+args.a+','+args.b+','+args.alpha+')';else if(key==='clamp')code='clamp('+args.value+','+args.min+','+args.max+')';else if(key==='saturate')code='clamp('+args.value+','+glValue(0,type)+','+glValue(1,type)+')';else if(key==='oneMinus')code='('+glValue(1,type)+'-'+args.value+')';else if(['normalize','sine','absolute','fraction','length'].includes(key))code=({sine:'sin',absolute:'abs',fraction:'fract'}[key]||key)+'('+args.value+')';else if(key==='dot')code='dot('+args.a+','+args.b+')';else if(key==='normalMap')code='normalize(vec3(('+args.value+'.xy*2.0-1.0)*'+args.strength+','+args.value+'.z*2.0-1.0))';else if(key==='tilingOffset')code='('+args.uv+'*'+args.tiling+'+'+args.offset+')';else if(key==='panner')code='('+args.uv+'+'+args.speed+'*'+args.time+')';else if(key==='rotateUV')code='hbRotate('+args.uv+','+args.angle+','+args.center+')';else throw Error('미지원 머테리얼 노드: '+key);
    }const variable='hbN'+serial++;lines.push(type+' '+variable+' = '+code+';');const result={code:variable,type};cache.set(token,result);return result;};
  const output=graph.nodes.find(node=>nodeKey(node)==='surface'),values={};for(const input of surfaceInputs){const edge=edges.find(edge=>edge.to.node===output?.id&&edge.to.pin===input.id);if(edge){const linked=expression(edge.from.node,edge.from.pin);values[input.id]=cast(linked.code,linked.type,input.type);}else values[input.id]=typeof surface[input.key]==='string'?'hbSRGB('+glValue(surface[input.key],input.type)+')':glValue(surface[input.key],input.type);}
  return {lines:lines.join('\n'),values,textures,normalConnected:edges.some(edge=>edge.to.node===output?.id&&edge.to.pin==='normal'),key:JSON.stringify(data)};
}
const fragmentHelpers=`varying vec3 hbWorldPosition; varying vec3 hbWorldNormal; varying vec2 hbUv; uniform float hbTime; uniform float hbEmissionIntensity;
float hbHash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
float hbNoise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hbHash(i),hbHash(i+vec2(1,0)),f.x),mix(hbHash(i+vec2(0,1)),hbHash(i+vec2(1,1)),f.x),f.y);}
${['float','vec2','vec3','vec4'].map(t=>`${t} hbSmooth(${t} a,${t} b,${t} v){${t} x=clamp((v-a)/max(b-a,${t}(0.000001)),${t}(0.0),${t}(1.0));return x*x*(${t}(3.0)-${t}(2.0)*x);}`).join('\n')}
vec3 hbSRGB(vec3 c){return mix(c/12.92,pow((c+0.055)/1.055,vec3(2.4)),step(vec3(0.04045),c));}
vec2 hbRotate(vec2 uv,float a,vec2 center){float s=sin(a),c=cos(a);vec2 p=uv-center;return vec2(c*p.x-s*p.y,s*p.x+c*p.y)+center;}
vec3 hbNormal(vec3 eye,vec3 n,vec3 mapN){vec3 q0=dFdx(eye),q1=dFdy(eye);vec2 st0=dFdx(hbUv),st1=dFdy(hbUv);vec3 s=normalize(q0*st1.t-q1*st0.t),t=normalize(-q0*st1.s+q1*st0.s);return normalize(mat3(s,t,n)*mapN);}`;
export function createThreeMaterial(THREE,data,{fileUrl=path=>'/api/file?path='+encodeURIComponent(path),onError=()=>{},renderer}={}){
  if(renderer?.hbMaterial)return renderer.hbMaterial(data,{fileUrl,onError});
  data=copy(data);const plan=compileMaterial(data),surface={...materialDefaults,...data.surface},textures=[],loading=[],uniforms={hbTime:{value:0},hbEmissionIntensity:{value:surface.emissiveIntensity}};let disposed=false;
  const material=new THREE.MeshPhysicalMaterial({color:'#ffffff',roughness:surface.roughness,metalness:surface.metalness,emissive:'#ffffff',emissiveIntensity:surface.emissiveIntensity,opacity:surface.opacity,transparent:surface.blendMode==='translucent',alphaTest:surface.blendMode==='masked'?surface.alphaTest:0,side:surface.doubleSided?THREE.DoubleSide:THREE.FrontSide,clearcoat:1,clearcoatRoughness:surface.clearcoatRoughness,transmission:plan.values.transmission!=='0.0'?1:surface.transmission,ior:surface.ior});
  for(const binding of plan.textures){const placeholder=new THREE.DataTexture(new Uint8Array([255,255,255,255]),1,1);placeholder.needsUpdate=true;textures.push(placeholder);uniforms[binding.uniform]={value:placeholder};loading.push(new Promise(resolve=>new THREE.TextureLoader().load(fileUrl(binding.path),texture=>{if(disposed){texture.dispose();resolve(null);return;}texture.colorSpace=THREE.NoColorSpace;texture.wrapS=texture.wrapT=binding.wrap==='repeat'?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping;uniforms[binding.uniform].value=texture;textures.push(texture);material.needsUpdate=true;resolve(texture);},undefined,error=>{onError('텍스처를 읽을 수 없어요: '+binding.path);resolve(null);})));}
  material.onBeforeCompile=shader=>{Object.assign(shader.uniforms,uniforms);shader.vertexShader='varying vec3 hbWorldPosition; varying vec3 hbWorldNormal; varying vec2 hbUv;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <uv_vertex>','#include <uv_vertex>\nhbUv = uv;');shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>','#include <project_vertex>\nhbWorldPosition=(modelMatrix*vec4(transformed,1.0)).xyz; hbWorldNormal=normalize(inverseTransformDirection(transformedNormal,viewMatrix));');shader.fragmentShader=fragmentHelpers+'\n'+plan.textures.map(binding=>'uniform sampler2D '+binding.uniform+';').join('\n')+'\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\n'+plan.lines+'\ndiffuseColor.rgb = '+plan.values.baseColor+'; diffuseColor.a = '+plan.values.opacity+';');shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\nroughnessFactor = clamp('+plan.values.roughness+',0.0,1.0);');shader.fragmentShader=shader.fragmentShader.replace('#include <metalnessmap_fragment>','#include <metalnessmap_fragment>\nmetalnessFactor = clamp('+plan.values.metallic+',0.0,1.0);');shader.fragmentShader=shader.fragmentShader.replace('#include <emissivemap_fragment>','#include <emissivemap_fragment>\ntotalEmissiveRadiance = '+plan.values.emissive+' * hbEmissionIntensity;');if(plan.normalConnected)shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nnormal = hbNormal(-vViewPosition,normal,normalize('+plan.values.normal+'));');shader.fragmentShader=shader.fragmentShader.replace('#include <lights_physical_fragment>',THREE.ShaderChunk.lights_physical_fragment.replace('material.ior = ior;','material.ior = clamp('+plan.values.ior+',1.0,2.5);').replace('material.clearcoat = clearcoat;','material.clearcoat = clamp('+plan.values.clearcoat+',0.0,1.0);').replace('material.clearcoatRoughness = clearcoatRoughness;','material.clearcoatRoughness = clamp('+plan.values.clearcoatRoughness+',0.0,1.0);'));shader.fragmentShader=shader.fragmentShader.replace('#include <transmission_fragment>',THREE.ShaderChunk.transmission_fragment.replace('material.transmission = transmission;','material.transmission = clamp('+plan.values.transmission+',0.0,1.0);'));shader.fragmentShader=shader.fragmentShader.replace('#include <aomap_fragment>','#include <aomap_fragment>\nreflectedLight.indirectDiffuse *= clamp('+plan.values.ao+',0.0,1.0);');};
  material.customProgramCacheKey=()=>plan.key;
  const baseDispose=material.dispose.bind(material);material.dispose=()=>{if(disposed)return;disposed=true;for(const texture of textures)texture.dispose();baseDispose();};
  material.userData.ready=Promise.all(loading);material.userData.hbMaterial=true;material.userData.materialSource=copy(data);material.userData.updateTime=time=>uniforms.hbTime.value=time;
  // Three's default clone does not retain onBeforeCompile; own a fresh texture set.
  material.clone=()=>createThreeMaterial(THREE,data,{fileUrl,onError});return material;
}
