import {nativeTargetPin} from './native-model.js';
import {RuntimeGame} from './runtime-game.js';
import {nativeSpawnRequest} from './native-spawn.js';
import {nativeBindings,mergeNativeReply} from './native-module-query.js';
import {createNativeChannel} from './native-channel.js';
import {nativeWorldClient,advanceNativeFrames} from './native-transport.js';
import {FrameProfiler} from './frame-profiler.js';
import {createFrameLoop} from './frame-loop.js';
import {renderGameViewport,fallbackGameCamera} from './game-camera.js';
import {bindRuntimePointer} from './runtime-input.js';
import {kioskSettings,resolveBuildPath,frameSettings} from './build-profile.js';
import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {session,flushStorage} from './project-session.js';
import {editorRequest,fileUrl} from './project-browser.js';
import {validScene,defaultEnvironment,defaultRuntimeSettings} from './model.js';
import {validValue} from './blueprint-model.js';
import {preparePlayWorld,resolvePlayAsset} from './play-world.js';
import {BlueprintRuntime} from './blueprint-runtime.js';
import {nativeRequestWorld} from './native-model.js';
import {engineOperations,loadModel} from './engine-services.js';
import {sceneRendering,visualComponentSignature} from './scene-rendering.js';
import {scenePrimitives} from './scene-primitives.js';
import {createSky,applySceneEnvironment,syncSkyToCamera,disposeSceneEnvironment} from './scene-environment.js';
const $=s=>document.querySelector(s),canvas=$('#game-canvas'),overlay=$('#game-ui'),menu=$('#pause-menu');
const config=await(await editorRequest('/api/player')).json();document.title=config.name;
const readAsset=async path=>(await editorRequest(fileUrl(path))).json(),readText=async path=>(await editorRequest(fileUrl(path))).text();
let renderer,world,visuals,primitives,vm,services,objects=[],builds=new Map(),currentScene,activeCamera,fallback,environment,sky,environmentContext,frame=0,sceneFrame=0,busy=false,closed=false,closing=false,failureCleanup,mobileActive=true,mobileSuspended=false,last=performance.now(),queued=0,sceneEpoch=0;
const kiosk=kioskSettings(config);let operatorMenu=false,lastInteraction=performance.now(),kioskResetting=false;
if(kiosk.enabled&&kiosk.hideCursor){const style=document.createElement('style');style.textContent='html,body,body *{cursor:none!important}';document.head.append(style);}
for(const type of ['pointerdown','pointermove','touchstart','keydown'])document.addEventListener(type,()=>{lastInteraction=performance.now();},{capture:true,passive:true});
async function kioskReset(){if(kioskResetting||closed||closing)return;kioskResetting=true;try{while(busy)await new Promise(resolve=>setTimeout(resolve,10));busy=true;if(menu.open)menu.close();runtimeGame.reset();held.clear();vm.resetInput();await openScene(session.startupScene);lastInteraction=performance.now();queued=0;}catch(error){await fail(error);}finally{busy=false;kioskResetting=false;last=performance.now();schedule();}}
let runtimeGame=new RuntimeGame();const nativeSamples=[];const profiler=new FrameProfiler(600,frameSettings(config).targetFrameRate),groups=new Map(),logs=[],held=new Set(),files=(await(await editorRequest('/api/project')).json()).entries;
const log=message=>{logs.push(String(message));if(logs.length>100)logs.shift();};
function remove(object){const g=groups.get(object.id);if(!g)return;visuals.dispose(g);g.removeFromParent();groups.delete(object.id);}
function build(object){const g=primitives.build(object);groups.set(object.id,g);world.add(g);update(object);g.userData.ready=visuals.build(object,g);g.userData.ready.catch(fail);return g;}
function update(object){let g=groups.get(object.id);if(!g)return;if(g.userData.componentSignature!==undefined&&g.userData.componentSignature!==visualComponentSignature(object)){const parent=g.parent,children=g.children.filter(c=>c.userData.objectId&&c.userData.objectId!==object.id);for(const c of children)c.removeFromParent();remove(object);g=build(object);parent?.add(g);children.forEach(c=>g.add(c));}g.position.fromArray(object.position);g.rotation.set(...object.rotation.map(THREE.MathUtils.degToRad));g.scale.fromArray(object.scale);g.visible=object.visible;}
const sendNative=createNativeChannel(session.nativeChannel,async data=>(await editorRequest('/api/native/call',{method:'POST',body:JSON.stringify(data)})).json());
async function nativeCall(request,bindingBuild){const started=performance.now(),owner=vm,epoch=sceneEpoch;bindingBuild??=builds.get((()=>{const o=objects.find(o=>o.id===request.self);return o?.blueprintAsset||o?.nativeBuildAsset;})());if(!bindingBuild)throw Error('C++ 바인딩 없음');const paths=new Set([...builds].filter(([,b])=>b.token===bindingBuild.token).map(([p])=>p)),result=mergeNativeReply(await nativeWorldClient(bindingBuild,owner).call({...request,...nativeSpawnRequest(owner,bindingBuild,services.spawnCatalog),nativeBindings:nativeBindings(objects,builds,owner.bindings,request,bindingBuild.metadata),scopes:[...owner.scopes],input:owner.inputSnapshot(),objects:nativeRequestWorld(objects,paths,request,bindingBuild.metadata,services.spriteSkinSnapshot)},bindingBuild.metadata,packet=>sendNative({token:bindingBuild.token,request:packet})),request.self);if(result.transport){nativeSamples.push(result.transport);if(nativeSamples.length>120)nativeSamples.shift();}if(epoch!==sceneEpoch)return {outputs:{},events:[],objects:[]};const applyStarted=performance.now();owner.nativeTiming={...result.transport};const states=result.objects||[],stateObjects=states.length>8?new Map(objects.map(o=>[o.id,o])):null;for(const state of states){const object=stateObjects?stateObjects.get(state.id):objects.find(o=>o.id===state.id);if(object){if(state.position!==undefined&&!validValue('transform',state))throw Error('C++ Transform 오류');Object.assign(object,state);if(state.position!==undefined)update(object);}}if(result.transport)result.transport.clientApplyMs=performance.now()-applyStarted;owner.nativeTiming={...result.transport};if(!request.calls)await owner.applyNativeOperations(result.operations||[],owner.bindings.find(b=>b.self===request.self)||{self:request.self,root:{components:[]}});if(result.clock){owner.core.scale=result.clock.scale;owner.core.paused=result.clock.paused;if(!request.command)owner.core.time=result.clock.time;}if(result.transport){result.transport.frontendMs=performance.now()-started;result.transport.callCount=request.command?0:result.results?.length??1;}return result;}
async function release(reason){sceneEpoch++;try{if(vm?.active)await vm.stop(reason);}finally{services?.dispose(reason);services=null;disposeSceneEnvironment(world);for(const o of objects)remove(o);world?.traverse(c=>{c.geometry?.dispose();for(const m of c.material?(Array.isArray(c.material)?c.material:[c.material]):[])m.dispose();});primitives?.dispose();primitives=null;world?.environment?.dispose();groups.clear();visuals?.dispose2D();}}
async function openScene(path,data,travelArguments={}){
  const carriedInput=vm?.active?vm.inputState:undefined;
  data??=await readAsset(path);if(!validScene(data))throw Error('장면 검증 실패: '+path);await release('LevelTransition');currentScene=path;sceneFrame=0;
  const prepared=await preparePlayWorld(structuredClone(data.objects),data.runtime,{game:runtimeGame,gameInstance:session.gameInstance||'',travelArguments,readAsset,readText,listAssets:async()=>files,buildNative:async(header,source)=>(await editorRequest('/api/native/build',{method:'POST',body:JSON.stringify({header,source})})).json()});objects=prepared.objects;builds=prepared.builds;
  world=new THREE.Scene();world.background=new THREE.Color();environment={...defaultEnvironment,...data.environment};const settings={...defaultRuntimeSettings,...data.runtime};primitives=scenePrimitives(data.surface);
  visuals=sceneRendering({read:readAsset,fileUrl,loadModel,current:id=>groups.get(id),all:()=>[...groups.values()],error:fail});objects.forEach(build);for(const object of objects)if(object.parent)groups.get(object.parent)?.add(groups.get(object.id));await Promise.all([...groups.values()].map(g=>g.userData.ready));await visuals.preparePhysics(objects);
  await visuals.prepareSpawn(prepared.spawnCatalog);
  const ambientLight=new THREE.HemisphereLight(0xd6e8ee,0x677955,1.15);world.add(ambientLight);const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();world.userData.environmentTarget=pmrem.fromScene(room,.04);world.environment=world.userData.environmentTarget.texture;room.dispose();pmrem.dispose();
  const groundFloor=primitives.mesh(world,new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x526c6d,roughness:1}),[0,-.78,0],[-Math.PI/2,0,0]);groundFloor.castShadow=false;groundFloor.visible=false;groundFloor.userData.editorHelper=true;sky=createSky(world);const sun=groups.get('sun-light')?.children.find(c=>c.isDirectionalLight);environmentContext={scene:world,environment,surface:data.surface,runtimeSettings:settings,ambientLight,mainRenderer:renderer,...sky,sun};applySceneEnvironment({...environmentContext,objects});world.traverse(node=>{if(node.userData.editorHelper)node.visible=false;});
  fallback=fallbackGameCamera(settings.dimension,canvas.clientWidth/Math.max(1,canvas.clientHeight));activeCamera=fallback;
  services=engineOperations({game:runtimeGame,particleSnapshot:visuals.particleSnapshot,material:visuals.material,materialFloat:visuals.materialFloat,spriteFrame:visuals.spriteFrame,spriteFlip:visuals.spriteFlip,tilemapFrame:visuals.tilemapFrame,spawnCatalog:prepared.spawnCatalog,gameplay:prepared.gameplay,physicsOptions:prepared.physicsOptions,listenerPosition:()=>activeCamera.getWorldPosition(new THREE.Vector3()).toArray(),build,remove,update,mesh:id=>groups.get(id),meshes:()=>[...groups.values()],scene:()=>world,overlay:()=>overlay,readAsset,asset:async(name,kind)=>resolvePlayAsset(files,/^(Assets|Source)\//.test(name)?resolveBuildPath(name,config.redirects):name,kind)});
  // Packaged execution never stops at editor breakpoints.
  for(const binding of prepared.bindings){const clear=value=>{if(Array.isArray(value))value.forEach(clear);else if(value&&typeof value==='object'){delete value.breakpoint;Object.values(value).forEach(clear);}};clear(binding.root);}
  vm=new BlueprintRuntime(objects,prepared.bindings,{...services,game:runtimeGame,startupScene:session.startupScene,scenePath:path,inputState:carriedInput,inputAssets:prepared.inputAssets,inputCamera:()=>visuals.gameCamera(objects,{width:canvas.clientWidth,height:canvas.clientHeight},vm?.sequenceCamera)||activeCamera,updateObject:update,native:nativeCall,nativeBuild:self=>builds.get((()=>{const o=objects.find(o=>o.id===self);return o?.blueprintAsset||o?.nativeBuildAsset;})()),log});for(const b of new Map([...builds.values()].map(b=>[b.token,b])).values())await nativeCall({command:'reset'},b);const audioWait=setTimeout(()=>{if(services?.audioState().state==='suspended')$('#start-game').hidden=false;},1500);try{await vm.start();}finally{clearTimeout(audioWait);}for(const key of held)await vm.input(key,1);
}
async function report(error){
  const data={ok:!error,scene:currentScene,frames:frame,time:vm?.core.time||0,renderer:'WebGL2',error:error?.message?.slice(0,4000)||null,drawCalls:renderer?.info.render.calls||0,performance:profiler.snapshot(),size:[canvas.width,canvas.height]};
  if(config.configuration==='development'||config.smoke){
    data.objects=objects.slice(0,2000).map(o=>({id:o.id,name:o.name,kind:o.kind,position:o.position,rotation:o.rotation,scale:o.scale,visible:o.visible,poolActive:o.poolActive,velocity:o.velocity,currentSprite:o.currentSprite,nativeProperties:o.nativeProperties}));
    data.variables=[];let budget=250000;for(const b of vm?.bindings||[]){const values={};for(const [id,value] of b.variables){const text=JSON.stringify(value);if(text.length<=16000&&text.length<budget){values[id]=value;budget-=text.length;}}if(Object.keys(values).length)data.variables.push({self:b.self,values});}
    data.nativeTransport=nativeSamples;data.logs=logs.map(s=>s.slice(0,2000));data.audio=services?.audioState();data.mobileActive=mobileActive;
    data.game=runtimeGame.snapshot();
  }
  // Diagnostics may fail (e.g. a read-only save directory) without stopping the game.
  try{await editorRequest('/api/player/report',{method:'POST',body:JSON.stringify(data)});}catch(issue){console.warn('게임 진단 저장 실패:',issue.message);}return data;
}
async function fail(error){if(closed)return;closed=true;frameLoop.stop();const issue=error instanceof Error?error:Error(String(error));$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent=issue.message;failureCleanup=(async()=>{try{await report(issue);}catch{}try{await release('Failed');}catch(cleanup){console.warn(cleanup);}try{await flushStorage();}catch(storageError){console.warn(storageError);}console.error(issue);})();await failureCleanup;}
async function step(delta){await vm.flushInput();await advanceNativeFrames(builds,vm,delta,nativeCall);await vm.tick(delta);if(vm.sceneRequest){const r=vm.sceneRequest;if(r.reset){runtimeGame.reset();held.clear();vm.resetInput();}await openScene(r.path,r.data,r.arguments);}}
let reportPending=false;
const frameLoop=createFrameLoop(animate,frameSettings(config));
const schedule=()=>{if(!closed&&!closing&&!kioskResetting&&mobileActive)frameLoop.start();};
async function animate(now){if(closed||closing||kioskResetting)return;if(kiosk.enabled&&kiosk.idleResetSeconds>0&&now-lastInteraction>=kiosk.idleResetSeconds*1000&&!kioskResetting){kioskReset();return;}if(!mobileActive){mobileSuspended=true;return;}const delta=Math.min(.1,Math.max(0,(now-last)/1000));last=now;if(!menu.open&&mobileActive)queued=Math.min(1,queued+delta);if(busy)return;busy=true;const frameStart=performance.now();let simulationEnd=frameStart;try{if(!menu.open&&mobileActive){const stepDelta=queued;queued=0;await step(stepDelta);}simulationEnd=performance.now();
  const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio()))renderer.setSize(w,h,false);const aspect=w/Math.max(1,h);if(fallback.isOrthographicCamera){fallback.left=-7*aspect;fallback.right=7*aspect;}else fallback.aspect=aspect;fallback.updateProjectionMatrix();activeCamera=visuals.gameCamera(objects,{width:w,height:h},vm.sequenceCamera)||fallback;canvas.style.imageRendering=activeCamera.userData.cameraProperties?.pixelPerfect?'pixelated':'';visuals.tickParticles(objects,menu.open?0:delta*vm.core.scale,true);visuals.syncDecals();applySceneEnvironment({...environmentContext,objects});syncSkyToCamera(sky,activeCamera,menu.open?0:delta*vm.core.scale);world.traverse(node=>{if(node.userData.editorHelper)node.visible=false;});const renderStart=performance.now();renderGameViewport(renderer,activeCamera,()=>{visuals.prepare2D(renderer,world,activeCamera,environmentContext.runtimeSettings.sortingLayers);visuals.renderBloom(renderer,world,activeCamera,objects);});frame++;sceneFrame++;profiler.frame(frameStart,performance.now(),simulationEnd-frameStart,performance.now()-renderStart);
  if(frame===10){await report();if(!config.acceptance)window.chrome?.webview?.postMessage('hbengine.ready.player');}else if(config.configuration==='development'&&frame%120===0&&!reportPending){reportPending=true;report().finally(()=>reportPending=false);}
}catch(error){await fail(error);}finally{busy=false;}}
if(config.configuration==='development'||config.smoke)window.hbPlayerDebug={
  ready:()=>sceneFrame>=10&&!closed&&!!services&&!!vm?.active,
  lifecycle:()=>({frame,sceneFrame,busy,closed,closing,kioskResetting,scene:currentScene,mobileActive,active:!!vm?.active}),
  runtimePrototype:()=>Object.getPrototypeOf(vm),
  report:()=>report(),
  input:packet=>{lastInteraction=performance.now();return vm.dispatchInput(packet);},
  resetProfile:()=>profiler.reset(),
  profile:()=>profiler.snapshot(),
  audio:()=>services?.audioState()||null,
  game:()=>runtimeGame.snapshot(),
  inspect:()=>!services||!vm?.active?null:({scene:currentScene,time:vm.core.time,nativeTiming:{...vm.nativeTiming},nativeFrameGroups:{...vm.nativeFrameGroups},animation:services.animationState(),spriteSkin:services.spriteSkinState({vertices:true}),work:vm.inspectWork(),input:vm.inputSnapshot(),objects:structuredClone(objects),physics:services.physicsState(),projectiles:services.projectileState(),camera:{position:activeCamera.getWorldPosition(new THREE.Vector3()).toArray(),projection:activeCamera.type},sprites:objects.filter(o=>groups.get(o.id)?.userData.spriteMesh).map(o=>{const g=groups.get(o.id),m=g.userData.spriteMesh;return {id:o.id,flip:m.scale.toArray(),sprite:o.currentSprite||null,image:[m.material.map?.image?.width||0,m.material.map?.image?.height||0],children:g.children.length,surface:{material:m.material.type,transparent:m.material.transparent,depthWrite:m.material.depthWrite,alphaCutoff:m.material.alphaTest,normalImage:[m.material.normalMap?.image?.width||0,m.material.normalMap?.image?.height||0],normalScale:m.material.normalScale?.toArray()||null,normalColorSpace:m.material.normalMap?.colorSpace??null,castShadow:m.castShadow,receiveShadow:m.receiveShadow,light2d:m.material.userData.hbLight2D?{count:m.material.userData.hbLight2D.hbLight2DCount.value,layer:m.material.userData.hbLight2D.hbLight2DLayer.value,bytes:m.material.userData.hbLight2D.hbLight2DData.value?.image.data.byteLength||0,shapeBytes:m.material.userData.hbLight2D.hbLight2DShape.value?.image.data.byteLength||0,cookieBytes:m.material.userData.hbLight2D.hbLight2DCookies.value?.image.data.byteLength||0,shadowAtlas:m.material.userData.hbLight2D.hbShadowAtlas.value?[m.material.userData.hbLight2D.hbShadowAtlas.value.image.width,m.material.userData.hbLight2D.hbShadowAtlas.value.image.height]:null}:null}};}),lights2d:objects.filter(o=>groups.get(o.id)?.userData.light2d).map(o=>{const g=groups.get(o.id);return {id:o.id,type:g.userData.light2d.lightType,volumeVisible:g.userData.light2dVolume?.visible||false,volumeOrder:g.userData.light2dVolume?.renderOrder||0};}),renderer:{programs:renderer.info.programs.map(p=>({runnable:p.diagnostics?.runnable!==false})),vendor:renderer.getContext().getParameter(renderer.getContext().VENDOR),renderer:renderer.getContext().getParameter(renderer.getContext().RENDERER),info:renderer.info.render,memory:renderer.info.memory}}),
  capture(){renderGameViewport(renderer,activeCamera,()=>{visuals.prepare2D(renderer,world,activeCamera,environmentContext.runtimeSettings.sortingLayers);visuals.renderBloom(renderer,world,activeCamera,objects);});return canvas.toDataURL('image/png');},
  async call(self,nativeId,args={}){lastInteraction=performance.now();while(busy)await new Promise(resolve=>setTimeout(resolve,1));busy=true;try{const object=vm.object(self),build=builds.get(object?.blueprintAsset||object?.nativeBuildAsset),[className,name]=nativeId.split('.'),f=build?.metadata.classes.find(c=>c.name===className)?.functions.find(f=>f.name===name);return await nativeCall({key:'nativeCall',self,nativeId,args:{[nativeTargetPin(f)]:self,...args},scope:'',overrides:[]});}finally{busy=false;}},
  async open(path,args={}){lastInteraction=performance.now();while(busy)await new Promise(resolve=>setTimeout(resolve,1));busy=true;try{await openScene(path,undefined,args);return report();}finally{busy=false;}},
  async operation(key,args,measure=false){lastInteraction=performance.now();while(busy)await new Promise(resolve=>setTimeout(resolve,1));busy=true;const start=performance.now();try{const result=await services.operation(key,args,vm.bindings[0]||{self:objects[0]?.id,root:{components:[]}},vm);return measure?{...result,elapsedMs:performance.now()-start}:result;}finally{busy=false;}},
};
if(kiosk.enabled){$('#quit').hidden=true;$('#fullscreen').hidden=true;$('#pause-toggle').hidden=true;}
menu.addEventListener('close',()=>{operatorMenu=false;if(kiosk.enabled)$('#quit').hidden=true;services?.pauseAudio(false)?.catch(fail);queued=0;});
window.hbMobileLifecycle=active=>{window.hbMobileHostLifecycle?.(active);const changed=mobileActive!==active;mobileActive=active;if(!active){mobileSuspended=true;frameLoop.stop();}last=performance.now();queued=0;if(active&&mobileSuspended&&!closed&&!closing){mobileSuspended=false;schedule();}if(!active){releaseKeys();flushStorage().catch(fail);}const playback=services?.pauseAudio(!active||menu.open);Promise.resolve(playback).then(()=>{if(changed&&!closed&&config.configuration==='development')return report();}).catch(fail);};
if(config.mobile)document.addEventListener('visibilitychange',()=>window.hbMobileLifecycle(!document.hidden));
function releaseKeys(){held.clear();vm?.releaseInput().catch(fail);}
bindRuntimePointer(canvas,{runtime:()=>vm,enabled:()=>!closed&&!closing&&!menu.open&&vm?.active&&!vm.paused,error:fail});
document.addEventListener('keydown',e=>{if(kiosk.enabled&&e.key==='F12'){e.preventDefault();kioskReset();return;}if(kiosk.enabled&&e.ctrlKey&&e.altKey&&e.shiftKey&&e.key.toLowerCase()==='q'){e.preventDefault();operatorMenu=true;releaseKeys();menu.showModal();services?.pauseAudio(true)?.catch(fail);$('#quit').hidden=false;return;}if(e.key==='Escape'&&kiosk.enabled&&!operatorMenu){e.preventDefault();return;}if(e.key==='Escape'){e.preventDefault();releaseKeys();if(menu.open)menu.close();else{menu.showModal();services?.pauseAudio(true)?.catch(fail);}return;}if(menu.open||e.target.closest('input,textarea,select,button,[role="button"],[contenteditable="true"]'))return;e.preventDefault();if(!e.repeat&&!held.has(e.key)){held.add(e.key);vm?.input(e.key,1).catch(fail);}});
document.addEventListener('keyup',e=>{if(held.delete(e.key)){e.preventDefault();vm?.input(e.key,0).catch(fail);}});window.addEventListener('blur',releaseKeys);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseKeys();});
$('#start-game').onclick=()=>{services?.unlockAudio()?.catch(fail);};
$('#pause-toggle').onclick=()=>{if(closed||closing)return;releaseKeys();menu.showModal();services?.pauseAudio(true)?.catch(fail);};
$('#resume').onclick=()=>{menu.close();canvas.focus();};
$('#fullscreen').hidden=kiosk.enabled||!document.fullscreenEnabled||typeof document.documentElement.requestFullscreen!=='function';$('#fullscreen').onclick=async()=>{if($('#fullscreen').hidden)return;$('#pause-status').hidden=true;try{await(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());}catch{$('#pause-status').textContent='전체 화면으로 전환하지 못했어요.';$('#pause-status').hidden=false;}};
window.hbEngineRequestClose=async()=>{if(kiosk.enabled&&!operatorMenu&&!config.smoke&&!config.acceptance)return;if(kiosk.enabled)window.chrome?.webview?.postMessage('hbengine.operator.unlock');if(closed){if(closing)return;closing=true;try{await failureCleanup;await flushStorage();window.chrome?.webview?.postMessage('hbengine.close');}catch(error){closing=false;$('#error').textContent='게임 저장 실패: '+error.message;}return;}if(closing)return;closing=true;frameLoop.stop();try{while(busy)await new Promise(resolve=>setTimeout(resolve,10));await release('Stopped');closed=true;await flushStorage();window.chrome?.webview?.postMessage('hbengine.close');}catch(error){closing=false;closed=false;await fail(error);}};$('#quit').onclick=()=>window.hbEngineRequestClose();
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;await openScene(session.startupScene);$('#loading').hidden=true;canvas.focus();last=performance.now();schedule();}catch(error){await fail(error);}
