import {resolveBuildPath} from './build-profile.js';
import * as THREE from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {session,flushStorage} from './project-session.js';
import {editorRequest,fileUrl} from './project-browser.js';
import {validScene,defaultEnvironment,defaultRuntimeSettings} from './model.js';
import {validValue} from './blueprint-model.js';
import {preparePlayWorld,resolvePlayAsset} from './play-world.js';
import {BlueprintRuntime} from './blueprint-runtime.js';
import {nativeWorld} from './native-model.js';
import {engineOperations,loadModel} from './engine-services.js';
import {sceneRendering} from './scene-rendering.js';
import {scenePrimitives} from './scene-primitives.js';
import {createSky,applySceneEnvironment,syncSkyToCamera,disposeSceneEnvironment} from './scene-environment.js';
const $=s=>document.querySelector(s),canvas=$('#game-canvas'),overlay=$('#game-ui'),menu=$('#pause-menu');
const config=await(await editorRequest('/api/player')).json();document.title=config.name;
const readAsset=async path=>(await editorRequest(fileUrl(path))).json(),readText=async path=>(await editorRequest(fileUrl(path))).text();
let renderer,world,visuals,primitives,vm,services,objects=[],builds=new Map(),currentScene,activeCamera,fallback,environment,sky,environmentContext,frame=0,busy=false,closed=false,closing=false,failureCleanup,last=performance.now(),queued=0,sceneEpoch=0;
const groups=new Map(),logs=[],held=new Set(),files=(await(await editorRequest('/api/project')).json()).entries;
const log=message=>{logs.push(String(message));if(logs.length>100)logs.shift();};
function remove(object){const g=groups.get(object.id);if(!g)return;visuals.dispose(g);g.removeFromParent();g.traverse(c=>{c.geometry?.dispose();});groups.delete(object.id);}
function build(object){const g=primitives.build(object);groups.set(object.id,g);world.add(g);update(object);g.userData.ready=visuals.build(object,g);g.userData.ready.catch(fail);return g;}
function update(object){let g=groups.get(object.id);if(!g)return;if(g.userData.componentSignature!==undefined&&g.userData.componentSignature!==JSON.stringify(object.components)){const parent=g.parent,children=g.children.filter(c=>c.userData.objectId&&c.userData.objectId!==object.id);for(const c of children)c.removeFromParent();remove(object);g=build(object);parent?.add(g);children.forEach(c=>g.add(c));}g.position.fromArray(object.position);g.rotation.set(...object.rotation.map(THREE.MathUtils.degToRad));g.scale.fromArray(object.scale);g.visible=object.visible;}
async function nativeCall(request,bindingBuild){const owner=vm,epoch=sceneEpoch;bindingBuild??=builds.get(objects.find(o=>o.id===request.self)?.blueprintAsset);if(!bindingBuild)throw Error('C++ 바인딩 없음');const paths=new Set([...builds].filter(([,b])=>b.token===bindingBuild.token).map(([p])=>p)),result=await(await editorRequest('/api/native/call',{method:'POST',body:JSON.stringify({token:bindingBuild.token,request:{...request,objects:nativeWorld(objects,paths)}})})).json();if(epoch!==sceneEpoch)return {outputs:{},events:[],objects:[]};for(const state of result.objects||[]){const object=objects.find(o=>o.id===state.id);if(object){if(state.position!==undefined&&!validValue('transform',state))throw Error('C++ Transform 오류');Object.assign(object,state);update(object);}}for(const operation of result.operations||[])await services.operation(operation.key,operation.args,owner.bindings.find(b=>b.self===request.self)||{self:request.self,root:{components:[]}},owner);if(result.clock){owner.core.scale=result.clock.scale;owner.core.paused=result.clock.paused;if(!request.command)owner.core.time=result.clock.time;}return result;}
async function release(reason){sceneEpoch++;try{if(vm?.active)await vm.stop(reason);}finally{services?.dispose();services=null;disposeSceneEnvironment(world);for(const o of objects)remove(o);world?.traverse(c=>{c.geometry?.dispose();for(const m of c.material?(Array.isArray(c.material)?c.material:[c.material]):[])m.dispose();});world?.environment?.dispose();groups.clear();}}
async function openScene(path,data){
  data??=await readAsset(path);if(!validScene(data))throw Error('장면 검증 실패: '+path);await release('LevelTransition');currentScene=path;
  const prepared=await preparePlayWorld(structuredClone(data.objects),data.runtime,{readAsset,readText,buildNative:async(header,source)=>(await editorRequest('/api/native/build',{method:'POST',body:JSON.stringify({header,source})})).json()});objects=prepared.objects;builds=prepared.builds;
  world=new THREE.Scene();world.background=new THREE.Color();environment={...defaultEnvironment,...data.environment};const settings={...defaultRuntimeSettings,...data.runtime};primitives=scenePrimitives(data.surface);
  visuals=sceneRendering({read:readAsset,fileUrl,loadModel,current:id=>groups.get(id),all:()=>[...groups.values()],error:fail});objects.forEach(build);for(const object of objects)if(object.parent)groups.get(object.parent)?.add(groups.get(object.id));await Promise.all([...groups.values()].map(g=>g.userData.ready));await visuals.preparePhysics(objects);
  const ambientLight=new THREE.HemisphereLight(0xd6e8ee,0x677955,1.15);world.add(ambientLight);const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();world.environment=pmrem.fromScene(room,.04).texture;room.dispose();pmrem.dispose();
  const groundFloor=primitives.mesh(world,new THREE.PlaneGeometry(200,200),new THREE.MeshStandardMaterial({color:0x526c6d,roughness:1}),[0,-.78,0],[-Math.PI/2,0,0]);groundFloor.castShadow=false;groundFloor.visible=false;groundFloor.userData.editorHelper=true;sky=createSky(world);const sun=groups.get('sun-light')?.children.find(c=>c.isDirectionalLight);environmentContext={scene:world,environment,surface:data.surface,runtimeSettings:settings,ambientLight,mainRenderer:renderer,...sky,sun};applySceneEnvironment({...environmentContext,objects});world.traverse(node=>{if(node.userData.editorHelper)node.visible=false;});
  fallback=settings.dimension==='2d'?new THREE.OrthographicCamera(-7,7,7,-7,.05,100000):new THREE.PerspectiveCamera(60,1,.05,100000);if(settings.dimension==='2d')fallback.position.set(0,0,20);else{fallback.position.set(8.6,7.2,10.5);fallback.lookAt(0,.45,0);}activeCamera=fallback;
  services=engineOperations({particleSnapshot:visuals.particleSnapshot,material:visuals.material,materialFloat:visuals.materialFloat,spriteFrame:visuals.spriteFrame,gameplay:prepared.gameplay,physicsOptions:prepared.physicsOptions,listenerPosition:()=>activeCamera.getWorldPosition(new THREE.Vector3()).toArray(),build,remove,update,mesh:id=>groups.get(id),meshes:()=>[...groups.values()],scene:()=>world,overlay:()=>overlay,readAsset,asset:async(name,kind)=>resolvePlayAsset(files,/^(Assets|Source)\//.test(name)?resolveBuildPath(name,config.redirects):name,kind)});
  // Packaged execution never stops at editor breakpoints.
  for(const binding of prepared.bindings){const clear=value=>{if(Array.isArray(value))value.forEach(clear);else if(value&&typeof value==='object'){delete value.breakpoint;Object.values(value).forEach(clear);}};clear(binding.root);}
  vm=new BlueprintRuntime(objects,prepared.bindings,{...services,inputAssets:prepared.inputAssets,updateObject:update,native:nativeCall,log});for(const b of new Map([...builds.values()].map(b=>[b.token,b])).values())await nativeCall({command:'reset'},b);const audioWait=setTimeout(()=>{if(services?.audioState().state==='suspended')$('#start-game').hidden=false;},1500);try{await vm.start();}finally{clearTimeout(audioWait);}for(const key of held)await vm.input(key,1);
}
async function report(error){
  const data={ok:!error,scene:currentScene,frames:frame,time:vm?.core.time||0,renderer:'WebGL2',error:error?.message?.slice(0,4000)||null,drawCalls:renderer?.info.render.calls||0};
  if(config.configuration==='development'||config.smoke){
    data.objects=objects.slice(0,2000).map(o=>({id:o.id,name:o.name,kind:o.kind,position:o.position,rotation:o.rotation,scale:o.scale,visible:o.visible,nativeProperties:o.nativeProperties}));
    data.variables=[];let budget=250000;for(const b of vm?.bindings||[]){const values={};for(const [id,value] of b.variables){const text=JSON.stringify(value);if(text.length<=16000&&text.length<budget){values[id]=value;budget-=text.length;}}if(Object.keys(values).length)data.variables.push({self:b.self,values});}
    data.logs=logs.map(s=>s.slice(0,2000));data.audio=services?.audioState();
  }
  // Diagnostics may fail (e.g. a read-only save directory) without stopping the game.
  try{await editorRequest('/api/player/report',{method:'POST',body:JSON.stringify(data)});}catch(issue){console.warn('게임 진단 저장 실패:',issue.message);}return data;
}
async function fail(error){if(closed)return;closed=true;const issue=error instanceof Error?error:Error(String(error));$('#loading').hidden=true;$('#error').hidden=false;$('#error').textContent=issue.message;failureCleanup=(async()=>{try{await report(issue);}catch{}try{await release('Failed');}catch(cleanup){console.warn(cleanup);}try{await flushStorage();}catch(storageError){console.warn(storageError);}console.error(issue);})();await failureCleanup;}
async function step(delta){for(const b of new Map([...builds.values()].map(b=>[b.token,b])).values()){const result=await nativeCall({command:'frame',delta,clock:{scale:vm.core.scale,paused:vm.core.paused}},b);for(const event of result.timerEvents||[])for(const binding of vm.bindings.filter(x=>builds.get(objects.find(o=>o.id===x.self)?.blueprintAsset)?.token===b.token))await vm.custom(binding,event);}await vm.tick(delta);if(vm.sceneRequest){const r=vm.sceneRequest;await openScene(r.path,r.data);}}
const schedule=()=>config.smoke?setTimeout(()=>animate(performance.now()),16):requestAnimationFrame(animate);
async function animate(now){if(closed||closing)return;const delta=Math.min(.1,Math.max(0,(now-last)/1000));last=now;schedule();if(!menu.open)queued=Math.min(1,queued+delta);if(busy)return;busy=true;try{if(!menu.open){const stepDelta=queued;queued=0;await step(stepDelta);}
  const w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==Math.round(w*renderer.getPixelRatio())||canvas.height!==Math.round(h*renderer.getPixelRatio()))renderer.setSize(w,h,false);const aspect=w/Math.max(1,h);if(fallback.isOrthographicCamera){fallback.left=-7*aspect;fallback.right=7*aspect;}else fallback.aspect=aspect;fallback.updateProjectionMatrix();activeCamera=visuals.gameCamera(objects,aspect,vm.sequenceCamera)||fallback;visuals.tickParticles(objects,menu.open?0:delta*vm.core.scale,true);visuals.syncDecals();applySceneEnvironment({...environmentContext,objects});syncSkyToCamera(sky,activeCamera,menu.open?0:delta*vm.core.scale);world.traverse(node=>{if(node.userData.editorHelper)node.visible=false;});renderer.render(world,activeCamera);frame++;
  if(frame===10){await report();window.chrome?.webview?.postMessage('hbengine.ready.player');}else if(config.configuration==='development'&&frame%120===0)await report();
}catch(error){await fail(error);}finally{busy=false;}}
menu.addEventListener('close',()=>{services?.pauseAudio(false)?.catch(fail);queued=0;});
function releaseKeys(){for(const key of held)vm?.input(key,0).catch(fail);held.clear();}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();releaseKeys();if(menu.open)menu.close();else{menu.showModal();services?.pauseAudio(true)?.catch(fail);}return;}if(menu.open||e.target.closest('input,textarea,select,[contenteditable="true"]'))return;e.preventDefault();if(!e.repeat&&!held.has(e.key)){held.add(e.key);vm?.input(e.key,1).catch(fail);}});
document.addEventListener('keyup',e=>{if(held.delete(e.key)){e.preventDefault();vm?.input(e.key,0).catch(fail);}});window.addEventListener('blur',releaseKeys);document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseKeys();});
$('#start-game').onclick=()=>{services?.pauseAudio(false)?.catch(fail);};
$('#resume').onclick=()=>{menu.close();canvas.focus();};$('#fullscreen').onclick=()=>{(document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()).catch(fail);};
window.hbEngineRequestClose=async()=>{if(closed){if(closing)return;closing=true;try{await failureCleanup;await flushStorage();window.chrome?.webview?.postMessage('hbengine.close');}catch(error){closing=false;$('#error').textContent='게임 저장 실패: '+error.message;}return;}if(closing)return;closing=true;try{while(busy)await new Promise(resolve=>setTimeout(resolve,10));await release('Stopped');closed=true;await flushStorage();window.chrome?.webview?.postMessage('hbengine.close');}catch(error){closing=false;closed=false;await fail(error);}};$('#quit').onclick=()=>window.hbEngineRequestClose();
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;await openScene(session.startupScene);$('#loading').hidden=true;canvas.focus();last=performance.now();schedule();}catch(error){await fail(error);}
