export class RuntimeProfiler {
  constructor({now=()=>performance.now(),capacity=300}={}){this.now=now;this.capacity=capacity;this.frames=[];this.sequence=0;this.recording=false;}
  begin(label='게임 프레임'){if(!this.recording)return null;return {id:++this.sequence,label,start:this.now(),samples:[],counters:{}};}
  async measure(frame,name,fn,parent=''){if(!frame)return fn();const start=this.now();try{return await fn();}finally{if(frame.samples.length<2048)frame.samples.push({name,parent,start:start-frame.start,duration:Math.max(0,this.now()-start)});}}
  finish(frame,counters={}){if(!frame)return;frame.duration=Math.max(0,this.now()-frame.start);frame.counters={...counters};this.frames.push(frame);if(this.frames.length>this.capacity)this.frames.splice(0,this.frames.length-this.capacity);}
  clear(){this.frames=[];}
  snapshot(){return {version:1,timing:'elapsed wall time; C++ includes IPC; GPU submission is not GPU duration',recording:this.recording,capacity:this.capacity,frames:structuredClone(this.frames)};}
}
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class ProfilerPanel {
  constructor(element,profiler){this.element=element;this.profiler=profiler;this.selected=null;this.query='';this.live=true;this.view='timeline';this.render();this.timer=setInterval(()=>{if(this.element.isConnected&&!this.element.contains(document.activeElement))this.render();},500);}
  render(){
    const p=this.profiler,frames=p.frames;if(this.live||!frames.some(f=>f.id===this.selected))this.selected=frames.at(-1)?.id;const f=frames.find(f=>f.id===this.selected),max=Math.max(33.33,...frames.map(f=>f.duration)),samples=(f?.samples||[]).filter(s=>s.name.toLowerCase().includes(this.query.toLowerCase()));this.element.className='workspace-view profiler-panel';
    const summary=new Map();for(const s of samples){const key=s.parent+'/'+s.name,row=summary.get(key)||{name:s.name,parent:s.parent,total:0,calls:0};row.total+=s.duration;row.calls++;summary.set(key,row);}
    this.element.innerHTML=`<header class="document-toolbar"><button data-profiler-record aria-pressed="${p.recording}">${p.recording?'기록 중지':'기록'}</button><button data-profiler-clear>지우기</button><label><input type="checkbox" data-profiler-live ${this.live?'checked':''}> 실시간</label><button data-profiler-export>JSON 내보내기</button><select data-profiler-view aria-label="프로파일러 표시"><option value="timeline" ${this.view==='timeline'?'selected':''}>타임라인</option><option value="hierarchy" ${this.view==='hierarchy'?'selected':''}>집계</option></select><input type="search" data-profiler-search aria-label="프로파일러 샘플 검색" placeholder="샘플 검색" value="${esc(this.query)}"></header><div class="profiler-frame-chart" role="listbox" aria-label="기록된 프레임">${frames.map(frame=>`<button role="option" aria-selected="${frame.id===this.selected}" data-profiler-frame="${frame.id}" title="${frame.label} #${frame.id} · ${frame.duration.toFixed(2)} ms" style="height:${Math.max(2,frame.duration/max*100)}%" class="${frame.id===this.selected?'selected':''}"></button>`).join('')}</div><div class="profiler-frame-summary">${f?`${esc(f.label)} #${f.id} · ${f.duration.toFixed(2)} ms`:'기록 없음'}${Object.entries(f?.counters||{}).map(([k,v])=>`<span>${esc(k)} ${esc(v)}</span>`).join('')}</div><main class="profiler-details">${this.view==='timeline'?samples.map(s=>`<div class="profiler-timeline-row"><span>${esc(s.name)}</span><div><i style="left:${s.start/Math.max(1,f.duration)*100}%;width:${Math.max(.5,s.duration/Math.max(1,f.duration)*100)}%" title="${s.duration.toFixed(3)} ms"></i></div><output>${s.duration.toFixed(3)} ms</output></div>`).join(''):`<table><thead><tr><th>샘플</th><th>호출 수</th><th>총 시간</th><th>평균</th></tr></thead><tbody>${[...summary.values()].sort((a,b)=>b.total-a.total).map(s=>`<tr><td>${esc(s.parent?s.parent+' / '+s.name:s.name)}</td><td>${s.calls}</td><td>${s.total.toFixed(3)} ms</td><td>${(s.total/s.calls).toFixed(3)} ms</td></tr>`).join('')}</tbody></table>`}</main>`;
    this.element.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-profiler-record'))p.recording=!p.recording;else if(b.hasAttribute('data-profiler-clear'))p.clear();else if(b.dataset.profilerFrame){this.selected=Number(b.dataset.profilerFrame);this.live=false;}else if(b.hasAttribute('data-profiler-export')){const url=URL.createObjectURL(new Blob([JSON.stringify(p.snapshot(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='HBEngine-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}this.render();};
    this.element.onchange=e=>{if(e.target.hasAttribute('data-profiler-live'))this.live=e.target.checked;else if(e.target.hasAttribute('data-profiler-view'))this.view=e.target.value;this.render();};
    this.element.querySelector('[data-profiler-search]').oninput=e=>{this.query=e.target.value;const pos=e.target.selectionStart;this.render();const input=this.element.querySelector('[data-profiler-search]');input.focus();input.setSelectionRange(pos,pos);};
  }
  dispose(){clearInterval(this.timer);}
}
