import {storageKey,storage} from './project-session.js';
import {icon,assetIcon} from './icons.js';
import {assetTypes,assetTitle,assetSuffix} from './asset-documents.js';
import {blueprintClasses} from './class-types.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function editorRequest(url,options={}){const response=await fetch(url,{...options,headers:{'X-HB-Editor':'1',...options.headers}});if(!response.ok){let message;try{message=(await response.json()).error;}catch{}throw Error(message||'요청 실패: '+response.status);}return response;}
export const fileUrl=path=>'/api/file?path='+encodeURIComponent(path);
export async function droppedFiles(transfer){
  const roots=[...transfer.items].filter(i=>i.kind==='file').map(i=>({entry:i.webkitGetAsEntry?.(),file:i.getAsFile()})),files=[];
  const visit=async(entry,depth=0)=>{if(depth>32)throw Error('폴더 깊이는 32단계까지 가져올 수 있어요.');if(entry.isFile){const file=await new Promise((resolve,reject)=>entry.file(resolve,reject));if(files.length>=100)throw Error('한 번에 100개 파일까지 가져올 수 있어요.');files.push({file,relativePath:entry.fullPath.replace(/^\//,'')});}else if(entry.isDirectory){const reader=entry.createReader();while(true){const children=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!children.length)break;for(const child of children)await visit(child,depth+1);}}};
  for(const root of roots){if(root.entry?.isDirectory)await visit(root.entry);else if(root.file){if(files.length>=100)throw Error('한 번에 100개 파일까지 가져올 수 있어요.');files.push(root.file);}}return files.length?files:[...transfer.files];
}
export class ProjectBrowser {
  constructor(element,breadcrumb,hooks={}){
    this.el=element;this.breadcrumb=breadcrumb;this.hooks=hooks;this.folder=storage.getItem(storageKey('hbengine.project.folder'))||'Assets';this.view=storage.getItem(storageKey('hbengine.project.view'))==='tiles'?'tiles':'list';this.selected=new Set();this.entries=[];this.request=0;
    element.innerHTML='<div class="project-tree" aria-label="프로젝트 폴더"></div><div class="project-files"><div class="project-tools"><input id="asset-search" type="search" placeholder="파일 검색" aria-label="프로젝트 파일 검색"><select data-project-type aria-label="파일 타입 필터">'+[['all','모든 타입'],['inputaction','Input Action'],['inputmapping','입력 매핑'],['curve','커브'],['data','데이터'],['scene','장면'],['blueprint','블루프린트'],['model','모델'],['texture','텍스처'],['material','머테리얼'],['animation','애니메이션'],['media','영상·오디오'],['code','코드'],['file','기타 파일']].map(([id,name])=>`<option value="${id}">${name}</option>`).join('')+'</select><label><input type="checkbox" data-contents>내용</label><label><input type="checkbox" data-recursive checked>하위 폴더</label><button data-project-refresh aria-label="프로젝트 새로고침">'+icon('refresh')+'</button><div class="project-view-toggle" role="group" aria-label="파일 표시 방식"><button data-project-view="list" aria-label="목록 보기" title="목록 보기" aria-pressed="false">'+icon('list')+'</button><button data-project-view="tiles" aria-label="타일 보기" title="타일 보기" aria-pressed="false">'+icon('tiles')+'</button></div></div><div class="project-list-heading" aria-hidden="true"><span>이름</span><span>타입</span><span>경로</span></div><div id="asset-grid" class="asset-grid project-grid" role="listbox" aria-multiselectable="true" aria-label="프로젝트 파일"></div><div class="project-status"><span id="asset-results"></span><button data-open-selected>선택 열기</button><button data-create-asset>새 에셋</button><button data-new-folder>새 폴더</button></div></div>';
    this.setView(this.view,false);
    element.addEventListener('input',e=>{if(e.target.id==='asset-search'){clearTimeout(this.searchTimer);this.searchTimer=setTimeout(()=>this.refresh(),180);}});
    element.addEventListener('change',e=>{if(e.target.matches('[data-project-type],[data-contents],[data-recursive]'))this.refresh();});
    element.addEventListener('click',e=>{const view=e.target.closest('[data-project-view]'),folder=e.target.closest('[data-project-folder]'),card=e.target.closest('[data-project-entry]');if(view)this.setView(view.dataset.projectView);else if(folder)this.navigate(folder.dataset.projectFolder);else if(card)this.select(Number(card.dataset.projectEntry),e);else if(e.target.closest('[data-project-refresh]'))this.refresh();else if(e.target.closest('[data-open-selected]'))this.openSelected();else if(e.target.closest('[data-create-asset]'))this.createDialog();else if(e.target.closest('[data-new-folder]'))this.nameDialog('folder');});
    element.addEventListener('dblclick',e=>{const card=e.target.closest('[data-project-entry]');if(card)this.open(this.entries[Number(card.dataset.projectEntry)]);});
    element.addEventListener('keydown',e=>{if(e.isComposing||e.target.matches('input,textarea,select'))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='f'){e.preventDefault();e.stopPropagation();element.querySelector('#asset-search').focus();}else if(mod&&e.key.toLowerCase()==='a'){e.preventDefault();e.stopPropagation();this.selected=new Set(this.entries.map(e=>e.path));this.selection();}else if(e.key==='Enter'){e.preventDefault();e.stopPropagation();this.openSelected();}else if(e.key==='Backspace'){e.preventDefault();e.stopPropagation();this.navigate(this.folder.split('/').slice(0,-1).join('/'));}else if(e.key==='F2'){e.preventDefault();e.stopPropagation();this.nameDialog('rename');}});
    element.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();const card=e.target.closest('[data-project-entry]');const folder=e.target.closest('[data-project-folder]');if(folder){this.navigate(folder.dataset.projectFolder).then(()=>this.menu(e));return;}if(card&&!this.selected.has(this.entries[Number(card.dataset.projectEntry)].path))this.select(Number(card.dataset.projectEntry),{});this.menu(e);});
    element.addEventListener('dragstart',e=>{const card=e.target.closest('[data-project-entry]');if(card){const file=this.entries[Number(card.dataset.projectEntry)];if(!this.selected.has(file.path))this.select(Number(card.dataset.projectEntry),{});e.dataTransfer.setData('application/x-hb-assets',JSON.stringify(this.entries.filter(e=>this.selected.has(e.path)&&e.kind!=='folder')));e.dataTransfer.effectAllowed='copy';}});
    this.refresh();
  }
  setView(view,persist=true){
    if(view!=='list'&&view!=='tiles')return;
    this.view=view;this.el.querySelector('#asset-grid').dataset.view=view;this.el.querySelector('.project-list-heading').hidden=view!=='list';
    this.el.querySelectorAll('[data-project-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.projectView===view)));
    this.el.querySelectorAll('[data-project-entry] .asset-name').forEach((label,i)=>{label.textContent=view==='list'?this.entries[i].name:assetTitle(this.entries[i].name);});
    if(persist)storage.setItem(storageKey('hbengine.project.view'),view);
  }
  async navigate(folder){this.folder=folder;this.anchor=undefined;this.selected.clear();this.el.querySelector('#asset-search').value='';storage.setItem(storageKey('hbengine.project.folder'),folder);await this.refresh();}
  async refresh(){const request=++this.request;try{const query=new URLSearchParams({folder:this.folder,q:this.el.querySelector('#asset-search').value,type:this.el.querySelector('[data-project-type]').value,contents:this.el.querySelector('[data-contents]').checked?'1':'0',recursive:this.el.querySelector('[data-recursive]').checked&&!!this.el.querySelector('#asset-search').value?'1':'0'});const data=await (await editorRequest('/api/project?'+query)).json();if(request!==this.request)return;this.entries=data.entries;this.anchor=undefined;this.selected=new Set([...this.selected].filter(path=>this.entries.some(e=>e.path===path)));this.el.querySelector('.project-tree').innerHTML=[{path:'',name:'Project',kind:'folder'},...data.folders].map(f=>`<button data-project-folder="${esc(f.path)}" class="${f.path===this.folder?'active':''}" style="padding-left:${10+f.path.split('/').length*11}px" title="${esc(f.path)}">${icon('folder')}<span>${esc(f.name)}</span></button>`).join('');this.breadcrumb.textContent=this.folder||'Project';this.breadcrumb.title=data.root;this.el.querySelector('#asset-grid').innerHTML=data.entries.map((f,i)=>`<button class="asset-card ${f.kind}" data-project-entry="${i}" draggable="${f.kind!=='folder'}" role="option" aria-selected="${this.selected.has(f.path)}" title="${esc(f.path+(f.line?':'+f.line+'\n'+f.match:''))}"><span class="project-thumbnail">${f.kind==='texture'?`<img src="${fileUrl(f.path)}" loading="lazy" alt="">`:icon(assetIcon(f.kind))}</span><span class="asset-name">${esc(this.view==='list'?f.name:assetTitle(f.name))}</span><span class="asset-type">${esc(assetTypes[f.kind]?.label||({folder:'폴더',model:'Static Mesh',texture:'Texture',media:'Media',code:'C++',file:'File'}[f.kind]||f.kind))}${f.line?' · '+f.line+'줄':''}</span><span class="asset-path">${esc(f.path)}</span></button>`).join('');this.el.querySelector('#asset-results').textContent=data.entries.length+'개 · '+this.selected.size+'개 선택';this.hooks.files?.(data.entries);this.selection();}catch(error){if(this.folder&&error.message.includes('ENOENT'))return this.navigate('');this.hooks.error?.(error.message);}}
  select(index,event){const file=this.entries[index];if(!file)return;if(event.shiftKey&&this.anchor!==undefined){if(!event.ctrlKey)this.selected.clear();for(let i=Math.min(this.anchor,index);i<=Math.max(this.anchor,index);i++)this.selected.add(this.entries[i].path);}else if(event.ctrlKey||event.metaKey){this.selected.has(file.path)?this.selected.delete(file.path):this.selected.add(file.path);this.anchor=index;}else{this.selected=new Set([file.path]);this.anchor=index;}this.selection();this.hooks.select?.(file);}
  selection(){this.el.querySelectorAll('[data-project-entry]').forEach(card=>{const selected=this.selected.has(this.entries[Number(card.dataset.projectEntry)]?.path);card.classList.toggle('selected',selected);card.setAttribute('aria-selected',String(selected));});this.el.querySelector('#asset-results').textContent=this.entries.length+'개 · '+this.selected.size+'개 선택';}
  async open(file){try{if(file.kind==='folder')await this.navigate(file.path);else await this.hooks.open?.(file);}catch(error){this.hooks.error?.(error.message);}}
  async openSelected(){for(const file of this.entries.filter(f=>this.selected.has(f.path)))await this.open(file);}
  nameDialog(mode){const selected=this.entries.find(e=>this.selected.has(e.path));if(mode==='rename'&&this.selected.size!==1)return;const suffix=mode==='rename'?Object.values(assetSuffix).find(s=>selected.name.endsWith(s))||'':'';const dialog=document.createElement('dialog');dialog.innerHTML=`<form><div class="dialog-heading"><h2>${mode==='folder'?'새 폴더':'이름 변경'}</h2></div><input aria-label="이름" required maxlength="120" value="${mode==='rename'?esc(suffix?assetTitle(selected.name):selected.name):''}"><div class="dialog-footer"><button type="button" data-cancel>취소</button><button class="primary-button">확인</button></div></form>`;document.body.append(dialog);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const name=dialog.querySelector('input').value.trim();if(!name||name.includes('/')||name.includes('\\'))throw Error('이름을 확인하세요.');const parent=mode==='rename'?selected.path.split('/').slice(0,-1).join('/'):this.folder;const relative=(parent?parent+'/':'')+name+(suffix&&!name.endsWith(suffix)?suffix:'');await editorRequest(mode==='folder'?'/api/folder':'/api/rename',{method:'POST',body:JSON.stringify(mode==='folder'?{path:relative}:{from:selected.path,to:relative})});if(mode==='rename')this.hooks.rename?.(selected.path,relative);dialog.close();await this.refresh();}catch(error){this.hooks.error?.(error.message);}};dialog.showModal();dialog.querySelector('input').focus();dialog.querySelector('input').select();}
  menu(e){
    document.querySelector('.project-menu')?.remove();const menu=document.createElement('div');menu.className='project-menu';menu.role='menu';
    const header=document.createElement('div');header.className='menu-location';header.textContent=this.folder||'Project';menu.append(header);
    const add=(label,ic,action)=>{const b=document.createElement('button');b.role='menuitem';b.innerHTML=icon(ic)+'<span>'+esc(label)+'</span>';b.onclick=()=>{menu.remove();action();};menu.append(b);};
    if(this.selected.size){add('열기','external',()=>this.openSelected());add('이름 변경','file',()=>this.nameDialog('rename'));const file=this.entries.find(f=>this.selected.has(f.path));if(this.selected.size===1&&file.kind==='code')add('이 클래스로 블루프린트 생성','blueprint',()=>this.hooks.wrap?.(file));add('에셋 경로 복사','copy',()=>navigator.clipboard.writeText([...this.selected].join('\n')));}
    const label=document.createElement('div');label.className='menu-section';label.textContent='새로 만들기';menu.append(label);
    for(const [kind,type] of Object.entries(assetTypes))add(type.label,assetIcon(kind),()=>this.createDialog(kind));
    add('새 폴더','folder',()=>this.nameDialog('folder'));add('가져오기','upload',()=>this.hooks.import?.());
    document.body.append(menu);menu.style.left=Math.max(6,Math.min(e.clientX,innerWidth-menu.offsetWidth-6))+'px';menu.style.top=Math.max(6,Math.min(e.clientY,innerHeight-menu.offsetHeight-6))+'px';
    const dismiss=e=>{if(!menu.contains(e.target)){menu.remove();document.removeEventListener('pointerdown',dismiss);}};document.addEventListener('pointerdown',dismiss);menu.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();menu.remove();document.removeEventListener('pointerdown',dismiss);}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=[...menu.querySelectorAll('button')],i=buttons.indexOf(document.activeElement);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}};menu.querySelector('button')?.focus();
  }
  createDialog(kind='blueprint'){
    const dialog=document.createElement('dialog');dialog.className='create-asset-dialog';
    dialog.innerHTML='<form><header><div><h2>에셋 만들기</h2><span>'+esc(this.folder||'Project')+'</span></div><button type="button" data-cancel aria-label="닫기">'+icon('close')+'</button></header><div class="create-asset-body"><nav class="asset-type-list" aria-label="에셋 종류">'+Object.entries(assetTypes).map(([k,t])=>'<button type="button" data-kind="'+k+'">'+icon(assetIcon(k))+'<span>'+t.label+'</span></button>').join('')+'</nav><section><div data-parents class="parent-class-grid" aria-label="부모 클래스">'+Object.entries(blueprintClasses).map(([k,t])=>'<button type="button" data-parent="'+k+'">'+icon(t.icon)+'<strong>'+t.label+'</strong><span>'+t.ko+'</span></button>').join('')+'</div><label class="asset-name-field">이름<input data-name aria-label="새 에셋 이름" required maxlength="80"></label><p class="create-error" role="alert"></p></section></div><footer><button type="button" data-cancel>취소</button><button class="primary-button" type="submit">만들기</button></footer></form>';
    document.body.append(dialog);let selectedKind=kind,parent='Actor';const select=next=>{selectedKind=next;dialog.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('selected',b.dataset.kind===next));dialog.querySelector('[data-parents]').hidden=!['blueprint','code'].includes(next);dialog.querySelector('[data-name]').value=assetTypes[next].prefix+'New'+(next==='code'?'Actor':'Asset');};select(kind);
    dialog.querySelector('[data-parent="Actor"]').classList.add('selected');dialog.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-cancel'))dialog.close();if(b.dataset.kind)select(b.dataset.kind);if(b.dataset.parent){parent=b.dataset.parent;dialog.querySelectorAll('[data-parent]').forEach(x=>x.classList.toggle('selected',x===b));dialog.querySelector('[data-name]').value=assetTypes[selectedKind].prefix+'New'+parent;}};
    dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type=submit]');button.disabled=true;try{const name=dialog.querySelector('[data-name]').value.trim(),file=await (await editorRequest('/api/asset/create',{method:'POST',body:JSON.stringify({folder:this.folder,kind:selectedKind,name,parent})})).json();dialog.close();await this.refresh();this.selected=new Set([file.path]);this.selection();await this.open(file);}catch(error){dialog.querySelector('.create-error').textContent=error.message;}finally{button.disabled=false;}};
    dialog.onclose=()=>dialog.remove();dialog.showModal();dialog.querySelector('[data-name]').select();
  }
}
