window.hbEngineRequestClose=async()=>{window.chrome?.webview?.postMessage('hbengine.close');return true;};
import {icon} from './icons.js';
const $=selector=>document.querySelector(selector),error=$('#hub-error');
document.querySelectorAll('[data-icon]').forEach(element=>element.insertAdjacentHTML('afterbegin',icon(element.dataset.icon)));
const showError=message=>{error.textContent=message;error.hidden=!message;};
async function request(path,data){const response=await fetch('/api/launcher'+path,{method:data?'POST':'GET',headers:{'X-HB-Editor':'1',...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});const result=await response.json();if(!response.ok)throw Error(result.error||'프로젝트 요청 실패');return result;}
async function busy(action){if(document.body.dataset.busy)return;document.body.dataset.busy='1';showError('');document.querySelectorAll('button').forEach(button=>button.disabled=true);try{await action();}catch(e){showError(e.message);}finally{delete document.body.dataset.busy;document.querySelectorAll('button').forEach(button=>button.disabled=false);}}
async function open(file){if(!file.trim())throw Error('프로젝트 파일을 선택하세요.');await request('/open',{file:file.trim()});location.href='/prototype/index.html';}
async function refresh(){const data=await request('');if(!Array.isArray(data.projects)||typeof data.defaultDirectory!=='string')throw Error('프로젝트 목록을 확인하세요.');const list=$('#recent-projects');list.replaceChildren();for(const project of data.projects){if(typeof project.name!=='string'||typeof project.file!=='string')continue;const button=document.createElement('button');button.className='recent-project';button.title=project.file;button.innerHTML='<span class="project-symbol">'+icon('scene')+'</span><span class="project-info"><strong></strong><small></small></span>'+icon('chevron');button.querySelector('strong').textContent=project.name;button.querySelector('small').textContent=project.file;button.onclick=()=>busy(()=>open(project.file));list.append(button);}if(!list.children.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='최근 프로젝트 없음';list.append(empty);}if(!$('#project-directory').value)$('#project-directory').value=data.defaultDirectory;}
$('#open-project').onsubmit=e=>{e.preventDefault();busy(()=>open($('#project-file').value));};
$('#create-project').onsubmit=e=>{e.preventDefault();busy(async()=>{const name=$('#project-name').value.trim(),directory=$('#project-directory').value.trim();if(!name||!directory)throw Error('이름과 저장 위치를 입력하세요.');await request('/create',{name,directory});location.href='/prototype/index.html';});};
$('#browse-project').onclick=()=>busy(async()=>{const result=await request('/browse',{kind:'project'});if(result.path){$('#project-file').value=result.path;$('#project-file').focus();}});
$('#browse-directory').onclick=()=>busy(async()=>{const result=await request('/browse',{kind:'folder'});if(result.path){$('#project-directory').value=result.path;$('#project-directory').focus();}});
$('#refresh-projects').onclick=()=>busy(refresh);
const initialError=new URLSearchParams(location.search).get('error');busy(refresh).then(()=>{if(initialError&&!error.textContent)showError(initialError);window.chrome?.webview?.postMessage('hbengine.ready.hub');});
