const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function editorRequest(url,options={}){const response=await fetch(url,{...options,headers:{'X-HB-Editor':'1',...options.headers}});if(!response.ok){let message;try{message=(await response.json()).error;}catch{}throw Error(message||'요청 실패: '+response.status);}return response;}
export const fileUrl=path=>'/api/file?path='+encodeURIComponent(path);
export async function droppedFiles(transfer){
  const roots=[...transfer.items].filter(i=>i.kind==='file').map(i=>({entry:i.webkitGetAsEntry?.(),file:i.getAsFile()})),files=[];
  const visit=async(entry,depth=0)=>{if(depth>32)throw Error('폴더 깊이는 32단계까지 가져올 수 있어요.');if(entry.isFile){const file=await new Promise((resolve,reject)=>entry.file(resolve,reject));if(files.length>=100)throw Error('한 번에 100개 파일까지 가져올 수 있어요.');files.push({file,relativePath:entry.fullPath.replace(/^\//,'')});}else if(entry.isDirectory){const reader=entry.createReader();while(true){const children=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!children.length)break;for(const child of children)await visit(child,depth+1);}}};
  for(const root of roots){if(root.entry?.isDirectory)await visit(root.entry);else if(root.file){if(files.length>=100)throw Error('한 번에 100개 파일까지 가져올 수 있어요.');files.push(root.file);}}return files.length?files:[...transfer.files];
}
export class ProjectBrowser {
  constructor(element,breadcrumb,hooks={}){
    this.el=element;this.breadcrumb=breadcrumb;this.hooks=hooks;this.folder=localStorage.getItem('hbengine.project.folder')||'Assets';this.selected=new Set();this.entries=[];this.request=0;
    element.innerHTML='<div class="project-tree" aria-label="프로젝트 폴더"></div><div class="project-files"><div class="project-tools"><input id="asset-search" type="search" placeholder="파일 검색" aria-label="프로젝트 파일 검색"><select data-project-type aria-label="파일 타입 필터">'+[['all','모든 타입'],['scene','장면'],['blueprint','블루프린트'],['model','모델'],['texture','텍스처'],['material','머테리얼'],['animation','애니메이션'],['media','영상·오디오'],['code','코드'],['file','기타 파일']].map(([id,name])=>`<option value="${id}">${name}</option>`).join('')+'</select><label><input type="checkbox" data-contents>내용</label><label><input type="checkbox" data-recursive checked>하위 폴더</label><button data-project-refresh aria-label="프로젝트 새로고침">↻</button></div><div id="asset-grid" class="asset-grid project-grid" role="listbox" aria-multiselectable="true" aria-label="프로젝트 파일"></div><div class="project-status"><span id="asset-results"></span><button data-open-selected>선택 열기</button><button data-new-folder>새 폴더</button></div></div>';
    element.addEventListener('input',e=>{if(e.target.id==='asset-search'){clearTimeout(this.searchTimer);this.searchTimer=setTimeout(()=>this.refresh(),180);}});
    element.addEventListener('change',e=>{if(e.target.matches('[data-project-type],[data-contents],[data-recursive]'))this.refresh();});
    element.addEventListener('click',e=>{const folder=e.target.closest('[data-project-folder]'),card=e.target.closest('[data-project-entry]');if(folder)this.navigate(folder.dataset.projectFolder);else if(card)this.select(Number(card.dataset.projectEntry),e);else if(e.target.closest('[data-project-refresh]'))this.refresh();else if(e.target.closest('[data-open-selected]'))this.openSelected();else if(e.target.closest('[data-new-folder]'))this.nameDialog('folder');});
    element.addEventListener('dblclick',e=>{const card=e.target.closest('[data-project-entry]');if(card)this.open(this.entries[Number(card.dataset.projectEntry)]);});
    element.addEventListener('keydown',e=>{if(e.isComposing||e.target.matches('input,textarea,select'))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='f'){e.preventDefault();e.stopPropagation();element.querySelector('#asset-search').focus();}else if(mod&&e.key.toLowerCase()==='a'){e.preventDefault();e.stopPropagation();this.selected=new Set(this.entries.map(e=>e.path));this.selection();}else if(e.key==='Enter'){e.preventDefault();e.stopPropagation();this.openSelected();}else if(e.key==='Backspace'){e.preventDefault();e.stopPropagation();this.navigate(this.folder.split('/').slice(0,-1).join('/'));}else if(e.key==='F2'){e.preventDefault();e.stopPropagation();this.nameDialog('rename');}});
    element.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();const card=e.target.closest('[data-project-entry]');if(card&&!this.selected.has(this.entries[Number(card.dataset.projectEntry)].path))this.select(Number(card.dataset.projectEntry),{});this.menu(e);});
    element.addEventListener('dragstart',e=>{const card=e.target.closest('[data-project-entry]');if(card){const file=this.entries[Number(card.dataset.projectEntry)];if(!this.selected.has(file.path))this.select(Number(card.dataset.projectEntry),{});e.dataTransfer.setData('application/x-hb-assets',JSON.stringify(this.entries.filter(e=>this.selected.has(e.path)&&e.kind!=='folder')));e.dataTransfer.effectAllowed='copy';}});
    this.refresh();
  }
  async navigate(folder){this.folder=folder;this.anchor=undefined;this.selected.clear();this.el.querySelector('#asset-search').value='';localStorage.setItem('hbengine.project.folder',folder);await this.refresh();}
  async refresh(){const request=++this.request;try{const query=new URLSearchParams({folder:this.folder,q:this.el.querySelector('#asset-search').value,type:this.el.querySelector('[data-project-type]').value,contents:this.el.querySelector('[data-contents]').checked?'1':'0',recursive:this.el.querySelector('[data-recursive]').checked&&!!this.el.querySelector('#asset-search').value?'1':'0'});const data=await (await editorRequest('/api/project?'+query)).json();if(request!==this.request)return;this.entries=data.entries;this.anchor=undefined;this.selected=new Set([...this.selected].filter(path=>this.entries.some(e=>e.path===path)));this.el.querySelector('.project-tree').innerHTML=[{path:'',name:'Project',kind:'folder'},...data.folders].map(f=>`<button data-project-folder="${esc(f.path)}" class="${f.path===this.folder?'active':''}" style="padding-left:${10+f.path.split('/').length*11}px" title="${esc(f.path)}">▸ ${esc(f.name)}</button>`).join('');this.breadcrumb.textContent=this.folder||'Project';this.breadcrumb.title=data.root;this.el.querySelector('#asset-grid').innerHTML=data.entries.map((f,i)=>`<button class="asset-card ${f.kind}" data-project-entry="${i}" draggable="${f.kind!=='folder'}" role="option" aria-selected="${this.selected.has(f.path)}" title="${esc(f.path+(f.line?':'+f.line+'\n'+f.match:''))}"><span class="project-thumbnail">${f.kind==='texture'?`<img src="${fileUrl(f.path)}" loading="lazy" alt="">`:{folder:'▰',blueprint:'BP',scene:'SCN',model:'3D',material:'MAT',animation:'ANIM',media:'▶',code:'C++',file:'FILE'}[f.kind]}</span><span class="asset-name">${esc(f.name)}</span><span class="asset-type">${esc(f.kind)}${f.line?' · '+f.line+'줄':''}</span></button>`).join('');this.el.querySelector('#asset-results').textContent=data.entries.length+'개 · '+this.selected.size+'개 선택';this.hooks.files?.(data.entries);this.selection();}catch(error){if(this.folder&&error.message.includes('ENOENT'))return this.navigate('');this.hooks.error?.(error.message);}}
  select(index,event){const file=this.entries[index];if(!file)return;if(event.shiftKey&&this.anchor!==undefined){if(!event.ctrlKey)this.selected.clear();for(let i=Math.min(this.anchor,index);i<=Math.max(this.anchor,index);i++)this.selected.add(this.entries[i].path);}else if(event.ctrlKey||event.metaKey){this.selected.has(file.path)?this.selected.delete(file.path):this.selected.add(file.path);this.anchor=index;}else{this.selected=new Set([file.path]);this.anchor=index;}this.selection();this.hooks.select?.(file);}
  selection(){this.el.querySelectorAll('[data-project-entry]').forEach(card=>{const selected=this.selected.has(this.entries[Number(card.dataset.projectEntry)]?.path);card.classList.toggle('selected',selected);card.setAttribute('aria-selected',String(selected));});this.el.querySelector('#asset-results').textContent=this.entries.length+'개 · '+this.selected.size+'개 선택';}
  async open(file){try{if(file.kind==='folder')await this.navigate(file.path);else await this.hooks.open?.(file);}catch(error){this.hooks.error?.(error.message);}}
  async openSelected(){for(const file of this.entries.filter(f=>this.selected.has(f.path)))await this.open(file);}
  nameDialog(mode){const selected=this.entries.find(e=>this.selected.has(e.path));if(mode==='rename'&&this.selected.size!==1)return;const dialog=document.createElement('dialog');dialog.innerHTML=`<form><div class="dialog-heading"><h2>${mode==='folder'?'새 폴더':'이름 변경'}</h2></div><input aria-label="이름" required maxlength="120" value="${mode==='rename'?esc(selected.name):''}"><div class="dialog-footer"><button type="button" data-cancel>취소</button><button class="primary-button">확인</button></div></form>`;document.body.append(dialog);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();try{const name=dialog.querySelector('input').value.trim();if(!name||name.includes('/')||name.includes('\\'))throw Error('이름을 확인하세요.');const parent=mode==='rename'?selected.path.split('/').slice(0,-1).join('/'):this.folder;const relative=(parent?parent+'/':'')+name;await editorRequest(mode==='folder'?'/api/folder':'/api/rename',{method:'POST',body:JSON.stringify(mode==='folder'?{path:relative}:{from:selected.path,to:relative})});dialog.close();await this.refresh();}catch(error){this.hooks.error?.(error.message);}};dialog.showModal();dialog.querySelector('input').focus();dialog.querySelector('input').select();}
  menu(e){document.querySelector('.project-menu')?.remove();const menu=document.createElement('div');menu.className='dock-menu project-menu';menu.style.cssText=`left:${Math.max(0,Math.min(e.clientX,innerWidth-145))}px;top:${Math.max(0,Math.min(e.clientY,innerHeight-160))}px`;for(const [name,action] of [['열기',()=>this.openSelected()],['새 폴더',()=>this.nameDialog('folder')],['이름 변경',()=>this.nameDialog('rename')],['새로고침',()=>this.refresh()]]){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{menu.remove();action();};menu.append(b);}document.body.append(menu);const dismiss=e=>{if(!menu.contains(e.target)){menu.remove();document.removeEventListener('pointerdown',dismiss);}};document.addEventListener('pointerdown',dismiss);}
}
