import {editorRequest} from './project-browser.js';
import {assetTitle} from './asset-documents.js';
import {icon,assetIcon} from './icons.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function referenceGraph(path,{read,depth=1,dependencyDepth=depth,referencerDepth=depth,breadth=20,direction='both'}={}){
  if(![dependencyDepth,referencerDepth].every(n=>Number.isInteger(n)&&n>=1&&n<=5)||!Number.isInteger(breadth)||breadth<1||breadth>100||!['both','dependencies','referencers'].includes(direction))throw Error('참조 검색 범위를 확인하세요.');
  const nodes=new Map(),edges=new Map(),readCache=new Map(),visited=new Map(),truncated=new Set();let budget=250;
  const load=async path=>{if(!readCache.has(path))readCache.set(path,Promise.resolve().then(()=>read(path)).catch(error=>({path,error:error.message,missing:true})));return readCache.get(path);};
  const walk=async(path,level,side)=>{const visitKey=JSON.stringify([path,side]),rank=Math.abs(level);if(visited.has(visitKey)&&visited.get(visitKey)<=rank)return;visited.set(visitKey,rank);const info=await load(path),old=nodes.get(path);nodes.set(path,{...old,...info,level:old?.level??level});if(info.missing||rank>=(side<0?referencerDepth:dependencyDepth))return;
    const key=side<0?'referencers':'dependencies',items=info[key]||[];if(items.length>breadth)truncated.add(path);
    for(const item of items.slice(0,breadth)){if(!nodes.has(item.path)){if(--budget<0){truncated.add(path);break;}nodes.set(item.path,{...item,level:level+side});}const from=side<0?item.path:path,to=side<0?path:item.path;edges.set(JSON.stringify([from,to]),{from,to});if(item.missing)continue;await walk(item.path,level+side,side);}
  };
  const root=await load(path);nodes.set(path,{...root,level:0});if(direction!=='dependencies')await walk(path,0,-1);if(direction!=='referencers')await walk(path,0,1);
  return {root:path,nodes:[...nodes.values()],edges:[...edges.values()],truncated:[...truncated]};
}
export class ReferenceViewer {
  constructor(element,path,hooks){this.element=element;this.path=path;this.hooks=hooks;this.history=[path];this.index=0;this.dependencyDepth=1;this.referencerDepth=1;this.breadth=20;this.direction='both';this.query='';this.type='';this.zoom=1;this.request=0;this.render();}
  async navigate(path){if(path===this.path)return;this.history=this.history.slice(0,this.index+1);this.history.push(path);this.index++;this.path=path;await this.render();}
  async navigateHistory(direction){const next=this.index+direction;if(next<0||next>=this.history.length)return false;this.index=next;this.path=this.history[next];await this.render();return true;}
  async render(){
    const request=++this.request;this.element.className='workspace-view reference-viewer';
    this.element.tabIndex=0;this.element.innerHTML=`<header class="document-toolbar"><button data-ref-back ${!this.index?'disabled':''} aria-label="참조 뒤로">${icon('chevronLeft')}</button><button data-ref-forward ${this.index===this.history.length-1?'disabled':''} aria-label="참조 앞으로">${icon('chevronRight')}</button><strong>${esc(assetTitle(this.path))}</strong><label>사용 깊이<input type="number" min="1" max="5" value="${this.referencerDepth}" data-ref-depth="referencerDepth" aria-label="사용하는 파일 깊이"></label><label>의존 깊이<input type="number" min="1" max="5" value="${this.dependencyDepth}" data-ref-depth="dependencyDepth" aria-label="의존성 깊이"></label><label>너비<input type="number" min="1" max="100" value="${this.breadth}" data-ref-breadth aria-label="참조 너비"></label><select data-ref-direction aria-label="참조 방향">${[['both','양쪽'],['dependencies','의존성'],['referencers','사용하는 파일']].map(([k,l])=>`<option value="${k}" ${k===this.direction?'selected':''}>${l}</option>`).join('')}</select><select data-ref-type aria-label="참조 에셋 타입"><option value="">모든 타입</option></select><input type="search" data-ref-search aria-label="참조 검색" placeholder="경로 검색" value="${esc(this.query)}"><button data-ref-fit title="전체 보기 · F">전체</button><button data-ref-export>CSV</button><button data-ref-refresh aria-label="참조 새로고침">${icon('refresh')}</button></header><div class="reference-graph"></div>`;
    try{
      const registry=await(await editorRequest('/api/asset/registry')).json(),records=new Map(registry.assets.map(a=>[a.path,a]));
      const graph=await referenceGraph(this.path,{read:async path=>{const record=records.get(path);if(!record)throw Error('에셋이 없어요: '+path);return record;},dependencyDepth:this.dependencyDepth,referencerDepth:this.referencerDepth,breadth:this.breadth,direction:this.direction});if(this.disposed||request!==this.request)return;
      const select=this.element.querySelector('[data-ref-type]');for(const kind of [...new Set(graph.nodes.map(n=>n.kind).filter(Boolean))].sort()){const option=document.createElement('option');option.value=kind;option.textContent=kind;select.append(option);}select.value=this.type;
      const nodes=graph.nodes,levels=[...new Set(nodes.map(n=>n.level))].sort((a,b)=>a-b),positions=new Map();let maxRows=1;for(const level of levels){const group=nodes.filter(n=>n.level===level);maxRows=Math.max(maxRows,group.length);group.forEach((n,i)=>positions.set(n.path,{x:levels.indexOf(level)*300+24,y:i*94+36}));}
      const width=Math.max(640,levels.length*300),height=Math.max(320,maxRows*94+72),host=this.element.querySelector('.reference-graph');
      const arrow='ref-arrow-'+crypto.randomUUID();host.innerHTML=`<div class="reference-graph-world" style="width:${width}px;height:${height}px"><svg width="${width}" height="${height}" aria-hidden="true"><defs><marker id="${arrow}" viewBox="0 0 10 10" refX="10" refY="5" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L10 5L0 10Z" style="fill:#668ead;stroke:none"/></marker></defs>${graph.edges.filter(e=>positions.has(e.from)&&positions.has(e.to)).map(e=>{const a=positions.get(e.from),b=positions.get(e.to);return `<path marker-end="url(#${arrow})" d="M${a.x+236},${a.y+31} C${a.x+274},${a.y+31} ${b.x-38},${b.y+31} ${b.x},${b.y+31}"/>`;}).join('')}</svg>${nodes.map(n=>{const p=positions.get(n.path);return `<article style="left:${p.x}px;top:${p.y}px" class="reference-node ${n.path===this.path?'root':''} ${n.missing?'missing':''}"><button data-ref-root="${esc(n.path)}" ${n.missing?'disabled':''}>${icon(assetIcon(n.kind))}<strong>${esc(assetTitle(n.path))}</strong></button><small title="${esc(n.path)}">${esc(n.path)}</small><footer><span>${n.missing?'파일 없음':n.error?esc(n.error):((n.size||0)/1024).toFixed(1)+' KB'}${graph.truncated.includes(n.path)?' · 검색 제한':''}</span><button data-ref-open="${esc(n.path)}" ${n.missing?'disabled':''}>열기</button></footer></article>`;}).join('')}</div>`;
      this.graph=graph;for(const [i,n] of nodes.entries()){const el=host.querySelectorAll('.reference-node')[i];el.dataset.refPath=n.path;}this.applyFilters();this.setZoom(this.zoom);this.bindGraph(host);
    }catch(e){if(request===this.request)this.hooks.error(e.message);}
    this.element.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-ref-back'))this.navigateHistory(-1);else if(b.hasAttribute('data-ref-forward'))this.navigateHistory(1);else if(b.hasAttribute('data-ref-refresh'))this.render();else if(b.hasAttribute('data-ref-fit'))this.fit();else if(b.hasAttribute('data-ref-export'))this.export();else if(b.dataset.refRoot)this.navigate(b.dataset.refRoot);else if(b.dataset.refOpen){const n=this.graph.nodes.find(n=>n.path===b.dataset.refOpen);this.hooks.open({...n,name:n.path.split('/').pop()});}};
    this.element.onchange=e=>{if(e.target.hasAttribute('data-ref-type')){this.type=e.target.value;this.applyFilters();return;}if(e.target.hasAttribute('data-ref-depth'))this[e.target.dataset.refDepth]=Number(e.target.value);else if(e.target.hasAttribute('data-ref-breadth'))this.breadth=Number(e.target.value);else if(e.target.hasAttribute('data-ref-direction'))this.direction=e.target.value;else return;this.render();};
    this.element.querySelector('[data-ref-search]').oninput=e=>{this.query=e.target.value;this.applyFilters();};
    this.element.onkeydown=e=>{if(e.target.closest('input,select,textarea'))return;const key=e.key.toLowerCase();if(e.altKey&&['arrowleft','arrowright'].includes(key)){e.preventDefault();e.stopPropagation();this.navigateHistory(key==='arrowleft'?-1:1);}else if(e.ctrlKey&&key==='f'){e.preventDefault();e.stopPropagation();this.element.querySelector('[data-ref-search]').focus();}else if(key==='f'){e.preventDefault();e.stopPropagation();this.fit();}else if(['r','d','l'].includes(key)&&!e.ctrlKey){e.preventDefault();e.stopPropagation();const field={r:'referencerDepth',d:'dependencyDepth',l:'breadth'}[key];this[field]=Math.max(1,Math.min(field==='breadth'?100:5,this[field]+(e.shiftKey?-1:1)));this.render();}};
  }
  applyFilters(){if(!this.graph)return;for(const el of this.element.querySelectorAll('.reference-node')){const n=this.graph.nodes.find(n=>n.path===el.dataset.refPath);el.classList.toggle('filtered',n.path!==this.path&&(!n.path.toLowerCase().includes(this.query.toLowerCase())||this.type&&n.kind!==this.type));}}
  setZoom(value){this.zoom=Math.max(.15,Math.min(2,value));const world=this.element.querySelector('.reference-graph-world');if(world)world.style.zoom=this.zoom;}
  fit(){const host=this.element.querySelector('.reference-graph'),world=host?.firstElementChild;if(!world)return;this.setZoom(Math.min(1,host.clientWidth/parseFloat(world.style.width),host.clientHeight/parseFloat(world.style.height)));host.scrollLeft=host.scrollTop=0;}
  bindGraph(host){host.onwheel=e=>{if(e.ctrlKey){e.preventDefault();this.setZoom(this.zoom*Math.exp(-e.deltaY*.001));}};host.oncontextmenu=e=>{e.preventDefault();if(this.panMoved){this.panMoved=false;return;}const path=e.target.closest('[data-ref-path]')?.dataset.refPath||this.path;this.menu?.remove();const menu=document.createElement('div');menu.className='ui-context-menu';for(const [label,action] of [['이 에셋을 기준으로 보기',()=>this.navigate(path)],['에셋 열기',()=>this.hooks.open({...this.graph.nodes.find(n=>n.path===path),name:path.split('/').pop()})],['의존성 경로 복사',()=>this.copyReferences(path,false)],['사용하는 파일 경로 복사',()=>this.copyReferences(path,true)],['전체 보기',()=>this.fit()]]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{menu.remove();action();};menu.append(b);}document.body.append(menu);menu.style.left=Math.min(e.clientX,innerWidth-menu.offsetWidth-8)+'px';menu.style.top=Math.min(e.clientY,innerHeight-menu.offsetHeight-8)+'px';this.menu=menu;};host.onpointerdown=e=>{this.menu?.remove();if(e.button!==1&&e.button!==2)return;e.preventDefault();this.panMoved=false;const x=e.clientX,y=e.clientY,left=host.scrollLeft,top=host.scrollTop,controller=new AbortController();this.dragAbort?.abort();this.dragAbort=controller;window.addEventListener('pointermove',v=>{if(Math.hypot(v.clientX-x,v.clientY-y)>3){this.panMoved=true;this.menu?.remove();}host.scrollLeft=left+x-v.clientX;host.scrollTop=top+y-v.clientY;},{signal:controller.signal});window.addEventListener('pointerup',()=>controller.abort(),{once:true,signal:controller.signal});};}
  async copyReferences(path,incoming){const paths=this.graph.edges.filter(e=>incoming?e.to===path:e.from===path).map(e=>incoming?e.from:e.to);try{await navigator.clipboard.writeText(paths.join('\n'));}catch(e){this.hooks.error(e.message);}}
  export(){if(!this.graph)return;const quote=value=>'"'+String(value??'').replaceAll('"','""')+'"',lines=[['경로','타입','크기(바이트)','파일 없음','의존성','사용하는 파일'],...this.graph.nodes.map(n=>[n.path,n.kind,n.size,!!n.missing,this.graph.edges.filter(e=>e.from===n.path).map(e=>e.to).join('\n'),this.graph.edges.filter(e=>e.to===n.path).map(e=>e.from).join('\n')])],url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='HBEngine-asset-references.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  dispose(){this.disposed=true;this.request++;this.dragAbort?.abort();this.menu?.remove();clearTimeout(this.timer);}
}
