import {Vector3} from 'three';
import {geometryColliderTypes} from './collision-geometry.js';
import {enabledComponent,objectComponents} from './scene-components.js';
import {colliderBounds,sceneWorldMatrix,sceneWorldPosition,setSceneWorldPosition} from './scene-runtime.js';
export const validGameplayTag=tag=>typeof tag==='string'&&tag.length<=80&&/^[\p{L}\p{N}_]+(?:\.[\p{L}\p{N}_]+)*$/u.test(tag);
export function hasGameplayTag(tags,tag,exact=false){if(!validGameplayTag(tag))throw Error('게임플레이 태그 형식 오류');return (tags||[]).some(t=>t===tag||!exact&&t.startsWith(tag+'.'));}
export function matchTagQuery(tags,query,depth=0,budget={remaining:256}){if(--budget.remaining<0||depth>16||!query||!['any','all','none'].includes(query.op)||!Array.isArray(query.tags||[])||!Array.isArray(query.queries||[])||(query.tags||[]).length>32||(query.queries||[]).length>32||typeof(query.exact??false)!=='boolean')throw Error('태그 쿼리 형식 또는 크기 오류');const values=[...(query.tags||[]).map(t=>hasGameplayTag(tags,t,query.exact)),...(query.queries||[]).map(q=>matchTagQuery(tags,q,depth+1,budget))];return query.op==='all'?values.every(Boolean):query.op==='none'?!values.some(Boolean):values.some(Boolean);}
const vector=v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite);
export function collisionObstacles(objects,ignore=[]){const skip=new Set(ignore),cache=new Map();return objects.filter(o=>!skip.has(o.id)&&o.collisionEnabled!==false&&!o.components?.some(c=>c.type==='NavigationObstacle'&&c.properties?.enabled===false)).flatMap(o=>[...objectComponents(o),...(o.tileColliders||[])].filter(c=>['BoxCollider','SphereCollider','CapsuleCollider','BoxCollider2D','CircleCollider2D','CapsuleCollider2D',...geometryColliderTypes].includes(c.type)&&c.properties?.enabled!==false&&!c.properties?.trigger).map(c=>colliderBounds(o,c,sceneWorldMatrix(o,objects,cache))));}
export function segmentBlocked(start,end,bounds){return bounds.some(b=>{let enter=0,leave=1;for(let i=0;i<3;i++){const d=end[i]-start[i],lo=b.center[i]-b.extent[i],hi=b.center[i]+b.extent[i];if(Math.abs(d)<1e-9){if(start[i]<lo||start[i]>hi)return false;}else{const a=(lo-start[i])/d,z=(hi-start[i])/d;enter=Math.max(enter,Math.min(a,z));leave=Math.min(leave,Math.max(a,z));if(enter>leave)return false;}}return leave>=0&&enter<=1;});}
// ponytail: bounded planar collision grid, not a polygon NavMesh; use a tiled mesh solver for slopes, links, and crowds.
export function findNavigationPath(objects,start,end,{gridId='',ignore=[],radius=.25,height=1.8,margin=0}={}){
  if(!vector(start)||!vector(end)||!Number.isFinite(radius)||radius<0||!Number.isFinite(height)||height<=0||!Number.isFinite(margin)||margin<0)throw Error('경로 좌표·에이전트 크기 오류');const grid=objects.find(o=>(!gridId||o.id===gridId)&&enabledComponent(o,'NavigationGrid'));if(!grid)throw Error('Navigation Grid를 배치하세요.');const p=enabledComponent(grid,'NavigationGrid'),center=sceneWorldPosition(grid,objects),axes=p.plane==='XY'?[0,1]:[0,2],normal=p.plane==='XY'?2:1,cell=p.cellSize,width=Math.ceil(p.extent[axes[0]]*2/cell),rows=Math.ceil(p.extent[axes[1]]*2/cell);if(width*rows>40000)throw Error('내비게이션 셀 제한 초과 (40000)');
  const origin=axes.map(i=>center[i]-p.extent[i]),coord=v=>axes.map((i,j)=>Math.floor((v[i]-origin[j])/cell)),inside=([x,y])=>x>=0&&x<width&&y>=0&&y<rows,index=([x,y])=>y*width+x,toWorld=([x,y])=>{const v=[...center];axes.forEach((a,i)=>v[a]=origin[i]+([x,y][i]+.5)*cell);v[normal]=start[normal];return v;},a=coord(start),z=coord(end);if(!inside(a)||!inside(z))return [];
  const agent=objects.find(o=>o.id===ignore[0]),footprint=axes.map((axis,i)=>({lo:-(p.plane==='XY'&&i===1?height/2:radius)-margin,hi:(p.plane==='XY'&&i===1?height/2:radius)+margin}));if(agent)for(const bound of collisionObstacles(objects,objects.filter(o=>o.id!==agent.id).map(o=>o.id)))axes.forEach((axis,i)=>{const offset=bound.center[axis]-start[axis];footprint[i].lo=Math.min(footprint[i].lo,offset-bound.extent[axis]-margin);footprint[i].hi=Math.max(footprint[i].hi,offset+bound.extent[axis]+margin);});const blocked=new Uint8Array(width*rows),bounds=collisionObstacles(objects,[...ignore,grid.id]).filter(b=>b.is2D===(p.plane==='XY')&&(p.plane==='XY'||b.center[1]+b.extent[1]>start[1]+.01&&b.center[1]-b.extent[1]<start[1]+height));for(const b of bounds){const lo=axes.map((i,j)=>Math.max(0,Math.floor((b.center[i]-b.extent[i]-footprint[j].hi-cell/2-origin[j])/cell))),hi=axes.map((i,j)=>Math.min((j?rows:width)-1,Math.floor((b.center[i]+b.extent[i]-footprint[j].lo-cell/2-origin[j])/cell)));for(let y=lo[1];y<=hi[1];y++)for(let x=lo[0];x<=hi[0];x++)blocked[y*width+x]=1;}if(blocked[index(a)]||blocked[index(z)])return [];
  const heap=[],push=item=>{heap.push(item);let i=heap.length-1;while(i){const parent=(i-1)>>1;if(heap[parent].f<=item.f)break;heap[i]=heap[parent];i=parent;}heap[i]=item;},pop=()=>{const first=heap[0],last=heap.pop();if(heap.length){let i=0;while(i*2+1<heap.length){let child=i*2+1;if(child+1<heap.length&&heap[child+1].f<heap[child].f)child++;if(heap[child].f>=last.f)break;heap[i]=heap[child];i=child;}heap[i]=last;}return first;},distance=c=>Math.hypot(c[0]-z[0],c[1]-z[1]),cost=new Float64Array(width*rows).fill(Infinity),parent=new Int32Array(width*rows).fill(-1),closed=new Uint8Array(width*rows),startIndex=index(a),goal=index(z);cost[startIndex]=0;push({id:startIndex,f:distance(a)});
  while(heap.length){const current=pop().id;if(closed[current])continue;closed[current]=1;if(current===goal){const path=[];let id=goal;while(id!==startIndex){path.push(toWorld([id%width,Math.floor(id/width)]));id=parent[id];}path.reverse();const destination=[...end];destination[normal]=start[normal];path.push(destination);return path;}const x=current%width,y=Math.floor(current/width);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1],[1,-1],[-1,-1]]){const next=[x+dx,y+dy],id=index(next);if(!inside(next)||blocked[id]||closed[id]||dx&&dy&&(blocked[y*width+x+dx]||blocked[(y+dy)*width+x]))continue;const g=cost[current]+Math.hypot(dx,dy);if(g<cost[id]){cost[id]=g;parent[id]=current;push({id,f:g+distance(next)});}}}return [];
}
export function perceptionSystems(hooks){
  const listeners=new Map(),noise=[];let time=0;
  async function changed(vm,owner,target,stimulus){const binding=vm.bindings.find(b=>b.self===owner.id);if(binding)await vm.custom(binding,'OnTargetPerceptionUpdated',{target:target.id,sense:stimulus.sense,sensed:stimulus.sensed,location:stimulus.location,tag:stimulus.tag||''});hooks.perceived?.(owner.id,target,stimulus);}
  async function tick(delta,vm){time+=delta;while(noise.length&&noise[0].time<time-60)noise.shift();for(const owner of vm.objects){const p=enabledComponent(owner,'AIPerception');if(!p){listeners.delete(owner.id);continue;}const source=vm.object(enabledComponent(owner,'AIController')?.pawn)||owner,origin=sceneWorldPosition(source,vm.objects),state=listeners.get(owner.id)||{accumulator:p.interval,seen:new Map()};listeners.set(owner.id,state);state.accumulator+=delta;if(state.accumulator<p.interval)continue;state.accumulator=0;const is2D=p.plane==='XY',forward=new Vector3(...(is2D?[1,0,0]:[0,0,1])).transformDirection(sceneWorldMatrix(source,vm.objects)).toArray(),current=new Set();
      for(const target of vm.objects){if(target===source||['component','widget'].includes(target.kind))continue;const s=enabledComponent(target,'PerceptionSource'),location=sceneWorldPosition(target,vm.objects),difference=location.map((v,i)=>v-origin[i]),distance=Math.hypot(...difference),old=state.seen.get(target.id);if(p.targetTag&&!hasGameplayTag(target.tags,p.targetTag))continue;
        const sight=s?.sight&&p.sight&&target.visible!==false&&distance<=(old?.sensed&&old.sense==='sight'?p.loseSightRadius:p.sightRadius)&&(distance<1e-9||difference.reduce((sum,v,i)=>sum+v*forward[i],0)/distance>=Math.cos(p.halfAngle*Math.PI/180))&&(!p.occlusion||!segmentBlocked(origin,location,collisionObstacles(vm.objects,[source.id,target.id,owner.id]).filter(b=>b.is2D===is2D))),heard=p.hearing&&noise.find(n=>n.source===target.id&&n.time>=time-p.maxAge&&Math.hypot(...n.position.map((v,i)=>v-origin[i]))<=Math.min(p.hearingRadius,n.radius)*n.loudness);
        if(sight||heard){const stimulus={sense:sight?'sight':'hearing',sensed:true,time:sight?time:heard.time,location:sight?location:heard.position,tag:heard?.tag||''};current.add(target.id);state.seen.set(target.id,stimulus);if(!old?.sensed||old.sense!==stimulus.sense)await changed(vm,owner,target,stimulus);}
      }
      for(const [id,old] of [...state.seen])if(!current.has(id)){if(old.sensed){old.sensed=false;const target=vm.object(id);if(target)await changed(vm,owner,target,old);}if(time-old.time>=p.maxAge||!vm.object(id))state.seen.delete(id);}hooks.targets?.(owner.id,[...current].map(id=>vm.object(id)).filter(Boolean).sort((a,b)=>Math.hypot(...sceneWorldPosition(a,vm.objects).map((v,i)=>v-origin[i]))-Math.hypot(...sceneWorldPosition(b,vm.objects).map((v,i)=>v-origin[i]))),vm);owner.gameplayDebug={...owner.gameplayDebug,perception:[...state.seen].map(([id,s])=>({id,...s,age:time-s.time}))};}
  }
  return {tick,targets:id=>[...(listeners.get(id)?.seen||[])].filter(([,s])=>s.sensed).map(([id])=>id),noise(source,position,loudness=1,radius=20,tag=''){if(!source||!vector(position)||!Number.isFinite(loudness)||loudness<0||!Number.isFinite(radius)||radius<0||typeof tag!=='string'||tag.length>80)throw Error('소리 자극 형식 오류');if(noise.length>=1000)noise.shift();noise.push({source,position:[...position],loudness,radius,tag,time});},forget:id=>listeners.delete(id),dispose(){listeners.clear();noise.length=0;time=0;}};
}
export class ParticleSimulation {
  constructor(settings){this.p=settings;this.particles=[];this.reset();}
  reset(){this.particles.length=0;this.time=0;this.carry=0;this.seed=(this.p.seed>>>0)||1;this.playing=true;this.paused=false;this.previous=null;this.initial=true;}
  random(){this.seed=(Math.imul(this.seed,1664525)+1013904223)>>>0;return this.seed/4294967296;}
  emit(count,matrix){if(!Number.isInteger(count)||count<0||count>100000)throw Error('파티클 방출 수 오류');const total=Math.min(count,this.p.maxParticles-this.particles.length);for(let i=0;i<total;i++){const p=this.p,a=this.random()*Math.PI*2,z=this.random()*2-1,r=p.radius*Math.pow(this.random(),p.shape==='sphere'?1/3:.5),direction=p.shape==='circle'?[Math.cos(a),Math.sin(a),0]:p.shape==='sphere'?[Math.sqrt(1-z*z)*Math.cos(a),z,Math.sqrt(1-z*z)*Math.sin(a)]:p.shape==='cone'?[Math.cos(a)*Math.sin(p.angle*Math.PI/180),Math.cos(p.angle*Math.PI/180),Math.sin(a)*Math.sin(p.angle*Math.PI/180)]:[0,1,0],position=p.shape==='box'?p.extent.map(v=>(this.random()*2-1)*v):direction.map(v=>v*r),velocity=direction.map(v=>v*p.speed);if(p.simulationSpace==='world'&&matrix){const origin=new Vector3().applyMatrix4(matrix),v=new Vector3(...velocity).applyMatrix4(matrix).sub(origin);velocity.splice(0,3,...v.toArray());position.splice(0,3,...new Vector3(...position).applyMatrix4(matrix).toArray());}this.particles.push({position,velocity,age:0,lifetime:p.lifetime+(p.lifetimeMax-p.lifetime)*this.random(),size:p.size});}}
  advance(delta,matrix){if(!Number.isFinite(delta)||delta<0||delta>120)throw Error('파티클 시간 범위 오류');if(this.paused)return;const p=this.p,old=this.time,next=old+delta;let emission=0;if(this.playing){const begin=Math.max(old,p.startDelay),end=p.loop?next:Math.min(next,p.startDelay+p.duration),active=Math.max(0,end-begin);this.carry+=active*p.rate;emission=Math.floor(this.carry);this.carry-=emission;
      if(p.burstCount&&p.burstProbability>0){const first=Math.max(0,Math.floor((old-p.startDelay)/p.duration)),last=Math.min(first+1000,Math.max(0,Math.floor((next-p.startDelay)/p.duration)));for(let cycle=first;cycle<=last;cycle++){if(!p.loop&&cycle)break;for(let n=0;n<p.burstCycles;n++){const t=p.startDelay+cycle*p.duration+p.burstTime+n*p.burstInterval;if((t>old&&t<=next||this.initial&&t===0)&&t<p.startDelay+(cycle+1)*p.duration&&this.random()<=p.burstProbability)emission+=p.burstCount;}}}
      const position=matrix?new Vector3().setFromMatrixPosition(matrix).toArray():[0,0,0];if(this.previous&&active>0){this.carry+=Math.hypot(...position.map((v,i)=>v-this.previous[i]))*p.rateOverDistance;const count=Math.floor(this.carry);emission+=count;this.carry-=count;}this.previous=position;if(!p.loop&&next>=p.startDelay+p.duration)this.playing=false;}
    for(const particle of this.particles){const step=Math.min(delta,particle.lifetime-particle.age),force=p.force.map((v,i)=>v+(i===1?-9.81*p.gravity:0));particle.position=particle.position.map((v,i)=>v+particle.velocity[i]*step+force[i]*step*step*.5);particle.velocity=particle.velocity.map((v,i)=>(v+force[i]*step)*Math.exp(-p.drag*step));particle.age+=delta;}this.particles=this.particles.filter(v=>v.age<v.lifetime);this.emit(Math.min(100000,emission),matrix);this.time=next;this.initial=false;}
}
