import {componentDefinitions,componentDefaults,objectComponents,enabledComponent,makeSceneComponent,installBlueprintComponents} from './scene-components.js';
import {validBlueprint} from './blueprint-model.js';
import {createBlueprintResolver} from './blueprint-inheritance.js';
import {derivesFrom} from './class-types.js';
import {Matrix4,Vector3,Euler,Quaternion} from 'three';
import {geometryColliderTypes} from './collision-geometry.js';
const clone=value=>structuredClone(value),add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),scale=(v,n)=>v.map(x=>x*n),dot=(a,b)=>a.reduce((n,x,i)=>n+x*b[i],0),length=v=>Math.hypot(...v),normalize=v=>length(v)>1e-8?scale(v,1/length(v)):[0,0,0];
const vector=v=>Array.isArray(v)&&v.length===3&&v.every(Number.isFinite);
const rotation=degrees=>{const [x,y,z]=degrees.map(v=>v*Math.PI/180),a=Math.cos(x),b=Math.sin(x),c=Math.cos(y),d=Math.sin(y),e=Math.cos(z),f=Math.sin(z);return [[c*e,-c*f,d],[a*f+b*d*e,a*e-b*d*f,-b*c],[b*f-a*d*e,b*e+a*d*f,a*c]];};
const rotate=(matrix,v)=>matrix.map(row=>dot(row,v));
export function sceneWorldMatrix(object,objects,cache=new Map(),visiting=new Set()){if(cache.has(object.id))return cache.get(object.id);if(visiting.has(object.id)||visiting.size>64)throw Error('부모 계층 순환 또는 깊이 제한 초과');visiting.add(object.id);const matrix=new Matrix4().compose(new Vector3(...object.position),new Quaternion().setFromEuler(new Euler(...object.rotation.map(v=>v*Math.PI/180))),new Vector3(...object.scale)),parent=(object.parentId||object.parent)?objects.find(o=>o.id===(object.parentId||object.parent)):null;if(parent)matrix.premultiply(sceneWorldMatrix(parent,objects,cache,visiting));visiting.delete(object.id);cache.set(object.id,matrix);return matrix;}
export function sceneWorldPosition(object,objects){if(!object.parentId&&!object.parent)return [...object.position];return new Vector3().setFromMatrixPosition(sceneWorldMatrix(object,objects)).toArray();}
export function setSceneWorldPosition(object,position,objects){if(!vector(position))throw Error('월드 위치를 확인하세요.');const parent=(object.parentId||object.parent)?objects.find(o=>o.id===(object.parentId||object.parent)):null;object.position=parent?new Vector3(...position).applyMatrix4(sceneWorldMatrix(parent,objects).invert()).toArray():[...position];return object;}
const moveWorld=(object,delta,objects)=>{const parent=(object.parentId||object.parent)?objects.find(o=>o.id===(object.parentId||object.parent)):null;if(!parent){object.position=add(object.position,delta);return;}const inverse=sceneWorldMatrix(parent,objects).invert(),origin=new Vector3().applyMatrix4(inverse),local=new Vector3(...delta).applyMatrix4(inverse).sub(origin);object.position=add(object.position,local.toArray());};
export function colliderBounds(object,component,worldMatrix){const p={...componentDefaults(component.type),...component.properties},is2D=component.type.endsWith('2D'),sphere=['SphereCollider','CircleCollider2D'].includes(component.type),capsule=component.type.startsWith('CapsuleCollider'),r=rotation(object.rotation),s=object.scale,center=worldMatrix?new Vector3(...p.center).applyMatrix4(worldMatrix).toArray():add(object.position,rotate(r,p.center.map((v,i)=>v*s[i]))),e=worldMatrix?.elements,linear=e?[[e[0],e[4],e[8]],[e[1],e[5],e[9]],[e[2],e[6],e[10]]]:r.map(row=>row.map((v,i)=>v*s[i])),scales=e?new Vector3().setFromMatrixScale(worldMatrix).toArray():s;if(geometryColliderTypes.has(component.type)){const points=component.type==='MeshCollider'?p.vertices:component.type==='PolygonCollider2D'?p.paths.flat():p.points,worldPoints=points.map(point=>center.map((v,i)=>v+linear[i].reduce((n,x,j)=>n+x*(point[j]||0),0))),min=[0,1,2].map(i=>Math.min(...worldPoints.map(p=>p[i]))),max=[0,1,2].map(i=>Math.max(...worldPoints.map(p=>p[i]))),extent=min.map((v,i)=>(max[i]-v)/2),boundsCenter=min.map((v,i)=>(max[i]+v)/2);if(is2D){boundsCenter[2]=0;extent[2]=1e12;}return {object,component,p,center:boundsCenter,extent,is2D,radius:null};}let extent=sphere?Array(3).fill(p.radius*Math.max(...scales.slice(0,is2D?2:3))):capsule?[p.radius,p.height/2,p.radius]:p.extent;extent=sphere?extent:linear.map(row=>row.reduce((sum,v,i)=>sum+Math.abs(v*extent[i]),0));if(is2D){center[2]=0;extent[2]=1e12;}return {object,component,p,center,extent,is2D,radius:sphere?extent[0]:null};}
function contact(a,b){
  if(a.radius!==null&&b.radius!==null){const difference=sub(a.center,b.center),distance=length(difference),penetration=a.radius+b.radius-distance;if(penetration< -1e-7)return null;return {normal:distance>1e-8?scale(difference,1/distance):[0,1,0],penetration:Math.max(0,penetration),position:sub(a.center,scale(distance>1e-8?scale(difference,1/distance):[0,1,0],a.radius))};}
  if(a.radius!==null||b.radius!==null){const sphere=a.radius!==null?a:b,box=sphere===a?b:a,closest=box.center.map((v,i)=>Math.max(v-box.extent[i],Math.min(v+box.extent[i],sphere.center[i]))),difference=sub(sphere.center,closest),distance=length(difference);let normal,penetration;if(distance>1e-8){penetration=sphere.radius-distance;if(penetration< -1e-7)return null;normal=scale(difference,1/distance);}else{const depths=box.extent.map((v,i)=>v-Math.abs(sphere.center[i]-box.center[i])),axis=depths.indexOf(Math.min(...depths));normal=[0,0,0];normal[axis]=sphere.center[axis]>=box.center[axis]?1:-1;penetration=sphere.radius+depths[axis];}return {normal:sphere===a?normal:scale(normal,-1),penetration:Math.max(0,penetration),position:closest};}
  const delta=sub(a.center,b.center),depths=a.extent.map((v,i)=>v+b.extent[i]-Math.abs(delta[i]));if(depths.some(v=>v< -1e-7))return null;const axis=depths.indexOf(Math.min(...depths)),normal=[0,0,0];normal[axis]=delta[axis]>=0?1:-1;return {normal,penetration:Math.max(0,depths[axis]),position:a.center.map((v,i)=>(Math.max(v-a.extent[i],b.center[i]-b.extent[i])+Math.min(v+a.extent[i],b.center[i]+b.extent[i]))/2)};
}
export function sceneContacts(objects){const matrices=new Map(),bounds=objects.filter(o=>o.kind!=='component'&&o.kind!=='widget'&&o.poolActive!==false&&o.collisionEnabled!==false).flatMap(o=>[...objectComponents(o),...(o.tileColliders||[])].filter(c=>['BoxCollider','SphereCollider','CapsuleCollider','BoxCollider2D','CircleCollider2D','CapsuleCollider2D'].includes(c.type)&&c.properties?.enabled!==false).map(c=>colliderBounds(o,c,sceneWorldMatrix(o,objects,matrices)))),contacts=[];
  // ponytail: bounded scene uses pair scans and capsule bounding boxes; use a broadphase and swept capsule solver for large worlds or character slope stepping.
  for(let i=0;i<bounds.length;i++)for(let j=i+1;j<bounds.length;j++){const a=bounds[i],b=bounds[j];if(a.object===b.object||a.is2D!==b.is2D||((a.p.mask>>>0)&(1<<b.p.layer))===0||((b.p.mask>>>0)&(1<<a.p.layer))===0)continue;const hit=contact(a,b);if(hit)contacts.push({a:a.object.id,b:b.object.id,componentA:a.component.id,componentB:b.component.id,trigger:a.p.trigger||b.p.trigger,...hit,colliderA:a,colliderB:b});}return contacts;
}
function body(object){const p=enabledComponent(object,'Rigidbody2D')||enabledComponent(object,'Rigidbody'),movement=enabledComponent(object,'CharacterMovement2D')||enabledComponent(object,'CharacterMovement'),is2D=!!enabledComponent(object,'Rigidbody2D')||!!enabledComponent(object,'CharacterMovement2D');if(!p&&!movement)return null;const properties=p||{mass:1,useGravity:true,isKinematic:false,drag:0,velocity:[0,0,0],freezePosition:is2D?[0,0,1]:[0,0,0]};object.velocity??=clone(properties.velocity);return {object,p:properties,movement,is2D,inverseMass:properties.isKinematic?0:1/properties.mass};}
const combineMode=(a,b)=>['average','min','multiply','max'][Math.max(0,['average','min','multiply','max'].indexOf(a),['average','min','multiply','max'].indexOf(b))];
const combine=(a,b,mode)=>mode==='min'?Math.min(a,b):mode==='max'?Math.max(a,b):mode==='multiply'?a*b:(a+b)/2;
export function createScenePhysics(objects,options={}){
  const fixedStep=options.fixedStep??options.fixedDeltaTime??1/60,maxSubsteps=options.maxSubsteps??8,gravity=options.gravity??[0,-9.81,0];if(!vector(gravity)||!Number.isFinite(fixedStep)||fixedStep<=0||fixedStep>1||!Number.isInteger(maxSubsteps)||maxSubsteps<1||maxSubsteps>128)throw Error('물리 설정을 확인하세요.');
  const keys=new Map(),inputs=new Map(),forces=new Map(),jumps=new Set();let accumulator=0,lastContacts=[],elapsed=0,ready=false;
  const materials=new Map(options.materials||[]),material=collider=>({...collider.p,...materials.get(collider.p.physicalMaterial)});
  const massBody=object=>{const result=body(object);if(result?.p.autoMass&&!result.p.isKinematic){let mass=0;for(const c of objectComponents(object).filter(c=>c.type.includes('Collider')&&c.properties?.enabled!==false)){const b=colliderBounds(object,c),p=material(b),r=p.radius*Math.max(...object.scale.slice(0,b.is2D?2:3)),volume=c.type.includes('Circle')?Math.PI*r*r:c.type.includes('Sphere')?4/3*Math.PI*r**3:c.type.includes('Capsule')?(b.is2D?2*r*Math.max(0,p.height*object.scale[1]-2*r)+Math.PI*r*r:Math.PI*r*r*Math.max(0,p.height*object.scale[1]-2*r)+4/3*Math.PI*r**3):b.is2D?4*b.extent[0]*b.extent[1]:8*b.extent[0]*b.extent[1]*b.extent[2];mass+=volume*(p.density??1);}result.inverseMass=1/Math.max(.0001,mass);}return result;};
  const state={objects,gameplay:options.gameplay||null,input(key,value){keys.set(key.toLowerCase(),value);if(key===' '&&value&&state.gameplay?.pawn)jumps.add(state.gameplay.pawn);},releaseInput(){keys.clear();inputs.clear();jumps.clear();},movement(object,direction,value=1){if(!vector(direction)||!Number.isFinite(value))throw Error('이동 입력을 확인하세요.');inputs.set(object.id,add(inputs.get(object.id)||[0,0,0],scale(direction,value)));},jump(object){jumps.add(object.id);},impulse(object,value){if(!vector(value))throw Error('충격량을 확인하세요.');const b=massBody(object);if(!b||!b.inverseMass)throw Error('활성화된 동적 Rigidbody가 필요해요.');object.velocity=add(object.velocity,scale(value,b.inverseMass));},force(object,value){if(!vector(value))throw Error('힘을 확인하세요.');if(!body(object)?.inverseMass)throw Error('활성화된 동적 Rigidbody가 필요해요.');forces.set(object.id,add(forces.get(object.id)||[0,0,0],value));},velocity(object,value){if(!vector(value))throw Error('속도를 확인하세요.');if(!body(object))throw Error('Rigidbody 또는 Character Movement가 필요해요.');object.velocity=clone(value);},contacts(){return lastContacts;},async loadMaterials(read){if(ready)return;for(const o of objects)for(const c of objectComponents(o)){const path=c.properties?.physicalMaterial;if(!path||materials.has(path))continue;const data=await read(path);if(data?.version!==1||!['friction','restitution','density'].every(k=>Number.isFinite(data[k]))||data.friction<0||data.friction>10||data.restitution<0||data.restitution>1||data.density<=0||!['average','min','max','multiply'].includes(data.frictionCombine)||!['average','min','max','multiply'].includes(data.restitutionCombine))throw Error('물리 머테리얼 검증 실패: '+path);materials.set(path,data);}ready=true;},async advance(delta,beforeStep,afterStep){if(!Number.isFinite(delta)||delta<0)throw Error('물리 시간을 확인하세요.');accumulator=Math.min(accumulator+delta,fixedStep*maxSubsteps);let count=0;while(accumulator+1e-9>=fixedStep&&count<maxSubsteps){await beforeStep?.(fixedStep);state.step(0,1);await afterStep?.();count++;}return count;},step(delta,limit=maxSubsteps){
    if(!Number.isFinite(delta)||delta<0)throw Error('물리 시간을 확인하세요.');accumulator=Math.min(accumulator+delta,fixedStep*maxSubsteps);let count=0;const frameContacts=new Map();
    while(accumulator+1e-9>=fixedStep&&count<limit){count++;accumulator=Math.max(0,accumulator-fixedStep);elapsed+=fixedStep;const bodies=new Map(objects.map(o=>[o.id,massBody(o)]));
      for(const o of objects){if(o.poolActive===false)continue;const b=bodies.get(o.id),move=enabledComponent(o,'TopDownMovement2D')||enabledComponent(o,'CharacterMovement2D')||enabledComponent(o,'CharacterMovement')||enabledComponent(o,'PawnMovement'),ai=enabledComponent(o,'AIController');if(ai&&ai.pawn&&ai.target){const pawn=objects.find(x=>x.id===ai.pawn),target=objects.find(x=>x.id===ai.target);if(pawn&&target){const direction=sub(target.position,pawn.position);if(length(direction)>ai.stoppingDistance)inputs.set(pawn.id,normalize([direction[0],0,direction[2]]));}}
        if(move){const nav=o.navigationControl;const controlled=state.gameplay?.pawn===o.id||move.autoPossess;const controller=state.gameplay?.controller&&objects.find(x=>x.id===state.gameplay.controller),control=controller&&enabledComponent(controller,'PlayerController'),allow=!control||control.inputEnabled;const topDown=enabledComponent(o,'TopDownMovement2D');const keyboard=controlled&&allow?[(keys.get('d')||keys.get('arrowright')||0)-(keys.get('a')||keys.get('arrowleft')||0),topDown?(keys.get('w')||keys.get('arrowup')||0)-(keys.get('s')||keys.get('arrowdown')||0):0,b?.is2D?0:(keys.get('s')||keys.get('arrowdown')||0)-(keys.get('w')||keys.get('arrowup')||0)]:[0,0,0],input=nav?nav.direction:add(inputs.get(o.id)||[0,0,0],keyboard),direction=length(input)>1?normalize(input):input,target=scale(direction,nav?.speed??move.speed),velocity=o.velocity??=[0,0,0],blend=Math.min(1,move.acceleration*fixedStep);velocity[0]+=(target[0]-velocity[0])*blend;if((nav||topDown)&&b?.is2D)velocity[1]+=(target[1]-velocity[1])*blend;velocity[2]+=(target[2]-velocity[2])*blend;if(jumps.has(o.id)&&move.jumpSpeed!==undefined&&o.grounded){velocity[1]=move.jumpSpeed;o.grounded=false;}}
        if(b&&b.inverseMass){const acceleration=forces.get(o.id)?scale(forces.get(o.id),b.inverseMass):[0,0,0],g=b.movement?[gravity[0],-b.movement.gravity,gravity[2]]:gravity;o.velocity=add(o.velocity,scale(add(acceleration,b.p.useGravity?g:[0,0,0]),fixedStep));o.velocity=scale(o.velocity,1/(1+b.p.drag*fixedStep));o.grounded=false;for(let axis=0;axis<3;axis++)if(b.p.freezePosition[axis]||b.is2D&&axis===2)o.velocity[axis]=0;moveWorld(o,scale(o.velocity,fixedStep),objects);}else if(!b&&o.velocity&&!objectComponents(o).some(c=>['Rigidbody','Rigidbody2D','CharacterMovement','CharacterMovement2D','PawnMovement'].includes(c.type)))moveWorld(o,scale(o.velocity,fixedStep),objects);
      }
      for(let pass=0;pass<3;pass++){const contacts=sceneContacts(objects);for(const hit of contacts){const id=JSON.stringify([hit.a,hit.componentA,hit.b,hit.componentB]);frameContacts.set(id,hit);if(hit.trigger)continue;const a=bodies.get(hit.a),b=bodies.get(hit.b),sum=(a?.inverseMass||0)+(b?.inverseMass||0);if(!sum)continue;const pa=material(hit.colliderA),pb=material(hit.colliderB),normal=hit.normal;for(const [body,sign] of [[a,1],[b,-1]])if(body?.inverseMass){const displacement=scale(normal,sign*hit.penetration*body.inverseMass/sum);for(let axis=0;axis<3;axis++)if(body.p.freezePosition[axis]||body.is2D&&axis===2)displacement[axis]=0;moveWorld(body.object,displacement,objects);if(normal[1]*sign>.5)body.object.grounded=true;}
        const relative=sub(a?.object.velocity||[0,0,0],b?.object.velocity||[0,0,0]),speed=dot(relative,normal);if(speed>=0)continue;const restitution=combine(pa.restitution,pb.restitution,combineMode(pa.restitutionCombine,pb.restitutionCombine)),impulse=-(1+restitution)*speed/sum,tangent=sub(relative,scale(normal,speed)),tangentLength=length(tangent),friction=combine(pa.friction,pb.friction,combineMode(pa.frictionCombine,pb.frictionCombine)),frictionImpulse=Math.min(tangentLength/sum,impulse*friction),force=add(scale(normal,impulse),tangentLength>1e-8?scale(tangent,-frictionImpulse/tangentLength):[0,0,0]);if(a?.inverseMass)a.object.velocity=add(a.object.velocity,scale(force,a.inverseMass));if(b?.inverseMass)b.object.velocity=sub(b.object.velocity,scale(force,b.inverseMass));
      }if(contacts.every(c=>c.trigger||c.penetration<1e-7))break;}
      for(const o of objects)if(bodies.get(o.id)||o.velocity)options.update?.(o);jumps.clear();
    }
    if(count){lastContacts=[...frameContacts.values()];forces.clear();inputs.clear();}else lastContacts=sceneContacts(objects);const game=state.gameplay;if(game){game.elapsed=elapsed;for(const key of ['gameMode','gameState']){const o=objects.find(o=>o.id===game[key]),p=o&&objectComponents(o).find(c=>c.type===(key==='gameMode'?'GameMode':'GameState'))?.properties;if(p){p.elapsed=elapsed;p.matchState=game.matchState;}}}return count;
  },dispose(){state.releaseInput();forces.clear();lastContacts=[];accumulator=0;}};return state;
}
export async function prepareGameplay(objects,{gameConfig=null,readAsset}={}){
  const resolveBlueprint=createBlueprintResolver(readAsset);
  const bindings=[],gameplay={gameMode:null,gameState:null,controller:null,playerState:null,pawn:null,elapsed:0,matchState:'waiting'},config=gameConfig||{},playerStart=objects.find(o=>o.kind==='playerStart'),spawnPosition=playerStart?sceneWorldPosition(playerStart,objects):config.spawnPosition||[0,1,0];
  async function create(key,className,kind){const role={defaultController:'playerController',defaultPawn:'pawn'}[key]||key,path=config[key],loaded=path?await resolveBlueprint(path):null;if(loaded&&!validBlueprint(loaded,{resolved:!!loaded.inheritance}))throw Error('게임 프레임워크 블루프린트 검증 실패: '+path);const root=loaded&&clone(loaded),parent=root?.settings?.parentClass||className,nativeBase=root?.native?.classes.find(c=>c.name===parent)?.base,base=nativeBase||parent;if(root&&!derivesFrom(base,className))throw Error(className+' 파생 블루프린트가 필요해요: '+path);let object=objects.find(o=>o.nativeClass===parent||o.frameworkRole===role||role==='playerController'&&enabledComponent(o,'PlayerController'));if(!object){if(objects.length>=500)throw Error('게임 프레임워크 오브젝트 제한 초과');object={id:crypto.randomUUID(),name:root?.name||className,kind,group:'GAMEPLAY',visible:['character','sprite'].includes(kind),position:clone(role==='pawn'?spawnPosition:[0,0,0]),rotation:role==='pawn'&&playerStart?clone(playerStart.rotation):[0,0,0],scale:[1,1,1],nativeClass:parent,frameworkRole:role};objects.push(object);}object.frameworkRole=role;if(root){object.blueprintAsset=path;object.components=clone(root.components);if(config.defaultInputMapping&&!root.settings.inputMapping)root.settings.inputMapping=config.defaultInputMapping;bindings.push({root,self:object.id,path});}else if(!objectComponents(object).some(c=>c.type===className)&&componentDefinitions[className])object.components.push(makeSceneComponent(className));return object;}
  gameplay.gameMode=(await create('gameMode','GameMode','gameMode')).id;gameplay.gameState=(await create('gameState','GameState','gameState')).id;gameplay.controller=(await create('defaultController','PlayerController','controller')).id;gameplay.playerState=(await create('playerState','PlayerState','playerState')).id;
  const playerController=objects.find(o=>o.id===gameplay.controller),explicitPawn=enabledComponent(playerController,'PlayerController')?.pawn;const existing=objects.find(o=>o.id===explicitPawn)||objects.find(o=>enabledComponent(o,'CharacterMovement2D')?.autoPossess||enabledComponent(o,'CharacterMovement')?.autoPossess||enabledComponent(o,'PawnMovement')?.autoPossess||enabledComponent(o,'TopDownMovement2D')?.autoPossess||o.frameworkRole==='pawn');if(existing){gameplay.pawn=existing.id;existing.frameworkRole='pawn';}else if(config.autoSpawnPlayer===true||config.defaultPawn){const pawn=await create('defaultPawn',config.defaultPawn?'Pawn':'Character',config.dimension==='2d'?'sprite':'character');if(config.dimension==='2d'&&!config.defaultPawn)pawn.components=['Transform','SpriteRenderer','CapsuleCollider2D','Rigidbody2D','CharacterMovement2D'].map(type=>makeSceneComponent(type,type==='CapsuleCollider2D'?{friction:0,frictionCombine:'min'}:{}));gameplay.pawn=pawn.id;}
  const controller=objects.find(o=>o.id===gameplay.controller),control=objectComponents(controller).find(c=>c.type==='PlayerController');if(control)control.properties.pawn=gameplay.pawn||'';controller.pawn=gameplay.pawn;controller.playerState=gameplay.playerState;controller.gameMode=gameplay.gameMode;controller.gameState=gameplay.gameState;const pawn=objects.find(o=>o.id===gameplay.pawn);if(pawn){pawn.controller=gameplay.controller;pawn.playerState=gameplay.playerState;}const mode=objects.find(o=>o.id===gameplay.gameMode);mode.gameState=gameplay.gameState;mode.playerController=gameplay.controller;mode.defaultPawn=gameplay.pawn;installBlueprintComponents(objects,bindings);return {gameplay,bindings,objects,physicsOptions:{backend:'rapier',dimension:config.dimension==='2d'?2:3,gravity:config.gravity||[0,-9.81,0],fixedStep:config.fixedDeltaTime||1/60,maxSubsteps:config.maxSubsteps||8}};
}
