import {shortcutCommands,eventChord,shortcutLabel} from './editor-shortcuts.js';
import {escapeText as esc} from './scene-editor.js';
import {icon} from './icons.js';
export function shortcutEditor(element,model,{error,changed}={}){
  let category='',query='',recording=null,pending=null;
  const update=()=>{changed?.();render();};
  function render(){
    const data=model.snapshot();element.className='shortcut-editor';element.innerHTML=`<header class="two-d-toolbar"><select data-shortcut-profile aria-label="단축키 프로필">${data.profiles.map(p=>`<option value="${esc(p.id)}" ${p.id===data.active?'selected':''}>${esc(p.name)}</option>`).join('')}</select><button data-shortcut-action="clone">${icon('plus')} 프로필</button><button data-shortcut-action="delete" ${data.active==='default'?'disabled':''}>${icon('trash')}</button><button data-shortcut-action="export">${icon('download')} 내보내기</button><button data-shortcut-action="import">${icon('upload')} 가져오기</button><input type="file" data-shortcut-file accept="application/json,.json" hidden></header><div class="shortcut-filter"><input data-shortcut-search type="search" aria-label="단축키 검색" placeholder="명령 또는 단축키 검색" value="${esc(query)}"><select data-shortcut-category aria-label="단축키 범주">${[['','전체'],['global','편집기'],['authoring','공통 편집'],['viewport','뷰포트'],['blueprint','블루프린트']].map(([id,name])=>`<option value="${id}" ${category===id?'selected':''}>${name}</option>`).join('')}</select></div><div class="shortcut-list"><table><thead><tr><th>명령</th><th>키 1</th><th>키 2</th><th></th></tr></thead><tbody>${shortcutCommands.filter(c=>(!category||c.scope===category)&&(c.label+' '+c.id+' '+model.keys(c.id).map(shortcutLabel).join(' ')).toLowerCase().includes(query.toLowerCase())).map(c=>`<tr><td>${esc(c.label)}</td>${[0,1].map(slot=>`<td><button data-shortcut-record="${c.id}" data-slot="${slot}" aria-label="${esc(c.label)} 단축키 ${slot+1}">${recording?.id===c.id&&recording.slot===slot?'키 입력…':esc(shortcutLabel(model.keys(c.id)[slot]))}</button><button data-shortcut-remove="${c.id}" data-slot="${slot}" aria-label="${esc(c.label)} 단축키 삭제" ${model.keys(c.id)[slot]?'':'disabled'}>${icon('close')}</button></td>`).join('')}<td><button data-shortcut-reset="${c.id}" aria-label="${esc(c.label)} 기본값 복원">${icon('undo')}</button></td></tr>`).join('')}</tbody></table></div>${pending?`<footer class="shortcut-conflict" role="alert"><span>${esc(pending.message)}</span><button data-shortcut-action="override">덮어쓰기</button><button data-shortcut-action="cancel">취소</button></footer>`:''}`;
  }
  element.onclick=e=>{const b=e.target.closest('button');if(!b)return;try{
    if(b.dataset.shortcutRecord){recording={id:b.dataset.shortcutRecord,slot:Number(b.dataset.slot)};pending=null;render();element.querySelector(`[data-shortcut-record="${recording.id}"][data-slot="${recording.slot}"]`).focus();return;}
    recording=null;
    if(b.dataset.shortcutRemove){model.assign(b.dataset.shortcutRemove,model.keys(b.dataset.shortcutRemove).filter((_,i)=>i!==Number(b.dataset.slot)));pending=null;update();return;}
    if(b.dataset.shortcutReset){model.reset(b.dataset.shortcutReset);update();return;}
    const action=b.dataset.shortcutAction;if(action==='cancel'){pending=null;recording=null;render();}else if(action==='override'){model.assign(pending.id,pending.keys,{override:true});pending=null;recording=null;update();}else if(action==='delete'){model.deleteProfile();update();}else if(action==='import')element.querySelector('[data-shortcut-file]').click();else if(action==='export'){const blob=new Blob([JSON.stringify(model.snapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=element.ownerDocument.createElement('a');a.href=url;a.download='HBEngine-shortcuts.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}else if(action==='clone'){
      const doc=element.ownerDocument,dialog=doc.createElement('dialog');dialog.innerHTML='<div class="dialog-heading"><h2>프로필 만들기</h2></div><form method="dialog"><label>이름<input data-profile-name maxlength="80" value="User"></label><div class="dialog-actions"><button value="cancel">취소</button><button value="create" class="primary-button">만들기</button></div></form>';doc.body.append(dialog);dialog.onclose=()=>{try{if(dialog.returnValue==='create'){model.cloneProfile(dialog.querySelector('input').value);update();}}catch(e){error?.(e.message);}finally{dialog.remove();}};dialog.showModal();dialog.querySelector('input').select();
    }
  }catch(e){error?.(e.message);}};
  element.oninput=e=>{if(e.target.hasAttribute('data-shortcut-search')){recording=null;query=e.target.value;const start=e.target.selectionStart;render();const input=element.querySelector('[data-shortcut-search]');input.focus();input.setSelectionRange?.(start,start);}};
  element.onchange=async e=>{try{if(e.target.hasAttribute('data-shortcut-profile')){model.activate(e.target.value);recording=null;pending=null;update();}else if(e.target.hasAttribute('data-shortcut-category')){category=e.target.value;render();}else if(e.target.hasAttribute('data-shortcut-file')){const file=e.target.files[0];if(!file)return;if(file.size>512000)throw Error('프로필 파일은 512 KB 이하여야 해요.');model.replace(JSON.parse(await file.text()));recording=null;pending=null;update();}}catch(e){error?.(e.message);}};
  element.onkeydown=e=>{if(!recording||!e.target.closest('[data-shortcut-record]'))return;e.preventDefault();e.stopPropagation();if(e.key==='Escape'){recording=null;render();return;}if(e.repeat||e.isComposing)return;const chord=eventChord(e);if(!chord)return;const id=recording.id,keys=model.keys(id);keys[recording.slot]=chord;const compact=keys.filter(Boolean);try{model.assign(id,compact);recording=null;pending=null;update();}catch(error){pending={id,keys:compact,message:error.message};render();}};
  element.onfocusout=e=>{if(recording&&e.relatedTarget&&!element.contains(e.relatedTarget)){recording=null;pending=null;render();}};
  render();return {render,recording:()=>!!recording&&!!element.ownerDocument.activeElement?.closest('[data-shortcut-record]')&&element.contains(element.ownerDocument.activeElement),dispose:()=>{recording=null;pending=null;element.onkeydown=null;element.onfocusout=null;}};
}
