import {defaultsFor,validTimeline,sampleTimeline,timelineLength} from './blueprint-model.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const modes=[['auto','Auto'],['user','User'],['break','Break'],['linear','Linear'],['constant','Constant']];
const colors=['#ec817d','#9acb78','#85b9e6','#d8d5b2'];
export class TimelineEditor {
  constructor(element,getNode,hooks={}){
    this.el=element;this.getNode=getNode;this.hooks=hooks;this.trackId=getNode().timeline.tracks[0]?.id;this.channel=0;this.selection=new Set();this.hidden=new Set();this.time=0;this.playing=0;this.fit();this.render();
    element.tabIndex=0;element.addEventListener('keydown',e=>{if(e.isComposing||e.target.matches('input,select,textarea'))return;if((e.ctrlKey||e.metaKey)&&['z','y','s'].includes(e.key.toLowerCase()))return;e.stopPropagation();if(e.key==='Delete'){e.preventDefault();this.removeKeys();}if(e.key==='Enter'){e.preventDefault();this.addKey(this.time);}if(e.key==='Home'||e.key.toLowerCase()==='a'){e.preventDefault();this.fit();this.draw();}if(e.key.toLowerCase()==='f'){e.preventDefault();this.fit(true);this.draw();}if(e.code==='Space'){e.preventDefault();this.playing=this.playing?0:1;}});
    this.observer=new ResizeObserver(()=>this.readableLabels());this.observer.observe(element);
    let previous;const animate=now=>{if(this.disposed||!this.el.isConnected)return;const dt=previous?Math.min((now-previous)/1000,.1):0;previous=now;if(this.playing&&this.el.offsetWidth){const t=this.node.timeline,length=timelineLength(t);this.time+=dt*this.playing*(t.playRate||1);if(this.time>=length||this.time<=0){this.time=t.loop?(this.playing>0?0:length):Math.max(0,Math.min(length,this.time));if(!t.loop)this.playing=0;}this.draw();this.scrub();}requestAnimationFrame(animate);};requestAnimationFrame(animate);
  }
  readableLabels(){const r=this.svg?.getBoundingClientRect();if(r?.width&&r.height)this.svg.style.setProperty('--curve-font',Math.max(11,11*1000/r.width,11*420/r.height)+'px');}
  dispose(){this.disposed=true;this.observer?.disconnect();}
  get node(){return this.getNode();}get track(){return this.node?.timeline.tracks.find(t=>t.id===this.trackId);}
  fit(selected=false){const t=this.node.timeline,keys=selected?[...this.selection]:[],values=keys.length?keys.flatMap(k=>Array.isArray(k.value)?k.value:[k.value??0]):(this.track?.type!=='event'?this.track?.keys||[]:[]).flatMap(k=>Array.isArray(k.value)?k.value:[k.value]);const lo=Math.min(0,...values),hi=Math.max(1,...values);const start=keys.length?Math.min(...keys.map(k=>k.time)):0,end=keys.length?Math.max(...keys.map(k=>k.time)):t.length,pad=Math.max(.05,(end-start)*.1);this.view={start:start-pad,end:end+pad,min:lo-(hi-lo)*.15,max:hi+(hi-lo)*.15};}
  change(edit,record=true){
    const original=this.node.timeline,candidate=structuredClone(original),selected=[...(this.selection)].map(key=>original.tracks.find(t=>t.id===this.trackId)?.keys.indexOf(key));
    const refs=selected.map(i=>candidate.tracks.find(t=>t.id===this.trackId)?.keys[i]).filter(Boolean);edit(candidate);if(!validTimeline(candidate)){this.hooks.error?.('타임라인의 시간·값·키 간격을 확인하세요.');return false;}
    if(record)this.hooks.before?.();this.node.timeline=candidate;this.selection=new Set(refs.filter(k=>this.track?.keys.includes(k)));this.hooks.change?.();return true;
  }
  render(){
    const t=this.node.timeline,track=this.track;this.el.className='workspace-view timeline-editor active';
    this.el.innerHTML=`<div class="curve-toolbar"><select data-add-track aria-label="트랙 추가"><option value="">+ 트랙</option><option value="float">Float</option><option value="vec3">Vector</option><option value="color">Color</option><option value="event">Event</option></select><label>길이<input type="number" data-setting="length" value="${t.length}" min=".01" max="10000" step=".1" aria-label="타임라인 길이"></label>${[['loop','반복'],['autoplay','자동 재생'],['lastKeyframe','마지막 키까지'],['ignoreTimeDilation','시간 배율 무시']].map(([k,label])=>`<label><input type="checkbox" data-setting="${k}" ${t[k]?'checked':''}>${label}</label>`).join('')}<label>속도<input type="number" data-setting="playRate" value="${t.playRate??1}" min=".01" max="100" step=".1" aria-label="재생 속도"></label><button data-fit>전체</button></div><div class="curve-keybar"><label>트랙<input data-track-name value="${esc(track?.name||'')}" maxlength="80" aria-label="트랙 이름" style="width:110px"></label><label>시간<input data-key-time type="number" step=".01" aria-label="키 시간"></label><label>값<input data-key-value type="number" step=".01" aria-label="키 값" ${track?.type==='event'?'disabled':''}></label><select data-interpolation aria-label="키 보간">${modes.map(([k,name])=>`<option value="${k}">${name}</option>`).join('')}</select><label>진입<input data-tangent="arriveTangent" type="number" step=".1" aria-label="진입 탄젠트"></label><label>진출<input data-tangent="leaveTangent" type="number" step=".1" aria-label="진출 탄젠트"></label><button data-add-key>키 추가</button><button data-delete-key>키 삭제</button></div><div class="curve-body"><div class="curve-tracks">${t.tracks.map(track=>`<div class="curve-track ${track.id===this.trackId?'selected':''}"><button data-track="${track.id}">${esc(track.name)}</button><small>${track.type==='vec3'?'Vector':track.type} · ${track.keys.length} keys</small>${track.type!=='event'?`<div class="curve-channels">${(track.type==='vec3'?['X','Y','Z']:track.type==='color'?['R','G','B','A']:['Value']).map((name,c)=>`<label style="color:${colors[c]}"><input type="checkbox" data-channel="${c}" data-channel-track="${track.id}" ${this.hidden.has(track.id+':'+c)?'':'checked'}>${name}</label>`).join('')}</div>`:''}</div>`).join('')}<div class="curve-track-actions"><button data-remove-track aria-label="트랙 삭제">트랙 삭제</button></div></div><div class="curve-plot"><svg viewBox="0 0 1000 420" preserveAspectRatio="none" aria-label="타임라인 커브 편집" tabindex="0"></svg></div></div><div class="curve-footer"><button data-transport="-1" aria-label="역재생">◀</button><button data-transport="0" aria-label="정지">■</button><button data-transport="1" aria-label="재생">▶</button><input type="range" data-scrub min="0" max="${timelineLength(t)}" value="${this.time}" step=".001" aria-label="타임라인 시간"><output data-time>${this.time.toFixed(3)} s</output><output data-sample></output></div>`;
    this.el.querySelector('[data-add-track]').onchange=e=>{const type=e.target.value;if(!type)return;if(t.tracks.length>=16)return this.hooks.error?.('트랙은 16개까지 만들 수 있어요.');const id='Track_'+crypto.randomUUID().replaceAll('-','');if(this.change(t=>t.tracks.push({id,name:type+' '+(t.tracks.length+1),type,interpolation:'linear',keys:type==='event'?[]:[{time:0,value:defaultsFor(type)},{time:t.length,value:defaultsFor(type)}]}))){this.trackId=id;this.selection.clear();this.render();}};
    this.el.querySelectorAll('[data-setting]').forEach(input=>input.onchange=()=>{this.change(t=>t[input.dataset.setting]=input.type==='checkbox'?input.checked:Number(input.value));this.render();});
    this.el.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{this.trackId=b.dataset.track;this.channel=0;this.selection.clear();this.fit();this.render();});
    this.el.querySelectorAll('[data-channel]').forEach(input=>input.onchange=()=>{const id=input.dataset.channelTrack+':'+input.dataset.channel;input.checked?this.hidden.delete(id):this.hidden.add(id);this.channel=Number(input.dataset.channel);this.draw();});
    this.el.querySelector('[data-track-name]').onchange=e=>{this.change(t=>{const track=t.tracks.find(t=>t.id===this.trackId);if(track)track.name=e.target.value.trim()||track.name;});this.render();};
    this.el.querySelector('[data-remove-track]').onclick=()=>{if(!this.track)return;const id=this.trackId;if(this.change(t=>t.tracks=t.tracks.filter(t=>t.id!==id))){this.hooks.removePin?.(id);this.trackId=this.node.timeline.tracks[0]?.id;this.selection.clear();this.render();}};
    this.el.querySelector('[data-add-key]').onclick=()=>this.addKey(this.time);this.el.querySelector('[data-delete-key]').onclick=()=>this.removeKeys();
    for(const selector of ['[data-key-time]','[data-key-value]','[data-interpolation]','[data-tangent]'])this.el.querySelectorAll(selector).forEach(input=>input.onchange=()=>this.editKeys(input));
    this.el.querySelector('[data-fit]').onclick=()=>{this.fit();this.draw();};this.el.querySelectorAll('[data-transport]').forEach(b=>b.onclick=()=>{this.playing=Number(b.dataset.transport);const length=timelineLength(this.node.timeline);if(this.playing===1&&this.time===length)this.time=0;if(this.playing===-1&&this.time===0)this.time=length;});
    this.el.querySelector('[data-scrub]').oninput=e=>{this.time=Number(e.target.value);this.draw();this.scrub();};
    this.svg=this.el.querySelector('svg');this.svg.onpointerdown=e=>this.pointer(e);this.svg.oncontextmenu=e=>this.context(e);this.svg.onwheel=e=>{e.preventDefault();const p=this.point(e),v=this.view,factor=e.deltaY>0?1.15:1/1.15;if(e.ctrlKey){v.min=p.value+(v.min-p.value)*factor;v.max=p.value+(v.max-p.value)*factor;}else{v.start=p.time+(v.start-p.time)*factor;v.end=p.time+(v.end-p.time)*factor;}this.draw();};this.draw();this.keybar();this.scrub();
  }
  point(e){const r=this.svg.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1000,y=(e.clientY-r.top)/r.height*420,v=this.view;return {x,y,time:v.start+(x-55)/930*(v.end-v.start),value:v.max-(y-25)/355*(v.max-v.min)};}
  draw(){
    if(!this.svg||!this.node)return;const v=this.view,x=time=>55+(time-v.start)/(v.end-v.start)*930,y=value=>25+(v.max-value)/(v.max-v.min)*355;let out='<defs><clipPath id="curve-clip-'+this.node.id+'"><rect x="55" y="25" width="930" height="355"/></clipPath></defs><rect width="1000" height="420" fill="#20282c"/>';
    for(let i=0;i<=10;i++){const time=v.start+(v.end-v.start)*i/10,value=v.min+(v.max-v.min)*i/10;out+=`<path d="M${x(time)} 25V380M55 ${y(value)}H985" stroke="#3c484d" stroke-width="1"/><text x="${x(time)}" y="402" text-anchor="middle">${Number(time.toFixed(2))}</text><text x="48" y="${y(value)+4}" text-anchor="end">${Number(value.toFixed(2))}</text>`;}
    out+=`<g clip-path="url(#curve-clip-${this.node.id})"><path d="M${x(0)} 25V380M${x(this.node.timeline.length)} 25V380" stroke="#809478" stroke-dasharray="4 4"/>`;
    const track=this.track;if(track){const count=track.type==='vec3'?3:track.type==='color'?4:1;for(let c=0;c<count;c++){if(this.hidden.has(track.id+':'+c))continue;const component=value=>Array.isArray(value)?value[c]:value;
      if(track.type!=='event'&&track.keys.length){const samples=Array.from({length:241},(_,i)=>{const time=Math.max(0,Math.min(this.node.timeline.length,v.start+(v.end-v.start)*i/240));return `${i?'L':'M'}${x(time)} ${y(component(sampleTimeline(track,time)))}`;});out+=`<path d="${samples.join('')}" fill="none" stroke="${colors[c]}" stroke-width="2"/>`;}
      track.keys.forEach((k,i)=>{const cy=track.type==='event'?190:y(component(k.value));out+=`<rect class="curve-key ${this.selection.has(k)&&c===this.channel?'selected':''}" data-key="${i}" data-axis="${c}" x="${x(k.time)-5}" y="${cy-5}" width="10" height="10" rx="1" fill="${track.type==='event'?'#dcbb76':colors[c]}" transform="rotate(45 ${x(k.time)} ${cy})"/>`;});}}
    out+=`<path d="M${x(this.time)} 25V380" stroke="#f0d287" stroke-width="1.5"/></g>`;this.svg.innerHTML=out;this.readableLabels();
  }
  keybar(){const key=[...this.selection][0],component=v=>Array.isArray(v)?v[this.channel]:v;for(const [selector,value] of [['[data-key-time]',key?.time],['[data-key-value]',component(key?.value)],['[data-interpolation]',(key?.interpolation||this.track?.interpolation||'linear').replace('step','constant')],['[data-tangent="arriveTangent"]',component(key?.arriveTangent)],['[data-tangent="leaveTangent"]',component(key?.leaveTangent)]]){const input=this.el.querySelector(selector);input.value=value??'';input.disabled=!key||(selector!=='[data-key-time]'&&this.track?.type==='event');}}
  scrub(){const output=this.el.querySelector('[data-time]');if(!output)return;output.textContent=this.time.toFixed(3)+' s';this.el.querySelector('[data-scrub]').value=this.time;this.el.querySelector('[data-sample]').textContent=this.track&&this.track.type!=='event'?JSON.stringify(sampleTimeline(this.track,this.time),(_,v)=>typeof v==='number'?Number(v.toFixed(3)):v):'';}
  addKey(time,value){if(!this.track)return;time=Math.max(0,Math.min(this.node.timeline.length,time));if(this.track.keys.some(k=>Math.abs(k.time-time)<.00001))return this.hooks.error?.('같은 시간에 키가 있어요.');const key={time,...(this.track.type==='event'?{}:{value:sampleTimeline(this.track,time)})};if(value!==undefined&&this.track.type!=='event'){if(Array.isArray(key.value))key.value[this.channel]=value;else key.value=value;}if(this.change(t=>{const track=t.tracks.find(t=>t.id===this.trackId);track.keys.push(key);track.keys.sort((a,b)=>a.time-b.time);})){this.selection=new Set([this.track.keys.find(k=>k.time===time)]);this.render();}}
  removeKeys(){if(!this.track||!this.selection.size)return;const indices=[...this.selection].map(k=>this.track.keys.indexOf(k));if(this.change(t=>{const track=t.tracks.find(t=>t.id===this.trackId);track.keys=track.keys.filter((_,i)=>!indices.includes(i));})){this.selection.clear();this.render();}}
  editKeys(input){if(!this.track||!this.selection.size)return;const indices=[...this.selection].map(k=>this.track.keys.indexOf(k)),value=Number(input.value);if(this.change(t=>{const track=t.tracks.find(t=>t.id===this.trackId);for(const i of indices){const k=track.keys[i];if(input.dataset.keyTime!==undefined)k.time=value;else if(input.dataset.interpolation!==undefined)k.interpolation=input.value;else{const property=input.dataset.tangent||'value';k[property]??=defaultsFor(track.type);if(Array.isArray(k[property]))k[property][this.channel]=value;else k[property]=value;if(input.dataset.tangent)k.interpolation=input.dataset.tangent==='arriveTangent'||k.interpolation==='break'?'break':'user';}}track.keys.sort((a,b)=>a.time-b.time);})){this.render();}else this.keybar();}
  pointer(e){
    e.preventDefault();e.stopPropagation();this.el.focus();const p=this.point(e),target=e.target.closest('[data-key]'),v={...this.view};this.svg.setPointerCapture(e.pointerId);
    if(e.button===1||e.button===2){this.suppressContext=false;const move=ev=>{if(Math.hypot(ev.clientX-e.clientX,ev.clientY-e.clientY)>3)this.suppressContext=true;const dx=(ev.clientX-e.clientX)/this.svg.getBoundingClientRect().width*(v.end-v.start),dy=(ev.clientY-e.clientY)/this.svg.getBoundingClientRect().height*(v.max-v.min);this.view={start:v.start-dx,end:v.end-dx,min:v.min+dy,max:v.max+dy};this.draw();};this.svg.onpointermove=move;this.svg.onpointerup=this.svg.onpointercancel=()=>this.svg.onpointermove=null;return;}
    if(!target){if(!e.ctrlKey&&!e.metaKey)this.selection.clear();this.time=Math.max(0,Math.min(this.node.timeline.length,p.time));if(e.shiftKey)this.addKey(this.time,p.value);else{this.draw();this.keybar();this.scrub();const initial=new Set(this.selection);this.svg.onpointermove=ev=>{if(Math.hypot(ev.clientX-e.clientX,ev.clientY-e.clientY)<3)return;const q=this.point(ev),low=Math.min(p.time,q.time),high=Math.max(p.time,q.time),bottom=Math.min(p.value,q.value),top=Math.max(p.value,q.value);this.selection=new Set(initial);for(const key of this.track?.keys||[]){const value=Array.isArray(key.value)?key.value[this.channel]:key.value;if(key.time>=low&&key.time<=high&&(this.track.type==='event'||value>=bottom&&value<=top))this.selection.add(key);}this.draw();this.keybar();const box=document.createElementNS('http://www.w3.org/2000/svg','rect');for(const [name,value] of Object.entries({x:Math.min(p.x,q.x),y:Math.min(p.y,q.y),width:Math.abs(q.x-p.x),height:Math.abs(q.y-p.y),fill:'#b8d89122',stroke:'#b8d891'}))box.setAttribute(name,value);this.svg.append(box);};this.svg.onpointerup=this.svg.onpointercancel=()=>{this.svg.onpointermove=null;this.draw();};}return;}
    const index=Number(target.dataset.key),key=this.track.keys[index];this.channel=Number(target.dataset.axis);if(e.ctrlKey||e.metaKey){this.selection.has(key)?this.selection.delete(key):this.selection.add(key);}else if(!this.selection.has(key))this.selection=new Set([key]);this.draw();this.keybar();const indices=[...this.selection].map(k=>this.track.keys.indexOf(k)),before=structuredClone(this.node.timeline);let recorded=false;
    this.svg.onpointermove=ev=>{if(Math.hypot(ev.clientX-e.clientX,ev.clientY-e.clientY)<3&&!recorded)return;const q=this.point(ev),candidate=structuredClone(before),track=candidate.tracks.find(t=>t.id===this.trackId),keys=indices.map(i=>track.keys[i]);for(const k of keys){k.time=Math.max(0,Math.min(candidate.length,k.time+q.time-p.time));if(track.type!=='event'){if(Array.isArray(k.value))k.value[this.channel]+=q.value-p.value;else k.value+=q.value-p.value;}}track.keys.sort((a,b)=>a.time-b.time);if(!validTimeline(candidate))return;if(!recorded){this.hooks.before?.();recorded=true;}this.node.timeline=candidate;this.selection=new Set(keys);this.draw();this.keybar();};
    this.svg.onpointerup=this.svg.onpointercancel=()=>{this.svg.onpointermove=null;if(recorded)this.hooks.change?.();};
  }
  context(e){e.preventDefault();e.stopPropagation();if(this.suppressContext){this.suppressContext=false;return;}document.querySelector('.curve-menu')?.remove();const p=this.point(e),target=e.target.closest('[data-key]');if(target&&!this.selection.has(this.track.keys[Number(target.dataset.key)])){this.channel=Number(target.dataset.axis);this.selection=new Set([this.track.keys[Number(target.dataset.key)]]);this.draw();this.keybar();}const menu=document.createElement('div');menu.className='dock-menu curve-menu';menu.style.left=Math.min(e.clientX,innerWidth-145)+'px';menu.style.top=Math.min(e.clientY,innerHeight-240)+'px';const add=(label,action)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{menu.remove();action();};menu.append(b);};add('키 추가',()=>this.addKey(p.time,p.value));if(this.selection.size){add('키 삭제',()=>this.removeKeys());if(this.track.type!=='event')for(const [mode,name] of modes)add(name,()=>this.editKeys({dataset:{interpolation:''},value:mode}));}document.body.append(menu);const close=e=>{if(!menu.contains(e.target)){menu.remove();document.removeEventListener('pointerdown',close);}};document.addEventListener('pointerdown',close);}
}
