import {immutableNativeSnapshot} from './native-transport.js';
import {bindVirtualControl,drawVirtualControl,virtualTypes,virtualDefaults} from './virtual-controls.js';
import {validWidgetAsset,validWidgetProperties,widgetContainers,widgetDefaults,widgetScale,widgetImageSource} from './ui-assets.js';

const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function renderWidgetTree(host,data,{preview=false,fileUrl=p=>p,event=()=>{},select=()=>{},input=()=>{},acceptInput=()=>true,inputSignal}={}){
  if(!validWidgetAsset(data))throw Error('위젯 에셋 검증 실패');
  const elements=new Map(),controls=new Map(),root=data.nodes.find(n=>!n.parent),document=host.ownerDocument;
  const frame=document.createElement('div');frame.className='hb-ui-safe-area';if(data.safeArea)for(const [index,side] of ['top','right','bottom','left'].entries())frame.style[side]=`calc(env(safe-area-inset-${side}, 0px) + ${data.safeAreaPadding?.[index]||0}px)`;const canvas=document.createElement('div');canvas.className='hb-ui-canvas';frame.append(canvas);host.replaceChildren(frame);let scale=1;
  const images=new Map(),fonts=new Map(),rendered=new Map(),pointerMedia=document.defaultView.matchMedia?.('(any-pointer: coarse)'),touchDevice=()=>!!((document.defaultView.navigator.maxTouchPoints||0)>0||pointerMedia?.matches);let lastTouchDevice=touchDevice();
  const fontFace=path=>{if(!path)return null;if(!fonts.has(path)){const Font=host.ownerDocument.defaultView.FontFace;const face=new Font('hb_ui_'+crypto.randomUUID().replaceAll('-',''),`url(${JSON.stringify(fileUrl(path))})`);fonts.set(path,face);face.load().then(face=>host.ownerDocument.fonts.add(face)).catch(()=>{});}return fonts.get(path);};
  const updateLayout=(el,node)=>{
    const p={...widgetDefaults,...node.properties},s=node.slot,parent=data.nodes.find(n=>n.id===node.parent);
    if(parent&&['Canvas','Panel'].includes(parent.type)){const [ax,ay,bx,by]=s.anchors,[x,y,w,h]=s.offset;Object.assign(el.style,{left:`calc(${ax*100}% + ${x}px)`,top:`calc(${ay*100}% + ${y}px)`,width:ax===bx?`${Math.max(0,w)}px`:`max(0px, calc(${(bx-ax)*100}% - ${x+w}px))`,height:ay===by?`${Math.max(0,h)}px`:`max(0px, calc(${(by-ay)*100}% - ${y+h}px))`});}
    else if(parent){el.style.width=s.fill?'auto':s.offset[2]+'px';el.style.height=s.fill&&parent.type==='VerticalBox'?'auto':s.offset[3]+'px';}
    el.style.transform=`translate(${-s.alignment[0]*100}%,${-s.alignment[1]*100}%) rotate(${p.rotation}deg) scale(${p.scale.join(',')})`;el.style.transformOrigin='center';el.style.fontSize=p.fontSize+'px';el.style.fontFamily=p.font?fontFace(p.font).family:'';el.style.color=p.color;el.style.backgroundColor=p.background;
    if(node.type==='ProgressBar'){const t=clamp((p.value-p.min)/(p.max-p.min),0,1),fill=el.firstElementChild,direction=p.fillDirection;Object.assign(fill.style,{position:'absolute',left:direction==='rightToLeft'?'auto':'0',right:direction==='rightToLeft'?'0':'auto',top:direction==='bottomToTop'?'auto':'0',bottom:direction==='bottomToTop'?'0':'auto',width:['leftToRight','rightToLeft'].includes(direction)?t*100+'%':'100%',height:['bottomToTop','topToBottom'].includes(direction)?t*100+'%':'100%',backgroundColor:p.accent,backgroundImage:p.fillTexture?`url(${JSON.stringify(fileUrl(p.fillTexture))})`:'none',backgroundSize:'100% 100%',maskImage:direction==='radial'?`conic-gradient(#000 ${t*360}deg, transparent 0deg)`:'none'});el.style.backgroundImage=p.backgroundTexture?`url(${JSON.stringify(fileUrl(p.backgroundTexture))})`:'none';el.style.backgroundSize='100% 100%';}
  };
  const visible=node=>{const p=node.properties,device=p.deviceVisibility||virtualDefaults.deviceVisibility,touch=(document.defaultView.navigator.maxTouchPoints||0)>0||pointerMedia?.matches;return p.visible&&(preview||!(device==='touch'&&!touch||device==='mouse'&&touch));};
  const updateImages=()=>{for(const {img,node} of images.values()){const p=node.properties,stamp=JSON.stringify([p,scale,document.defaultView.devicePixelRatio||1,visible(node)]);if(img.hbImageStamp===stamp)continue;img.hbImageStamp=stamp;const source=widgetImageSource(p,scale,document.defaultView.devicePixelRatio||1);if(img.dataset.asset!==source){img.dataset.asset=source;if(source)img.src=fileUrl(source);else img.removeAttribute('src');}const border=p.nineSlice||[0,0,0,0],sliced=border.some(v=>v>0),outer=img.parentElement;if(sliced&&source){outer.style.borderStyle='solid';outer.style.borderWidth=[border[3],border[2],border[1],border[0]].map(v=>v+'px').join(' ');outer.style.borderImageSource=`url(${JSON.stringify(fileUrl(source))})`;outer.style.borderImageSlice=[border[3],border[2],border[1],border[0]].join(' ')+' fill';outer.style.borderImageRepeat='stretch';}else {outer.style.borderImageSource='none';outer.style.borderWidth=p.borderWidth+'px';}img.style.display=sliced?'none':'';img.style.objectFit=p.imageFit||'contain';img.style.imageRendering=/\.svg$/i.test(source)?'auto':p.imageRendering||'auto';img.hidden=!source||node.type==='Image'&&!visible(node);}};
  const enabled=node=>{let at=node;while(at){if(!at.properties.enabled)return false;at=data.nodes.find(n=>n.id===at.parent);}return true;};
  const build=node=>{
    const p={...widgetDefaults,...node.properties},tag={Button:'button',TouchButton:'button',Image:'div',Slider:'input',TextInput:'input',CheckBox:'label'}[node.type]||'div',element=document.createElement(tag);
    element.className='hb-ui-element hb-ui-'+node.type;element.dataset.widgetId=node.id;element.dataset.widgetName=node.name;element.title=p.tooltip;
    element.style.pointerEvents=preview||node.events?.click||virtualTypes.has(node.type)||['Button','Slider','TextInput','CheckBox','ScrollBox'].includes(node.type)?'auto':'none';
    if(node.type==='Slider'){element.type='range';element.setAttribute('aria-label',node.name);}
    if(node.type==='TextInput'){element.type='text';element.setAttribute('aria-label',node.name);element.placeholder=p.placeholder;element.maxLength=p.maxLength;}
    if(node.type==='Image'){const img=document.createElement('img');img.alt=p.text;img.draggable=false;Object.assign(img.style,{width:'100%',height:'100%'});element.append(img);images.set(node.id,{img,node});}
    if(['Button','TouchButton'].includes(node.type)){const img=document.createElement('img');img.alt='';img.draggable=false;img.className='hb-ui-button-image';element.append(img);images.set(node.id,{img,node});if(node.type==='Button'){const label=document.createElement('span');label.className='hb-ui-button-label';element.append(label);}}
    if(node.type==='CheckBox'){const input=document.createElement('input');input.type='checkbox';input.setAttribute('aria-label',p.text||node.name);const text=document.createElement('span');element.append(input,text);}
    if(node.type==='ProgressBar'){element.setAttribute('role','progressbar');element.setAttribute('aria-label',node.name);const fill=document.createElement('div');fill.className='hb-ui-progress-fill';element.append(fill);}
    const parent=data.nodes.find(n=>n.id===node.parent),s=node.slot;
    if(node.parent&&['Canvas','Panel'].includes(parent.type)){
      const [ax,ay,bx,by]=s.anchors,[x,y,w,h]=s.offset;
      Object.assign(element.style,{position:'absolute',left:`calc(${ax*100}% + ${x}px)`,top:`calc(${ay*100}% + ${y}px)`,width:ax===bx?`${Math.max(0,w)}px`:`max(0px, calc(${(bx-ax)*100}% - ${x+w}px))`,height:ay===by?`${Math.max(0,h)}px`:`max(0px, calc(${(by-ay)*100}% - ${y+h}px))`,transform:`translate(${-s.alignment[0]*100}%,${-s.alignment[1]*100}%)`});
    }else if(node.parent){Object.assign(element.style,{position:'relative',width:s.fill?'auto':`${Math.max(0,s.offset[2])}px`,height:s.fill&&parent.type==='VerticalBox'?'auto':`${Math.max(0,s.offset[3])}px`,flex:s.fill?`${s.fill} 1 0`:'0 0 auto'});}
    else Object.assign(element.style,{position:'absolute',inset:'0',width:'100%',height:'100%'});
    Object.assign(element.style,{zIndex:String(s.zIndex),fontSize:p.fontSize+'px',color:p.color,background:p.background,border:`${p.borderWidth}px solid ${p.borderColor}`,borderRadius:p.radius+'px',padding:widgetContainers.has(node.type)?p.padding+'px':'0',gap:p.gap+'px',textAlign:p.align,whiteSpace:p.wrap?'pre-wrap':'nowrap',gridTemplateColumns:node.type==='Grid'?`repeat(${p.columns}, minmax(0,1fr))`:'none'});
    for(const key of ['accent','hover','pressed'])element.style.setProperty('--ui-'+key,p[key]);
    element.tabIndex=preview?-1:p.focusable&&['Button','TouchButton','Slider','TextInput','CheckBox','ScrollBox'].includes(node.type)?0:-1;
    const control=node.type==='CheckBox'?element.querySelector('input'):element;
    const signal=type=>{if(preview||!enabled(node)||!node.properties.visible)return;if(['changed','click','submit'].includes(type)){if(node.type==='Slider')node.properties.value=Number(control.value);if(node.type==='CheckBox')node.properties.checked=control.checked;if(node.type==='TextInput')node.properties.text=control.value;}event(node,type);};
    if(virtualTypes.has(node.type)&&preview)drawVirtualControl(element,node);
    if(virtualTypes.has(node.type)&&!preview)controls.set(node.id,bindVirtualControl(element,node,{input,event:signal,signal:inputSignal,accept:()=>acceptInput()&&enabled(node)&&node.properties.visible}));
    if(node.type==='CheckBox'){element.tabIndex=-1;control.tabIndex=preview||!p.focusable?-1:0;}
    if(!preview){control.addEventListener('click',()=>signal('click'));control.addEventListener(node.type==='CheckBox'?'change':'input',()=>signal('changed'));control.addEventListener('focus',()=>signal('focus'));control.addEventListener('blur',()=>signal('blur'));control.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'&&node.type==='TextInput')signal('submit');});element.addEventListener('pointerdown',e=>e.stopPropagation());element.addEventListener('wheel',e=>e.stopPropagation());}
    else element.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();select(node,e);});
    elements.set(node.id,element);for(const child of data.nodes.filter(n=>n.parent===node.id))element.append(build(child));return element;
  };
  canvas.append(build(root));
  const update=()=>{for(const node of data.nodes){const el=elements.get(node.id),p=node.properties,control=node.type==='CheckBox'?el.querySelector('input'):el,active=enabled(node),shown=visible(node),stamp=JSON.stringify([p,node.slot,active,shown]);if(rendered.get(node.id)===stamp)continue;rendered.set(node.id,stamp);el.hidden=!shown;const controlState=controls.get(node.id);if((!active||el.hidden)&&controlState)controlState.reset();controlState?.update();el.style.opacity=String(p.opacity);el.classList.toggle('is-disabled',!active);el.setAttribute('aria-disabled',String(!active));if('disabled' in control)control.disabled=!active;if(node.type==='Text')el.textContent=p.text;if(node.type==='Button')el.querySelector('.hb-ui-button-label').textContent=p.text;if(node.type==='Image')el.querySelector('img').alt=p.text;if(node.type==='TextInput'&&control.value!==p.text)control.value=p.text;if(node.type==='CheckBox'){control.checked=p.checked;el.querySelector('span').textContent=p.text;}if(node.type==='Slider'){el.min=p.min;el.max=p.max;el.step=p.step;el.value=p.value;}if(node.type==='ProgressBar'){const t=clamp((p.value-p.min)/(p.max-p.min),0,1);el.firstElementChild.style.width=t*100+'%';el.setAttribute('aria-valuemin',p.min);el.setAttribute('aria-valuemax',p.max);el.setAttribute('aria-valuenow',p.value);}updateLayout(el,node);}updateImages();};
  const resize=()=>{const w=frame.clientWidth||host.clientWidth||data.referenceSize[0],h=frame.clientHeight||host.clientHeight||data.referenceSize[1];scale=widgetScale(data,data.scaleRule?host.clientWidth||w:w,data.scaleRule?host.clientHeight||h:h);Object.assign(canvas.style,{width:w/scale+'px',height:h/scale+'px',zoom:String(scale)});canvas.dataset.uiScale=String(scale);updateImages();};
  const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(resize):null;observer?.observe(host);observer?.observe(frame);const window=document.defaultView;window.addEventListener('resize',resize);resize();update();
  const refresh=()=>update();refresh();
  return {elements,data,update:refresh,fontsReady:()=>Promise.all([...fonts.values()].map(face=>face.loaded)),resetControls:emit=>{for(const control of controls.values())control.reset(emit);},endFrame:()=>{const touch=touchDevice();if(touch!==lastTouchDevice){lastTouchDevice=touch;update();}for(const control of controls.values())control.endFrame();},dispose(reason){observer?.disconnect();window.removeEventListener('resize',resize);for(const control of controls.values())control.dispose(reason);for(const face of fonts.values())document.fonts.delete(face);frame.remove();}};
}

export class WidgetSystem {
  constructor(hooks={}){this.hooks=hooks;this.instances=new Map();this.events=[];this.disposed=false;this.animations=new Map();this.batchDepth=0;this.dirty=new Set();}
  key(owner,instance){return JSON.stringify([owner,instance]);}
  state(owner,instance){const state=this.instances.get(this.key(owner,instance));if(!state)throw Error('위젯 인스턴스를 찾을 수 없어요: '+instance);return state;}
  node(state,name){const node=state.data.nodes.find(n=>n.id===name||n.name===name);if(!node)throw Error('위젯 요소가 없어요: '+name);return node;}
  sync(state,vm){const owner=vm.object(state.owner);if(!owner)return;owner.gameplayDebug??={};owner.gameplayDebug.ui??={};owner.gameplayDebug.ui=immutableNativeSnapshot({...owner.gameplayDebug.ui,[state.instance]:Object.fromEntries(state.data.nodes.map(n=>[n.name,{type:n.type,...n.properties,slot:structuredClone(n.slot),value:n.type==='CheckBox'?Number(n.properties.checked):n.properties.value}]))});}
  refresh(state,vm){if(this.batchDepth){this.dirty.add(state);return;}state.view?.update();this.sync(state,vm);}
  async writeBatch(callback,vm){this.batchDepth++;try{return await callback();}finally{if(--this.batchDepth===0){const changed=[...this.dirty];this.dirty.clear();for(const state of changed)if(this.instances.get(this.key(state.owner,state.instance))===state)this.refresh(state,vm);}}}
  async operation(key,a,b,vm){
    if(!key.startsWith('ui'))return undefined;
    const owner=!a.target||a.target==='self'?b.self:a.target;if(!vm.object(owner))throw Error('위젯 소유 오브젝트가 없어요.');
    if(key==='uiShow'){
      if(typeof a.instance!=='string'||!a.instance||a.instance.length>80)throw Error('위젯 인스턴스 이름을 확인하세요.');
      const data=await this.hooks.readAsset(a.asset);if(this.disposed)return {};if(!validWidgetAsset(data))throw Error('위젯 에셋 검증 실패');if(!this.instances.has(this.key(owner,a.instance))&&this.instances.size>=32)throw Error('위젯 인스턴스 제한 초과');
      this.remove(owner,a.instance,vm);const state={owner,instance:a.instance,data:structuredClone(data)};this.instances.set(this.key(owner,a.instance),state);
      const overlay=this.hooks.overlay?.();if(overlay){const host=overlay.ownerDocument.createElement('div');host.className='hb-ui-host';host.dataset.widgetInstance=a.instance;overlay.append(host);state.host=host;state.view=renderWidgetTree(host,state.data,{fileUrl:this.hooks.fileUrl,inputSignal:this.hooks.inputSignal,input:(key,value,source)=>{const active=this.hooks.runtime?.()||vm;if(active.active&&!active.paused&&!active.stopping)active.dispatchInput({key,value,source,device:'touch'}).catch(error=>this.hooks.error?.(error));},acceptInput:()=>{const active=this.hooks.runtime?.()||vm;return active.active&&!active.paused&&!active.stopping;},event:(node,type)=>{this.sync(state,vm);if(node.events[type]){if(this.events.length>=256)this.events.shift();this.events.push({state,node:node.id,event:node.events[type],type,text:node.properties.text,value:node.type==='CheckBox'?Number(node.properties.checked):node.properties.value});}}});}
      await state.view?.fontsReady();this.sync(state,vm);return {};
    }
    if(key==='uiRemove'){this.remove(owner,a.instance,vm);return {};}
    const state=this.state(owner,a.instance),node=this.node(state,a.element),p=node.properties;
    if(key==='uiGetText')return {return:p.text};if(key==='uiGetValue')return {return:node.type==='CheckBox'?Number(p.checked):p.value};
    if(key==='uiSetText'){if(typeof a.text!=='string'||a.text.length>10000)throw Error('위젯 텍스트 길이 초과');if(p.text===a.text)return {};p.text=a.text;}
    else if(key==='uiSetValue'){if(!Number.isFinite(a.value))throw Error('위젯 값은 유한한 수여야 해요.');const value=clamp(a.value,p.min,p.max);if(p.value===value&&(node.type!=='CheckBox'||p.checked===Boolean(a.value)))return {};p.value=value;if(node.type==='CheckBox')p.checked=Boolean(a.value);}
    else if(key==='uiSetVisible'){const value=Boolean(a.visible);if(p.visible===value)return {};p.visible=value;}
    else if(key==='uiSetEnabled'){const value=Boolean(a.enabled);if(p.enabled===value)return {};p.enabled=value;}
    else if(key==='uiFocus'){const el=state.view?.elements.get(node.id);(el?.querySelector('input')||el)?.focus();}
    else if(key==='uiAnimate'){if(!['opacity','rotation','x','y','blink'].includes(a.property)||!Number.isFinite(a.to)||Math.abs(a.to)>10000||a.property==='opacity'&&(a.to<0||a.to>1)||!Number.isFinite(a.duration)||a.duration<=0||a.duration>3600)throw Error('위젯 애니메이션 값을 확인하세요.');const from=a.property==='x'?node.slot.offset[0]:a.property==='y'?node.slot.offset[1]:a.property==='blink'?p.opacity:p[a.property]??0;this.animations.set(JSON.stringify([owner,a.instance,node.id,a.property]),{state,node,property:a.property,from,to:a.to,duration:a.duration,elapsed:0});return {};}
    else if(key.startsWith('uiSet')){
      const n={...node,slot:structuredClone(node.slot),properties:structuredClone(p)},value={uiSetTexture:['texture',a.texture],uiSetRotation:['rotation',a.rotation],uiSetScale:['scale',a.scale],uiSetColor:['color',Array.isArray(a.color)&&a.color.length===4?a.color.map(v=>Math.round(clamp(v,0,1)*255).toString(16).padStart(2,'0')).join(''):a.color],uiSetOpacity:['opacity',a.opacity],uiSetFont:['font',a.font],uiSetFontSize:['fontSize',a.fontSize],uiSetFillDirection:['fillDirection',a.direction]}[key];
      if(key==='uiSetPosition'||key==='uiSetSize'){const v=key==='uiSetPosition'?a.position:a.size;if(!Array.isArray(v)||v.length!==2||!v.every(Number.isFinite))throw Error('위젯 위치·크기를 확인하세요.');n.slot.offset.splice(key==='uiSetPosition'?0:2,2,...v);}
      else if(value)n.properties[value[0]]=value[0]==='color'&&typeof value[1]==='string'&&!value[1].startsWith('#')?'#'+value[1]:value[1];else throw Error('위젯 함수가 없어요: '+key);
      if(key==='uiSetTexture'&&node.properties.texture!==a.texture)n.properties.vectorTexture='';if(!validWidgetProperties(n))throw Error('위젯 속성 범위를 확인하세요.');if(JSON.stringify([node.slot,p])===JSON.stringify([n.slot,n.properties]))return {};Object.assign(node,n);
    }
    else throw Error('위젯 함수가 없어요: '+key);
    this.refresh(state,vm);if(key==='uiSetFont')await state.view?.fontsReady();return {};
  }
  remove(owner,instance,vm){const key=this.key(owner,instance),state=this.instances.get(key);if(!state)return;state.view?.dispose();state.host?.remove();this.instances.delete(key);for(const [id,animation] of this.animations)if(animation.state===state)this.animations.delete(id);this.events=this.events.filter(e=>e.state!==state);const ui=vm.object(owner)?.gameplayDebug?.ui;if(ui){const {[instance]:removed,...rest}=ui;vm.object(owner).gameplayDebug.ui=immutableNativeSnapshot(rest);}}
  removeOwner(owner,vm){for(const state of [...this.instances.values()])if(state.owner===owner)this.remove(owner,state.instance,vm);}
  releaseInput(){for(const state of this.instances.values())state.view?.resetControls(false);}
  async tick(vm){
    for(const [key,animation] of this.animations){const {state,node,property}=animation;if(this.instances.get(this.key(state.owner,state.instance))!==state){this.animations.delete(key);continue;}animation.elapsed=Math.min(animation.duration,animation.elapsed+vm.core.delta);const t=animation.elapsed/animation.duration,value=property==='blink'?animation.from*(Math.sin(t*Math.PI*12)>0?1:0):animation.from+(animation.to-animation.from)*t;if(property==='x'||property==='y')node.slot.offset[property==='x'?0:1]=value;else node.properties[property==='blink'?'opacity':property]=property==='opacity'?clamp(value,0,1):value;if(t===1){if(property==='blink')node.properties.opacity=animation.from;this.animations.delete(key);}state.view?.update();this.sync(state,vm);}
    const queued=this.events.splice(0);for(const e of queued){if(this.disposed||this.instances.get(this.key(e.state.owner,e.state.instance))!==e.state)continue;for(const b of vm.bindings.filter(b=>b.self===e.state.owner))await vm.custom(b,e.event,{widget:e.state.instance,element:e.node,type:e.type,text:e.text,value:e.value});}
    for(const state of [...this.instances.values()]){if(!vm.object(state.owner)){this.remove(state.owner,state.instance,vm);continue;}const binding=vm.bindings.find(b=>b.self===state.owner);let changed=false;for(const node of state.data.nodes)for(const [property,variable] of Object.entries(node.bindings)){const symbol=binding?.root.variables.find(v=>v.id===variable||v.name===variable),key=symbol?.id||variable;if(!variable||!binding?.variables.has(key))continue;const value=binding.variables.get(key),next=property==='text'?String(value).slice(0,10000):property==='value'&&Number.isFinite(value)?clamp(value,node.properties.min,node.properties.max):['visible','enabled','checked'].includes(property)&&typeof value==='boolean'?value:node.properties[property];if(!Object.is(node.properties[property],next)){node.properties[property]=next;changed=true;}}if(changed){state.view?.update();this.sync(state,vm);}state.view?.endFrame();}
  }
  dispose(reason){this.disposed=true;this.animations.clear();for(const state of this.instances.values()){state.view?.dispose(reason);state.host?.remove();}this.instances.clear();this.events=[];}
}
